### DISCUSSION TITLE
Question: Guardrail config in central Configuration .yaml

### DISCUSSION THREAD

**Discussion by VonNao** [BerriAI/litellm#10443] [Q&A]
Hello. Is it possible to set the  "guardrail_config": {"language": "es"} in configuration .yaml for the litellm container?

**Comment by ghost** [comment]
which guardrail is this for? 

cc: @ishaan-jaff

**Reply by VonNao** [reply]
In this case it would be presidio. We are from germany and would like to implement a dlp based on presidio. Right now presidio uses english to verify inputs. 

```
guardrails:
  - guardrail_name: "presidio-pre-guard"
    litellm_params:
      guardrail: presidio
      mode: "pre_call"
      output_parse_pii: True
      default_on: true
```

https://docs.litellm.ai/docs/proxy/guardrails/pii_masking_v2#set-language-per-request it would be really if this step could be done via .yaml configuration
