### DISCUSSION TITLE
Perplexity API Model 401

### DISCUSSION THREAD

**Discussion by stif** [BerriAI/litellm#10947] [Q&A] [answered]
Hi Guys,

I have 2 instances of openwebui with litellm (via docker compose) and the only difference is: instance 2 has a postgres db backend for config.

I added Perplexity to litellm config on both instances (so they have the same litellm-config.yaml):
``` yaml
[...]
   - model_name: "Perplexity Sonar Pro"
      litellm_params:
          model: "perplexity/sonar-pro"
          api_key: "os.environ/PERPLEXITYAI_API_KEY"
[...]
 ```
and got a `401: litellm.AuthenticationError` on instance 1; but after upgrade with `docker compose pull` the error was gone and i can use the sonar-pro model there.
but on instance 2 i still have the 401 error after the `docker compose pull` and cannot get it to work.

Is for some reason the PERPLEXITYAI_API_KEY not picked up when using db backend?
Any Idea why it fails and what i can do?
