### DISCUSSION TITLE
Configuring fallbacks in config.yaml

### DISCUSSION THREAD

**Discussion by zegerius** [BerriAI/litellm#11258] [Q&A]
My fallbacks don't seem to work, with errors. I opened this issue (https://github.com/BerriAI/litellm/issues/11197), but I am curious if it might just be a configuration error.

My config:

```yaml
model_list:
  - model_name: anthropic.claude-sonnet-4-20250514-v1:0
    litellm_params:
      model: bedrock/eu.anthropic.claude-sonnet-4-20250514-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_EU_1
      rpm: 200
      tpm: 200000

  - model_name: anthropic.claude-sonnet-4-20250514-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_EU_2
      rpm: 200
      tpm: 200000

  # Anthropic Claude Sonnet 3.7 20250219 (v1)
  - model_name: anthropic.claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/eu.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_EU_1
      rpm: 250
      tpm: 1000000
  - model_name: anthropic.claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name:  os.environ/AWS_REGION_EU_2
      rpm: 250
      tpm: 1000000

router_settings:
  fallbacks:
    - anthropic.claude-sonnet-4-20250514-v1:0:
        - anthropic.claude-3-7-sonnet-20250219-v1:0
```

The error:

```
litellm.RateLimitError: BedrockException - {"message":"Too many tokens, please wait before trying again."}. Received Model Group=anthropic.claude-sonnet-4-20250514-v1:0
Available Model Group Fallbacks=None
Error doing the fallback: list index out of range LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
```

The documentation on this topic is incomplete, with different sections of the documentation using different config keys. I have also tried to use the "JSON"-approach from the docs (`[{"model": ["fallback1"]}]`), but (obviously) that makes no difference.

I prefer my config as code, so I do not store model definitions in the database. Am I doing something wrong?
