### DISCUSSION TITLE
How to avoid Python files related to customs guardrails from being placed in the same directory as yaml configuration file.

### DISCUSSION THREAD

**Discussion by IleAuxVaches** [BerriAI/litellm#11408] [Ideas]
> In file `litellm/proxy/guardrails/guardrail_registry.py`, it seems that custom guardrails are dynamically instantiated from the yaml configuration file directory.  
> To avoid to have custom guardrails python files in the same directory of config.yaml file, in method ` def initialize_custom_guardrail` perhaps could we replace this lines (L317-325) ?

```python
        _file_name, _class_name = guardrail_type.split(".")
        verbose_proxy_logger.debug(
            "Initializing custom guardrail: %s, file_name: %s, class_name: %s",
            guardrail_type,
            _file_name,
            _class_name,
        )

        directory = os.path.dirname(config_file_path)
        module_file_path = os.path.join(directory, _file_name) + ".py"
``` 
by a stuff like this :
```python
        parts = guardrail_type.split("/")
        if len(parts) == 2:
            directory = parts[0]                
            _file_name, _class_name = parts[1].split(".")
        else : 
            directory = os.path.dirname(config_file_path)
            _file_name, _class_name = guardrail_type.split(".")
        module_file_path = os.path.join(directory, _file_name) + ".py"
```

should work with this kind of config :

```yaml
guardrails:
  - guardrail_name: "detectsecrets-pre-guard"
    litellm_params:
      default_on: false
      guardrail: "my_custom_guardrails/detectsecrets.DetectSecrets"
      mode: pre_call  
```
