### DISCUSSION TITLE
I can't get Bedrock settings to work

### DISCUSSION THREAD

**Discussion by recrudesce** [BerriAI/litellm#11443] [General]
So, it seems that performanceConfig was added to Bedrock capability back in March as per https://github.com/BerriAI/litellm/issues/7606#event-17038029876 - I found the documentation here: https://docs.litellm.ai/docs/providers/bedrock#usage---latency-optimized-inference

But if I configure as per that documentation, I get the following error during inference:
`litellm.BadRequestError: BedrockException - validationException {"message":"The model returned the following errors: performanceConfig: Extra inputs are not permitted"}`

Config is as follows:
```
  - model_name: claude-3.7-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: NO
      aws_secret_access_key: NO
      aws_region_name: us-west-2
      performanceConfig: {"latency": "optimized"}
      rpm: 250
  ```

Same goes if I try setting the reasoningEffort as per the documentation - I set `reasoning_effort: "low"` in my config and it throws `400: litellm.UnsupportedParamsError: bedrock does not support parameters: {'reasoning_effort': 'low'}, for model=us.anthropic.claude-3-7-sonnet-20250219-v1:0. To drop these, set `litellm.drop_params=True` or for proxy:`

What am I doing wrong when I'm following the documentation exactly for these options ?
