### DISCUSSION TITLE
How can we set pricing for Bedrock inference profiles?

### DISCUSSION THREAD

**Discussion by mknet3** [BerriAI/litellm#11553] [General]
I have this configuration for `claude-sonnet-4` and I don't see the pricing (I'm following this [config](https://docs.litellm.ai/docs/proxy/custom_pricing#set-base_model-for-cost-tracking-eg-azure-deployments)):
```yaml
      - model_name: anthropic-claude-sonnet-4
        litellm_params:
          model: bedrock/converse/arn:aws:bedrock:...
          aws_region_name: us-east-1
        model_info:
          base_model: us.anthropic.claude-sonnet-4-20250514-v1:0
```

What I see in model configuration:

```json
{
  "model_group": "anthropic-claude-sonnet-4",
  "providers": [
    "bedrock"
  ],
  "max_input_tokens": null,
  "max_output_tokens": null,
  "input_cost_per_token": 0,
  "output_cost_per_token": 0,
  "mode": null,
  "tpm": null,
  "rpm": null,
  "supports_parallel_function_calling": false,
  "supports_vision": false,
  "supports_web_search": false,
  "supports_reasoning": false,
  "supports_function_calling": false,
  "supported_openai_params": [
    "max_tokens",
    "max_completion_tokens",
    "stream",
    "stream_options",
    "stop",
    "temperature",
    "top_p",
    "extra_headers",
    "response_format",
    "tools",
    "tool_choice",
    "thinking",
    "reasoning_effort"
  ],
  "configurable_clientside_auth_params": null
}
```

![image](https://github.com/user-attachments/assets/ece87889-f751-4d4a-b225-f87b6fe303e2)
