### DISCUSSION TITLE
LiteLLM + Ollama + lobe-chat implementation issues.

### DISCUSSION THREAD

**Discussion by adan89lion** [BerriAI/litellm#1345] [Q&A] [answered]
Hi,

I'm trying to use [lobe-chat](https://github.com/lobehub/lobe-chat) as a frontend for Ollama, proxied via LiteLLM. However, I've been encountering 500 internal server error.

The following are my docker-compose and config files
**LiteLLM Docker Compose File**
```
version: "3.9"
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    ports:
      - "1234:8000"
    volumes:
      - ./config.yml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "8000", "--num_workers", "8" ]
```

**LiteLLM Config File**
```
model_list:
  - model_name: mistral-v2-7b-uncensored
    litellm_params:
      model: ollama/dolphin-mistral:7b-v2-q5_K_S
      api_base: http://192.168.0.161:11434
```

**lobe-chat Docker Compose File**
```
version: '3.8'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: unless-stopped
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: sk-xxxx
      OPENAI_PROXY_URL: http://192.168.0.161:1234/
      ACCESS_CODE: lobe66
```

Accessing `model list` produces the following error for LiteLLM
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1430, in chat_completion
    response = await litellm.acompletion(**data)
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2349, in wrapper_async
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2241, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 227, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6534, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 5556, in exception_type
    raise APIError(
litellm.exceptions.APIError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
INFO:     192.168.148.1:35271 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
```

And lobe-chat returned the following error
```
{
  "endpoint": "http://192.168.***.161:****/",
  "error": {
    "headers": {
      "content-length": "2244",
      "content-type": "application/json",
      "date": "Sat, 06 Jan 2024 17:01:43 GMT",
      "server": "uvicorn"
    },
    "stack": "Error: 500 status code (no body)\n    at W.generate (/app/.next/server/app/api/openai/chat/route.js:22:1839)\n    at tL.makeStatusError (/app/.next/server/app/api/openai/chat/route.js:22:13170)\n    at tL.makeRequest (/app/.next/server/app/api/openai/chat/route.js:22:13900)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async k (/app/.next/server/app/api/openai/chat/route.js:2:2906)\n    at async /app/.next/server/app/api/openai/chat/route.js:7:64510",
    "status": 500
  }
}```

Am I missing something for my configuration? Thanks in advance.

**Comment by Ganesh-403** [comment, marked as answer]
@adan89lion 
The error message actually points to something different from the Ollama configuration:

```text
OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

This isn't an Ollama error—it means LiteLLM ended up trying to initialize an **OpenAI client** without an API key. :contentReference[oaicite:0]{index=0}

A few things I'd check:

1. **Can LiteLLM talk to Ollama directly?**

   Before involving LobeChat, try:

   ```bash
   curl http://192.168.0.161:1234/chat/completions \
     -H "Content-Type: application/json" \
     -d '{
       "model":"mistral-v2-7b-uncensored",
       "messages":[{"role":"user","content":"Hello"}]
     }'
   ```

   If this already fails with the same OpenAI error, then the problem is on the LiteLLM side rather than LobeChat.

2. **Verify the model list.**

   Does:

   ```bash
   curl http://192.168.0.161:1234/models
   ```

   return:

   ```json
   {
     "id": "mistral-v2-7b-uncensored"
   }
   ```

   If not, LiteLLM may not be loading your `config.yaml` as expected.

3. **Check the Ollama endpoint.**

   Your configuration:

   ```yaml
   litellm_params:
     model: ollama/dolphin-mistral:7b-v2-q5_K_S
     api_base: http://192.168.0.161:11434
   ```

   is the expected format for an Ollama backend. LiteLLM supports `ollama/...` models with an `api_base` pointing at the Ollama server. :contentReference[oaicite:1]{index=1}

4. **Enable debug logging.**

   Running LiteLLM with detailed debug output should show **which provider** it is attempting to dispatch to. If it's resolving the request as `openai` instead of `ollama`, that would explain why an OpenAI client is being created.

One question that would help narrow this down:

- What version of LiteLLM are you running (`main-latest` at the time was changing frequently)?
- Does the error occur even when you call LiteLLM directly with `curl`, or only when the request comes from LobeChat?

If a direct request to LiteLLM succeeds but LobeChat fails, then it's likely an issue with the request LobeChat is sending (e.g. model name or endpoint). If both fail with the same stack trace, it would point more toward a LiteLLM configuration or a bug in that particular version.

If this solves your problem, feel free to mark it as the accepted answer so others can find it easily.
