### DISCUSSION TITLE
How to setup Helicone using config.yaml?

### DISCUSSION THREAD

**Discussion by abnerjacobsen** [BerriAI/litellm#1507] [Q&A] [answered]
Hi,

I'm trying to configure LiteLLM proxy to send logs to my Helicone account but without success.

Could anyone give me an example of how to do this using config.yaml?

My config.yaml looks like this:

```
litellm_settings:
   drop_params: True
   set_verbose: False
   add_function_to_prompt: False
   success_callback: helicone
```

And in the .env of my server, which runs using docker, I have:

`HELICONE_API_KEY="sk-helicone...."
`

Anyone can hekp me?
