### DISCUSSION TITLE
[Bug]: H Using `athina` as the `success_callback` will cause CPU usage to reach 90%

### DISCUSSION THREAD

**Discussion by Caixiaopig** [BerriAI/litellm#2957] [General]
### What happened?

In config.yaml, I set litellm_settings: success_callback to athina and found that the CPU usage was abnormal, even reaching up to 90%. Meanwhile, I also tested other success_callback providers like langfuse and promptlayer, and they did not encounter this issue.

code example
```
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
litellm_settings:
  success_callback: ["athina"]
```

**Comment by ishaan-jaff** [comment]
This looks like an issue related to athina specifically

**Comment by ishaan-jaff** [comment]
making discussions since not a litellm issue

**Comment by ishaan-jaff** [comment]
@vivek-athina can you take a look at this

**Comment by vivek-athina** [comment]
I used the same config and ran multiple requests. The CPU usage never reached 90%, infact it was not abnormal at all.
Config used
```yaml
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
litellm_settings:
  success_callback: ["athina"]
```
curl command used
```curl
curl --location 'http://0.0.0.0:4000/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "which llm are you"
        }
    ]
}'
```
Video on my test run where the usage never went above 90%

https://github.com/BerriAI/litellm/assets/153479827/9c690d8c-1463-4e87-af65-88ee9edd953c
