### DISCUSSION TITLE
LiteLLM + Ollama: Model list not returned

### DISCUSSION THREAD

**Discussion by ther3zz** [BerriAI/litellm#3948] [Q&A] [answered]
Can anyone point me in the right direction?

I'm attempting to use LiteLLM with Ollama but I'm not receiving a model list.
I'm seeing:
`{'data': [], 'object': 'list'}`

I'm thinking something is incorrect with my config.yaml.... 

Any help is much appreciated!

```
general_settings: {}

litellm_settings:
  failure_callback: ["langfuse"]
  success_callback: ["langfuse"]

model_list:
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/mistral
  model_name: ollama/mistral
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/mistral-openorca
  model_name: ollama/mistral-openorca
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/phi3
  model_name: ollama/phi3
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llava
  model_name: ollama/llava
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llama3-gradient
  model_name: ollama/llama3-gradient
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llama3-chatqa:8b
  model_name: ollama/llama3-chatqa:8b
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llava-llama3
  model_name: ollama/llava-llama3

router_settings:
  redis_host: 172.17.0.11
  redis_port: 6379
```

I would try to config via the new UI but it looks like ollama is not listed there
