### DISCUSSION TITLE
Langfuse Team logging bug

### DISCUSSION THREAD

**Discussion by miesgre** [BerriAI/litellm#4038] [Q&A]
I would like to log to langfuse and it is working great,
but now I want to log one team to a different langfuse project.

This is my configuration:
```
litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
  langfuse_secret: os.environ/LANGFUSE_SECRET_KEY
  default_team_settings: 
    - team_id: team1
      success_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_TEAM1
      langfuse_secret: os.environ/LANGFUSE_SECRET_KEY_TEAM1
```
My idea is to log all the calls in the first langfuse project, but log those from team1 in the second langfuse project.

The problem is that now all logs go to this secong langfuse project instead of only the logs from team1.

Have I configured it wrong or is it not possible to do this?
