### DISCUSSION TITLE
running litellm behind proxy server

### DISCUSSION THREAD

**Discussion by amirclam** [BerriAI/litellm#4539] [General]
I am running litellm behind proxy server using local text generation inference model

```
Setup:
model_list:
- model_name: star-coder
  litellm_params:
    model: huggingface/my-model
    api_base: [{local model adrress}]
    api_key: no-key
    caching: False
litellm_settings:
  json_logs: true
  cache: True
  telemetry: False
general_settings:
  alerting_threshold: 1
  alerting: ["email"]
  otel: False
  disable_spend_logs: True
  proxy_batch_write_at: 120  

```

when running it with our setting https_proxy every call get stuck for 5 minutes

even due my model and redis are inside my k8s cluster 

what configuration am i missing ?
