### DISCUSSION TITLE
Autodetect Feature?

### DISCUSSION THREAD

**Discussion by changchiyou** [BerriAI/litellm#6948] [Q&A] [answered]
Hello, a quick question here:

Does Litellm support something like autodetect? For instance, is it possible to set configs like below?

```
model_list:
  - model_prefix: "[openai] "
    litellm_params:
      model: openai/autodetect
      api_key: "myKey"
      api_base: "myBase"
```

**Comment by ishaan-jaff** [comment]
yes - wildcard routing @changchiyou https://docs.litellm.ai/docs/wildcard_routing

**Reply by changchiyou** [reply]
~~My `config.yaml` setup:~~

```
model_list:
  - model_name: "[trendmicro] *"
    litellm_params:
      model: openai/*
      api_key: os.environ/TRENDMICRO_API_KEY
      api_base: https://api.rdsec.trendmicro.com/prod/aiendpoint/v1

litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

general_settings:
  master_key: "os.environ/MASTER_KEY"
```

~~What I get from Open WebUI:~~

|What I get|What I want|
|-|-|
|![](https://github.com/user-attachments/assets/876cfb36-5315-4af6-a526-1a062f473af5)|![](https://github.com/user-attachments/assets/63b39695-dc21-499c-81f1-904b18a357cb)|

~~Is it possible?~~
