### DISCUSSION TITLE
Symptom where User ID is not visible in langfuse Trace

### DISCUSSION THREAD

**Discussion by diana-jung** [BerriAI/litellm#7101] [Q&A]
## Env
LiteLLM v1.50.4-stable
Langfuse 2.93.1

```
  config.yaml: |
    model_list:
    litellm_settings:
      set_verbose: True
      json_logs: true
      num_retries: 2
      success_callback: ["langfuse"]
      failure_callback: ["langfuse"]
      enforced_params:
        - user
        - metadata.generation_name
      drop_params: True
      langfuse_default_tags: ["user_api_key_alias", "user_api_key_user_id" ]
```

We are doing LiteLLM logging through Langfuse. Basically, we are using the Virtual key to store user_id, key_alias, user, team_id, and metadata as data and using the /key/generate API to generate it.
However, the User information is not shown in the Trace by default.
To solve this, we added the `enforced_params: - user` value and called the API, and confirmed that the user information is sent in the body.
```
curl --location 'https://<litllem-url>/chat/completions' \
    --header 'Content-Type: application/json' \
    --header 'Authorization: Bearer sk-7q' \
    --data '{
    "model": "<model>",
    ❗️ "user": "diana.jung", 
    "messages": [
        {
        "role": "user",
        "content": "what llm are you"
        }
    ]
}'
```

So, in order to reflect this when generating the key, I configured the client as follows, but it seems like the key information is not entered, so it is not reflected in the trace.
```
'https://<litllem-url>/key/generate',
        {
          models: [],
          user_id: diana.jung, 
          key_alias: diana.jung, 
          user: diana.jung, 
          team_id: team,
          metadata: {
            team: team,
            trace_user_id: diana.jung, 
            name: diana.jung,
            user: diana.jung, 
            phase: "production"
          },
        },
        {
          headers: {
            'Authorization': 'Bearer ',
            'Content-Type': 'application/json'
          }
        }
```
