### DISCUSSION TITLE
litellm.exceptions.BadRequestError: litellm.BadRequestError: AzureException BadRequestError - Error code: 400 - {'error': {'message': "Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.", 'type': 'invalid_request_error', 'param': 'stream', 'code': 'unsupported_value'}}

### DISCUSSION THREAD

**Discussion by Huyueeer** [BerriAI/litellm#7577] [Q&A]
I'm having problems with litellm,
litellm version: `v1.44.9`
config configuration:
```yaml
litellm_settings:
  # other litellm settings
  max_budget: 0 # (float) sets max budget as $0 USD
  # budget_duration: 30d # (str) frequency of reset - You can set duration as seconds ("30s"), minutes ("30m"), hours ("30h"), days ("30d").
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  enable_preview_features: true

model_list:
  - model_name: o1-preview
    litellm_params:
      model: azure/o1-preview
      api_base: https://XXXXXX.openai.azure.com/
      api_key: XXXXXXXXX
      api_version: "2024-02-15-preview"
      input_cost_per_token: 0.000015
      output_cost_per_token: 0.00006
      stream: False
```

Request error:
```
litellm.exceptions.BadRequestError: litellm.BadRequestError: AzureException BadRequestError - Error code: 400 - {'error': {'message': "Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.", 'type': 'invalid_request_error', 'param': 'stream', 'code': 'unsupported_value'}}
```
