### DISCUSSION TITLE
Hi all, im trying to get this work, but i am stuck with Notfound error

### DISCUSSION THREAD

**Discussion by todap** [BerriAI/litellm#8283] [Q&A]
from litellm import completion
import litellm

```
response = completion(
    model="bedrock/converse/us.amazon.nova-micro-v1:0",
    messages=[{ "content": "Hello, how are you?","role": "user"}],
    base_url="http://0.0.0.0:4000",
)

```
Error:
```
HTTPStatusError: Client error '404 Not Found' for url 'http://0.0.0.0:4000/model/us.amazon.nova-micro-v1:0/converse'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

During handling of the above exception, another exception occurred:
BedrockError: {"detail":"Not Found"}

During handling of the above exception, another exception occurred:
NotFoundError: litellm.NotFoundError: BedrockException - {"detail":"Not Found"}
```

here is my config.yaml file
```
model_list:
 - model_name: bedrock-model
   litellm_params:
     model: bedrock/converse/us.amazon.nova-micro-v1:0
 - model_name: gpt-4o
   litellm_params:
     model: gpt-4o
 - model_name: text-embedding-3-small
   litellm_params:
     model: text-embedding-3-small
litellm_settings:
  success_callback: ["langfuse"]
```
it works perfectly when i remove the base_url
