### DISCUSSION TITLE
How can we use Bedrock Application Inference Profiles?

### DISCUSSION THREAD

**Discussion by mknet3** [BerriAI/litellm#8905] [Q&A]
Hi! is there a way to use [Bedrock Application Inference Profiles](https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-create.html) ?

I checked Cross-Region Inference profile and it works fine with something like this:
```yaml
      - model_name: anthropic-claude-3-7-sonnet
        litellm_params:
          model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
          aws_region_name: us-east-1
```

But, what about an application inference profile? I tested in many ways but I could not make it work. E.g.:
```yaml
      - model_name: anthropic-claude-3-7-sonnet
        litellm_params:
          model: bedrock/arn:aws:bedrock:us-east-1:000000000000:application-inference-profile/0z0z0z0z0z0
          aws_region_name: us-east-1
```

also with this:

```yaml
      - model_name: anthropic-claude-3-7-sonnet
        litellm_params:
          model: bedrock/anthropic/arn:aws:bedrock:us-east-1:000000000000:application-inference-profile/0z0z0z0z0z0
          model_id: bedrock/arn:aws:bedrock:us-east-1:000000000000:application-inference-profile/0z0z0z0z0z0
          aws_region_name: us-east-1
```

Application Inference Profiles are a strong requirement in AWS if you want to know usage / costs per application.

Any idea how to configure it? 🙏

**Comment by ghost** [comment]
maybe relevant to @mirodrr2's issue

**Reply by mknet3** [reply]
Just to link it here -> https://github.com/BerriAI/litellm/issues/8911
I think it is close related, I will look into the issue! Thanks!!

**Comment by mknet3** [comment]
I tested with the latest version ([main-v1.63.11-nightly](https://github.com/BerriAI/litellm/pkgs/container/litellm/374813323?tag=main-v1.63.11-nightly)) and it works perfect. Thank you so much. This is how it works to me:
```yaml
  - model_name: anthropic-claude-3-5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      # You have to set the ARN application inference profile in the model_id parameter
      model_id: arn:aws:bedrock:eu-central-1:000000000000:application-inference-profile/a0a0a0a0a0a0
      aws_region_name: eu-central-1
```
