### DISCUSSION TITLE
How to properly setup vertex claude 3.7?

### DISCUSSION THREAD

**Discussion by ProblemFactory** [BerriAI/litellm#9541] [Q&A]
My GCP account has 1.5M Tokens TPM quote for claude 3.7 on us-east5, but most gemini experimental models are only available in us-central1 (calling with us-east5 credential will result in 404), so I tested around how to properly setup litellm to use us-east5 for clause 3.7 and us-central1 for other models.
However, while I was doing some tests, I found out a weird behavior of litellm. When I setup a wildcard model like this:
```
    - model_name: vertex_ai/*
      litellm_params:
        model: vertex_ai/*
        vertex_project: "*****"
        vertex_location: "us-central1"
```
I can use both gemini experimental models (e.g. `vertex_ai/gemini-2.0-pro-exp-02-05`) and claude 3.7 (`vertex_ai/claude-3-7-sonnet@20250219`). As I further tested, the claude 3.7 calls used my quota on us-east5.

However, if I add another model like this:
```
    - model_name: vertex_ai/us-central1/claude-3-7-sonnet@20250219
      litellm_params:
        model: vertex_ai/claude-3-7-sonnet@20250219
        vertex_project: "*****"
        vertex_location: "us-central1"
```
This model (`vertex_ai/us-central1/claude-3-7-sonnet@20250219`) could not be used, always result in 400.

```
Error occurred while generating model response. Please try again. Error: Error: 400 litellm.BadRequestError: VertexAIException BadRequestError - b'[{\n "error": {\n "code": 400,\n "message": "Project `**{numerical id}**` is not allowed to use Publisher Model `projects/*****/locations/us-central1/publishers/anthropic/models/claude-3-7-sonnet@20250219`",\n "status": "FAILED_PRECONDITION"\n }\n}\n]'. Received Model Group=vertex_ai/claude-3-7-sonnet@20250219 Available Model Group Fallbacks=None
```

Also if I set wildcard model to us-east5, the gemini experimental models will 404.
```
Error occurred while generating model response. Please try again. Error: Error: litellm.NotFoundError: VertexAIException - b'{\n "error": {\n "code": 404,\n "message": "Publisher Model `projects/*****/locations/us-east5/publishers/google/models/gemini-2.0-pro-exp-02-05` not found.",\n "status": "NOT_FOUND"\n }\n}\n'
```

My litellm has no fallback setup, so I believe that is not the issue.

What is causing this weird behavior? Is this expected?

**Comment by ProblemFactory** [comment]
I figured it out. I have another model setup as 
```
    - model_name: vertex_ai/us-east5/claude-3-7-sonnet@20250219
      litellm_params:
        model: vertex_ai/claude-3-7-sonnet@20250219
        vertex_project: "gen-lang-client-0863170297"
        vertex_location: "us-east5"
```
From the debug log, it seems that litellm made a failed request to us-central1 but then retried with us-east5. After I delete this us-east5 model, vertex_ai/claude-3-7-sonnet@20250219 will result in 400 as expected.
