### DISCUSSION TITLE
Batches V2 Implementation / Managed Files

### DISCUSSION THREAD

**Discussion by ghost** [BerriAI/litellm#9632] [Ideas]
Writing down an idea for an improvement on the current batches implementation. Key challanges:
- allow going across providers / deployments when using files 
- consistent cost tracking with the same 'litellm model name'

tldr; if we store the `.jsonl` in the Proxy DB, we could easily go across providers by doing the create/batch operation when required on that deployment 

---

### 1. Setup config.yaml

```yaml
model_list:
   - model_name: gpt-4o-batch
      litellm_params:
        model: azure/gpt-4o-mle-deployment
        api_key: os.environ/AZURE_API_KEY
        api_base: os.environ/AZURE_API_BASE
      model_info:
        mode: batch
```

### 2. User sends file to proxy

```bash
curl http://localhost:4000/v1/files \
  -H "Authorization: Bearer sk-1234" \
  -F purpose="fine-tune" \
  -F file="@mydata.jsonl" # {"model": "gpt-4o-batch", "litellm_params": {..}..}
```

- File stored in proxy DB, as model is a proxy model name.
- All models under ‘model_name’ validated to check if they can serve purpose

### 3. User can create batch request

```bash
curl http://localhost:4000/v1/batches \
        -H "Authorization: Bearer sk-1234" \
        -H "Content-Type: application/json" \
        -d '{
            "input_file_id": "file-abc123",
            "endpoint": "/v1/chat/completions",
            "completion_window": "24h"
    }'
```

- Available deployment picked
- File created in model region
- Batch created for file
- Response returned
