### ISSUE TITLE
[Bug]: Custom Pricing does not seem to work for custom image generation models

### ISSUE THREAD

**Issue by thetonus** [BerriAI/litellm#10023]
### What happened?

For custom image generation models, custom pricing does not work.

When setting `output_cost_per_second` or `output_cost_per_image` in the `model_info` key of the proxy config, the response cost is always zero. After doing some digging, seems that unless the model is a Bedrock or Vertex AI model, it uses the [default](https://github.com/BerriAI/litellm/blob/aff0d1a18c016ad7db4fdbb42ad5065b15b9c5c5/litellm/cost_calculator.py#L755) cost calculator. In that function, it uses `input_cost_per_pixel`. Setting that in the config does not work as well.

It would be great to either set these values in the config and the cost is automatically computed or a special hook in the `CustomLLM` to define custom cost calculation like Vertex AI or Bedrock.

### Relevant log output

```shell
litellm-1  | 16:26:15 - LiteLLM Router:INFO: router.py:1859 - litellm.aimage_generation(model=stable_diffusion/stabilityai/stable-diffusion-xl-base-1.0) 200 OK
litellm-1  | INFO:     192.168.64.1:49938 - "POST /images/generations HTTP/1.1" 200 OK
litellm-1  | 16:26:15 - LiteLLM Proxy:INFO: db_spend_update_writer.py:313 - Writing spend log to db - request_id: 4fa61850-9675-491d-ab24-925a29c1560f, spend: 0.0
litellm-1  | 16:26:15 - LiteLLM Proxy:INFO: db_spend_update_writer.py:864 - Logged request status: success
litellm-1  | 16:26:23 - LiteLLM Proxy:INFO: db_spend_update_writer.py:807 - Processed 1 daily spend transactions in 0.02s
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.66.1

**Comment by thetonus** [comment]
@krrishdholakia  Hate to report that this is still an issue. I upgraded to `1.68.1` and the problem still persists.

**Comment by ghost** [comment]
Hey @thetonus can you share how you're setting this (e.g. your config.yaml) ?

**Comment by thetonus** [comment]
Yes. The model server I am trying to compute cost metrics for is a self-hosted stable diffusion xl model.

```yaml
model_list:
  - model_name: stabilityai/stable-diffusion-xl-base-1-0
    litellm_params:
      model: stable_diffusion/stabilityai/stable-diffusion-xl-base-1-0
      api_base: http://localhost:8888
      api_key: foo
    model_info:
      mode: image_generation
      output_cost_per_second: 0.005690828733333334

litellm_settings:
  request_timeout: 600 # raise Timeout error if call takes longer than 600 seconds. Default value is 6000seconds if not set

  # Custom callbacks
  callbacks: [batch_redis_requests, otel]

  # Mapping custom models
  custom_provider_map:
    - {
        "provider": "stable_diffusion",
        "custom_handler": custom_stable_diffusion.stable_diffusion,
      }
```
