### ISSUE TITLE
[Feature]: Support for AzureAI Image Generation Models

### ISSUE THREAD

**Issue by TobiasGoerke** [BerriAI/litellm#10057]
### The Feature

Azure has recently added [support for stable diffusion models on Azure AI Foundry](https://stability.ai/news/stable-diffusion-35-large-is-now-available-on-microsoft-ai-foundry).

However, deploying and adding the model to the config like shown below will lead to an exception, as a `data` argument was expected but `image` supplied.
```
model_list:
  - model_name: Stable Diffusion
    litellm_params:
      model: azure_ai/stable-diffusion
      api_base: https://your-url.models.ai.azure.com/
      api_key: xxx
    model_info:
      mode: image_generation
```

Exception: 
```
File \"/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/llm_response_utils/convert_dict_to_response.py\", line 296, in convert_to_image_response\nTypeError: ImageResponse.__init__() got an unexpected keyword argument 'image'. Did you mean 'usage'?
```

## "Hacking" the solution

While this is hardly a suitable fix, it shows the `image` param only needs to be mapped / converted to data.
When running litellm with this change added [here](https://github.com/BerriAI/litellm/blob/ca593e003ad8fb072831fbe968f20a853239b5a1/litellm/litellm_core_utils/llm_response_utils/convert_dict_to_response.py#L295), Stable Diffusion works just fine.

```
from litellm.types.utils import ImageObject

# ...

if model_response_dict.get("image") and not model_response_dict.get("data"):
    model_response_dict["data"] = [
        ImageObject(b64_json=model_response_dict["image"])
    ]
    del model_response_dict["image"]
```

### Motivation, pitch

I'm working for a consultancy that is currently testing LiteLLM in multiple projects / for multiple clients. 
We're making sure, all models that are in use can be integrated into LiteLLM before rolling out the platform.

### Are you a ML Ops Team?

Yes
