### ISSUE TITLE
[Feature]: Requests Per Day (rpd) proxy setting (useful for Google models)

### ISSUE THREAD

**Issue by hongkongkiwi** [BerriAI/litellm#10090]
### The Feature

Some providers have requests per day (rpd) limits in additional to rpm & tpm limits.

It would be great to be able to set `rpd: 1000` alongside tpm & rpm which we can currently do. It also makes sense to add tpd (tokens per day) as well since some providers will limit to that, however rpd is the key one for gemini.

See here for the Google Gemini rate limits table and you can see what I mean. I suspect most users will be at tier 1 which means a 1000 rpd limit for their latest models.
https://ai.google.dev/gemini-api/docs/rate-limits#tier-1

I'd like to be able to set something like this:
```
  - model_name: gemini/mytest
     litellm_params:
       model: gemini/gemini-2.5-pro-preview-03-25
       api_key: os.environ/GEMINI_API_KEY
       rpm: 150
       tpm: 2000000
       rpd: 1000
    model_info:
       mode: completion
```

### Motivation, pitch

The rate limits for Google's "good" models are brutal.

### Are you a ML Ops Team?

Yes
