### ISSUE TITLE
[Bug]: default_team_disabled setting is not work

### ISSUE THREAD

**Issue by 22mSqRi** [BerriAI/litellm#10151]
### What happened?

If you set default_team_disabled to true in config.yaml, you can still register a Virtual Key with no Team ID.

config.yaml
```yaml
general_settings:
  default_team_disabled: true
```

docker-compose.yaml
```yaml
version: "3.11"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-v1.66.0-stable
    ########################################
    # Uncomment these lines to start proxy with a config.yaml file ##
    volumes:
     - ./config.yaml:/app/config.yaml
    command:
     - "--config=/app/config.yaml"
    #############################################
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
        DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
        STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
    env_file:
      - .env # Load local .env file
    depends_on:
      - db  # Indicates that this service depends on the 'db' service, ensuring 'db' starts first
    healthcheck:  # Defines the health check configuration for the container
      test: [ "CMD", "curl", "-f", "http://localhost:4000/health/liveliness || exit 1" ]  # Command to execute for health check
      interval: 30s  # Perform health check every 30 seconds
      timeout: 10s   # Health check command times out after 10 seconds
      retries: 3     # Retry up to 3 times if health check fails
      start_period: 40s  # Wait 40 seconds after container start before beginning health checks

 
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists Postgres data across container restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    restart: always

volumes:
  prometheus_data:
    driver: local
  postgres_data:
    name: litellm_postgres_data  # Named volume for Postgres data persistence

```

### Relevant log output

```shell
$ curl --location 'http://0.0.0.0:4000/key/generate' \
--header 'Authorization: Bearer sk-1234' \
--header 'Content-Type: application/json' \
--data '{
  "key_alias": "invalid_key",
  "models": []
}'

{"key_alias":"invalid_key","duration":null,"models":[],"spend":0.0,"max_budget":null,"user_id":null,"team_id":null,"max_parallel_requests":null,"metadata":{},"tpm_limit":null,"rpm_limit":null,"budget_duration":null,"allowed_cache_controls":[],"config":{},"permissions":{},"model_max_budget":{},"model_rpm_limit":null,"model_tpm_limit":null,"guardrails":null,"blocked":null,"aliases":{},"key":"sk-zyjOfSSywQcb0QWPBSVPxw","budget_id":null,"tags":null,"enforced_params":null,"key_name":"sk-...VPxw","expires":null,"token_id":"79fa55365984cb4593bf71523d73ec7eea7c2b260a0ccf67674ff2b9ffeeda5a","litellm_budget_table":null,"token":"sk-zyjOfSSywQcb0QWPBSVPxw","created_by":"default_user_id","updated_by":"default_user_id"}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.66.0-stable
