### ISSUE TITLE
[Bug]: 401 Authentication Error with custom_llm_provider: openai, completion_url, and api_key for Custom Endpoint

### ISSUE THREAD

**Issue by d-ploutarchos** [BerriAI/litellm#10154]
### What happened?

Hi LiteLLM Team and Community,

I'm trying to configure LiteLLM (v1.66.3) to act as a proxy for a custom LLM endpoint provided by Letta (https://letta.com/).

Endpoint Details:

- URL Structure: https://LETTASERVER/v1/agents/<AGENT_ID>/messages (Note the /messagespath, not/chat/completions)
- Authentication: Requires a server password sent as a Bearer token: Authorization: Bearer <server_password>

Working Direct Request (curl):

According to Letta's documentation, the following curl command works directly against their API:

```
curl --request POST \
  --url https://LETTASERVER/v1/agents/AGENT_ID/messages \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer LETTA_PASSWORD' \
  --data '{
  "messages": [
    {
      "role": "user",
      "text": "hows it going????"
    }
  ]
}'
```
(I have verified that this curl command works and that LETTA_PASSWORD is the correct password.)

**LiteLLM Configuration Issue:**

Based on LiteLLM documentation for custom OpenAI-compatible providers and the Letta API details, the following configuration in litellm.config.yaml should theoretically work:

```
model_list:
  - model_name: letta-business-coach    # Alias for clients
    litellm_params:
      model: custom/letta-business-coach # Internal name
      litellm_provider: custom
      custom_llm_provider: openai        # Treat as OpenAI compatible
      # Use completion_url for the specific /messages endpoint
      completion_url: "https://LETTASERVER/v1/agents/AGENT_ID/messages"
      # Provide the Letta Server Password via api_key for Bearer auth
      api_key: "LETTA_PASSWORD"
```

**Error Encountered:**
When using the configuration above and sending a request to the LiteLLM proxy (http://PROXY_URL:4000/v1/chat/completions with model: letta-business-coach), I consistently receive the following error:
```
{
    "error": {
        "message": "litellm.AuthenticationError: AuthenticationError: OpenAIException - Incorrect API key provided. Received Model Group=letta-business-coach\\nAvailable Model Group Fallbacks=None",
        "type": "proxy_error", // Or similar type
        "param": null,
        "code": "401"
    }
}
```
This 401 error occurs despite confirming that the password provided in the api_key field is 100% correct.

**Other Configurations Tried (and why they failed):**

- Using api_base instead of completion_url: Results in 404 or 405 errors, likely because LiteLLM appends /chat/completions to the base URL.
- Using explicit headers: block with Authorization: Bearer ...: Causes errors requiring api_key when custom_llm_provider: openai is set, or doesn't resolve the 401 if api_key is also present.
- Removing custom_llm_provider: openai: Leads to errors requiring api_base or api_key to be set.

**Suspected Problem:**

It seems there might be an issue with how LiteLLM handles the api_key parameter when custom_llm_provider: openai is used in combination with completion_url. It appears the api_key might not be correctly translated into the Authorization: Bearer <password> header when the request is forwarded to the completion_url, leading to the 401 from the target server.

**Question:**

Is there a known issue or a specific configuration nuance required to make LiteLLM correctly handle Bearer token authentication (via api_key) for an OpenAI-compatible custom provider when using completion_url to target a non-standard path like /messages?

Any help or pointers would be greatly appreciated!

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.66.3
