### ISSUE TITLE
[Bug]: set verbose on config.yaml breaks proxy streaming

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1030]
### What happened?

turning on verbose seems to break streaming calls. I can reproduce the issue 100% of the time. if set_verbose is set to True, I cant make streaming chat completion calls to my models. With it set to False it works fine.

### Relevant log output

```shell
litellm_settings: 
      set_verbose: True
```

**Comment by ghost** [comment]
unable to repro this -  

<img width="823" alt="Screenshot 2023-12-06 at 2 20 11 PM" src="https://github.com/BerriAI/litellm/assets/17561003/16244636-5652-45e8-84f7-f17704477be3">

<img width="958" alt="Screenshot 2023-12-06 at 2 18 50 PM" src="https://github.com/BerriAI/litellm/assets/17561003/e7c32470-52de-4f86-a7e6-ca3f3469f626">

**Comment by ghost** [comment]
For context, this is my config.yaml 

```yaml 
model_list: 
  - model_name: "cloudflare-azure-model"
    litellm_params:
      model: "azure/gpt-turbo"
      api_key: "os.environ/AZURE_FRANCE_API_KEY"
      api_base: "https://gateway.ai.cloudflare.com/v1/fa4cdcab1f32b95ca3b53fd36043d691/test/azure-openai/openai-france-1234"
  - model_name: "bedrock-cohere"
    litellm_params:
      model: "bedrock/cohere.command-text-v14"
      aws_region_name: "us-east-1"
  - model_name: "bedrock-cohere"
    litellm_params:
      model: "bedrock/cohere.command-text-v14"
      aws_region_name: "us-west-2"
  - model_name: "bedrock-titan"
    litellm_params:
      model: "bedrock/amazon.titan-text-express-v1"
      aws_region_name: "us-west-2"
  - model_name: "bedrock-ai21"
    litellm_params:
      model: "bedrock/ai21.j2-mid-v1"
      aws_region_name: "us-west-2"
  - model_name: "bedrock-ai21"
    litellm_params:
      model: "bedrock/ai21.j2-mid-v1"
      aws_region_name: "us-west-2"
    model_info:
      id: "sk-1234"
  

litellm_settings:
  drop_params: True
  set_verbose: True

```
