### ISSUE TITLE
[Bug]: Azure Get/Delete Responses API Proxy 400 Errors

### ISSUE THREAD

**Issue by marty-sullivan** [BerriAI/litellm#10359]
### What happened?

@ishaan-jaff When trying to use your new GET/DELETE responses endpoints with an Azure deployment, I'm getting the following exception in proxy server. 

Same exception is raised for both `responses.retrieve` and `responses.delete`

```python
from openai import OpenAI

client = OpenAI()

prompt = """Write a very short story for a child's bedtime"""
model_name = 'openai.gpt-4.1-nano'

response = client.responses.create(
    model=model_name,
    input=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
)

retrieved_response = client.responses.retrieve(
    response_id=response.id,
)

print(retrieved_response.model_dump_json(indent=2))
```

### Relevant log output

```shell
[92m09:15:39 - LiteLLM Proxy:ERROR[0m: common_request_processing.py:344 - litellm.proxy.proxy_server._handle_llm_api_exception(): Exception occured - 400: {'error': 'aget_responses: Invalid model name passed in model=None. Call `/v1/models` to view available models for your key.'}
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/litellm/proxy/response_api_endpoints/endpoints.py", line 128, in get_response
    return await processor.base_process_llm_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<16 lines>...
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm/proxy/common_request_processing.py", line 243, in base_process_llm_request
    llm_call = await route_request(
               ^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm/proxy/route_llm_request.py", line 115, in route_request
    raise ProxyModelNotFoundError(
    ...<2 lines>...
    )
litellm.proxy.route_llm_request.ProxyModelNotFoundError: 400: {'error': 'aget_responses: Invalid model name passed in model=None. Call `/v1/models` to view available models for your key.'}
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.67.4

**Comment by marty-sullivan** [comment]
A note, I do have the routing prechecks enabled:

```yaml
router_settings:
  routing_strategy: 'usage-based-routing-v2'
  optional_pre_call_checks: 
    - 'prompt_caching'
    - 'responses_api_deployment_check'
```

**Comment by marty-sullivan** [comment]
@ishaan-jaff @krrishdholakia still seeing this error in 1.68.0

**Comment by ishaan-jaff** [comment]
Can I see how you set up your model list on the config?

**Comment by marty-sullivan** [comment]
@ishaan-jaff just several entries like:

```yaml
  - model_name: 'openai.gpt-4.1-nano'
    litellm_params:
      model: 'azure/gpt-4.1-nano-2025-04-14'
      api_base: 'https://example.openai.azure.com/'
      api_version: '2025-03-01-preview'
      api_key: 'secret'
```

I suppose there is probably a need to specify a specific azure openai deployment somewhere in the request as in the files setup?
