### ISSUE TITLE
[Bug]: Future attached to a different loop in DualCache.async_batch_get_cache()

### ISSUE THREAD

**Issue by kunalchamoli** [BerriAI/litellm#10376]
### What happened?

Hello, I am getting the following error in my litellm setup, with the following settings.
```
litellm_settings:
  cache: true
  cache_params:
    type: redis
    ttl: 600
    host: $REDIS_HOST
    port: $REDIS_PORT
    password: $REDIS_PASSWORD
```

### Relevant log output

```shell
{"message": "Error occurred in async batch get cache - Task <Task pending name='Task-375' coro=<DualCache.async_batch_get_cache() running at /usr/lib/python3.13/site-packages/litellm/caching/dual_cache.py:280> cb=[run_until_complete.<locals>.done_cb()]> got Future <Future pending> attached to a different loop", "level": "ERROR", "timestamp": "2025-04-28T07:19:56.435537"}
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v65.0
