### ISSUE TITLE
[Bug]: 2 `mcp` servers with the same `tool_name` - Allow specifying mcp_server when calling mcp_tool 

### ISSUE THREAD

**Issue by zigelboim-misha** [BerriAI/litellm#10404]
### What happened?

I can configure 2 `mcp` servers with the same `tool_name`s (but different parameters like different `GitHub` organizations):

```yaml
mcp_servers:
    {
        "github-A": {
            "url": "http://github-mcp-server-a.mcp.svc.cluster.local:8000/sse",
        },
        "github-B": {
            "url": "http://github-mcp-server-b.mcp.svc.cluster.local:8000/sse",
        }
    }
```

When I fetch all tools i get the following expected result:

```json
[
    {
        "name": "get_me",
        "description": "Get details of the authenticated GitHub user. Use this when a request include \"me\", \"my\"...",
        "inputSchema": {
            "type": "object",
            "properties": {
                "reason": {
                    "description": "Optional: reason the session was created",
                    "type": "string"
                }
            }
        },
        "mcp_info": {
            "server_name": "github-A"
        }
    },
    {
        "name": "get_me",
        "description": "Get details of the authenticated GitHub user. Use this when a request include \"me\", \"my\"...",
        "inputSchema": {
            "type": "object",
            "properties": {
                "reason": {
                    "description": "Optional: reason the session was created",
                    "type": "string"
                }
            }
        },
        "mcp_info": {
            "server_name": "github-B"
        }
    }
]
```

And when I want to call one of these tools, it only uses the latest `mcp` server:

```bash
curl -X 'POST' "http://localhost:4000/mcp/tools/call" \
     -H "Content-Type: application/json" \
     -H "Accept: */*" \
     -d '{
            "name": "get_me",
            "arguments": {"reason":"test"},
        }'
```

I haven't found a way in the docs to decide which `mcp` server to use if multiple are available...

---

I have found this inner dict:

- https://github.com/BerriAI/litellm/blob/f984089b013709a4bd666bec158afee95770ea5c/litellm/proxy/_experimental/mcp_server/mcp_server_manager.py#L103

Where only the last `mcp` server is stored per `tool_name`.

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.67.4-stable
