### ISSUE TITLE
[Bug]: Azure Audio Transcription & DALL-E (Access denied)

### ISSUE THREAD

**Issue by nikes** [BerriAI/litellm#10440]
### What happened?

Where use **whisper, dall-e, or gpt-4o-transcribe** this not work, in logs display `Access denied due to invalid subscription key or wrong API endpoint`

I check native openai library with this API key & endpoint and it work fine.

config.yaml
```
  - model_name: gpt-4o-transcribe
    litellm_params:
      model: "azure/gpt-4o-transcribe"
      api_base: "https://<RESOURCE>.openai.azure.com/"
      api_version: "2025-03-01-preview"
      api_key: os.environ/AZURE_API_KEY_SE
      tpm: 100000
      rpm: 10000
    model_info:
      mode: audio_transcription

  - model_name: whisper
    litellm_params:
      model: "azure/whisper"
      api_base: "https://<RESOURCE>.openai.azure.com/"
      api_version: "2024-06-01"
      api_key: os.environ/AZURE_API_KEY_EUS2
      rpm: 3
    model_info:
      mode: audio_transcription
```

### Relevant log output

```shell
Type:
HTTPException
Message:
500: litellm.AuthenticationError: AzureException AuthenticationError - Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.. Received Model Group=whisper Available Model Group Fallbacks=None
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v.1.67.5
