### ISSUE TITLE
Use HTTP or SOCKS proxy

### ISSUE THREAD

**Issue by bitnom** [BerriAI/litellm#10453]
I would like to litellm to use an HTTP or SOCKS proxy for its connections. I searched the docs and issues but have not found it. How can this be done?

**Comment by ObjectiveTruth** [comment]
This is what I did and seemed to work though it would be nice to have it already included.
It uses env vars but hopefully it'll help someone that was in my shoes

```yaml
containers:
  - name: litellm
    image: dockerproxyregistry.home.objectivetruth.ca/berriai/litellm:main-latest
    imagePullPolicy: Always
    ports:
      - containerPort: 4000
    env:
      - name: ALL_PROXY
        value: "socks5://localhost:1052"
      - name: NO_PROXY
        value: "localhost,127.0.0.1"
    command: ["/bin/sh", "-c"]
    args:
      - pip install httpx[socks] pysocks --no-cache-dir \
          && exec docker/prod_entrypoint.sh --port 4000 --config /app/config/config.yml
```


The above still uses the official container but I intercept the `entrypoint.sh` and install the httpx[socks] and pysocks package to allow for http proxies.

This way it can read ALL_PROXY and NO_PROXY env vars and use those when needed
