### ISSUE TITLE
[Bug]: /file Unable to use files_settings with Azure config unless env vars are explicitly set

### ISSUE THREAD

**Issue by lloukmane** [BerriAI/litellm#10561]
### What happened?

Hi team,

We’re encountering an issue when using files_settings in the config file to define a custom Azure provider. Here's the configuration we’re using: 
```
files_settings:
  - custom_llm_provider: azure
    api_base: https://resource.openai.azure.com
    api_key: os.environ/MY_KEY
    api_version: "my_version"
```
Despite providing api_base, api_key, and api_version in the config, we receive the below error.

It seems like litellm still expects env vars listed in [proxy_server_config.yaml](https://github.com/BerriAI/litellm/blob/main/proxy_server_config.yaml#L176) even though the config file explicitly defines everything.

### Relevant log output

```shell
{
  "error": {
    "message": "Must provide one of the `base_url` or `azure_endpoint` arguments, or the `AZURE_OPENAI_ENDPOINT` environment variable",
    "type": "None",
    "param": "None",
    "code": "500"
  }
}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.57.0
