### ISSUE TITLE
[Bug]: LiteLLM Startup Stuck at All necessary views exist!

### ISSUE THREAD

**Issue by andrefecto** [BerriAI/litellm#10577]
### What happened?

If you try to restart your LiteLLM container, you will intermittently get stuck at "All necessary views exist!" and the uvicorn server does not start.

### Relevant log output

```shell
23:52:22 - LiteLLM Proxy:DEBUG: utils.py:1158 - Creating Prisma Client..
23:52:23 - LiteLLM Proxy:DEBUG: utils.py:1181 - Success - Created Prisma Client
23:52:23 - LiteLLM Proxy:DEBUG: utils.py:2227 - PrismaClient: connect() called Attempting to Connect to DB
23:52:23 - LiteLLM Proxy:DEBUG: utils.py:2231 - PrismaClient: DB not connected, Attempting to Connect to DB
23:52:23 - LiteLLM Proxy:DEBUG: proxy_server.py:578 - prisma_client: <litellm.proxy.utils.PrismaClient object at 0x7fb4ba58dd30>
23:52:23 - LiteLLM Proxy:DEBUG: proxy_server.py:2316 - len new_models: 0
23:52:24 - LiteLLM Proxy:INFO: utils.py:1288 - All necessary views exist!
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.68.0

**Comment by andrefecto** [comment]
Bump. This is making LiteLLM unreliable as a service because it is unable to come back online without manual intervention.

**Comment by ghost** [comment]
Hey @andrefecto can you confirm you see this on the latest stable release? 

If so - what is your config (to repro)

**Comment by andrefecto** [comment]
@krrishdholakia This is happening on the latest 1.69 version, and with two different configs.
Config 1:
```
general_settings:
  disable_spend_logs: false
  store_model_in_db: True
  store_prompts_in_spend_logs: True
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 1
  database_connection_pool_limit: 10
  forward_client_headers_to_llm_api: true
litellm_settings:
  drop_params: True
  num_retries: 5
  request_timeout: 600
  telemetry: False
```

Config 2:
```
litellm_settings:
  drop_params: true
  num_retries: 5
  request_timeout: 600
general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
  proxy_batch_write_at: 1
  database_connection_pool_limit: 20
  forward_client_headers_to_llm_api: true
  telemetry: False
guardrails:
  - guardrail_name: "lakera-pre-guard"
    litellm_params:
      guardrail: lakera
      mode: "pre_call"
      api_key: "os.environ/LAKERA_API_KEY"
model_list:
  - model_name: "stability.stable-image-core-v1:1"
    litellm_params:
      model: "bedrock/stability.stable-image-core-v1:1"
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
      aws_region_name: "os.environ/AWS_REGION_NAME"
  - model_name: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
    litellm_params:
      model: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
      aws_region_name: "os.environ/AWS_REGION_NAME"
  - model_name: gpt-4o
    litellm_params:
      model: "azure/gpt-4o"
      api_base: "os.environ/AZURE_API_BASE"
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "os.environ/AZURE_API_VERSION"
  - model_name: text-embedding-3-small
    model_info:
      mode: embedding
    litellm_params:
      model: "azure/text-embedding-3-small"
      api_base: "os.environ/AZURE_API_BASE"
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "os.environ/AZURE_API_VERSION"
  - model_name: gpt-4o-mini-tts
    model_info:
      mode: audio.speech
    litellm_params:
      model: "azure/gpt-4o-mini-tts"
      api_base: "os.environ/AZURE_US_EAST_2_API_BASE"
      api_key: "os.environ/AZURE_US_EAST_2_API_KEY"
      api_version: "os.environ/AZURE_US_EAST_2_API_VERSION"
  - model_name: gpt-4o-mini-transcribe
    model_info:
      mode: audio.transcription
    litellm_params:
      model: "azure/gpt-4o-mini-transcribe"
      api_base: "os.environ/AZURE_API_BASE_US_EAST_2"
      api_key: "os.environ/AZURE_API_KEY_US_EAST_2"
      api_version: "os.eviron/AZURE_API_VERSION_US_EAST_2"
```

Let me know if you need anything else.
