### ISSUE TITLE
[Bug]: LiteLLM Proxy to Transcription Model Fails

### ISSUE THREAD

**Issue by klaudworks** [BerriAI/litellm#10584]
### What happened?

I am successfully running LLMs, served via vLLM, behind LiteLLM. The setup is running in Kubernetes.

However, I can't seem to get Whisper as a transcription model running. The error I encounter is the following:

```
curl --location 'https://vllm.embraceable.cloud/v1/audio/transcriptions' \
--header 'Authorization: Bearer sk-XXX' \
--form 'file=@"test.mp3"' \
--form 'model="whisper-tiny"' 

{
   "error":{
      "message":"litellm.BadRequestError: OpenAIException - Currently only support response_format `text` or `json`. Received Model Group=whisper-tiny\nAvailable Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2",
      "type":"None",
      "param":"None",
      "code":"500"
   }
}
```

Bypassing LiteLLM and accessing the vLLM Service directly via port forwarding works. 

```
curl --location 'http://localhost:8080/v1/audio/transcriptions' \
--form 'file=@"/Users/nico/Downloads/test.mp3"' \
--form 'model="openai/whisper-tiny"'

{"text":" Hello, this is a short test to test the WISPA transcription service."}%  
```

The LiteLLM config looks as follows:

```yaml
model_list:
  - model_name: phi-4
    litellm_params:
      model: openai/microsoft/phi-4
      api_base: http://vllm-phi-4-leader:8080/v1
      api_key: dummy
  - model_name: phi-4-mini-instruct
    litellm_params:
      model: openai/microsoft/phi-4-mini-instruct
      api_base: http://vllm-phi-4-mini-instruct-leader:8080/v1
      api_key: dummy
  - model_name: whisper-tiny
    litellm_params:
      model: openai/openai/whisper-tiny
      api_base: http://vllm-whisper-tiny-leader:8080/v1
      api_key: dummy
      model_info:
        mode: audio_transcription
```

The same error also occurs when I use the Python OpenAI client and explicitly specify response_format="json":

```
from openai import OpenAI

from vllm.assets.audio import AudioAsset

mary_had_lamb = AudioAsset('mary_had_lamb').get_local_path()

openai_api_key = "sk-XXX"
openai_api_base = "https://vllm.embraceable.cloud/vllm/v1"

client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base
)

try:
    with open(str(mary_had_lamb), "rb") as audio_file:
        transcription = client.audio.transcriptions.create(
            response_format="json",
            model="openai/whisper-tiny", 
            file=audio_file,
            language="en", 
            temperature=0.0         
        )
        print("Transcription result:", transcription.text)
except FileNotFoundError:
    print(f"Error: Audio file not found at {mary_had_lamb}")
except Exception as e:
    print(f"An error occurred during transcription: {e}")
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

litellm/litellm:v1.67.0-stable

**Comment by cyvcloud** [comment]
We are facing the same problem and would be interested in a solution.

**Comment by klaudworks** [comment]
The issue seems to be that the API request sent by LiteLLM to the vLLM hosted model is `verbose_json` which is not supported by the model hosted via vLLM.

```
curl -X POST \
  http://vllm-whisper-large-leader:8080/v1/ \
  -H 'Content-Type: application/json' \
  -d '{
  {
    "model": "distil-whisper/distil-large-v3.5",
    "file": {},
    "timestamp_granularities": null,
    "response_format": "verbose_json"
  }
  }'
```

is there any way to change this to just "json" in LiteLLM?

**Comment by lentiann** [comment]
Hi guys, i have tested this feature myself from openwebui to litellm proxy, i think the audio file should converted to wav type.
Use this when you want to limit the file size for requests sent to `audio/transcriptions`

This text is taken from docs/my-website/docs/text_to_speech.md might be helpfull for your case

```yaml
- model_name: whisper
  litellm_params:
    model: whisper-1
    api_key: sk-*******
    max_file_size_mb: 0.00001 # 👈 max file size in MB  (Set this intentionally very small for testing)
  model_info:
    mode: audio_transcription
```

Make a test Request with a valid file
```shell
curl --location 'http://localhost:4000/v1/audio/transcriptions' \
--header 'Authorization: Bearer sk-1234' \
--form 'file=@"/Users/ishaanjaffer/Github/litellm/tests/gettysburg.wav"' \
--form '
