### ISSUE TITLE
[Bug]: Most of system OTEL traces are duplicated

### ISSUE THREAD

**Issue by hnykda** [BerriAI/litellm#10588]
### What happened?

For some reason, some of the spans are logged exactly twice. The only thing that is different is `SpanID`, otherwise they are totally identical. 

```
  litellm_settings:
    callbacks: ["otel"]

  envVars:
   OTEL_EXPORTER: "otlp_grpc"
   OTEL_ENDPOINT: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4317"
   OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
   OTEL_TRACES_SAMPLER_ARG: "0.001"
```

![Image](https://github.com/user-attachments/assets/f8fdb8cc-54c8-4c48-98d4-77633177033c)

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.67.4-stable
