### ISSUE TITLE
[Bug]: Spend tracking per request is always zero (both input and output per token are zero in metadata)

### ISSUE THREAD

**Issue by eyaldar** [BerriAI/litellm#10598]
### What happened?

Hi, I'm trying to get spend tracking working and can't figure out if it's not supported in the OSS version or whether i'm doing something wrong. I have a local setup that includes litellm proxy server, postgres, redis and ollama in a docker-compose. I've tried sending completion requests to both openai/o4-mini and ollama/tinyllama with custom pricing but I just can't it to show any spending details bigger than zero - the models are shown with the correct pricing per 1M tokens in model hub but whenever I send a request the logging shows spend as zero and usage doesn't calculate any spending. 
I've tried using both user virtual key and just virtual key.

I should note - I do get responses for my completion request and the validation for the right models per defined key works great, so does the UI, this is strictly about the spend tracking feature.

This is my config:
```yaml
model_list:
  - model_name: ollama/tinyllama
    litellm_params:
      model: ollama/tinyllama
      api_base: http://ollama:11434
      temperature: 0.7
      max_tokens: 10000
      context_window: 2048
      input_cost_per_token: 0.000006
      output_cost_per_token: 0.00003
  - model_name: openai/o4-mini
    litellm_params:
      model: openai/o4-mini
      temperature: 0.7
      max_tokens: 10000

model_info:
  ollama/tinyllama:
    input_cost_per_token: 0.000006
    output_cost_per_token: 0.00003

litellm_settings:
  drop_params: true
  set_verbose: true
  request_timeout: 600
  cache: true
  cache_params:
    type: redis
    host: redis
    port: 6379

general_settings:
  completion_model: ollama/tinyllama
  embedding_model: ollama/tinyllama
  cache: redis
  redis_url: redis://redis:6379
  database_url: postgresql://litellm:litellm@postgres:5432/litellm
  database_connection_pool_limit: 100
  database_connection_timeout: 60
  background_health_checks: false
  health_check_interval: 300
  store_model_in_db: true
  store_prompts_in_spend_logs: true
```

and this is my docker-compose:
```yaml
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.68.0-stable
    platform: linux/arm64/v8
    volumes:
      - ./litellm_config.yaml:/home/litellm/config.yaml
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=litellm
      - POSTGRES_USER=litellm
      - POSTGRES_PASSWORD=litellm
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_API_BASE=http://ollama:11434
    env_file:
      - ../.env
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    command: --config /home/litellm/config.yaml --detailed_debug

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull tinyllama &&
        wait
      "

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=litellm
      - POSTGRES_USER=litellm
      - POSTGRES_PASSWORD=litellm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  ollama_data: 
```

Additionally my .env include two environment variables: OPENAI_API_KEY and LITELLM_MASTER_KEY.

Thanks in advance!

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

litellm:main-v1.68.0-stable
