### ISSUE TITLE
How to config 3rd part API provider use tokenizer base on model name ?

### ISSUE THREAD

**Issue by eromoe** [BerriAI/litellm#10614]
For example, I am using a 3rd part deepseek v3 API from volcengine . And there is no token counter and usage by default .

I found I need add below to count tokens. 
```
  - model_name: deepseek-v3-241226
    litellm_params:
      model: volcengine/deepseek-v3-241226
      api_base: https://ark.cn-beijing.volces.com/api/v3
      api_key: "os.environ/VOLCENGINE_API_KEY"
      provider: volcengine
    model_info:
      access_groups: ["restricted-models"]
      custom_tokenizer: 
        identifier: deepseek-ai/DeepSeek-V3-Base
        revision: main
        auth_token: os.environ/HUGGINGFACE_API_KEY

```

But is there an easy way to tell litellm this is a deepseek-v3 model, so that no need config HUGGINGFACE_API_KEY .
