### ISSUE TITLE
[Bug]: Swagger and Ui issue with kubernetes

### ISSUE THREAD

**Issue by kbencherif** [BerriAI/litellm#10626]
### What happened?

I have a lite llm service running on k8s behind the path /llm.
I built the image with the UI_BASE_PATH env var like the doc and set the env var SERVER_ROOT_PATH to /llm
Unfortunately I dont have any access to the UI or the swagger

here is my Dockerfile
```Dockerfile
FROM ghcr.io/berriai/litellm:main-v1.68.0-stable

WORKDIR /app

RUN apk upgrade --no-cache && apk add --update npm curl

ENV NVM_DIR=/root/.nvm

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

ENV NODE_VERSION=18.17.0

ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN mkdir -p $NVM_DIR && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
    . $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && nvm use default


RUN mkdir -p config

COPY ./config.yaml ./config
COPY ./google_credentials.json ./config

WORKDIR /app/ui/litellm-dashboard
RUN npm install

ENV UI_BASE_PATH=/llm/ui

RUN UI_BASE_PATH=$UI_BASE_PATH npm run build

RUN mkdir -p /app/litellm/proxy/_experimental/out

RUN rm -rf /app/litellm/proxy/_experimental/out/* && \
    mv ./out/* /app/litellm/proxy/_experimental/out/

WORKDIR /app

RUN chmod +x ./docker/entrypoint.sh
RUN chmod +x docker/prod_entrypoint.sh

EXPOSE 4000/tcp

CMD ["--port", "4000", "--config", "./config/config.yaml"]
```

And my ingress config:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lite-llm
  namespace: application

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /llm
        pathType: Prefix
        backend:
          service:
            name: lite-llm
            port:
              number: 4000```

### Relevant log output

```shell
On /llm/ui:
All the request are made on https://mydns.com/ui/_next/*

On /llm:
I have this error on the console:
Uncaught ReferenceError: SwaggerUIBundle is not defined
    <anonymous> https://mydns.com/llm/:15

and all the request are made in /swagger/* instead of /llm/swagger/* which is accessible with curl.
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.68.0
