### ISSUE TITLE
[Bug]: support for read-only filesystem Docker deployment

### ISSUE THREAD

**Issue by miguelangelmorenochacon** [BerriAI/litellm#10624]
### What happened?

We're trying to deploy the LiteLLM proxy in a very secure environment, non-root and read-only filesystem, and we're facing some major issues, is the product read to work in this kind of scenario?

This is the Kubernetes deployment we're using

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        # Custom image with non-root user
        image: litellm:v1.68.0-stable-non-root
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: config-volume
          mountPath: /app/proxy_server_config.yaml
          subPath: config.yaml
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
        env:
          - name: STORE_MODEL_IN_DB
            value: "True"
          - name: LITELLM_MASTER_KEY
            value: sk-xxxxxxxxxxxxxxxxxxxxxxxx
          - name: LITELLM_SALT_KEY
            value: sk-xxxxxxxxxxxxxxxxxxxx
          - name: DATABASE_URL
            value: postgresql://litellm:litellm@10.147.0.3:5432/litellm
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
              - NET_RAW
      imagePullSecrets:
        - name: github-actions-artifacts
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
      securityContext:
        supplementalGroups: [101]
        fsGroup: 1000
```

### Relevant log output

```shell
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/proxy/common_request_processing.py", line 256, in base_process_llm_request
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     responses = await llm_responses
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:                 ^^^^^^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 961, in acompletion
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise e
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 937, in acompletion
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     response = await self.async_function_with_fallbacks(**kwargs)
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 3423, in async_function_with_fallbacks
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise original_exception
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 3237, in async_function_with_fallbacks
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     response = await self.async_function_with_retries(*args, **kwargs)
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 3615, in async_function_with_retries
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise original_exception
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 3506, in async_function_with_retries
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     response = await self.make_call(original_function, *args, **kwargs)
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 3624, in make_call
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     response = await response
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:                ^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 1100, in _acompletion
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise e
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/router.py", line 1059, in _acompletion
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     response = await _response
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:                ^^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/utils.py", line 1461, in wrapper_async
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise e
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/utils.py", line 1322, in wrapper_async
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     result = await original_function(*args, **kwargs)
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/main.py", line 526, in acompletion
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise exception_type(
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:           ~~~~~~~~~~~~~~^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:         model=model,
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:         ^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     ...<3 lines>...
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:         extra_kwargs=kwargs,
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:         ^^^^^^^^^^^^^^^^^^^^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     )
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     ^
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2224, in exception_type
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise e
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:   File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 459, in exception_type
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     raise APIError(
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     ...<6 lines>...
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]:     )
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]: litellm.exceptions.APIError: litellm.APIError: APIError: OpenAIException - Connection error.. Received Model Group=gpt-4o
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]: Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
dedicated-19729/litellm-deployment-7c8bfd9fd6-gfhkg[litellm]: INFO:     127.0.0.1:42830 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.68.0-stable
