### ISSUE TITLE
[Docs]: Add proxy / sentry logging to docs

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1067]
### The Feature

Once this commit is published - https://github.com/BerriAI/litellm/commit/f06c3e0f08cddd8079955f355612e2517c076055

Add a tutorial in docs on how to add sentry to the proxy: 

```yaml
litellm_settings:
    # ... other settings
    failure_callback: ["sentry']
```

This will enable even failed db read/writes to be captured

### Motivation, pitch

user had faced failed db calls. provide them with better logging for this.
