### ISSUE TITLE
[Bug]: Custom server root path not working properly

### ISSUE THREAD

**Issue by miguelangelmorenochacon** [BerriAI/litellm#10761]
### What happened?

We've tried to set a custom server root path and is not working. The custom server root path is `/litellm` and UI is set to. `/litellm/ui`, but when accessing the LiteLLM UI, we got redirected to `/sso/key/generate`, when it should be `/litellm/sso/key/generate`

We have the LiteLLM deployment running behind an NGINX proxy that is forwarding the requests matching `/litellm/*`, so the `/sso/key/generate` doesn't match and a 404 error is returned

**Dockerfile**

```Dockerfile
# Use the provided base image
FROM ghcr.io/berriai/litellm:main-v1.68.0-stable

################################################################################
# Configure custom server root path
################################################################################

# https://docs.litellm.ai/docs/proxy/deploy#1-custom-server-root-path-proxy-base-url
# https://github.com/CartoDB/litellm/blob/v1.68.0-stable/docker/Dockerfile.custom_ui

# Set the working directory to /app
WORKDIR /app

# Install Node.js and npm (adjust version as needed)
# FIXME: With the latest nodejs version, the build never ends
RUN apk add --no-cache nodejs=20.18.3-r0 npm

# Copy the UI source into the container
COPY ./ui/litellm-dashboard /app/ui/litellm-dashboard

# Set an environment variable for UI_BASE_PATH
# This can be overridden at build time
# set UI_BASE_PATH to "<your server root path>/ui"
# 👇👇 Enter your UI_BASE_PATH here
ENV UI_BASE_PATH="/litellm/ui"

# Build the UI with the specified UI_BASE_PATH
WORKDIR /app/ui/litellm-dashboard
RUN npm install
RUN UI_BASE_PATH=${UI_BASE_PATH} npm run build

# Create the destination directory
RUN mkdir -p /app/litellm/proxy/_experimental/out

# # Move the built files to the appropriate location
# # Assuming the build output is in ./out directory
# RUN rm -rf /app/litellm/proxy/_experimental/out/* && \
#     mv ./out/* /app/litellm/proxy/_experimental/out/

# Move the built files to the appropriate location
# Assuming the build output is in ./out directory
RUN rm -rf /usr/lib/python3.13/site-packages/litellm/proxy/_experimental/out/* && \
    mv -f ./out/* /usr/lib/python3.13/site-packages/litellm/proxy/_experimental/out/

################################################################################

################################################################################
# Allow running with non-root user
################################################################################

# https://github.com/CartoDB/litellm/blob/v1.68.0-stable/docker/Dockerfile.non_root

# Switch back to the main app directory
WORKDIR /app

# Create the litellm user (non-root user)
RUN adduser -D litellm

# Prisma allows you to specify the binary cache directory to use
ENV PRISMA_BINARY_CACHE_DIR=/nonexistent

RUN pip install --no-cache-dir nodejs-bin prisma

# Make a /non-existent folder and assign chown to nobody
RUN mkdir -p /nonexistent && \
    chown -R litellm:litellm /app && \
    chown -R litellm:litellm /nonexistent && \
    chown -R litellm:litellm /usr/lib/python3.13/site-packages/prisma/

RUN chmod +x docker/entrypoint.sh
RUN chmod +x docker/prod_entrypoint.sh

# Run Prisma generate as user = litellm
USER litellm

RUN prisma generate

################################################################################
```

**Kubernetes**

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
data:
  config.yaml: |
    litellm_settings:
      json_logs: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        # Custom image with non-root user
        image: gcr.io/carto-artifacts/litellm:v1.68.0-stable-carto
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: config-volume
          mountPath: /app/proxy_server_config.yaml
          subPath: config.yaml
        - name: litellm-migration-dir
          mountPath: /tmp/prisma/migrations
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
        env:
          - name: STORE_MODEL_IN_DB
            value: "True"
          - name: LITELLM_MASTER_KEY
            value: sk-xxxxxxxxxxxxxxxxxx
          - name: LITELLM_SALT_KEY
            value: sk-xxxxxxxxxxxxxxxxxxxxxx
          # FIXME: The LiteLLM database and user has been manually created
          - name: DATABASE_URL
            value: postgresql://litellm:litellm@10.147.0.3:5432/litellm?sslmode=require
          # Required for read-only filesystem
          - name: LITELLM_MIGRATION_DIR
            value: /tmp/prisma/migrations
          - name: USE_PRISMA_MIGRATE
            value: "True"
          - name: SERVER_ROOT_PATH
            value: /litellm
          - name: HTTP_PROXY
            value: http://proxy:3128
          - name: HTTPS_PROXY
            value: http://proxy:3128
          - name: GRPC_PROXY
            value: http://proxy:3128
          - name: NO_PROXY
            value: localhost,127.0.0.1
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
              - NET_RAW
      imagePullSecrets:
        - name: github-actions-artifacts
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
        # Required for read-only filesystem
        - name: litellm-migration-dir
          emptyDir: {}
      securityContext:
        supplementalGroups: [101]
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.68.0-stable
