### ISSUE TITLE
[Enhancement]: Expand additional drop params to cover non-openai params

### ISSUE THREAD

**Issue by gustavz** [BerriAI/litellm#10791]
### What happened?

My understanding of `drop_params` is that it should drop unsupported params before making a call to the LLM provider. Is this correct? if yes then it does not work. If not please explain what it should actually do 🙏 

### Relevant log output

```shell
import litellm

response = litellm.completion(
    model="gpt-4", 
    messages=[{"role": "user", "content": "Hey, how's it going?"}],
    system_prompt="you are a bad pirate", # NOT SUPPORTED PARAM
    drop_params=True,
    )

>>
BadRequestError: litellm.BadRequestError: OpenAIException - Unrecognized request argument supplied: system_prompt
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.67.4.post1

**Comment by gustavz** [comment]
@krrishdholakia

**Comment by amoghnalwaya** [comment]
Same issue but going through config

```
model_list:
  - model_name: openai:gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      drop_params: true
      additional_drop_params:
        - red
```
On running 

```
import requests

url = "http://0.0.0.0:4000/chat/completions"

headers = {"Content-Type": "application/json", "Authorization": "Bearer sk-..."}
body = {
    "model": "openai:gpt-4o",
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Tell me "}
    ],
    "max_tokens": 2000,
    "red": False
}

resp = requests.post(url, headers=headers, json=body)
print(resp.json())
```
`{'error': {'message': 'litellm.BadRequestError: OpenAIException - Unrecognized request argument supplied: red. Received Model Group=openai:gpt-4o\nAvailable Model Group Fallbacks=None', 'type': 'invalid_request_error', 'param': None, 'code': '400'}}`

version: 1.71.2
