### ISSUE TITLE
proxy - together_ai - LLM Provider NOT provided

### ISSUE THREAD

**Issue by llvll0hsen** [BerriAI/litellm#10824]
I'm trying to use few models from together AI by adding them to my config.yaml file and use virtual key to track the key costs. but I keep getting this error. openai models work. 

here is my config file 

```
model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini                       
      api_key: os.environ/OPENAI_API_KEY
      base_url: os.environ/OPENAI_BASE_URL  
  - model_name: gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_key: os.environ/OPENAI_API_KEY
      base_url: os.environ/OPENAI_BASE_URL
    model_info:
      input_cost_per_token: 0.0000001
      output_cost_per_token: 0.0000004
      cache_read_input_token_cost: 0.00000003
  - model_name: Qwen3-235B
    litellm_params:
      model: together_ai/Qwen/Qwen3-235B-A22B-fp8-tput
      api_key: os.environ/TOGETHERAI_API_KEY
    model_info:
      input_cost_per_token: 0.0000002
      output_cost_per_token: 0.0000006
  - model_name: llama-4
    litellm_params:
      model: together_ai/meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
      api_key: os.environ/TOGETHERAI_API_KEY
    model_info:
      input_cost_per_token: 0.00000027
      output_cost_per_token: 0.00000085

general_settings:
  master_key: sk-1234      # enter your own master key, ensure it starts with 'sk-'
  proxy_batch_write_at: 60 # Batch write spend updates every 60s
  database_connection_pool_limit: 10 # limit the number of database connections to = MAX Number of DB Connections/Number of instances of 
```

and this is how call the model

```
import litellm
from litellm import completion, acompletion, token_counter,completion_cost


base_url = "http://localhost:4000"
litellm.api_base = base_url
litellm.api_key = master_key

msg =  [   {
        "role": "user",
        "content": "this is a test request, write a short poem"
    }
]
response = completion(model="llama-4",api_key=virt_key,messages=msg)
```

when I call the API directly I get the `invalid api key` error.

```
import requests

response = requests.post(
    url='http://localhost:4000/chat/completions',
    headers={
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {virt_key}'
    },
    json={
        'model': 'llama-4',
        'user': 'user_id_24358956',
        'messages': [
            {
                'role': 'user',
                'content': 'respond in 50 lines'
            }
        ]
    }
)


response.raise_for_status()
response.json() 
```

error:
`itellm.exceptions.BadRequestError: litellm.BadRequestError: Together_aiException - Invalid API key provided. You can find your API key at https://api.together.xyz/settings/api-keys..`
