### ISSUE TITLE
[Bug]:  <think> opening tag is not emitted in model output when using nvidia_nim/fireworks via LiteLLM Proxy

### ISSUE THREAD

**Issue by TechBeme** [BerriAI/litellm#10848]
### What happened?

When invoking QwQ-32B through the LiteLLM Proxy pointed at either the NVIDIA NIM (`nvidia_nim/qwen/qwq-32b`) or Fireworks AI (`fireworks_ai/accounts/fireworks/models/qwq-32b`) endpoints, the generated response always ends with `</think>` but never begins with the corresponding `<think>` tag. This breaks downstream parsers and wrappers that expect the full think block.

### To Reproduce

1. Configure LiteLLM Proxy with either provider:

   ```yaml
   model_list:
     - model_name: qwen-qwq-32b
       litellm_params:
         model: nvidia_nim/qwen/qwq-32b     # or fireworks_ai/accounts/fireworks/models/qwq-32b
         api_key: os.environ/NVIDIA_API_KEY
   ```
2. Send a chat completion request.
3. Inspect the returned `content` field; it contains only a trailing `</think>`, not the opening `<think>`.

![Image](https://github.com/user-attachments/assets/2d19522f-eaac-4902-a316-33fc4c745321)

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

main-v1.69.2-nightly
