### ISSUE TITLE
[Bug]: LiteLLM Team Table expanding makes /v1/models slow

### ISSUE THREAD

**Issue by ante-maric** [BerriAI/litellm#10849]
### What happened?

GET /v1/models takes minimum 2s and very often it goes up to 10s. I'm using Open WebUI which will call that endpoint on each prompt. All responses are now regularly waited for at least 5s. Looking at the Langfuse Time to first token is less than a second.

I can observe the same thing when I call that endpoint from Postman and when opening list of models on LiteLLM Dashboard. I can't say when this started to happen, but it is weeks. These are the models that I have:

dall-e-3  
openai/chatgpt-4o-latest  
gemini/gemini-2.0-flash  
gpt-4.1  
openai/text-embedding-3-large  
gemini/gemini-2.5-flash-preview-04-17  
gpt-4.1-nano  
gemini/gemini-2.5-pro-preview-05-06  
openai/o3-mini  
openai/gpt-4o-mini  
local/llama3.2:1b  
openai/gpt-4o  
local/gemma2:2b  
openai/gpt-4o-latest  
gemini/gemini-2.5-pro-preview-03-25  
o3  
o4-mini  
gpt-4.1-mini  
mistral/mistral-small-latest

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.69.0

**Comment by ghost** [comment]
Do you have `check_provider_endpoints` enabled? 

```yaml
litellm_settings:
  check_provider_endpoints: true
```

**Comment by ante-maric** [comment]
> Do you have `check_provider_endpoints` enabled?
> 
> litellm_settings:
>   check_provider_endpoints: true

No, these are my settings:

```yaml
      general_settings:
          alerting: ["email"]
      litellm_settings:
          turn_off_message_logging: True
          log_raw_request_response: False
          success_callback: ["langfuse"]
          failure_callback: ["langfuse"]
```
