### ISSUE TITLE
[Feature]: Support projected volume for mounting multiple ConfigMaps via Helm chart

### ISSUE THREAD

**Issue by niklas-letz** [BerriAI/litellm#10886]
### The Feature

Currently, it's not possible to mount a custom Guardrail config (e.g. a Python script, as described [here](https://docs.litellm.ai/docs/proxy/guardrails/custom_guardrail)) alongside the existing litellm-config ConfigMap using the Helm chart.

**Problem**

The Helm chart mounts the litellm-config ConfigMap at `/etc/litellm/`. However, adding a custom Guardrail configuration also requires mounting another file (e.g. custom_guardrail.py) into the same directory.

Since Kubernetes does not support mounting two separate volumes into the same path directly, this currently isn't possible with the Helm chart as-is.

**Proposed Solution**

Use a projected volume, which allows combining multiple ConfigMaps into a single mount point. This approach is supported by Kubernetes and would enable users to extend the configuration with additional custom Guardrail configs.

More info: [Kubernetes Projected Volumes](https://kubernetes.io/docs/concepts/storage/projected-volumes/)

It would be helpful to introduce a Helm value (e.g. `extraGuardrailConfigMaps`) that accepts a list of additional ConfigMaps. These could be automatically included in the projected volume via a Helm template loop. 

**Basic Example**

```
spec:
  template:
    spec:
      containers:
        - volumeMounts:
            - name: litellm-config
              mountPath: /etc/litellm
      volumes:
        - name: litellm-config
          projected:
            sources:
              - configMap:
                  name: guardrail-config-py
                  items:
                    - key: "custom_guardrail.py"
                      path: "custom_guardrail.py"
              - configMap:
                  name: {{ include "litellm.fullname" . }}-config
                  items:
                    - key: "config.yaml"
                      path: "config.yaml"
```

### Motivation, pitch

This change would make the chart more flexible, allowing users to mount custom Guardrail configs into the container and directly use them by LiteLLM.

### Are you a ML Ops Team?

Yes

### Twitter / LinkedIn details

https://www.linkedin.com/in/niklas-letz/
