### ISSUE TITLE
[Question] Is codex-mini-latest (responses-API only models) supported?

### ISSUE THREAD

**Issue by matthid** [BerriAI/litellm#10925]
I was referred to this project by:
https://github.com/open-webui/open-webui/discussions/11874#discussioncomment-13180018

And it might make my configuration a lot easier, however it seems like lightllm has the same issue as OpenWebUI:

```
  - model_name: openai/codex-mini-latest
    litellm_params:
      model: openai/codex-mini-latest
      api_key: "sk-"
```

Setup according to this:
https://docs.litellm.ai/docs/tutorials/openweb_ui

![Image](https://github.com/user-attachments/assets/5fd20101-4b09-4491-87f9-bc5fa81bee84)

I guess LiteLLM currently cannot proxy/route chat/completions requests to the new responses API, correct? Or am I just missing a configuration parameter.

One other thing I noticed is that when I do:

```
  - model_name: openai/*
    litellm_params:
      model: openai/*
      api_key: "sk-"
```

Then the codex-mini-latest model is not even available in the list in /models, so there might be another issue there.

Thanks for any help. If this is in fact missing and you agree to have this feature I might try to send a PR (if there isn't already one)

**Comment by kennyparsons** [comment]
I am having this issue too with the following model config:
```
model_list:
  - model_name: litellm/openai/o1-pro
    litellm_params:
      model: openai/o1-pro
      api_key:  sk-000
```

I feel like the model params should have a way to rewrite the url from `/chat/completions` to `/responses`. I looked over the docs and couldn't find anything. 

Now, just to confirm I did this correctly, I can manually call the right api `/responses` endpoint, and it does work.
