### ISSUE TITLE
How to Enable enable_thinking with Qwen3 Model via OpenAI-Compatible API ,litellm proxy?

### ISSUE THREAD

**Issue by NEWbie0709** [BerriAI/litellm#10938]
I'm currently using the Qwen3 model Qwen3-14B via an OpenAI-compatible API. How can I correctly enable enable_thinking via the OpenAI-compatible API litellm proxy?

**Comment by stif** [comment]
Did not tried it with the qwen3 model, but i enabled "thinking" with claude like this (in litellm-config.yaml):
```
    - model_name: "Anthropic claude 3.7 sonnet thinking"
      litellm_params:
          model: "anthropic/claude-3-7-sonnet-latest"
          api_key: "os.environ/ANTHROPIC_API_KEY"
          thinking: { "type": "enabled", "budget_tokens": 4096 }
```

also did the same with the gemini-2-5-flash model..
