### ISSUE TITLE
[Bug]: Adding a selfhosted TGI endpoint to config.yaml makes LiteLLM stuck on pod startup

### ISSUE THREAD

**Issue by andresC98** [BerriAI/litellm#10937]
### What happened?

> **TLDR**: When adding a [HF TGI ](https://github.com/huggingface/text-generation-inference)selfhosted model endpoint to LiteLLM config.yaml using the documented way, pod gets stuck on Application startup

I have the following config.yaml

```yaml
model_list:
  - model_name: qwen3-32b
    litellm_params:
      model: hosted_vllm/qwen3-32b
      api_base: https://my-qwen3-local-vllm-endpoint/v1
      api_key: none
      rpm: 1440
    model_info:
      supports_reasoning: True
  - model_name: huggingface/mistral7b
    litellm_params:
      model: huggingface/mistral7b
      api_base: https://my-mistral-local-tgi-endpoint/v1
      api_key: os.environ/MISTRAL_7B
general_settings:
    master_key: os.environ/PROXY_MASTER_KEY
    background_health_checks: False
litellm_settings:
    ssl_verify: false
```

I have also tried with `model: huggingface/tgi` without any luck either, as well as removing `/v1` suffix from api base, etc.

If I am only using the vLLM model, it works fine. However, **the moment I add the TGI inference endpoint model**, LiteLLM is **unable** to start (gets stuck on Uvicorn Waiting for Application startup). This also happens if I only keep the TGI model in the list (removing the vLLM one).

I have validated that there is **existing** connectivity between the LiteLLM proxy pod and the vLLM and TGI pods. 

Testing this **via UI** (trying to add new model but checking connection, as I cannot add models via UI since **I am deploying LiteLLM via Helm chart**) **works**, as the model connection check succeeds.

However, when doing the model addition via yaml, the LiteLLM proxy pod is stuck on `INFO: Waiting for application startup.`. DEBUG logs also doesn't show anything else.

### Relevant log output

```shell
Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "litellm", schema "public" at "genai-gateway-db"
The database is already in sync with the Prisma schema.
Running generate... (Use --skip-generate to skip the generators)
Running generate... - Prisma Client Python (v0.11.0)
Some types are disabled by default due to being incompatible with Mypy, it is highly recommended
to use Pyright instead and configure Prisma Python to use recursive types. To re-enable certain types:
generator client {
provider = "prisma-client-py"
recursive_type_depth = -1
}
If you need to use Mypy, you can also disable this message by explicitly setting the default value:
generator client {
provider = "prisma-client-py"
recursive_type_depth = 5
}
For more information see: https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/#default-type-limitations
✔ Generated Prisma Client Python (v0.11.0) to ./../../prisma in 370ms
INFO: Started server process [1]
INFO: Waiting for application startup.
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

1.69.0

**Comment by andresC98** [comment]
**Update:** seems that the only way I managed to get it working is to **use vLLM setup** but for the TGI endpoint, as follows

```
...
  - model_name: mistral7b
    litellm_params:
      model: hosted_vllm/mistral7b
...
```

which is surprising to me since the recommended setup for the Hugginface TGI inference endpoints does not work https://docs.litellm.ai/docs/providers/huggingface

**Comment by andresC98** [comment]
As a note, specifying the suggested config in the docs for TGI also doesnt work

```
proxy_config:
  model_list:
  - model_name: mistral7b
    litellm_params:
      model: huggingface/tgi
      api_base: https://selfhosted-tgI-endpoint.com
```
