### ISSUE TITLE
[Bug]: Custom GuardRail not Working

### ISSUE THREAD

**Issue by fabriciojoc** [BerriAI/litellm#10951]
### What happened?

I've upgraded my LiteLLM from version 1.68 to 1.70.0 and I had to rollback. All my custom guardrails stopped working, even though they are on the config file, they are not shown in the UI. I've checked the documentation and I noticed that stuff changed for guardrails, but there is nothing about custom guardrails (the doc is the same - they are under the `guardrails` tag in the config file, not under `litellm_settings` > `guardrails`). Did something change?

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.70.0

**Comment by ishaan-jaff** [comment]
Hi @fabriciojoc when you say not working, is it not working on the llm api call ? or are you just not seeing it on the UI ?

**Comment by fabriciojoc** [comment]
Both! I cannot see it in the UI and it's not being called.

**Comment by ishaan-jaff** [comment]
@fabriciojoc how do you call them ? with a dynamic param?

**Comment by ishaan-jaff** [comment]
just tested a custom guardrail, I can confirm it still works for me 

```yaml
guardrails:
  - guardrail_name: "custom-pre-guard"
    litellm_params:
      guardrail: custom_guardrail.myCustomGuardrail  # 👈 Key change
      mode: "pre_call"                  # runs async_pre_call_hook
  - guardrail_name: "custom-during-guard"
    litellm_params:
      guardrail: custom_guardrail.myCustomGuardrail  
      mode: "during_call"               # runs async_moderation_hook
  - guardrail_name: "custom-post-guard"
    litellm_params:
      guardrail: custom_guardrail.myCustomGuardrail
      mode: "post_call"                 # runs async_post_call_success_hook

```


request 
```
curl -i --location 'http://0.0.0.0:4000/chat/completions' \
    --header 'Content-Type: application/json' \
    --header 'Authorization: Bearer sk-1234' \
    --data '{
    "model": "openai/gpt-4o",
    "messages": [
        {
        "role": "user",
        "content": "Respond with litellm2"
        }
    ],
    "guardrails": ["custom-pre-guard"]
}'
```
