### ISSUE TITLE
Allow specifying presidio language on guardrail config 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#11026]
In this case it would be presidio. We are from germany and would like to implement a dlp based on presidio. Right now presidio uses english to verify inputs. 

```
guardrails:
  - guardrail_name: "presidio-pre-guard"
    litellm_params:
      guardrail: presidio
      mode: "pre_call"
      output_parse_pii: True
      default_on: true
```

https://docs.litellm.ai/docs/proxy/guardrails/pii_masking_v2#set-language-per-request it would be really if this step could be done via .yaml configuration

_Originally posted by @VonNao in https://github.com/BerriAI/litellm/discussions/10443#discussioncomment-13216652_
