### ISSUE TITLE
[Bug]: Exception litellm.APIError: APIError: Hosted_vllmException -  Connection error

### ISSUE THREAD

**Issue by kresimirfijacko** [BerriAI/litellm#11044]
### What happened?

Version: main-v1.70.1-stable
I can't configure vllm hosted openai server model

Configuration:
```
model_list:
  - model_name: chat-main
    litellm_params:
      model: hosted_vllm/Qwen/Qwen3-30B-A3B-FP8
      api_base: http://0.0.0.0:9001/v1
      api_key: sk-localdev
      # merge_reasoning_content_in_choices: True

general_settings:
  master_key: sk-localdev
```

My CURL request:
```
curl -X POST http://0.0.0.0:9000/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer sk-localdev" \
-d '{
    "model": "chat-main",
    "messages": [
        {
            "role": "user",
            "content": "Hello!"
        }
    ]
}'
```

To me it seems that my request is not translated well, because i get releveant log output below.
Exception litellm.APIError: APIError: Hosted_vllmException - Connection error

The correct command should have (tested it works ok) 'chat/completions' and 'content type' header
```
curl -X POST http://0.0.0.0:9001/v1/chat/completions \
-H "Content-Type: application/json" \
-H 'Authorization: Bearer sk-localdev' \
-d '{"model": "Qwen/Qwen3-30B-A3B-FP8", "messages": [{"role": "user", "content": "Hello!"}], "extra_body": {}}'
```

### Relevant log output

```shell
Exception litellm.APIError: APIError: Hosted_vllmException - Connection error

POST Request Sent from LiteLLM:                                                                                                                                            
curl -X POST \                                                                                                                                                             
http://0.0.0.0:9001/v1/ \                                                                                                                                                  
-H 'Authorization: Be****ev' \                                                                                                                                             
-d '{'model': 'Qwen/Qwen3-30B-A3B-FP8', 'messages': [{'role': 'user', 'content': 'Hello!'}], 'extra_body': {}}'
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.70.1-stable
