### ISSUE TITLE
[Bug]: Passthrough Endpoint for Bedrock gives boto auth error

### ISSUE THREAD

**Issue by mngeow** [BerriAI/litellm#11055]
### What happened?

Hello all!

I was reading passthrough endpoints for Bedrock [here](https://docs.litellm.ai/docs/pass_through/bedrock) , and wrote some code to try to patch a boto3 client and try the converse api myself.

Here is my code:
```
from dotenv import dotenv_values
import os 
import boto3 
from botocore.exceptions import ClientError
config = dotenv_values(".env")

os.environ["AWS_ACCESS_KEY_ID"] = "my-fake-key-id"
os.environ["AWS_SECRET_ACCESS_KEY"] = "my-fake-access-key"

LITELLM_URL = config["LITELLM_URL"]
LITELLM_API_KEY = config["LITELLM_API_KEY"]

proxy_endpoint = f"{LITELLM_URL}/bedrock"

model_id = "anthropic.claude-3-7-sonnet-20250219-v1:0"

custom_headers = {
    'x-litellm-api-key': f'Bearer {LITELLM_API_KEY}'
}

runtime_client = boto3.client(
    service_name="bedrock-runtime", 
    region_name="us-west-2", 
    endpoint_url=proxy_endpoint
)

def inject_custom_headers(request, **kwargs):
    request.headers.update(custom_headers)

runtime_client.meta.events.register('before-send.*.*', inject_custom_headers)

user_message = "Describe the purpose of a 'hello world' program in one line."
conversation = [
    {
        "role": "user",
        "content": [{"text": user_message}],
    }
]

try:
    response = runtime_client.converse(
        modelId=model_id,
        messages=conversation,
        inferenceConfig={"maxTokens": 512, "temperature": 0.5, "topP": 0.9},
    )

    response_text = response["output"]["message"]["content"][0]["text"]
    print(response_text)

except (ClientError, Exception) as e:
    print(f"ERROR: Can't invoke '{model_id}'. Reason: {e}")
    exit(1)
```

When I run this code, I get a Server 500 error from litellm proxy, logs are shown in this post.

I even tried running the curl command for converse api, as per the litellm docs:
```
curl -X POST 'https://litellm.mngeow.ai/bedrock/model/us.anthropic.claude-3-7-sonnet-20250219-v1:0/converse' \
-H 'x-litellm-api-key: Bearer sk-12345' \
-H 'Content-Type: application/json' \
-d '{
    "messages": [
         {"role": "user",
        "content": [{"text": "Hello"}]
    }
    ]
}'
```

Same error.

The following is my litellm proxy config:
```
  model_list:
    - model_name: anthropic.claude-3-sonnet-20240229-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-sonnet-20240229-v1:0
        aws_region_name: us-west-2
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
    - model_name: anthropic.claude-3-5-sonnet-20241022-v2:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
        aws_region_name: us-west-2
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        tpm: 3900000
        rpm: 450
    - model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0
        aws_region_name: us-west-2
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        tpm: 3900000
        rpm: 450
    - model_name: anthropic.claude-3-7-sonnet-20250219-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
        aws_region_name: us-west-2
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        rpm: 740
    - model_name: anthropic.claude-3-7-sonnet-20250219-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
        aws_region_name: us-west-2
        aws_session_name: litellm_second
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        rpm: 740
    - model_name: anthropic.claude-3-7-sonnet-20250219-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
        aws_region_name: us-west-2
        aws_session_name: litellm_third
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        rpm: 740
    - model_name: anthropic.claude-3-5-haiku-20241022-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
        aws_region_name: us-west-2
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        rpm: 740
    - model_name: anthropic.claude-3-5-haiku-20241022-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
        aws_region_name: us-west-2
        aws_session_name: litellm_second
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        rpm: 740
    - model_name: anthropic.claude-3-5-haiku-20241022-v1:0
      litellm_params:
        model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
        aws_region_name: us-west-2
        aws_session_name: litellm_third
        aws_role_name: arn:aws:iam::123456:role/litellm
        timeout: 600             
        stream_timeout: 600
        rpm: 740
  general_settings:
    master_key: os.environ/PROXY_MASTER_KEY
  router_settings:
    routing_strategy: usage-based-routing-v2
    num_retries: 2
```
Also one related question, assuming that I find a fix:

If I use bedrock passthrough endpoints, will they also be load balanced across multiple bedrock deployments for the same model? 

Any help would be appreciated. Thanks!

### Relevant log output

```shell
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/lib/python3.13/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ~~~~~~~~~~~~~~~~~~~~~~~^^
  |   File "/usr/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 685, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     )
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         self.scope, self.receive, self.send
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     )
    |     ^
    |   File "/usr/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |          ~~~~~~~~~~~~~~~~~~^^
    |   File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    |     self.gen.throw(value)
    |     ~~~~~~~~~~~~~~^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/litellm/proxy/middleware/prometheus_auth_middleware.py", line 47, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/fastapi/routing.py", line 301, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     ...<3 lines>...
    |     )
    |     ^
    |   File "/usr/lib/python3.13/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/litellm/proxy/pass_through_endpoints/llm_passthrough_endpoints.py", line 432, in bedrock_proxy_route
    |     sigv4.add_auth(_request)
    |     ~~~~~~~~~~~~~~^^^^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/botocore/auth.py", line 433, in add_auth
    |     string_to_sign = self.string_to_sign(request, canonical_request)
    |   File "/usr/lib/python3.13/site-packages/botocore/auth.py", line 408, in string_to_sign
    |     sts.append(self.credential_scope(request))
    |                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    |   File "/usr/lib/python3.13/site-packages/botocore/auth.py", line 398, in credential_scope
    |     return '/'.join(scope)
    |            ~~~~~~~~^^^^^^^
    | TypeError: sequence item 1: expected str instance, NoneType found
    +------------------------------------
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
         ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/litellm/proxy/middleware/prometheus_auth_middleware.py", line 47, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/usr/lib/python3.13/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/lib/python3.13/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/litellm/proxy/pass_through_endpoints/llm_passthrough_endpoints.py", line 432, in bedrock_proxy_route
    sigv4.add_auth(_request)
    ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/botocore/auth.py", line 433, in add_auth
    string_to_sign = self.string_to_sign(request, canonical_request)
  File "/usr/lib/python3.13/site-packages/botocore/auth.py", line 408, in string_to_sign
    sts.append(self.credential_scope(request))
               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/botocore/auth.py", line 398, in credential_scope
    return '/'.join(scope)
           ~~~~~~~~^^^^^^^
TypeError: sequence item 1: expected str instance, NoneType found
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.70.1-stable
