### ISSUE TITLE
[Bug]: proxy server with disk cache not saving embeddings

### ISSUE THREAD

**Issue by ricopinazo** [BerriAI/litellm#11062]
### What happened?

I'm trying to use the proxy server with the disk cache. My configuration is as follows:

```yaml
model_list:
  - model_name: text-embedding-3-small
    litellm_params:
      model: text-embedding-3-small
    litellm_settings:
      set_verbose: True
      cache: True
      cache_params:
        type: disk
        disk_cache_dir: /tmp/cache-dir
        ttl: 604800
```

And then I'm running the proxy server with:
```bash
export $$(cat .env | xargs) && litellm --config openai-proxy.yaml
```

Also, I installed litellm with: `pip install 'litellm[all]'`
And diskcache just in case with: `pip install diskcache`

With this setup, I don't get the proxy server to ever write anything into the folder `/tmp/cache-dir`. Is this behavior normal? Am I doing something wrong?

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.70.2
