### ISSUE TITLE
[Feature]: Support Gemini imagen

### ISSUE THREAD

**Issue by boosh** [BerriAI/litellm#11087]
### The Feature

```
response = image_generation(model='gemini/imagen-3.0-generate-002', prompt='futuristic cityscape at sunset', n=1)
```
returns
```
ImageResponse(created=1787925156, data=[], usage=Usage(completion_tokens=0, prompt_tokens=0, total_tokens=0, completion_tokens_details=None, prompt_tokens_details=None))
```
Please add support for imagen.

### Motivation, pitch

Image generation

### LiteLLM is hiring a founding backend engineer, are you interested in joining us and shipping to all our users?

No

**Comment by Classic298** [comment]
Imagen 3 works for me (proxy).

**Comment by boosh** [comment]
Strange. Can you share some sample code please?

**Comment by Classic298** [comment]
```
### Image Generation

  - model_name: imagen-3.0-generate-002
    litellm_params:
      model: vertex_ai/imagen-3.0-generate-002
      aspectRatio: "16:9"
      person_generation: allow_all
      safety_filter_level: block_none
    model_info:
      output_cost_per_image: 0.04
```

(btw litellm fails to track the cost, even when explicitly setting the cost, but otherwise it works)
