### ISSUE TITLE
[Bug]: In Proxy streaming mode, text-completions are redirected to chat completions

### ISSUE THREAD

**Issue by fullstackwebdev** [BerriAI/litellm#1109]
### What happened?

 In streaming mode, text-completions are redirected to chat completions

If I call LiteLLM directly to proxy this request with this config:

```yaml

litellm_settings:
  set_verbose: True
  telemetry: False
  drop_params: True
  # debug: True

general_settings:
  telemetry: False

  # openhermes-2.5-mistral-7b on perplexity! pplx-70b-online
model_list:
  - model_name: text-davinci-003
    litellm_params:
      model: openai/text-davinci-003
      # mode: completion
      api_key: sk-Imn
      api_base: http://localhost:6001/v1
    model_info:
      mode: completion
```

And enable "stream" : true
It incorrectly tries to call /chat/completion when it should be calling /complete
If streaming is false, it _correctly_ calls /complete

Right now I think it is trying to "emulate" /complete to be compatible with providers that don't have a /complete (? my guess), but only in the case of streaming mode.

the correct behavior should be always call /complete, regardless of streaming mode or not. 

and perhaps if you want the ability to "emulate" /complete it should be a feature flag somewhere like this,

```yaml
model_list:
  - model_name: text-davinci-003
    litellm_params:
      model: openai/text-davinci-003
      # mode: completion
      api_key: sk-Imn
      api_base: http://localhost:6001/v1
    model_info:
      mode: **chat**    <--- I tried putting "complete" here no go
```

I tried setting mode: complete in my config and it had no effect.

### Relevant log output

```shell
https://gist.github.com/fullstackwebdev/f8ce87f58d138e108ad96327736b3d43

see gist

and 

 http://localhost:6000/v1/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer YOUR_API_KEY" \
-d '{"model": "text-davinci-003", "prompt": "Say this is a test", "temperature": 0, "max_tokens": 70, "stream":false}'


vs "stream" : true
```
