### ISSUE TITLE
[Bug]: Redis cache timeout causes message content to leak into logs

### ISSUE THREAD

**Issue by MemmoB** [BerriAI/litellm#11157]
### What happened?

Occasionally there are timeouts against our Redis instance for LiteLLM caching. When the exception is logged it includes the message content although the settings are as follows:
```
 litellm_settings:                                                                                                                   
   turn_off_message_logging: true                                                                                                    
   callbacks: ["otel"]                                                                                                               
   request_timeout: 600                                                                                                              
   set_verbose: false                                                                                                                
   json_logs: true                                                                                                                   
   cache: true
```
The exception trace:	
`{"message": "LiteLLM Redis Caching: async set() - Got exception from REDIS Timeout reading from 10.35.XX.X:6379, Writing value={'timestamp': 1748204688.8742855, 'response': '{\"id\":\"chatcmpl-ac4594b5-d85b-4a5d-9bc7-fbc430e57054\",\"created\":1748204525,\"model\":\"\",\"object\":\"chat.completion\",\"system_fingerprint\":null,\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\` <-- Here the whole message leaks

LiteLLM Image: ghcr.io/berriai/litellm-non_root:main-v1.65.4-stable

We don't want to leak any messages to our tracing/logging back-end.

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.65.4
