### ISSUE TITLE
[Bug]: Litellm reports Bedrock AWS secret access key and access key ID to Langfuse

### ISSUE THREAD

**Issue by fengjiajie** [BerriAI/litellm#11150]
### What happened?

When litellm reports data to Langfuse for Bedrock API calls, it appears to include sensitive AWS credentials, specifically the aws_access_key_id and aws_secret_access_key.

![Image](https://github.com/user-attachments/assets/109a4064-313c-4e45-8b4f-b4b648059141)

```
litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  langfuse_default_tags: ["cache_hit", "proxy_base_url", "user_api_key_alias", "user_api_key_user_id", "user_api_key_user_email", "user_api_key_team_alias", "semantic-similarity", "proxy_base_url"]
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.71.1
