### ISSUE TITLE
[Bug]: Wrong Gemini 2.5 cost calculation

### ISSUE THREAD

**Issue by JohanBekker** [BerriAI/litellm#11156]
### What happened?

Gemini 2.5 supports implicit context caching, but litellm does not take this into account while calculating the cost.

Example:

```
from litellm import ModelResponse
import litellm
from dotenv import load_dotenv

load_dotenv() # Gemini & langfuse API key's

litellm.success_callback = ["langfuse"]
litellm.failure_callback = ["langfuse"]
litellm._turn_on_debug()


messages = [
    {
        "role": "system",
        "content": "You are a helpful assistant."
    },
    {
        "role": "user",
        "content": "\n".join(["This is a test message to check the response from the Gemini model."]*1000)
    },
]

response: ModelResponse = litellm.completion(
    model="gemini/gemini-2.5-flash-preview-04-17",
    messages=messages,
    thinking={"type": "disabled", "budget_tokens": 0} # turn off thinking
)

messages.extend(
    [
        {
            "role": "assistant",
            "content": response.choices[0].message.content
        },
        {
            "role": "user",
            "content": "This is a test message to check the response from the Gemini model."
        }
    ]
)

response: ModelResponse = litellm.completion(
    model="gemini/gemini-2.5-flash-preview-04-17",
    messages=messages,
    thinking={"type": "disabled", "budget_tokens": 0}
)
```

This gives the following debug log:

```
LiteLLM:DEBUG: utils.py:338 - RAW RESPONSE:
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "Understood. This is a test message to check the response from the Gemini model."
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "index": 0
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 15033,
    "candidatesTokenCount": 17,
    "totalTokenCount": 15050,
    "cachedContentTokenCount": 14316,
    "promptTokensDetails": [
      {
        "modality": "TEXT",
        "tokenCount": 15033
      }
    ],
    "cacheTokensDetails": [
      {
        "modality": "TEXT",
        "tokenCount": 14316
      }
    ]
  },
  "modelVersion": "models/gemini-2.5-flash-preview-04-17",
  "responseId": "VFg0aK_YCv64nsEPgLKoqA4"
}
```

And litellm reports the following cost:

```
litellm_logging.py:1130 - response_cost: 0.00226515
```

Gemini pricing:
input: $0.15 / 1000000 tokens
output: $0.60 / 1000000 tokens

Which corresponds to `0.15*(15033/1000000) + 0.6*(17/1000000) = 0.00226515`.

However, implicit caching should give a 75% discount for cached input tokens:
https://developers.googleblog.com/en/gemini-2-5-models-now-support-implicit-caching/

Which would come down to:

`0.15*0.25*(14316/1000000)+0.15*((15033-14316)/1000000)+0.6*(17/1000000) = 0.0006546`

The difference is quite substantial, around 3.5x, so it would be great to get this to work properly. 

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

1.71.1

**Comment by recrudesce** [comment]
Seems none of the Gemini models have cache pricing configured in https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

You can override it in your own config, though - example here shown for Claude, but it gives you the syntax:

```
model_list:
  - model_name: "prod/claude-3-5-sonnet-20241022"
    litellm_params:
      model: "anthropic/claude-3-5-sonnet-20241022"
      api_key: os.environ/ANTHROPIC_PROD_API_KEY
    model_info:
      input_cost_per_token: 0.000006
      output_cost_per_token: 0.00003
      cache_creation_input_token_cost: 0.0000075
      cache_read_input_token_cost: 0.0000006
```
