### ISSUE TITLE
[Bug]: Max langfuse clients reached: 20 is greater than 20

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#11169]
### What happened?

[92m01:06:45 - LiteLLM:ERROR[0m: litellm_logging.py:2078 - LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 2010, in async_success_handler
    await callback.async_log_success_event(
    ...<4 lines>...
    )
  File "/usr/lib/python3.13/site-packages/litellm/integrations/langfuse/langfuse_prompt_management.py", line 259, in async_log_success_event
    langfuse_logger_to_use = LangFuseHandler.get_langfuse_logger_for_request(
        globalLangfuseLogger=self,
        standard_callback_dynamic_params=standard_callback_dynamic_params,
        in_memory_dynamic_logger_cache=in_memory_dynamic_logger_cache,
    )
  File "/usr/lib/python3.13/site-packages/litellm/integrations/langfuse/langfuse_handler.py", line 65, in get_langfuse_logger_for_request
    LangFuseHandler._create_langfuse_logger_from_credentials(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        credentials=credentials_dict,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        in_memory_dynamic_logger_cache=in_memory_dynamic_logger_cache,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm/integrations/langfuse/langfuse_handler.py", line 118, in _create_langfuse_logger_from_credentials
    langfuse_logger = LangFuseLogger(
        langfuse_public_key=credentials.get("langfuse_public_key"),
        langfuse_secret=credentials.get("langfuse_secret"),
        langfuse_host=credentials.get("langfuse_host"),
    )
  File "/usr/lib/python3.13/site-packages/litellm/integrations/langfuse/langfuse.py", line 89, in __init__
    self.Langfuse: Langfuse = self.safe_init_langfuse_client(parameters)
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/litellm/integrations/langfuse/langfuse.py", line 139, in safe_init_langfuse_client
    raise Exception(
        f"Max langfuse clients reached: {litellm.initialized_langfuse_clients} is greater than {MAX_LANGFUSE_INITIALIZED_CLIENTS}"
    )
Exception: Max langfuse clients reached: 20 is greater than 20

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.71.1.stable

### Twitter / LinkedIn details

_No response_

**Comment by ghost** [comment]
Hey @langgg0511 this looks related to a reliability check. 

Are you setting 20+ langfuse projects w/ litellm? 

- Langfuse initializes 1 thread everytime a client is initialized.
- We've had an incident in the past where we reached 100% cpu utilization because Langfuse was initialized several times.

**Comment by langgg0511** [comment]
@krrishdholakia I am using default_team_settings and have 10 teams, each connecting to 10 Langfuse instances.

**Comment by ghost** [comment]
so 10 total langfuse instances?

**Comment by ghost** [comment]
cc: @ishaan-jaff

**Comment by langgg0511** [comment]
> so 10 total langfuse instances?

yes

**Comment by ghost** [comment]
Seems like the underlying issue is 2x langfuse clients being created - can i see your config? @langgg0511

**Comment by langgg0511** [comment]
@krrishdholakia 
```yaml
general_settings:
  disable_master_key_return: true # If true, turns off returning master key on UI. (checked on '/user/info' endpoint)
  disable_reset_budget: true # If true, turns off reset budget scheduled task
  disable_retry_on_max_parallel_request_limit_error: true # If true, turns off retries when max parallel request limit is reached
  master_key: "sk-"
  alerting: ["slack"]
  alert_types: ["llm_exceptions", "llm_requests_hanging"]
  database_url: "postgresql://postgresql:5432/litellm"
  database_connection_pool_limit: 5
  database_connection_timeout: 60
  proxy_batch_write_at: 60
  store_model_in_db: true
  disable_spend_logs: true
  disable_error_logs: true
  allow_requests_on_db_unavailable: true

litellm_settings:
  request_timeout: 600
  set_verbose: false
  ssl_verify: false
  json_logs: true
  cache: True
  cache_params:
    type: redis
    namespace: "litellm_caching"
    host: "redis.db"
    port: 6379
    ttl: 86400
    supported_call_types: ["acompletion", "atext_completion", "aembedding", "atranscription"]
  

  drop_params: true
  num_retries: 0

  redact_user_api_key_info: true

  content_policy_fallbacks: [{"azure/gpt-4o-mini": ["openai/gpt-4o-mini"]},{"azure/gpt-4o": ["openai/gpt-4o"]}]
  default_team_settings:
    - team_id: "27d3b84e-21e3-4ea7-ba3b-b3c1e2d7755a"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"
    - team_id: "562da1c6-9c83-4107-b082-d34b8084b408"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"
    - team_id: "5c7b03c6-e502-4bc9-a969-b254084fdbd3"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"
    - team_id: "9530bcc7-dc68-482e-a200-f294296c78d6"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"

    - team_id: "dev"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"

    - team_id: "e830412c-2ddf-47e8-8d87-744623a66d4e"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"
    - team_id: "f2132c57-877a-47d7-91a6-4c8f893305ad"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"
    - team_id: "f268fa46-5443-47c1-acec-d766c45fdc88"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"

    - team_id: "fb4ea4b6-2c97-4767-acb9-903ed53ca4ce"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"

    - team_id: "office"
      success_callback: ["langfuse"]
      langfuse_public_key: "pl-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: "https://langfuse"

router_settings:
  routing_strategy: simple-shuffle # Literal["simple-shuffle", "least-busy", "usage-based-routing","latency-based-routing"], default="simple-shuffle"

  redis_host: "redis.db"
  redis_port: 6379

  num_retries: 0
  allowed_fails: 20 # cooldown model if it fails > 1 call in a minute.
  cooldown_time: 5 # how long to cooldown model if fails/min > allowed_fails
```
