### ISSUE TITLE
[Bug]: model fallback list index out of range

### ISSUE THREAD

**Issue by zegerius** [BerriAI/litellm#11197]
### What happened?

When a model fails with 429, I don't see a fallback happening, but rather see error:

```
litellm.RateLimitError: BedrockException - {"message":"Too many tokens, please wait before trying again."}. Received Model Group=anthropic.claude-sonnet-4-20250514-v1:0
Available Model Group Fallbacks=None
Error doing the fallback: list index out of range LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
```

I make heavy use of model aliases and I have configured in my config.yaml the following (simplified):

```
model_list:
  - model_name: anthropic.claude-sonnet-4-20250514-v1:0
    litellm_params:
      model: bedrock/eu.anthropic.claude-sonnet-4-20250514-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_EU_1
      rpm: 200
      tpm: 200000

  - model_name: anthropic.claude-sonnet-4-20250514-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_EU_2
      rpm: 200
      tpm: 200000

  # Anthropic Claude Sonnet 3.7 20250219 (v1)
  - model_name: anthropic.claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/eu.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_EU_1
      rpm: 250
      tpm: 1000000
  - model_name: anthropic.claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name:  os.environ/AWS_REGION_EU_2
      rpm: 250
      tpm: 1000000

router_settings:
  fallbacks:
    - anthropic.claude-sonnet-4-20250514-v1:0:
        - anthropic.claude-3-7-sonnet-20250219-v1:0
        - google.gemini-2.5-pro
```

I see the same when I do a call to OpenAI Whisper (for which I do not have a fallback configures):

```
500: litellm.BadRequestError: OpenAIException - Audio file is too short. Minimum audio length is 0.1 seconds.. Received Model Group=openai-whisper-1
Available Model Group Fallbacks=None
Error doing the fallback: list index out of range LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
```

Am I doing something wrong, or this is a bug?

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.71.1
