### ISSUE TITLE
[Feature]: Add support for vLLM pooling/classify endpoints

### ISSUE THREAD

**Issue by ankandrew** [BerriAI/litellm#11205]
### The Feature

Right now the vLLM officially supported endpoints are: `/chat/completions`, `/embeddings` and `/completions`. vLLM has these nice pooling endpoints https://docs.vllm.ai/en/latest/models/pooling_models.html. I'd like to see the `/classify` endpoint officially supported.

### Motivation, pitch

Using SequenceClassification models from vLLM with LiteLLM proxy provides great value. Right now, the workaround seems to be use `Pass Through Endpoints`, but it would be very nice if we can officially support the pooling endpoints from vLLM.

### LiteLLM is hiring a founding backend engineer, are you interested in joining us and shipping to all our users?

No

**Comment by cdgraff** [comment]
+1

**Comment by ghost** [comment]
Hey @cdgraff @ankandrew these can already be used via litellm today through our passthrough endpoints - https://docs.litellm.ai/docs/pass_through/vllm


Let me know if this solves your problem!

**Comment by ankandrew** [comment]
Hi @krrishdholakia! Thanks for the quick reply. I tried the passthrough flow with `HOSTED_VLLM_API_BASE`, but won't that support only one host? It looks like that env var lets LiteLLM talk to just one vLLM server. In a typical prod setup we might run several vLLM servers.

**Comment by ghost** [comment]
Hey @ankandrew how would you want to specify which server to call for `/classify`?

**Comment by ankandrew** [comment]
Hi @krrishdholakia! Thanks for asking. Easiest I can imagine would be to use it like:

```yaml
  - model_name: papluca/xlm-roberta-base-language-detection
    litellm_params:
      model: hosted_vllm/papluca/xlm-roberta-base-language-detection
      api_base: http://localhost:8098/classify
      api_key: none
```

This way we could keep using `/classify` normally, and LiteLLM would forward the request to the correct vLLM instance based on the model name just like it already does for `/chat` or `/completions`. vLLM doesn't support loading multiple models in the same server instance. Thats why in prod, we often run one model per vLLM server, each on its own port or host. So being able to map each model to its own `api_base` (classify endpoint) would be great!

**Comment by ghost** [comment]
what's the proposed clientside request for this model name? @ankandrew

**Comment by ankandrew** [comment]
If we define the model like this in `model_list`:

```yaml 
- model_name: papluca/xlm-roberta-base-language-detection
  litellm_params:
    model: hosted_vllm/papluca/xlm-roberta-base-language-detection
    api_base: http://localhost:8098/classify
    api_key: none
```

Then from the client side, the request stays same style as `/chat` or `/completions`:

```
curl "https://XYZ-liteLLM-host/classify" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "papluca/xlm-roberta-base-language-detection",
    "input": "What language is this?"
  }'
```

So LiteLLM handles everything behind the scenes figuring out which `api_base` to call based on the model name in the request. The client doesn't need to worry about which server runs which model.

**Comment by ghost** [comment]
Hey @ankandrew trying to figure out how we can support this without having to onboard each endpoint from vllm onto litellm. 

Idea 1: support passing litellm model name in headers 

We can then use this to route to correct vllm api base. 

```bash
curl "https://XYZ-liteLLM-host/vllm/classify" \
  -H "Content-Type: application/json" \
  -H "x-litellm-model-name: papluca/xlm-roberta-base-language-detection"
  -d '{
    "model": "value sent straight to vllm",
    "input": "What language is this?"
  }'
```

Cons: the model would be sent straight through - so user would need to know what the vllm supported model name is 

---
Any other approaches?

**Comment by ankandrew** [comment]
Hi @krrishdholakia! I guess header idea works technically but forces every client to deviate from the standard OpenAI call pattern. We could keep the normal `/classify` path and reuse `model_list`, like:

```yaml
model_list:
  - model_name: papluca/xlm-roberta-base-language-detection
    litellm_params:
      model: hosted_vllm/papluca/xlm-roberta-base-language-detection
      api_base: http://localhost:8098
      endpoint: /classify  # Or default if ommitted
      api_key: none
```

And we can keep same request format like:

```shell
curl "https://XYZ-liteLLM-host/classify" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "papluca/xlm-roberta-base-language-detection",
    "input": "What language is this?"
  }'
```

vLLM seems to support only just 3 pooling endpoints (i.e. one is `/classify`), see https://docs.vllm.ai/en/stable/models/pooling_models.html. It would be nice since vLLM is growing a lot. Also I think much of the same logic could be applied to the 3 endpoints vLLM supports.

**Comment by ghost** [comment]
Adding support via router model list

**Comment by ghost** [comment]
1. Add vllm model on config yaml 
 
```yaml
- model_name: papluca/xlm-roberta-base-language-detection
    litellm_params:
      model: hosted_vllm/papluca/xlm-roberta-base-language-detection
      api_base: http://localhost:8090
```

2. Call `/classify` endpoint 

```bash
curl "https://XYZ-liteLLM-host/vllm/classify" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "papluca/xlm-roberta-base-language-detection", # 👈 USE MODEL NAME FROM MODEL LIST
    "input": "What language is this?"
  }'
```

The solution is generic, so it should work across any vllm endpoint
