### ISSUE TITLE
Regression: Redis/Valkey cache backend not initializing, `/cache/ping` endpoint 404, no cache health in Docker (v1.71.x+)

### ISSUE THREAD

**Issue by arbscs** [BerriAI/litellm#11243]
Redis/Valkey cache backend does not initialize in LiteLLM (v1.71.1 and newer, including `main-latest`), even with correct config and all known workarounds. The `/cache/ping` endpoint always returns 404, and there is no cache health check available. All environment variables, config.yaml, and Docker Compose settings are correct. This is a regression compared to older versions.

1. Use the following `config.yaml`:
    ```yaml
    cache:
      type: redis
      redis:
        host: redis
        port: 6379
    ```
2. Use the following Docker Compose service for LiteLLM:
    ```yaml
    litellm:
      image: ghcr.io/berriai/litellm:main-latest
      container_name: litellm
      restart: unless-stopped
      depends_on:
        litellm-db:
          condition: service_healthy
        redis:
          condition: service_healthy
      environment:
        DEBUG: "True"
        DATABASE_URL: postgresql://${LITELLM_POSTGRES_USER}:${LITELLM_POSTGRES_PASSWORD}@litellm-db:5432/${LITELLM_POSTGRES_DB}
        LITELLM_USE_CACHE: true
        LITELLM_CACHE_TYPE: redis
        LITELLM_CACHE_ENABLED: true
        REDIS_HOST: redis
        REDIS_PORT: 6379
      ports:
        - "4000:4000"
      volumes:
        - litellm_data:/app/data
    ```
3. Redis/Valkey is healthy and reachable from the container.
4. All required Python packages (`redis`, `aioredis`) are installed in the container.
5. Start the stack and check `/cache/ping` or similar endpoints.

- Cache backend should initialize and be used.
- `/cache/ping` (or equivalent) should return 200 OK if cache is healthy.
- Cache hits/misses should be visible in logs.

- `/cache/ping` and all similar endpoints return 404.
- No cache health check endpoint is available.
- No errors in logs, but cache is not used.
- This persists across all recent images (`main-latest`, `v1.71.2-nightly`, etc.) and with both Redis and Valkey.

I have tried
- All known environment variable combinations (`LITELLM_USE_CACHE`, `LITELLM_CACHE_TYPE`, `LITELLM_CACHE_ENABLED`, etc.).
- Clean and minimal `config.yaml`.
- Both Redis and Valkey as backend.
- Manual install of `aioredis` and `redis` in the container.
- Network and health checks (Redis is reachable and healthy).
- Downgrade not possible due to missing ARM64 images for older tags.
- No relevant documentation or community solution found.

System info
- oci ammpere instance ubuntu 22
- LiteLLM image: `ghcr.io/berriai/litellm:main-latest` (and others)
- Redis/Valkey: `docker.io/valkey/valkey:8-alpine` and official `redis:7.2`
- Docker Compose environment

- Please clarify if the cache health endpoint has changed or been removed.
- Is there a new way to verify cache backend health?
- Is there a regression in cache backend initialization in recent versions?
- Any working example for Docker Compose + Redis/Valkey cache backend would be appreciated.

Thanks!
