### ISSUE TITLE
[Enhancement]: Support vertex ai passthrough, when vertex credentials set in env var not via `vertex_credentials` param

### ISSUE THREAD

**Issue by Ziyann** [BerriAI/litellm#11245]
### What happened?

I couldn't get Vertex AI pass-through to work with GCP Service Account authentication. My setup is like so:
```yaml
model_list:
  - model_name: vertex_ai/*
    litellm_params:
      model: vertex_ai/*
      vertex_project: XXX
      vertex_location: us-central1
      use_in_pass_through: true
```
Deployed on Google Cloud Run. Normal requests through ```vertex_ai``` models work fine, but trying to use pass-through, I get the below error.

### Relevant log output

```shell
No credentials found on proxy for project_name=XXX + location=us-central1, check /model/info for allowed project + region combinations with use_in_pass_through: true. Headers were passed through directly but request failed with error: { "error": { "code": 401, "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "status": "UNAUTHENTICATED", "details": [ { "@type": "type.googleapis.com/google.rpc.ErrorInfo", "reason": "CREDENTIALS_MISSING", "domain": "googleapis.com", "metadata": { "service": "aiplatform.googleapis.com", "method": "google.cloud.aiplatform.v1.PredictionService.PredictLongRunning" } } ] } }
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.71.2-nightly
