### ISSUE TITLE
[Bug]: LiteLLM Proxy $0 Cost Tracking for Codestral

### ISSUE THREAD

**Issue by ndrsfel** [BerriAI/litellm#11266]
### What happened?

Hey all, in our LiteLLM Proxy set-up under `v1.71.2-nightly` all requests to `text-completion-codestral/codestral-latest` are tracked with $0.

We've previously had this problem with `azure/gpt-4.1` as well on `v1.71.1-stable` but this is fixed with the new version. Thanks for that!!!

Our `values.yaml` looks like
```yaml
...
model_list:
  - model_name: codestral-latest
    litellm_params:
      model: text-completion-codestral/codestral-latest
      api_base: <base-url>
      api_key: <api-key>
    model_info:
      input_cost_per_token: 0.0000003
      output_cost_per_token: 0.0000009
...
litellm_settings:
  set_verbose: false
  json_logs: true
  cache: true
  cache_params:
    type: redis
    supported_call_types: []
    port: 6379
  redact_messages_in_exceptions: True
```
however, this is the only model, that displays `cost_per_token` in exponential-notation in the LiteLLM metadata logs of a request:
```
...
  "input_cost_per_token": "3e-07",
  "output_cost_per_token": "9e-07",
...
```
Could this be the cause? Happy to provide more information.

Cheers, Andreas ✌️

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.71.2-nightly

**Comment by ghost** [comment]
Hey @ndrsfel can you share the complete debug log? and the request used to trigger this (is it on `/chat/completion` or `/completion`, etc.)

**Comment by ndrsfel** [comment]
Hey @krrishdholakia we've figured it out what went wrong. Sharing our solution might be helpful for you as well.

As stated in the description above, we define 
```yaml
model_info:
  input_cost_per_token: 0.0000003
  output_cost_per_token: 0.0000009
```
in our yaml, which then gets converted to  
```yaml
model_info:
  input_cost_per_token: 3e-07
  output_cost_per_token: 9e-07
```
using your helm setup, to be more specific [here](https://github.com/BerriAI/litellm/blob/39de3610becc64fd616f1084bb5036c59fcbff79/deploy/charts/litellm-helm/templates/configmap-litellm.yaml#L7).

Back in LiteLLM, the model config for `codestral-latest` is converted to 
```
...
  "input_cost_per_token": "3e-07",
  "output_cost_per_token": "9e-07",
...
```
and LiteLLM has issues to translate this string into token costs during inference. However, the UI displays token costs correctly.

### Solution

We fixed this issue by adjusting the above `configmap-litellm.yaml` to
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.fullname" . }}-config
data:
  config.yaml: |
{{ .Values.proxy_config | toYaml | replace "3e-07" "0.0000003" | replace "9e-07" "0.0000009" | indent 6 }}
```
which is not suitable for a permanent solution but gets the job done for now.

Our final model config in the LiteLLM UI looks like this
```
...
    "input_cost_per_token": 3e-7,
    "output_cost_per_token": 9e-7,
...
```
which works as expected. Feel free to reproduce the issue by setting the token costs in a `config.yaml` with `3e-07` and `9e-07` respectively which will result in $0 token costs on each inference call.

**TL;DR** Setting token costs using `xe-0y` does not work for `text-completion-codestral/codestral-latest` but `xe-y` does :)

Happy to provide more information ✌️
