### ISSUE TITLE
[Bug]: Master Key Exposed in Cache Settings Logs

### ISSUE THREAD

**Issue by mknet3** [BerriAI/litellm#11264]
### What happened?

In the logs for cache settings, the master key is being logged in plaintext.

These are the params I have configured for cache:
```
      cache: True
      cache_params:
        type: redis
        host: "open-webui-redis.open-webui.svc.cluster.local"
        port: 6379
        namespace: "litellm.caching.caching"
```


### Relevant log output

```shell
│ Setting Cache on Proxy                                                                                                                                                                                                                            
│ General settings: {'master_key': 'sk-XXXXXXXX'}                                                                                                                                                                             
│ Custom auth settings: None                                                                                                                                                                                                                        
│ Custom auth settings: None
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.71.2-nightly

### Twitter / LinkedIn details

_No response_
