### ISSUE TITLE
[Bug]: Groq's distil-whisper-large-v3-en not working with litellm_stable_release_branch-v1.72.0.rc

### ISSUE THREAD

**Issue by stronk7** [BerriAI/litellm#11325]
### What happened?

Was testing `litellm_stable_release_branch-v1.72.0.rc` docker image, because it fixes a problem with gpt-image-1 for us and, when running the standard tests I've started to get this test failing.

The test is passing with `litellm_stable_release_branch-v1.71.1-stable`.

This is the configuration:
```
  - model_name: "whisper-distil-groq"
    litellm_params:
      model: "groq/distil-whisper-large-v3-en"
      api_key: "os.environ/GROQ_API_KEY"
      model_info:
        mode: audio_transcription
```

And this is the test:
```
curl --request POST \
  --url http://0.0.0.0:4000/v1/audio/transcriptions \
  --header 'authorization: Bearer {{bearer_token}}' \
  --header 'content-type: multipart/form-data' \
  --form file=@hello-test.m4a \
  --form model=whisper-distil-groq
```

That, when working, returns:
```
{
  "text": " Hello, how are you?"
}
```

### Relevant log output

```shell
{
  "error": {
    "message": "litellm.BadRequestError: GroqException - unknown param `GROQ_TRANSCRIPTION_PARAMS[]`. Received Model Group=whisper-distil-groq\nAvailable Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2",
    "type": "None",
    "param": "None",
    "code": "500"
  }
}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.72.0.rc
