### ISSUE TITLE
[Bug]: Prisma doesn't know which engines to download for the Linux distro "wolfi"

### ISSUE THREAD

**Issue by ocristaldo** [BerriAI/litellm#11363]
### What happened?

prisma:warn Prisma doesn't know which engines to download for the Linux distro "wolfi". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "wolfi". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "litellm_db", schema "public" at "postgres:5432"
The database is already in sync with the Prisma schema.
Running generate... (Use --skip-generate to skip the generators)
Running generate... - Prisma Client Python (v0.11.0)
Some types are disabled by default due to being incompatible with Mypy, it is highly recommended
to use Pyright instead and configure Prisma Python to use recursive types. To re-enable certain types:
generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = -1
}
If you need to use Mypy, you can also disable this message by explicitly setting the default value:
generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = 5
}
For more information see: https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/#default-type-limitations
✔ Generated Prisma Client Python (v0.11.0) to ./../../prisma in 549ms

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.72

**Comment by alikhabazian** [comment]
Is this bug exist  yet
I try create lite lllm pod but I got this error in connection with postgress
```
2026-01-05 12:34:22,091 - litellm_proxy_extras - INFO - Running prisma migrate deploy
2026-01-05 12:34:32,513 - litellm_proxy_extras - INFO - prisma db error: prisma:warn Prisma doesn't know which engines to download for the Linux distro "wolfi". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "wolfi". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Error: P1001: Can't reach database server at `litellm-postgres`:`5432`

Please make sure your database server is running at `litellm-postgres`:`5432`.
, e: Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "litellm", schema "public" at "litellm-postgres:5432"

```
and 
```
litellm-deployment.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
data:
  config.yaml: |
      model_list: 
        - model_name: Qwen/Qwen3-32B
          litellm_params:
            model: hosted_vllm/Qwen/Qwen3-32B
            api_base: http://vllm-router-service:80/
            api_key: nothing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image:  192.168.1.173:5555/litellm:v1.78.0-stable
        args:
          - "--config" 
          - "/app/proxy_server_config.yaml"
        env:
          - name: LITELLM_MASTER_KEY
            value: "sk-1234"
          - name: UI_USERNAME
            value: "admin@test.com"
          - name: UI_PASSWORD
            value: "ABcd12#$"
          - name: DATABASE_URL
            value: postgresql://litellm_user:litellm_password@litellm-postgres:5432/litellm

        ports:
        - containerPort: 4000
        volumeMounts:
        - name: config-volume
          mountPath: /app/proxy_server_config.yaml
          subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-service
spec:
  type: ClusterIP
  selector:
    app: litellm
  ports:
    - name: http
      port: 4000
      targetPort: 4000
```
I have test I coud connect to db on others pod the problem is another thing
