### ISSUE TITLE
Support custom timeout on ollama

### ISSUE THREAD

**Issue by Skeo220** [BerriAI/litellm#1137]
I keep getting these errors. I think my server is slow so how do extend the timeout duration?

Traceback (most recent call last):
  File "/.../python3.11/site-packages/litellm/llms/ollama.py", line 233, in ollama_acompletion
    async for line in resp.content.iter_any():
  File "/.../python3.11/site-packages/litellm/llms/ollama.py", line 44, in __anext__
    rv = await self.read_func()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/litellm/llms/ollama.py", line 395, in readany
    await self._wait("readany")
  File "/.../python3.11/site-packages/litellm/llms/ollama.py", line 301, in _wait
    with self._timer:
  File "/.../python3.11/site-packages/litellm/llms/ollama.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
An error occurred: 'NoneType' object is not subscriptable

**Comment by ghost** [comment]
seems relevant to this - https://github.com/BerriAI/litellm/issues/1139

**Comment by ghost** [comment]
Hey @Skeo220 Just realized - you can extend the timeout by just setting timeout in the proxy config 

```yaml 
litellm_settings:
  num_retries: 3 # retry call 3 times on each model_name (e.g. zephyr-beta)
  request_timeout: 10 # raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout 
```
