### ISSUE TITLE
[Feature]: Docs - how to use vLLM OpenAI with Proxy

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1150]
### The Feature

> how do I set the values again like "top_k" and "top_p" in the config file?

Example config a user tried for vLLM + proxy. Our docs did not show how to do this 

```yaml
  - model_name: ishaan-model
    litellm_params:
      model: openai/llama2
      api_base: api-base
      api_key: random
      params: {
            temperature: 0.7,
            top_p: 0.5,
            top_k: 40,
        }
```

## Correct way 
```yaml
 
- model_name: ishaan-model
    litellm_params:
      model:  openai/llama2
      api_base: api-base
      api_key: random
      temperature: 0.7,
      top_p: 0.5,
```

### Motivation, pitch

user struggled with our proxy
