### ISSUE TITLE
[Bug]: Invalid content part type: file

### ISSUE THREAD

**Issue by mantrakp04** [BerriAI/litellm#11529]
### What happened?

Event:
```json
{
  "event": "on_chain_start",
  "data": {
    "input": {
      "messages": [
        {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain_core",
            "messages",
            "HumanMessage"
          ],
          "kwargs": {
            "content": [
              {
                "type": "text",
                "text": "summarize"
              },
              {
                "type": "file",
                "file": {
                  "file_id": "https://neighborly-cuttlefish-201.convex.cloud/api/storage/3ac9f7f1-c8e9-4faa-8ca3-5748190c2c1c",
                  "format": "application/pdf"
                }
              }
            ],
            "additional_kwargs": {},
            "response_metadata": {}
          }
        }
      ]
    }
  },
  "name": "LangGraph",
  "tags": [],
  "run_id": "d88f912e-fd5e-4020-b9c0-12b402929166",
  "metadata": {
    "thread_id": "k172eq6t9d423grc2k3m687pb97hfeh0",
    "langgraph_step": 2,
    "langgraph_node": "agent",
    "langgraph_triggers": [
      "branch:passToShouldPlan:condition:agent"
    ],
    "langgraph_path": [
      "__pregel_pull",
      "agent"
    ],
    "langgraph_checkpoint_ns": "agent:3f11b1a7-0999-5c42-9f1f-a5d7f6cd452a",
    "__pregel_task_id": "3f11b1a7-0999-5c42-9f1f-a5d7f6cd452a",
    "checkpoint_ns": "agent:3f11b1a7-0999-5c42-9f1f-a5d7f6cd452a"
  }
}
```

Error:
```log
Uncaught Error: Uncaught Error: 400 litellm.BadRequestError: OpenAIException - Error code: 400 - [{'error': {'code': 400, 'message': 'Invalid content part type: file', 'status': 'INVALID_ARGUMENT'}}]. Received Model Group=gemini-2.5-flash
Available Model Group Fallbacks=None
```

Config:
```yaml
model_list:
  - model_name: gemini-2.5-flash
    litellm_params:
      model: openai/gemini-2.5-flash-preview-05-20
      base_url: https://generativelanguage.googleapis.com/v1beta/openai/
      api_key: os.environ/GOOGLE_API_KEY
      tags: ["text", "image", "audio", "video", "pdf"]
  - model_name: embeddings
    litellm_params:
      model: gemini/text-embedding-004
      api_key: os.environ/GOOGLE_API_KEY
      tags: ["text", "embeddings"]

litellm_settings:
  drop_params: true

general_settings:
  master_key: os.environ/OPENAI_API_KEY
```

### Relevant log output

```shell
Uncaught Error: Uncaught Error: 400 litellm.BadRequestError: OpenAIException - Error code: 400 - [{'error': {'code': 400, 'message': 'Invalid content part type: file', 'status': 'INVALID_ARGUMENT'}}]. Received Model Group=gemini-2.5-flash
Available Model Group Fallbacks=None
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

ghcr.io/berriai/litellm:main-latest

### Twitter / LinkedIn details

https://x.com/barre_of_lube

**Comment by mantrakp04** [comment]
using gemini as the provider
```yaml
model_list:
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-05-20
      api_key: os.environ/GOOGLE_API_KEY
      tags: ["text", "image", "audio", "video", "pdf"]
  - model_name: embeddings
    litellm_params:
      model: gemini/text-embedding-004
      api_key: os.environ/GOOGLE_API_KEY
      tags: ["text", "embeddings"]

litellm_settings:
  drop_params: true

general_settings:
  master_key: os.environ/OPENAI_API_KEY
```


error:
```json
{
  "error": {
    "message": "litellm.BadRequestError: VertexAIException BadRequestError - b'{\\n  \"error\": {\\n    \"code\": 400,\\n    \"message\": \"* GenerateContentRequest.tools[0].function_declarations[0].parameters.properties[repoUrl].format: only \\'enum\\' and \\'date-time\\' are supported for STRING type\\\\n* GenerateContentRequest.tools[0].function_declarations[1].parameters.properties[repoUrl].format: only \\'enum\\' and \\'date-time\\' are supported for STRING type\\\\n* GenerateContentRequest.tools[0].function_declarations[2].parameters.properties[repoUrl].format: only \\'enum\\' and \\'date-time\\' are supported for STRING type\\\\n\",\\n    \"status\": \"INVALID_ARGUMENT\"\\n  }\\n}\\n'",
    "type": null,
    "param": null,
    "code": "400"
  }
}
```

essentially
```json
  {
  "function_declarations": [
    {
      "name": "get_repo_info",
      "parameters": {
        "type": "object",
        "properties": {
          "repoUrl": {
            "type": "string",
            "format": "url" // <--- THIS IS THE PROBLEM!
          }
        },
        "required": ["repoUrl"]
      }
    }
  ]
  }
```

special case / drop it maybe?:
```json
{
  "function_declarations": [
    {
      "name": "get_repo_info",
      "parameters": {
        "type": "object",
        "properties": {
          "repoUrl": {
            "type": "string" // <--- Removed the "format" field
          }
        },
        "required": ["repoUrl"]
      }
    }
  ]
}
```
