### ISSUE TITLE
[Bug]: Vertex AI gemini-2.5-pro-preview returns an empty string response in v1.72.2

### ISSUE THREAD

**Issue by yorha-l** [BerriAI/litellm#11549]
### What happened?

This was working correctly in v1.72.1. After upgrading to v1.72.2, all responses from the Vertex AI provider have an empty string as content.

Config:
```
- model_name: google/gemini-2.5-pro-preview
    litellm_params:
      vertex_credentials: "xxx.json"
      vertex_location: "global"
      model: vertex_ai/gemini-2.5-pro-preview-06-05
```

### Relevant log output

```shell
{
  "id": "OZZGaMCxN-vJ4_UPmomq2QM",
  "model": "gemini-2.5-pro-preview-06-05",
  "usage": {
    "total_tokens": 42,
    "prompt_tokens": 42,
    "completion_tokens": 0,
    "prompt_tokens_details": {
      "audio_tokens": null,
      "cached_tokens": null
    },
    "completion_tokens_details": {
      "audio_tokens": null,
      "reasoning_tokens": 0,
      "accepted_prediction_tokens": null,
      "rejected_prediction_tokens": null
    }
  },
  "object": "chat.completion",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "",
        "tool_calls": null,
        "function_call": null
      },
      "finish_reason": "stop"
    }
  ],
  "created": 1749456442,
  "system_fingerprint": null
}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.72.2
