### ISSUE TITLE
[Bug]: additional_drop_params not work when using /chat/completions -> /responses bridge

### ISSUE THREAD

**Issue by ZeroClover** [BerriAI/litellm#11722]
### What happened?

When using the responses API only model through the chat completions bridge, the `additional_drop_params` parameter does not take effect.

LiteLLM Proxy config
```yaml
...
      - model_name: gpt-o3-pro
        litellm_params:
          model: openai/o3-pro
          api_base: os.environ/OPENAI_API_BASE
          api_key: os.environ/OPENAI_API_KEY
          input_cost_per_token: 2e-5
          output_cost_per_token: 8e-5
          additional_drop_params: ["temperature", "top_p", "top_k"]
...
```

Make a request to litellm chat completions api to use o3 pro model w/ temperature param then:

<code>litellm.BadRequestError: OpenAIException - { "error": { "message": "Unsupported parameter: 'temperature' is not supported with this model.", "type": "invalid_request_error", "param": "temperature", "code": null } } {"error":{"message":"litellm.BadRequestError: OpenAIException - {\n \"error\": {\n \"message\": \"Unsupported parameter: 'temperature' is not supported with this model.\",\n \"type\": \"invalid_request_error\",\n \"param\": \"temperature\",\n \"code\": null\n }\n}","type":null,"param":null,"code":"400"}}
</code>

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.72.4
