### ISSUE TITLE
[Bug]: Budget for users created with JWT authentication is not being reset

### ISSUE THREAD

**Issue by abarahonar** [BerriAI/litellm#11775]
### What happened?

We are trying JWT authentication, and with the following configuration, even though the users are created correctly, when the job ResetBudgetJob.reset_budget executes it doesn't create reset the budget for any user created through your JWT implementation. Giving one look to the table in the database I can see that the JWT implementation does not populate the `budget_reset_at` column.

```yaml
general_settings:
  enable_jwt_auth: True
  litellm_jwtauth:
    user_email_jwt_field: "email"
    user_id_upsert: true

litellm_settings:
  default_internal_user_params:
    user_role: internal_user
    max_budget: 20
    budget_duration: 1m
```

Previously we had a a custom auth callback that ended up calling the `NewUserRequest` with the email and the role `internal_user` with the following configuration. This works

```yaml
general_settings:
  custom_auth: our_auth

litellm_settings:
  max_internal_user_budget: 20
  internal_user_budget_duration: "1d"
```

![Image](https://github.com/user-attachments/assets/facbce8d-2811-4a5f-93f0-b2fede1fd457)

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

1.72.4
