### ISSUE TITLE
[Bug]: Passthrough should not modify model base_uri

### ISSUE THREAD

**Issue by MightyGoldenOctopus** [BerriAI/litellm#11925]
### What happened?

Let us consider the following model:
```
  - model_name: xxxx
    litellm_params:
      model: hosted_vllm/xxxx
      api_base: "https://xxxx/server/2/v1/"
    model_info:
      mode: embedding
```

**Expected behaviour:**
Calling `/vllm/endpoint` should forward to `https://xxxx/server/2/v1/endpoint`

**Actual behaviour:**
User defined base_uri get stripped from any pre-existing route and forward to: `https://xxxx/endpoint` instead.

Error happens [here](https://github.com/BerriAI/litellm/blob/7abece4ad8d0911d62fc920f5f88cb4b5b5f9e46/litellm/passthrough/main.py#L136) in the code.

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.72.2
