### ISSUE TITLE
[Bug]: Vertex AI Claude Prompt Caching costs are not tracked

### ISSUE THREAD

**Issue by yigitcan-dh** [BerriAI/litellm#11935]
### What happened?

Using LiteLLM GCP Vertex Passthrough with Claude Code.
Got a `5.94$` spent alert from Claude Code but LiteLLM shows the spending as `0.54$`.

Claude Code excessively used "cache read" and "cache write" in my session. This seems to be missing from the LiteLLM calculations.

```
> /cost 
  ⎿  Total cost:            $5.94
...
     Token usage by model:
         claude-3-5-haiku:  105.4k input, 3.6k output, 0 cache read, 0 cache write
         claude-sonnet:  450 input, 36.1k output, 14.0m cache read, 293.7k cache write
```

From the numbers and model pricing, it seems like LiteLLM is only considering input / output tokens. However the cache cost is not included.

### Configuration

```
model_list:
  - model_name: vertex-passthrough-us-east5
    litellm_params:
      model: vertex_ai/*
      use_in_pass_through: true
      vertex_project: project-name
      vertex_location: us-east5
      vertex_credentials: /some-path
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.72.6.post1-nightly
