### ISSUE TITLE
[Bug]: Health check for embedding endpoints

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1202]
### What happened?

Right now, the `/health` endpoint incorrectly attempts to use embeddings endpoints as if they were chat endpoints. This results in `unhealthy_endpoints` incorrectly reporting all the embeddings endpoints.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
Hey @Manouchehri can you try setting `model: 'embedding'` and let me know if that works? 

```yaml
- model_name: GPT-J 6B - Sagemaker Text Embedding (Internal)
    litellm_params: 
      model: "sagemaker/berri-benchmarking-gpt-j-6b-fp16"
    model_info: 
      mode: "embedding"
```

<img width="934" alt="Screenshot 2023-12-21 at 7 50 10 AM" src="https://github.com/BerriAI/litellm/assets/17561003/ea76239f-e94c-4770-99a0-b76028662889">
<img width="715" alt="Screenshot 2023-12-21 at 7 50 07 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c5d5ce49-f73d-4e0a-843a-2ade02261cd1">

**Comment by ishaan-jaff** [comment]
we need some way to know if the model is an embedding model when running checks, 

if you have this in your config, specifying `mode` it makes an embedding health check 

```yaml
model_list:
  - model_name: azure-embedding-model
    litellm_params:
      model: azure/azure-embedding-model
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2023-07-01-preview"
    model_info:
      mode: embedding
      base_model: text-embedding-ada-002
```
