### ISSUE TITLE
[Bug]: Unable to use chat/completions with o3-pro even follow the instruction

### ISSUE THREAD

**Issue by hsuyuming** [BerriAI/litellm#12059]
### What happened?

@krrishdholakia i look at your documentation and try to use it within our environment. (https://docs.litellm.ai/docs/providers/azure/azure_responses#calling-via-chatcompletions), but i still get error, any suggestion?

Do i have to use "azure/responses" as prefix?  If i use this, i get this error "Resource not found"
```
- model_name: o3-pro
    litellm_params:
      model: azure/responses/o3-pro
      api_base: https://xxxxx.openai.azure.com/
      api_version: "2025-03-01-preview"
      tenant_id: os.environ/AZURE_TENANT_ID
      client_id: os.environ/AZURE_CLIENT_ID
      client_secret: os.environ/AZURE_CLIENT_SECRET
      drop_params: true
```

```
user@abehsu-us-vscode:~/abehsu/litellm_clone$ curl -X POST http://localhost:4000/v1/chat/completions -H "Content-Type: application/json"  -H "Authorization: Bearer xxxxxx" -d '{
    "model": "o3-pro",
    "messages": [
        {
            "role": "user",
            "content": "Hello!"
        }
    ]
}'
{"error":{"message":"litellm.APIError: AzureException APIError - Resource not found. Received Model Group=o3-pro\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"404"}}
```
endpoint: https://xxxxx.openai.azure.com/openai/deployments/responses/o3-pro/chat/completions?api-version=2025-04-01-preview

If i use "azure/o3-pro", then i get this error "The chatCompletion operation does not work with the specified model, o3-pro"
```
- model_name: o3-pro
    litellm_params:
      model: azure/o3-pro
      api_base: https://xxxxx.openai.azure.com/
      api_version: "2025-03-01-preview"
      tenant_id: os.environ/AZURE_TENANT_ID
      client_id: os.environ/AZURE_CLIENT_ID
      client_secret: os.environ/AZURE_CLIENT_SECRET
      drop_params: true
```

{"error":{"message":"litellm.BadRequestError: AzureException - The chatCompletion operation does not work with the specified model, o3-pro. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.. Received Model Group=o3-pro\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"400"}}

endpoint: https://xxxxx.openai.azure.com/openai/deployments/o3-pro/chat/completions?api-version=2025-03-01-preview

### Relevant log output

```shell
azure/responses/o3-pro:
{"error":{"message":"litellm.APIError: AzureException APIError - Resource not found. Received Model Group=o3-pro\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"404"}}

azure/o3-pro:

{"error":{"message":"litellm.BadRequestError: AzureException - The chatCompletion operation does not work with the specified model, o3-pro. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.. Received Model Group=o3-pro\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"400"}}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.73.2

### Twitter / LinkedIn details

https://www.linkedin.com/in/hsuyuming
