### ISSUE TITLE
[bug] togetherai api key not working on proxy 

### ISSUE THREAD

**Issue by Huge** [BerriAI/litellm#1208]
### The Feature

Even though the outside/[global docs](https://docs.litellm.ai/docs/proxy/configs) are not bad, they refer to local/live Swagger doc's ConfigYAML object, which lacks the complete list of options supported, the syntax for picking the models. The information is expected to appear down here:
![image](https://github.com/BerriAI/litellm/assets/111648/4bd1eb6c-eb4b-445f-96aa-49e4ecacb9f3)
likely in as https://swagger.io/docs/specification/data-models/enums .

### Motivation, pitch

I was not able to get it running at all yet with my Together account.  "os.environ/TG_API_KEY" seems my last chance remaining.

### Twitter / LinkedIn details

https://twitter.com/userhuge

**Comment by ghost** [comment]
Hey @Huge thanks for this. Want to make sure we solve your problem well, what was the issue you ran into?

**Comment by Huge** [comment]
I have tried some very basic setup where the `1dadadadadada` was a key provided to me by Together. My requests to the proxy instance with that setup were failing so I was like ouch..-)

```
model_list:
  - model_name: llama2-70b-chat
    litellm_params:
      model: togethercomputer/llama-2-70b-chat
      api_key: 1dadadadadada
      rpm: 1
```

I guess maybe if the template has covered all the providers just as you .env.template had( IIRC) in the old repo, that would ease things up while also inflating the template which could be seen negative.
