### ISSUE TITLE
[Bug]: LiteLLM and Langfuse Prompt Management fails

### ISSUE THREAD

**Issue by marumugam-lg** [BerriAI/litellm#12097]
### What happened?

LiteLLM and Langfuse Prompt Integration fails with Bad request error 

Details: 

We have created a config with below details

model_list:
  - model_name: langfuse-model
    litellm_params:
      model: langfuse/anthropic.claude-3-5-sonnet  # langfuse/bedrock/ anthropic.claude-3-5-sonnet  
      prompt_id: "LiteLLM_Testing"      
     aws_access_key_id: ******************
      aws_secret_access_key: **********************
      aws_region_name: **************

  - model_name: anthropic.claude-3-5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_access_key_id: ******************
      aws_secret_access_key: **********************
      aws_region_name: eu-central-1
environment_variables:
  LANGFUSE_HOST: http://127.0.0.1.nip.io/
  LANGFUSE_PUBLIC_KEY: pk-lf-**************
  LANGFUSE_SECRET_KEY: sk-lf-****************

Request 👍 
response = client.chat.completions.create(
    model="langfuse/anthropic.claude-3-5-sonnet-20240620-v1:0, #
    messages=[
        {"role": "user", "content": "what is 1+1"}
    ],
    extra_body={
        "prompt_id":"LiteLLM_Testing"
    }
)
Received Response as 

An error occurred: litellm.BadRequestError: Unmapped LLM provider for this endpoint. You passed model=anthropic.claude-3-5-sonnet-20240620-v1:0, custom_llm_provider=langfuse. Check supported provider and route: https://docs.litellm.ai/docs/providers. Received Model Group=langfuse/anthropic.claude-3-5-sonnet-20240620-v1:0
Available Model Group Fallbacks=None None

Similarly tried various configuration like langfuse/langfuse-model, langfuse-model

An error occurred: 400: {'error': '/chat/completions: Invalid model name passed in model=langfuse/langfuse-model. Call `/v1/models` to view available models for your key.'

We end up in Badrequest or Server error

Also I see error from Langfuse 
    self.Langfuse = langfuse_client_init(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/litellm/integrations/langfuse/langfuse_prompt_management.py", line 105, in langfuse_client_init
    client = Langfuse(**parameters)
TypeError: __init__() got an unexpected keyword argument 'sdk_integration'

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.73.2

**Comment by krrishdholakia** [comment]
@marumugam-lg unable to repro the issue. 

What is the value of your config on langfuse 

<img width="608" alt="Image" src="https://github.com/user-attachments/assets/d19e9784-819d-4216-bf0e-130e781e7b55" />

**Comment by krrishdholakia** [comment]
<img width="1224" alt="Image" src="https://github.com/user-attachments/assets/5165e6ac-4b3e-403d-b5be-8faee05b80fe" />

```yaml
model_list:
  - model_name: langfuse-model
    litellm_params:
      model: langfuse/anthropic.claude-3-5-sonnet # langfuse/bedrock/ anthropic.claude-3-5-sonnet
      prompt_id: "jokes"
      

  - model_name: anthropic.claude-3-5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
```
