### ISSUE TITLE
[Feature]: Support DeepInfra embeddings with parameters

### ISSUE THREAD

**Issue by bgeneto** [BerriAI/litellm#12110]
### The Feature

LiteLLM can support DeepInfra embeddings via OpenAI compatible endpoints. 
The issue is that LiteLLM does not accepts additional parameters (non-supported by OpenAI models) in the request this way. I know it has an option to drop them (`drop_params`). But the fact is that in its current state we cannot use the proxy to set parameters such as `normalize` or `dimensions` for models like Qwen3 embeddings, only if LiteLLM adds support for DeepInfra (and others) as a provider for embeddings. Or create an option so instead of dropping we can ignore non-compatilble OpenAI parameters...

```yaml
  # THIS WON'T WORK
  - model_name: qwen3-embedding-4B
    litellm_params:
      model: deepinfra/Qwen/Qwen3-Embedding-4B
      drop_params: false
      normalize: true
      encoding_format: float
      api_key: os.environ/DEEPINFRA_API_KEY
    model_info:
      mode: embedding
```
> NOTE: Currently, Qwen3 is the best performing embedding model in MTEB bench. 

See [DeepInfra](https://deepinfra.com/Qwen/Qwen3-Embedding-4B/api?example=http) for API details.

### Motivation, pitch

Qwen3 is the best performing embedding model in MTEB bench nowadays, but it uses high embedding dimensions by default (2560 or 4096) that are not supported by pgvector Postgres extension (max. around 2000). So it is important to generate embeddings using a `dimensions` parameter - Qwen3 model [supports](https://qwenlm.github.io/blog/qwen3-embedding/) that config - in order to decrease the deafult value (and to save storage and complexity in the RAG queries). 

### LiteLLM is hiring a founding backend engineer, are you interested in joining us and shipping to all our users?

No

**Comment by BananaLoaf** [comment]
@bgeneto I found a workaround:
```yml
  - model_name: bge-m3
    litellm_params:
      model: openai/BAAI/bge-m3
      api_base: https://api.deepinfra.com/v1/openai
      api_key: os.environ/DEEPINFRA_API_KEY
```
