### ISSUE TITLE
[Feature]: Support order in router

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1212]
### The Feature

User is trying to basically call the latest model first, and then older models in descending order. Make that easier
<img width="489" alt="Screenshot 2023-12-21 at 1 13 03 PM" src="https://github.com/BerriAI/litellm/assets/17561003/bcde83ec-315e-4dba-972a-920ae9cfd96f">

### Motivation, pitch

improve proxy/router for users

**Comment by ishaan-jaff** [comment]
we already support this, if you say `fallbacks = ['gpt-4', 'gpt-4-preview', 'gpt-3']`we loop through the models 

what were you hoping to add here @krrishdholakia ?

**Comment by ghost** [comment]
Just seemed simpler to set order in the model_list, instead of having to configure fallbacks etc. 

I think there might be some perf gains here, but the driver is convenience
```
- model_name: azure-models
  order: 1
  litellm_params: 
    model: azure/chatgpt-v-2
    api_key: os.environ/AZURE_API_KEY
    api_base: os.environ/AZURE_API_BASE
    api_version: os.environ/AZURE_API_VERSION
- model_name: azure-models
  order: 2  
  litellm_params: 
    model: azure/gpt-turbo
    api_key: os.environ/AZURE_FRANCE_API_KEY
    api_base: https://openai-france-1234.openai.azure.com
    api_version: os.environ/AZURE_API_VERSION
- model_name: azure-models
  order: 3
  litellm_params: 
    model: azure/gpt-35-turbo
    api_key: os.environ/AZURE_EUROPE_API_KEY
    api_base: https://my-endpoint-europe-berri-992.openai.azure.com
    api_version: os.environ/AZURE_API_VERSION
```
