### ISSUE TITLE
[Bug]: Bedrock Guardrails - Sensitive Data Leaked to Logs When Using SensitiveInformationPolicyConfig

### ISSUE THREAD

**Issue by marty-sullivan** [BerriAI/litellm#12152]
### What happened?

When configuring a Bedrock Guardrail for Sensitive Information (PII), triggering the Guardrail causes the sensitive information, plus the entire prompt & completion, to leak to both the system logs and to the LiteLLM logs stored in the database.

To reproduce:

1. Configure a Bedrock Guardrail to block Sensitive Information (cloudformation below)
2. Configure the guardrail in your config.yaml
3. Attempt to trigger the guardrail by providing a prompt containing fake name, fake ssn and fake phone number.

CloudFormation for Guardrail:

```yaml
MaskPiiGuardrail:
    Type: 'AWS::Bedrock::Guardrail'
    Properties:
      Name: 'mask-pii'
      BlockedInputMessaging: 'Your prompt has triggered a content filter, please check for PII data in your prompt and try again.'
      BlockedOutputsMessaging: 'The model response has triggered a content filter, please check for PII data in your prompt and try again.'  
      SensitiveInformationPolicyConfig:
        PiiEntitiesConfig:
          - Type: 'ADDRESS'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'AGE'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'AWS_ACCESS_KEY'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'AWS_SECRET_KEY'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'CA_HEALTH_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'CA_SOCIAL_INSURANCE_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'CREDIT_DEBIT_CARD_CVV'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'CREDIT_DEBIT_CARD_EXPIRY'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'CREDIT_DEBIT_CARD_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'DRIVER_ID'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'EMAIL'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'INTERNATIONAL_BANK_ACCOUNT_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'IP_ADDRESS'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'LICENSE_PLATE'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'MAC_ADDRESS'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'NAME'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'PASSWORD'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'PHONE'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'PIN'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'SWIFT_CODE'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'UK_NATIONAL_HEALTH_SERVICE_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'UK_NATIONAL_INSURANCE_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'URL'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'US_BANK_ACCOUNT_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'US_BANK_ROUTING_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'US_PASSPORT_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'US_SOCIAL_SECURITY_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'USERNAME'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
          - Type: 'VEHICLE_IDENTIFICATION_NUMBER'
            Action: 'BLOCK'
            InputAction: 'BLOCK'
            InputEnabled: true
            OutputAction: 'BLOCK'
            OutputEnabled: true
```

Config.yaml:

```yaml
guardrails:
  - guardrail_name: 'pii'
    litellm_params:
      guardrail: 'bedrock'
      mode: 'pre_call'
      guardrailIdentifier: os.environ/BEDROCK_GUARDRAIL_MASK_PII_ID
      guardrailVersion: os.environ/BEDROCK_GUARDRAIL_MASK_PII_VERSION
      aws_region_name: 'us-east-1'
```

Python code to generate the log output:

```python
from openai import OpenAI, BadRequestError
from os import getenv

client = OpenAI(
    base_url=getenv('OPENAI_BASE_URL'),
    api_key=getenv('OPENAI_API_KEY'),
)

model_name = 'google.gemini-2.5-flash'

# Test PII Guardrail

pii_prompt = 'My name is John Smith and my SSN is 324-12-3212 and my phone number is 607-456-7890. Can you please repeat to me my name and phone number?'

try:
    response = client.chat.completions.create(
        model=model_name,
        messages=[
            {
                'role': 'user', 
                'content': pii_prompt,
            },
        ],
        extra_body=dict(
            guardrails=[
                'pii',
            ]),

    )

    print(response.model_dump_json(indent=2))

except BadRequestError as e:
    print(e)

    # Example Output to Logs:

    """
    Error code: 400 - {
      "error": {
        "message": {
          "error": "Violated guardrail policy",
          "bedrock_guardrail_response": {
            "action": "GUARDRAIL_INTERVENED",
            "actionReason": "Guardrail masked.",
            "assessments": [
              {
                "invocationMetrics": {
                  "guardrailCoverage": {
                    "textCharacters": {
                      "guarded": 138,
                      "total": 138
                    }
                  },
                  "guardrailProcessingLatency": 349,
                  "usage": {
                    "contentPolicyImageUnits": 0,
                    "contentPolicyUnits": 0,
                    "contextualGroundingPolicyUnits": 0,
                    "sensitiveInformationPolicyFreeUnits": 0,
                    "sensitiveInformationPolicyUnits": 1,
                    "topicPolicyUnits": 0,
                    "wordPolicyUnits": 0
                  }
                },
                "sensitiveInformationPolicy": {
                  "piiEntities": [
                    {
                      "action": "ANONYMIZED",
                      "detected": true,
                      "match": "John Smith",
                      "type": "NAME"
                    },
                    {
                      "action": "ANONYMIZED",
                      "detected": true,
                      "match": "324-12-3212",
                      "type": "US_SOCIAL_SECURITY_NUMBER"
                    },
                    {
                      "action": "ANONYMIZED",
                      "detected": true,
                      "match": "607-456-7890",
                      "type": "PHONE"
                    }
                  ]
                }
              }
            ],
            "guardrailCoverage": {
              "textCharacters": {
                "guarded": 138,
                "total": 138
              }
            },
            "output": [
              {
                "text": "My name is {{NAME}} and my SSN is {{US_SOCIAL_SECURITY_NUMBER}} and my phone number is {{PHONE}}. Can you please repeat to me my name and phone number?"
              }
            ],
            "outputs": [
              {
                "text": "My name is {{NAME}} and my SSN is {{US_SOCIAL_SECURITY_NUMBER}} and my phone number is {{PHONE}}. Can you please repeat to me my name and phone number?"
              }
            ],
            "usage": {
              "contentPolicyImageUnits": 0,
              "contentPolicyUnits": 0,
              "contextualGroundingPolicyUnits": 0,
              "sensitiveInformationPolicyFreeUnits": 0,
              "sensitiveInformationPolicyUnits": 1,
              "topicPolicyUnits": 0,
              "wordPolicyUnits": 0
            }
          }
        },
        "type": "None",
        "param": "None",
        "code": "400"
      }
    }
    """
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v 1.73.0
