### ISSUE TITLE
[Bug]: Proxy gemini models ends with `o` won't appears at model list when check_provider_endpoint is enabled

### ISSUE THREAD

**Issue by oott123** [BerriAI/litellm#12160]
### What happened?

using litellm proxy

config.yaml:

```
model_list:
  - model_name: "gemini/*"
    litellm_params:
      model: "gemini/*"
      api_key: os.environ/GEMINI_API_KEY
litellm_settings:
  check_provider_endpoint: true
```

repro:

```
$ curl -sq litellm/v1/models | jq '.data[].id' | grep gemini-2.5-pr
"gemini/gemini-2.5-pro-preview-03-25"
"gemini/gemini-2.5-pro-preview-05-06"
"gemini/gemini-2.5-pro-preview-06-05"
"gemini/gemini-2.5-pr" <-- o is missing!
"gemini/gemini-2.5-pro-preview-tt"
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.73.2
