### ISSUE TITLE
[Bug]: requester_metadata is not included in the OpenTelemetry spans

### ISSUE THREAD

**Issue by luismarquezgft** [BerriAI/litellm#12166]
### What happened?

Cline VS Code extension sends `requester_metadata` with the key `cline_task_id`. However, the integration with OpenTelemetry does not consider requester_metadata and sends this attribute empty. I mean, if you connect Cline with LiteLLM, Cline sends requester_metadata with a session id which is not being included in the OpenTelemetry traces.

> BTW, I'm not really sure about it, but I think it does work in the integration with Langfuse.

This is what Cline sends to LiteLLM:
![Image](https://github.com/user-attachments/assets/284284ef-3068-451e-8b52-8488666cdd78)

This is the OpenTelemetry payload emitted by LiteLLM for that Cline session. Notice `requester_metadata` is empty:
```yaml
                        {
                            "trace_id": "SafYb3uXd/6MHtIQxGMmZg==",
                            "span_id": "tRjizP7YEaw=",
                            "parent_span_id": "T7wl1vgAOkc=",
                            "name": "litellm_request",
                            "kind": 1,
                            "start_time_unix_nano": "1751292838794711040",
                            "end_time_unix_nano": "1751292841143768064",
                            "attributes": [
                                {
                                    "key": "metadata.user_api_key_hash",
                                    "value": {
                                        "string_value": "88**************************************88"
                                    }
                                },
...
                                {
                                    "key": "metadata.requester_metadata",
                                    "value": {
                                        "string_value": "{}"
                                    }
                                },
...
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.72.2
