### ISSUE TITLE
Load balance over several llama.cpp engines 

### ISSUE THREAD

**Issue by gelim** [BerriAI/litellm#1273]
### What happened?

Hello,
I've a setup where I have 8 gpus busy with 4 llama.cpp `. /server` engines (serving same mixtral GGUF each over 2 GPUs). If several users concurrently launch completion requests I fail to have litellm redirect them to the next free engine.

My best result so far is to select `simple-shuffle` strategy but this is not optimal as there is still odds that a query will be redirected toward a busy engine (and denied) 

I tried playing with tpm/rpm parameters and according strategies but nothing does what I expect. `least-busy` does not work as expected either. All calls will be toward first engine while the 3 next are free.

Would be awesome to have some guidance here :) 
Cheers, 

NB: I tried also with llama-cpp-python + `interrupt_requests=False` this will have second requests blocked waiting for engine to have a free slot but still not optimal as the routing can redirect to a busy engine while others will be free.

**Comment by ghost** [comment]
Hey @gelim, I'll look into this ASAP.

> tpm/rpm parameters and according strategies but nothing does what I expect
> least-busy does not work as expected either


Can you share a stacktrace/anything i can use to repro this ?

I'm also working to repro and fix this on our end. Thank you for raising this.

**Comment by krrishdholakia** [comment]
Hey @gelim, I wasn't able to repro this issue, but I did find that least_busy was tracking usage based on the deployment name, not id, which could be causing collisions for multiple deployments with the same name. 

I pushed a fix to move it to id, and also added some unit testing here. 

It would help to know how you're constructing your model_list, to repro what might be causing this. 

For context, here's our test - https://github.com/BerriAI/litellm/blob/678bbfa9be8b62a1f57afb1cf702b877c4cb07f5/litellm/tests/test_least_busy_routing.py#L70

**Comment by ghost** [comment]
Hey @gelim just pushed a fix to least-busy for it to use model id's instead of names, which could be causing collisions. 

https://github.com/BerriAI/litellm/commit/678bbfa9be8b62a1f57afb1cf702b877c4cb07f5

**[ASK]: Can you share how you're setting model_list for repro?**

Here's how we test it btw, let me know if we're missing a case: https://github.com/BerriAI/litellm/blob/54d7bc2cc37fb7d3deedbd06147f8bf2467eef7b/litellm/tests/test_least_busy_routing.py#L70

**Comment by gelim** [comment]
Hey @krrishdholakia thanks for looking into it.

> Hey @gelim just pushed a fix to least-busy for it to use model id's instead of names, which could be causing collisions.
> 
> [678bbfa](https://github.com/BerriAI/litellm/commit/678bbfa9be8b62a1f57afb1cf702b877c4cb07f5)
> 
> **[ASK]: Can you share how you're setting model_list for repro?**
> 

My current config.yaml looks like this:

``` yaml
model_list:
  - model_name: mixtral
    litellm_params:
      model: openai/mixtral-gpu01
      api_key: $API_KEY
      api_base: http://$LLAMAHOST:8080/v1

  - model_name: mixtral
    litellm_params:
      model: openai/mixtral-gpu23
      api_key: $API_KEY
      api_base: http://$LLAMAHOST:8081/v1
[...] 
     
router_settings:
  routing_strategy: simple-shuffle

litellm_settings:
  drop_params: False
  set_verbose: False
``` 

I shortened the list of models but you get the idea.

> Here's how we test it btw, let me know if we're missing a case:
> 
> https://github.com/BerriAI/litellm/blob/54d7bc2cc37fb7d3deedbd06147f8bf2467eef7b/litellm/tests/test_least_busy_routing.py#L70

I will check that later on thanks

**Comment by ghost** [comment]
@gelim also refactored our tpm/rpm routing, to deal with the model id issue. 

But looking at your config, that doesn't seem to be what's causing this. 

I'll run more testing against the proxy and see what might be happening. I can confirm this commit has tpm/rpm routing working as expected - https://github.com/BerriAI/litellm/commit/cf91e49c87ae7f92a5bd16060847f378b7d9d7a4

Will investigate more on proxy.

**Comment by gelim** [comment]
I added a comment on a int cast that is breaking the logic: https://github.com/BerriAI/litellm/commit/678bbfa9be8b62a1f57afb1cf702b877c4cb07f5#r135896151

**Comment by ghost** [comment]
Hey @gelim thanks for the catch, pushed a fix - https://github.com/BerriAI/litellm/commit/2fc264ca0400561d033d6ba13f12d77422b51095

The changes aren't stable, i'm still fixing some issues raised by our ci/cd pipeline. Do you have a test script your running against the proxy?

**Comment by ghost** [comment]
I'll update this ticket once we have a stable release with the changes.

**Comment by gelim** [comment]
> Hey @gelim thanks for the catch, pushed a fix - [2fc264c](https://github.com/BerriAI/litellm/commit/2fc264ca0400561d033d6ba13f12d77422b51095)
> 
> The changes aren't stable, i'm still fixing some issues raised by our ci/cd pipeline. Do you have a test script your running against the proxy?

No, it's all manual for the moment (having 2 chats and asking for completion). But yeah if that takes longer to debug, would be better to have some automated way to validate the behavior.

**Comment by gelim** [comment]
so my test case to reproduce the bad behavior is doing 2 requests to the completion API of litellm with a query that keep the engine busy for a few tenth of seconds. If I run the payload again (I have a different user id for the second one) I get a blank answer with HTTP data `data:  [DONE]`

completion json `userX.json`:
``` json
{
  "model": "mixtral",
  "temperature": 1,
  "top_p": 1,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "stop": [
    "||>",
    "\nUser:",
    "<|diff_marker|>"
  ],
  "user": "6589934e8407ab6ece3ee58f",
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "Hello, can you generate a 500 words poem?"
    }
  ]
}
``` 

``` bash
$ curl litellm:8000/v1/api/completions -d @user0.json
(data: {"id": "chatcmpl-I2nvxtFu4QBWvjBvKIFuuHg7OwgDlK6u", "choices": [{"finish_reason": null, "index": 0, "delta": {"function_call": null, "tool_calls": null, "content": "'", "role": null}}], "created": 1703864965, "model": "mixtral-gpu23", "object": "chat.completion.chunk", "system_fingerprint": null, "usage": {}})

[...]
```

``` bash
$ curl litellm:8000/v1/api/completions -d @user1.json
data:  [DONE]
```
to run this test I was using [2fc264c](https://github.com/BerriAI/litellm/commit/2fc264ca0400561d033d6ba13f12d77422b51095) and with config I previously shared, just I changed the strategy to `least-busy`



we can see `mixtral-gpu23` got all requests and thus dropped the second one for user1, while `mixtral-gpu01` was idling

**Comment by ghost** [comment]
@gelim thanks this is helpful. I'll have a fix out for you by tomorrow, and I'll add this test to our ci/cd.

**Comment by ghost** [comment]
Hey, @gelim you're input looks incorrect - you're passing a `messages` request to `/completions`. 

`/completions` only accepts prompt  - https://platform.openai.com/docs/api-reference/completions/create

Are you trying to call `/chat/completions` instead?

**Comment by ghost** [comment]
Hey @gelim, I can confirm least busy works on the proxy here - https://github.com/BerriAI/litellm/commit/38f55249e10695bc316ea3444049b504e9918149

This is my script for testing: 
```python
from openai import AsyncOpenAI, AsyncAzureOpenAI
import random, uuid
import time, asyncio, litellm
# import logging
# logging.basicConfig(level=logging.DEBUG)
#### LITELLM PROXY #### 
litellm_client = AsyncOpenAI(
    api_key="sk-1234", # [CHANGE THIS]
    base_url="http://0.0.0.0:8000"
)


async def test_router_completion_streaming():
    messages = [
        {"role": "user", "content": "Hello, can you generate a 500 words poem?"}
    ]
    model = "azure-models"
    ### Call the async calls in sequence, so we start 1 call before going to the next.

    ## CALL 1
    await asyncio.sleep(random.uniform(0, 2))
    response_1 = await litellm_client.chat.completions.with_raw_response.create(model=model, messages=messages, stream=True)
    model_id_1 = response_1.headers.get('x-litellm-model-id')
    print(f"Response 1 litellm header: {model_id_1}")
    ## CALL 2
    await asyncio.sleep(random.uniform(0, 2))
    response_2 = await litellm_client.chat.completions.with_raw_response.create(model=model, messages=messages, stream=True)
    model_id_2 = response_2.headers.get('x-litellm-model-id')
    print(f"Response 2 litellm header: {model_id_2}")
    ## CALL 3
    await asyncio.sleep(random.uniform(0, 2))
    response_3 = await litellm_client.chat.completions.with_raw_response.create(model=model, messages=messages, stream=True)
    model_id_3 = response_3.headers.get('x-litellm-model-id')
    print(f"Response 3 litellm header: {model_id_3}")

    ## Test Uniqueness
    assert model_id_1 != model_id_2
    assert model_id_1 != model_id_3
    assert model_id_2 != model_id_3
    

    
asyncio.run(test_router_completion_streaming())
```

This is my config file: 

```yaml
model_list:
- model_name: azure-models
  litellm_params: 
    model: azure/chatgpt-v-2
    api_key: os.environ/AZURE_API_KEY
    api_base: os.environ/AZURE_API_BASE
    api_version: os.environ/AZURE_API_VERSION
- model_name: azure-models
  litellm_params: 
    model: azure/gpt-turbo
    api_key: os.environ/AZURE_FRANCE_API_KEY
    api_base: https://openai-france-1234.openai.azure.com
    api_version: os.environ/AZURE_API_VERSION
- model_name: azure-models
  litellm_params: 
    model: azure/gpt-35-turbo
    api_key: os.environ/AZURE_EUROPE_API_KEY
    api_base: https://my-endpoint-europe-berri-992.openai.azure.com
    api_version: os.environ/AZURE_API_VERSION
router_settings:
  routing_strategy: "least-busy"
```
