### ISSUE TITLE
[Feature]: Add alerting to proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1298]
### The Feature

Add alerting based on thresholds: 
- [x] Responses taking too long 
- [x] Requests are hanging 
- [x] Calls are failing 
- [x] DB Read/Writes are failing 

### Motivation, pitch

Inspired by this: https://github.com/BerriAI/litellm/issues/1252#issuecomment-1870199251; https://github.com/BerriAI/litellm/issues/1056; https://github.com/BerriAI/litellm/issues/1278

**Comment by ghost** [comment]
Slack alerting should be a good start

**Comment by ishaan-jaff** [comment]
this will help us with load testing too, useful issue !

**Comment by ghost** [comment]
Thinking through how a user might use this: 

```yaml
general_settings: 
     alerting: ["slack"]

environment_variables:
    SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/<>/<>/<>"
```
