### ISSUE TITLE
[Bug]: Have /key/generate work on Kubernetes pod - 8 workers 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1321]
### The Feature

Support kubernetes health checks on proxy, to enable auto-scaling 

### Motivation, pitch

Proxy shows that it's healthy, before it's actually working on kubernetes. 

This can cause unhealthy pods to get used

**Comment by ghost** [comment]
Here's a high-level approach to achieve this:

1. Use Gunicorn to manage workers of your FastAPI app.
2. Implement custom health checks in your FastAPI app.
3. Create readiness and liveness probes in Kubernetes for orchestrated deployment.

**Comment by ghost** [comment]
```python
from fastapi import FastAPI

app = FastAPI()

# Create an in-memory structure to hold worker initialization states
WORKER_READY = {}

@app.on_event("startup")
async def startup_event():
    worker_id = get_worker_id()  # You need to implement `get_worker_id()` so it returns a unique identifier for the worker
    WORKER_READY[worker_id] = False

@app.get("/ready")
async def readiness_probe():
    # This will return successful when all workers are set to True in WORKER_READY
    return {"status": "ready" if all(WORKER_READY.values()) else "initializing"}

@app.get("/liveness")
async def liveness_probe():
    return {"status": "live"}

@app.get("/")
async def root():
    worker_id = get_worker_id()  # Same as before, identify the worker
    WORKER_READY[worker_id] = True  # Mark this worker as ready
    return {"message": "Hello World"}
    
def get_worker_id():
    # Implement this so it returns a unique worker identifier
    # This could be based on environment variables set by Gunicorn/Uvicorn.
    return "unique_worker_id"

# Other FastAPI routes and logic...
```

**Gunicorn Configuration (`gunicorn_conf.py`):**

```python
# Assuming the workers need to be preload-enabled
preload_app = True
# Number of workers
workers = 8

# Gunicorn hook for post-fork to mark workers as not ready initially
def post_fork(server, worker):
    server.app.callable.WORKER_READY[worker.pid] = False
    
# Other Gunicorn config settings...
```

**Kubernetes Deployment:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: your-image-name:your-tag
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        command: ["gunicorn", "-c", "/path/to/gunicorn_conf.py", "main:app", "--bind", "0.0.0.0:8000", "--worker-tmp-dir", "/dev/shm"]
```
