### ISSUE TITLE
[Bug]: Sagemaker Cost Tracking not working on Proxy 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1592]
### What happened?

- Make Sagemaker calls on the proxy 
- make 1 request, no cost was tracked. I only see a log saying sagemaker model is not in model_cost_map 

- We should by default support sagemaker cost track 
- The exceptions for cost tracking were not raised, i had to view logs to figure this out

**Comment by ghost** [comment]
@ishaan-jaff sagemaker pricing depends on machine used 

Here's how to enable it - https://docs.litellm.ai/docs/proxy/custom_pricing

**Comment by ishaan-jaff** [comment]
@krrishdholakia still does not work for me

Here's my config.yaml

```
  - model_name: sagemaker
    litellm_params:
      model: sagemaker/berri-benchmarking-Llama-2-70b-chat-hf-4
      input_cost_per_second: 0.000420
      output_cost_per_second: 0.000420
```

**Comment by ishaan-jaff** [comment]
looks like this works for non-streaming and fails for streaming

**Comment by ghost** [comment]
Ok, i'll take a look at this

**Comment by ishaan-jaff** [comment]
Do i need to set both `input_cost_per_second` and `output_cost_per_token` The doc said I only need this in my yaml?Can you clarify this on the doc 

```
model_list:
  - model_name: sagemaker-completion-model
    litellm_params:
      model: sagemaker/berri-benchmarking-Llama-2-70b-chat-hf-4
      input_cost_per_second: 0.000420
  - model_name: sagemaker-embedding-model
    litellm_params:
      model: sagemaker/berri-benchmarking-gpt-j-6b-fp16
      input_cost_per_second: 0.000420
```
