### ISSUE TITLE
[Question]: openai proxy with together_ai - multiple models support

### ISSUE THREAD

**Issue by 7flash** [BerriAI/litellm#1609]
### What happened?

to reproduce,

1. `pip install litellm[proxy]`
2. `export TOGETHERAI_API_KEY=""`
3. `litellm --model together_ai/togethercomputer/llama-2-70b-chat`
4.
```
curl --location 'http://0.0.0.0:8000/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "together_ai/togethercomputer/llama-2-70b-chat",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ]
    }
'
```

It works as expected. But if I change "model" field in my curl request it does not affect the output, still using same model specified when starting litellm. I would like to be able specify multiple models on start or "all" specifier, because I need to be able to choose actual model in my chat UI.

**Comment by ishaan-jaff** [comment]
@7flash you should use the config.yaml when you using the proxy with multiple models 

https://docs.litellm.ai/docs/proxy/configs 


```yaml
model_list:
  - model_name: gpt-3.5-turbo # user-facing model alias
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: azure/gpt-turbo-small-eu
      api_base: https://my-endpoint-europe-berri-992.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY_EU" # does os.getenv("AZURE_API_KEY_EU")
      rpm: 6      # Rate limit for this deployment: in requests per minute (rpm)
  - model_name: bedrock-claude-v1 
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-turbo-small-ca
      api_base: https://my-endpoint-canada-berri992.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY_CA"
      rpm: 6
  - model_name: vllm-models
    litellm_params:
      model: openai/facebook/opt-125m # the `openai/` prefix tells litellm it's openai compatible
      api_base: http://0.0.0.0:8000
      rpm: 1440
    model_info: 
      version: 2

```

Start proxy 
```shell
 litellm --config /path/to/config.yaml
```

**Comment by ghost** [comment]
@7flash did that solve your issue?

**Comment by ghost** [comment]
@7flash bump on this? 

Would also like to setup a direct support channel on: 
- linkedin - https://www.linkedin.com/in/krish-d/ 
- discord - #krrish8748

if that works? 

Happy to do a 10 min. call this week, to improve litellm for you - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by 7flash** [comment]
Thanks, yes it works

I have updated my config to support all together-ai chat models with langfuse logging:

```
model_list:
  - model_name: deepseek-coder-33b-instruct
    litellm_params:
      model: together_ai/deepseek-ai/deepseek-coder-33b-instruct
  - model_name: Nous-Hermes-2-Mixtral-8x7B-DPO
    litellm_params:
      model: together_ai/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
  - model_name: dolphin-2.6-mistral-7b-dpo-laser
    litellm_params:
      model: together_ai/cognitivecomputations/dolphin-2.6-mistral-7b-dpo-laser
  - model_name: alpaca-7b
    litellm_params:
      model: together_ai/togethercomputer/alpaca-7b
  - model_name: chronos-hermes-13b
    litellm_params:
      model: together_ai/Austism/chronos-hermes-13b
  - model_name: CodeLlama-7b-Instruct-hf
    litellm_params:
      model: together_ai/codellama/CodeLlama-7b-Instruct-hf
  - model_name: CodeLlama-13b-Instruct-hf
    litellm_params:
      model: together_ai/codellama/CodeLlama-13b-Instruct-hf
  - model_name: CodeLlama-34b-Instruct-hf
    litellm_params:
      model: together_ai/codellama/CodeLlama-34b-Instruct-hf
  - model_name: DiscoLM-mixtral-8x7b-v2
    litellm_params:
      model: together_ai/DiscoResearch/DiscoLM-mixtral-8x7b-v2
  - model_name: falcon-40b-instruct
    litellm_params:
      model: together_ai/togethercomputer/falcon-40b-instruct
  - model_name: falcon-7b-instruct
    litellm_params:
      model: together_ai/togethercomputer/falcon-7b-instruct
  - model_name: GPT-NeoXT-Chat-Base-20B
    litellm_params:
      model: together_ai/togethercomputer/GPT-NeoXT-Chat-Base-20B
  - model_name: Llama-2-7b-chat-hf
    litellm_params:
      model: together_ai/meta-llama/Llama-2-7b-chat-hf
  - model_name: Llama-2-13b-chat-hf
    litellm_params:
      model: together_ai/meta-llama/Llama-2-13b-chat-hf
  - model_name: Llama-2-70b-chat-hf
    litellm_params:
      model: together_ai/meta-llama/Llama-2-70b-chat-hf
  - model_name: Llama-2-7B-32K-Instruct
    litellm_params:
      model: together_ai/togethercomputer/Llama-2-7B-32K-Instruct
  - model_name: Mistral-7B-Instruct-v0.1
    litellm_params:
      model: together_ai/mistralai/Mistral-7B-Instruct-v0.1
  - model_name: Mistral-7B-Instruct-v0.2
    litellm_params:
      model: together_ai/mistralai/Mistral-7B-Instruct-v0.2
  - model_name: Mixtral-8x7B-Instruct-v0.1
    litellm_params:
      model: together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1
  - model_name: MythoMax-L2-13b
    litellm_params:
      model: together_ai/Gryphe/MythoMax-L2-13b
  - model_name: Nous-Hermes-llama-2-7b
    litellm_params:
      model: together_ai/NousResearch/Nous-Hermes-llama-2-7b
  - model_name: Nous-Hermes-Llama2-13b
    litellm_params:
      model: together_ai/NousResearch/Nous-Hermes-Llama2-13b
  - model_name: Nous-Hermes-Llama2-70b
    litellm_params:
      model: together_ai/NousResearch/Nous-Hermes-Llama2-70b
  - model_name: Nous-Hermes-2-Mixtral-8x7B-SFT
    litellm_params:
      model: together_ai/together_ai/NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT
  - model_name: Nous-Hermes-2-Yi-34B
    litellm_params:
      model: together_ai/NousResearch/Nous-Hermes-2-Yi-34B
  - model_name: Nous-Capybara-7B-V1p9
    litellm_params:
      model: together_ai/NousResearch/Nous-Capybara-7B-V1p9
  - model_name: openchat-3.5-1210
    litellm_params:
      model: together_ai/openchat/openchat-3.5-1210
  - model_name: OpenHermes-2-Mistral-7B
    litellm_params:
      model: together_ai/teknium/OpenHermes-2-Mistral-7B
  - model_name: OpenHermes-2p5-Mistral-7B
    litellm_params:
      model: together_ai/teknium/OpenHermes-2p5-Mistral-7B
  - model_name: Mistral-7B-OpenOrca
    litellm_params:
      model: together_ai/Open-Orca/Mistral-7B-OpenOrca
  - model_name: Platypus2-70B-instruct
    litellm_params:
      model: together_ai/garage-bAInd/Platypus2-70B-instruct
  - model_name: Pythia-Chat-Base-7B-v0.16
    litellm_params:
      model: together_ai/togethercomputer/Pythia-Chat-Base-7B-v0.16
  - model_name: RedPajama-INCITE-Chat-3B-v1
    litellm_params:
      model: together_ai/togethercomputer/RedPajama-INCITE-Chat-3B-v1
  - model_name: RedPajama-INCITE-7B-Chat
    litellm_params:
      model: together_ai/togethercomputer/RedPajama-INCITE-7B-Chat
  - model_name: Qwen-7B-Chat
    litellm_params:
      model: together_ai/togethercomputer/Qwen-7B-Chat
  - model_name: SOLAR-0-70b-16bit
    litellm_params:
      model: together_ai/upstage/SOLAR-0-70b-16bit
  - model_name: StripedHyena-Nous-7B
    litellm_params:
      model: together_ai/togethercomputer/StripedHyena-Nous-7B
  - model_name: vicuna-7b-v1.5
    litellm_params:
      model: together_ai/lmsys/vicuna-7b-v1.5
  - model_name: vicuna-13b-v1.5
    litellm_params:
      model: together_ai/lmsys/vicuna-13b-v1.5
  - model_name: vicuna-13b-v1.5-16k
    litellm_params:
      model: together_ai/lmsys/vicuna-13b-v1.5-16k
  - model_name: Yi-34B-Chat
    litellm_params:
      model: together_ai/zero-one-ai/Yi-34B-Chat
                 
litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  # post_call_rules: post_call_rules.my_custom_rule
  set_verbose: True

router_settings:
  num_retries: 0

environment_variables:
  TOGETHERAI_API_KEY: ""
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""
```

Also it works with any custom proxy server exposing /v1/chat/completions such as script implemented here: https://github.com/outlines-dev/outlines/issues/594#issuecomment-1928793333

It's very useful to implement custom logic for handling prompts with multiple models. Notice, in script above we initialize outlines pointing to litellm endpoint, and then deploy the script itself to endpoint which is included in same config:

```
  - model_name: my-proxy-model
      litellm_params:
      model: openai/my-proxy-model
      api_base: https://my-proxy-model-as.a.run.app
```

For example, now I can redirect prompts with longer context to mixtral and use gpt-4 for shorter questions etc..
