### ISSUE TITLE
[Discussion]: Setting model name during client init

### ISSUE THREAD

**Issue by MypaceEngine** [BerriAI/litellm#1610]
### What happened?

litellm create wrong URL pattern for Azure OpenAI.
Example of Azure OpenAI Endpoint: http://xxxx.openai.azure.com/openai/deployments/chatgpt-2 
But litellm create http://xxxx.openai.azure.com/openai/ and use this for communication to Azure OpenAI service.
litellm get HTTP error code and communication is faulure.
OpenAI Proxy does not work in case of Azure OpenAI.  

I define config.yaml:
```
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/chatgpt-v-2
      api_base: https://openai-gpt-4-test-v-1.openai.azure.com/
      api_version: "2023-05-15"
      api_key: "xxxxxxxxxxxxxxxxxxxxx"
```

I think https://cognitiveservices.azure.com is not permitted in some company for company rule.
In this situation, deployments id is needed. like https://github.com/BerriAI/litellm/blob/main/litellm/llms/azure.py.
If user assign deployment id  like azure/chatgpt-v-2. Please assign deployment id to openai.AzureOpenAI/openai.AsyncAzureOpenAI.

Sample source of patch:
https://github.com/BerriAI/litellm/commit/00513f31bbc8d959c129bf12970c8a14317d775a
