### ISSUE TITLE
[Feature]: Proxy SSO Login - Add OpenID, Azure AD 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1658]
### The Feature

> OK, did not know I wanted it until you added Google SSO :) I would like OpenID authentication so I can configure it with AzureAD.

@bsu3338

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
@bsu338 can you help use understand this better ? 

Are you hoping for other team members to Auth into the Proxy using Azure AD SSO ?

**Comment by bsu3338** [comment]
Correct, as employees or students at the school come across tools that are requesting openai api access, I could have them request their api keys through an azure ad auth portal. Group access could also be controlled that way.

**Comment by ishaan-jaff** [comment]
@bsu3338 will add it this week, will you be able to give us feedback / hop on a call once we add this?

**Comment by ishaan-jaff** [comment]
![litellm-key-gen-2](https://github.com/BerriAI/litellm/assets/29436595/783d70cf-2bb7-49f7-bd17-96d7c2c9331e)

Here's a demo of the flow with Google

**Comment by bsu3338** [comment]
@ishaan-jaff will do, the advantage of supporting openid is it should work with other auth providers as well

**Comment by bsu3338** [comment]
Good timing on this, now that codellama 70 has been released, I want to see if the developers can use the portal to get an api key to get access to a local version of codellama running behind litellm. I am going to try to integrate visual code with continue.dev

**Comment by ishaan-jaff** [comment]
Working on this now @bsu3338 here's a ss of Microsoft Auth setup - is this what you wanted ? 
Flow here is:
- sign in using your MSFT SSO 
- Once signed in we allow you to create an API keys on LiteLLM Proxy UI 

<img width="1280" alt="Screenshot 2024-01-30 at 1 38 26 PM" src="https://github.com/BerriAI/litellm/assets/29436595/0f8c4b7d-bf6a-429f-80a0-293926f942f5">

**Comment by ishaan-jaff** [comment]
@bsu3338 is it important that it's OpenID ? or will it work for your use case if we allow you to set the following:

```python
MicrosoftSSO(
    client_id="84583a4d-*****", 
    client_secret="nbk8********",
    tenant="5a397376-**********,
    redirect_uri="http://localhost:4000/microsoft-callback",
)
```

**Comment by bsu3338** [comment]
That looks like that would work, how would I test it out?

**Comment by ishaan-jaff** [comment]
@bsu3338 working on a PR - will put out a dev release for you to try

**Comment by ishaan-jaff** [comment]
PR: https://github.com/BerriAI/litellm/pull/1691

**Comment by ishaan-jaff** [comment]
merged to main, will update as soon as a new release is out

**Comment by bsu3338** [comment]
Do you want screenshots of the setup I do on the Azure Ad side for your documentation

**Comment by ishaan-jaff** [comment]
okay new release is out
release: https://github.com/BerriAI/litellm/releases/tag/v1.20.6 
docs on setting this up: https://docs.litellm.ai/docs/proxy/ui 

@bsu3338 can you let me know if this works for you ? 
- do you have any feedback / feature requests on the Key Creation UI ? (this is a new feature and I'd love to improve it for you)

**Comment by bsu3338** [comment]
@ishaan-jaff  I think I am doing something wrong.  I am running my admin interface as :443 and my proxy on 8443 behind ssl termination with haproxy. haproxy proxies 443 to port 3000 for the ui and 8443 to 8000. 
  
Both pages come up when I hit their ports.  The admin page request for the proxy url, once I add it, I get redirect to https://FQDN:8443/sso/key/generate

That displays a 404 page cannot be found.  I have the same experience if I put it in https://litellm-dashboard.vercel.app/

This is the first time I have tried the gui, will it work behind a ssl proxy?

Compose looks like:
```yaml
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "8000:8000"
    volumes:
      - /srv/litellm/config/litellm-config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "8000", "--num_workers", "8" ]
    environment:
      PROXY_BASE_URL: https://FQDN:8443/
      MICROSOFT_CLIENT_ID: ID
      MICROSOFT_CLIENT_SECRET: Secret
      MICROSOFT_TENANT: Tenant
      OPENAI_API_KEY: sk-KEY
      LANGFUSE_PUBLIC_KEY: pk-lf-Random
      LANGFUSE_SECRET_KEY: sk-lf-Random
      LANGFUSE_HOST: http://langfuse-server:3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: Random
  litellm-ui:
    image: ghcr.io/berriai/litellm-ui:main-latest
```

I also have the below error on the admin page:
![image](https://github.com/BerriAI/litellm/assets/11950213/14b96e3f-f8cb-4a52-a856-efe9f3958b32)
