### ISSUE TITLE
[Bug]: cache option stays active even when you setup to False in config.yml file

### ISSUE THREAD

**Issue by Extremys** [BerriAI/litellm#1660]
### What happened?

The cache feature stays active even when you setup to False in the config.yml file.

In those cases the cache is active:
```yaml
litellm_settings:
  cache: True
environment_variables:
  REDIS_URL: {{ REDIS_URL }}
```
```yaml
litellm_settings:
  cache: False
environment_variables:
  REDIS_URL: {{ REDIS_URL }}
```

The cache is effectively disabled when you don't setup the var at all in the config.yml file:
```yaml
litellm_settings:
  
environment_variables:
  REDIS_URL: {{ REDIS_URL }}
```
