### ISSUE TITLE
[Feature]: Allow admins to create new user defaults on ui (budgets, models they have access to, etc.) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1670]
### The Feature

Allow proxy admins to set defaults in the proxy ui for new users in terms of budgets + models they have access to 

### Motivation, pitch

user concern - around new users created via ui having unlimited budgets and unlimited models

**Comment by ishaan-jaff** [comment]
already have an active issue here: https://github.com/BerriAI/litellm/issues/1667

**Comment by ishaan-jaff** [comment]
Makes sense to add this control on the Admin UI too, I assume you're working on the UI @krrishdholakia ? 

I had a PR to add this control on the proxy: https://github.com/BerriAI/litellm/pull/1669

**Comment by ishaan-jaff** [comment]
I actually tried both flows
- setting defaults on the config.yaml 
```yaml
litellm_settings:
  default_key_generate_params:
    max_budget: 1.5000
    models: ["azure-gpt-3.5"]
    duration: None
```
- setting this on the UI

I preferred using the yaml since that's where I put all my configs. What would you prefer @Manouchehri ?
