### ISSUE TITLE
[Feature]: SpendLogs Tracking Fails during high traffic 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1714]
## Log user sees
```
prisma.errors.DataError: Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)
```

Happened after running proxy for 20-30 calls

**Comment by ghost** [comment]
Solution: 
- batching failed calls 
- increasing connection limit

**Comment by Manouchehri** [comment]
Hmm, I know I had flip flopped on this before, but maybe a `spend_logs` setting would be nice.

```yaml
litellm_settings:
  failure_callback: ["sentry"]
  num_retries_per_request: 3
  success_callback: ["langfuse", "s3"]
  spend_logs: False
  default_team_settings:
    - team_id: john_smith_dev
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_JOHN
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_JOHN
      spend_logs: True # We don't trust this guy
    - team_id: epic_prod
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_PROD
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_PROD
      # spend_logs will inherit from the top level
```

Since we switched to Google Cloud SQL, putting less load and less data in that (which is $$$) is probably a nice bonus. Everything I wanted from spend logs is now in Langfuse anyway.
