### ISSUE TITLE
[Bug]: Failing to proxy Mixtral on TogetherAI while GPT-4 is working

### ISSUE THREAD

**Issue by qdrop17** [BerriAI/litellm#1830]
Hello everyone. I recognize significant potential in this project; excellent job!

Regrettably, I have been unable to configure TogetherAI to work with the LiteLLM proxy, even in the simplest setup. After dedicating several hours today to this issue and seeking assistance on both the LiteLLM and TogetherAI Discord channels, I have decided to report this problem.

docker-compose.yml:
```
version: '3.4'
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    volumes:
      - ./proxy_server_config.yaml:/app/proxy_server_config.yaml
    ports:
      - "4000:4000"
```

proxy_server_config.yaml:
```
model_list:
  - model_name: OpenAI-GPT-4
    litellm_params:
      model: openai/gpt-4
      api_key: "obfuscated"
  - model_name: Together-AI-Mixtral-8x7B-Instruct-v0.1
    litellm_params:
      model: together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1
      api_key: "obfuscated"
litellm_settings:
  drop_params: True
  set_verbose: True
```

Curl Mixtral on TogetherAI:
```
curl http://192.168.7.14:4000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "Together-AI-Mixtral-8x7B-Instruct-v0.1",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
   
   {
  "error": {
    "message": "'coroutine' object is not subscriptable\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py\", line 2180, in chat_completion\n    response = await llm_router.acompletion(**data)\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 365, in acompletion\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 361, in acompletion\n    response = await self.async_function_with_fallbacks(**kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 921, in async_function_with_fallbacks\n    raise original_exception\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 844, in async_function_with_fallbacks\n    response = await self.async_function_with_retries(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 980, in async_function_with_retries\n    raise original_exception\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 938, in async_function_with_retries\n    response = await original_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 427, in _acompletion\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/litellm/router.py\", line 406, in _acompletion\n    response = await litellm.acompletion(\n  File \"/usr/local/lib/python3.9/site-packages/litellm/utils.py\", line 2868, in wrapper_async\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/litellm/utils.py\", line 2734, in wrapper_async\n    post_call_processing(original_response=result, model=model)\n  File \"/usr/local/lib/python3.9/site-packages/litellm/utils.py\", line 2140, in post_call_processing\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/litellm/utils.py\", line 2134, in post_call_processing\n    model_response = original_response[\"choices\"][0][\"message\"][\nTypeError: 'coroutine' object is not subscriptable\n",
    "type": "None",
    "param": "None",
    "code": 500
  }
}
```

Curl GPT-4:
```
curl http://192.168.7.14:4000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "OpenAI-GPT-4",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
   
{"id":"chatcmpl-8ozsNS39fkQYPF82Yq5bYL9K02H0V","choices":[{"finish_reason":"stop","index":0,"message":{"content":"This is a test!","role":"assistant"}}],"created":1707164943,"model":"gpt-4-0613","object":"chat.completion","system_fingerprint":null,"usage":{"completion_tokens":5,"prompt_tokens":13,"total_tokens":18}}
```

Here are the logs from my litellm proxy docker container: [litellm.log](https://github.com/BerriAI/litellm/files/14171622/litellm.log)

I would greatly appreciate it if you could identify what I'm doing wrong or pinpoint where the bug is located. I'm also willing to submit a pull request with enhanced documentation for the use case I'm attempting to implement (with LibreChat).
