### ISSUE TITLE
Dashboard UI broken when running liteLLM inside docker-compose with Traefik managing SSL

### ISSUE THREAD

**Issue by GeorgeStrakhov** [BerriAI/litellm#1884]
First, thanks for an amazing project!

I'm trying to run in a docker-compose driven setup with traefik managing SSL (letseccrypt). I need everything to go over https (port 443)
Postgres running in a separate container.
All working as expected except /ui seems broken:

I can create new keys and they are saved and work, but old keys are not loaded.
Error in the console of the browser:

Mixed Content: The page at 'https://apiservices.mydomain.com/ui/?userID=admin&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VasdfiuyOIUYSDFOIuysdf6luIiwia2V5Ijoic2stTnJXSXdhUHU1bVY0bWd1YWs4NmtGQSJ9.BkEyKNa1ZgAtShq2wECQB0kstxawQ4YdY1lBIW-eV-0' was loaded over HTTPS, but requested an insecure resource 'http://apiservices.mydomain.com/user/info?user_id=admin'. This request has been blocked; the content must be served over HTTPS.

**Comment by ghost** [comment]
@GeorgeStrakhov Is this with SSO?

**Comment by ishaan-jaff** [comment]
Thanks for trying the UI @GeorgeStrakhov , can you share your docker compose / traefik setup so I can repro the issue ?

**Comment by ishaan-jaff** [comment]
can you see if setting PROXY_BASE_URL=https://apiservices.mydomain.com` in your env fixes this ? 

It looks like you got redirected to an `http` endpoint

**Comment by GeorgeStrakhov** [comment]
I'm afraid PROXY_BASE_URL didn't help. I might be missing something obvious.


Also in browser console I see this:
```
User role not defined
page-7f03ccc8529ada97.js:1 User Email is not set [object Object]
```
_**Should I be setting the user email somewhere?**_

### My docker-compose:
```
version: "3.9"

services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm-database:main-latest
    command: [ "--config", "/app/lconfig.yaml", "--port", "8000", "--num_workers", "8" ]
    volumes:
       - "./litellm_config.yml:/app/lconfig.yaml"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.litellm.rule=Host(`apiservices.mydomain.com`)"
      - "traefik.http.routers.litellm.entrypoints=websecure"
      - "traefik.http.routers.litellm.tls.certresolver=myresolver"
      - "traefik.http.services.litellm.loadbalancer.server.port=8000"
    networks:
      - web

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=hello@mydomain.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "./acme.json:/acme.json"
    networks:
      - web

networks:
  web:
    name: web

volumes:
  postgres-data:
  litellm-config:
    driver: local
```

###  My litellm_config.yaml:

```
model_list:
  - model_name: gpt-4-32k ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: azure/gpt-4-32k ### MODEL NAME sent to `litellm.completion()` ###
      api_base: "os.environ/AZURE_API_BASE"
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "os.environ/AZURE_API_VERSION"

general_settings:
  master_key: "os.environ/PROXY_MASTER_KEY"
  database_url: "os.environ/DATABASE_URL"
```

### my .env (obfuscated obvsly):

```
AZURE_DEPLOYMENT=gpt-4-32k
AZURE_API_VERSION=2023-05-15
AZURE_API_KEY=xxx
AZURE_API_BASE=https://xxx.openai.azure.com
UI_USERNAME=admin
UI_PASSWORD=xxx
DB_USER=admin
DB_PASSWORD=xxx
DB_NAME=apiservices
DATABASE_URL=postgresql://admin:xxx@postgres:5432/apiservices
PROXY_BASE_URL=https://apiservices.mydomain.com
PROXY_ADMIN_ID=admin
PROXY_MASTER_KEY=sk-xxx
```

Thanks for your help!
