### ISSUE TITLE
[Bug]: Mixed models list

### ISSUE THREAD

**Issue by Lunik** [BerriAI/litellm#1939]
### What happened?

When usinh OpenAI Proxy with a list of multiple modules and using the following features : `Virtual keys` and `access_groups`.

With the following configuration : 
```yaml
  model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_key: "os.environ/AZURE_OPENAI_API_KEY"
      api_base: https://xxxxxx.openai.azure.com
    model_info:
      location: "Azure - France Central"
      access_groups: ["public-beta"]

  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: "os.environ/AZURE_OPENAI_API_KEY"
      api_base: https://xxxxxx.openai.azure.com
    model_info:
      location: "Azure - France Central"
      access_groups: ["public-beta"]

  - model_name: mistral-tiny
    litellm_params:
      model: openai/mistralai/Mistral-7B-Instruct-v0.2
      api_base: http://my-vllm.local:8000/v1
      api_key: "dummy"
    model_info:
      location: "On Prem"
      access_groups: ["private-beta"]
```

When generating a key with the following `models` with the value `["private-beta", "public-beta"]` and querying the `/v1/models` API Endpoint, I get : 
```json
{
  "data": [
    {
      "id": "gpt-4-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "mistral-tiny",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "mistral-tiny",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

Also when querying the `/v1/chat/completions` endpoint with the API Key dans the model `gpt-35-turbo`, I get à `401` code with an error message telling me that the `gpt-35-turbo` model is not allowed but `["gpt-4-turbo", "mistral-tiny", "mistral-tiny"]` is allowed instead.

**Comment by Lunik** [comment]
Here are other examples : 

```yaml
  model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_key: "os.environ/AZURE_OPENAI_API_KEY"
      api_base: https://xxxxxx.openai.azure.com
    model_info:
      location: "Azure - France Central"
      access_groups: ["public-beta", "private-beta"]

  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: "os.environ/AZURE_OPENAI_API_KEY"
      api_base: https://xxxxxx.openai.azure.com
    model_info:
      location: "Azure - France Central"
      access_groups: ["public-beta", "private-beta"]

  - model_name: mistral-tiny
    litellm_params:
      model: openai/mistralai/Mistral-7B-Instruct-v0.2
      api_base: http://my-vllm.local:8000/v1
      api_key: "dummy"
    model_info:
      location: "On Prem"
      access_groups: ["private-beta"]
```

==========

When generating a key with the following `models` with the value `["private-beta", "public-beta"]` and querying the `/v1/models` API Endpoint, I get : 
```json
{
  "data": [
    {
      "id": "private-beta",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "mistral-tiny",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

==========

When generating a key with the following `models` with the value `["private-beta"]` and querying the `/v1/models` API Endpoint, I get : 
```json
{
  "data": [
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "mistral-tiny",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

**Comment by ishaan-jaff** [comment]
@Lunik I will take a look at this today

**Comment by ishaan-jaff** [comment]
are you free to hop on a quick call today? it helps us debug the issue faster - any specific time that works for you ?

Sharing a link to my calendar for your convenience: https://calendly.com/ishaan-berri/30min

**Comment by Lunik** [comment]
After testing multiple scenarios I was only able to replicate the behavior with ce container image. Using only Python on my workstation works fine. The issue is maybe in the proxy code.

Also I have noticed that when creating a new key with `/user/new`, the first time I query the model list, I get the issue but next times it has desapeared. Maybe the issue is related to something dynamically calculated during execution. Uptime of the upstream servers ? I was not able to find any clues on that note.

Will look tomorrow a few more scenarios and publish here if I found new informations.
For now I will fallback on the new "Restrict models by Team ID" wich is much more appropriated to my use case

**Comment by ishaan-jaff** [comment]
@Lunik I'm on here for the next 2-3 hours if you're free let me know - we can debug this together: 
https://meet.google.com/nws-bfhz-ney

**Comment by ishaan-jaff** [comment]
Just tried this with running the proxy locally - it works fine 

## Config
```yaml
model_list:
  - model_name: azure-gpt-3.5
    litellm_params:
      model: azure/chatgpt-v-2
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2023-07-01-preview"
    model_info:
      mode: chat
      max_tokens: 4096
      base_model: azure/gpt-4-1106-preview
      access_groups: ["public"] 
  - model_name: openai-gpt-3.5
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      access_groups: ["public"]
  - model_name: anthropic-claude-v2.1
    litellm_params:
      model: bedrock/anthropic.claude-v2:1
      timeout: 300 # sets a 5 minute timeout
    model_info:
      access_groups: ["private"]
```
## Key Generate 
```shell
curl --location 'http://localhost:4000/key/generate' \
-H 'Authorization: Bearer sk-1234' \
-H 'Content-Type: application/json' \
-d '{"models": ["public"]}'
```
## Completions - Both calls work since in access group 
```shell
curl --location 'http://0.0.0.0:4000/chat/completions' \
    --header 'Content-Type: application/json' \
    --header 'Authorization: Bearer sk-e6RNDzxG_GZLxefi0XHVZA' \
    --data '{
        "model": "azure-gpt-3.5",
        "messages": [
            {
                "role": "user",
                "content": "hi"
            }
        ]
    }'
```
