### ISSUE TITLE
[Bug]: Langfuse v2+ Error during the callback

### ISSUE THREAD

**Issue by Extremys** [BerriAI/litellm#1956]
### What happened?

My LangFuse server version is v2.4.0
Langfuse package version is v 2.13.1
LiteLLM version is 1.23.12 
My litellm config file:

```
[...]
litellm_settings:
  set_verbose: True
  drop_params: True
  success_callback: ["langfuse"]
  request_timeout: 1000
environment_variables:
  LANGFUSE_PUBLIC_KEY: {{ LANGFUSE_PUBLIC_KEY }}
  LANGFUSE_SECRET_KEY: {{ LANGFUSE_SECRET_KEY }}
  LANGFUSE_HOST: "https://{{ LANGFUSE_INGRESS_DNS }}"
```

Thanks for your feedback

### Relevant log output

```shell
Langfuse Layer Logging - logging to langfuse v2
Langfuse Layer Error - Traceback (most recent call last):
  File "/code/litellm/litellm/integrations/langfuse.py", line 234, in _log_langfuse_v2
    metadata_tags = metadata["tags"]
KeyError: 'tags'
```
