### ISSUE TITLE
[Feature]: DAY 1 SUPPORT - Gemini 1.5 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1982]
### The Feature

https://blog.google/technology/ai/google-gemini-next-generation-model-february-2024/#build-experiment

### Motivation, pitch

.

**Comment by ghost** [comment]
Added the new renamed gemini pro models. 

Looks like gemini-1.5 is in private preview (model names not released). Will update this ticket once they're out.

**Comment by ghost** [comment]
Model strings added to https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

You should now be able to call this.

## Vertex AI 

**via SDK**
```python
import litellm
litellm.vertex_project = "hardy-device-38811" # Your Project ID
litellm.vertex_location = "us-central1"  # proj location

response = litellm.completion(model="gemini-1.5-pro", messages=[{"role": "user", "content": "write code for saying hi from LiteLLM"}])
```

**via Proxy Server**

```yaml
litellm_settings: 
  vertex_project: "hardy-device-38811" # Your Project ID
  vertex_location: "us-central1" # proj location

model_list: 
  - model_name: team1-gemini-pro
     litellm_params: 
       model: gemini-1.5-pro
```

## Google AI Studio

**via SDK**
```python
import litellm
litellm.vertex_project = "hardy-device-38811" # Your Project ID
litellm.vertex_location = "us-central1"  # proj location

response = litellm.completion(model="google/gemini-1.5-pro", messages=[{"role": "user", "content": "write code for saying hi from LiteLLM"}])
```

**via Proxy Server**

```yaml
litellm_settings: 
  vertex_project: "hardy-device-38811" # Your Project ID
  vertex_location: "us-central1" # proj location

model_list: 
  - model_name: team1-gemini-pro
     litellm_params: 
       model: gemini/gemini-1.5-pro
```
