### ISSUE TITLE
[Feature]: Enable custom instructions for Llama Guard 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2044]
### The Feature

Allow user to add custom instructions to Llama Guard prompt 

### Motivation, pitch

better content moderation

**Comment by ghost** [comment]
## Thinking 

Allow users to define their own unsafe content categories. 

And pass them to litellm via the config 

```yaml
litellm_settings:
   callbacks: ["llamaguard_moderations"]
   llamaguard_model_name: "sagemaker/jumpstart-dft-meta-textgeneration-llama-guard-7b"
   llamaguard_unsafe_content_categories: my_custom_categories.txt 
```


How does a user know if this worked or didn't work? 

We can show the formatted message going into the litellm.completion call as a verbose_proxy_logger.info() message, so a user can use 

`litellm --config /path/to/config.yam --info`
