### ISSUE TITLE
[Bug]: Support no_proxy env to use openai compatible api from internal behind corporate firewall

### ISSUE THREAD

**Issue by VfBfoerst** [BerriAI/litellm#2127]
### What happened?

A bug happened!  
  
Hello there :)  
  
As discussed in #1458 , the proxy is already supported. We can confirm that, while we tried to configure VLLM locally. Regarding to the [Docs](https://litellm.vercel.app/docs/proxy/configs#quick-start), vllm is set up like that:  
  
```yaml
  - model_name: vllm-models
    litellm_params:
      model: openai/facebook/opt-125m # the `openai/` prefix tells litellm it's openai compatible
      api_base: http://123.123.123.123:8000
      rpm: 1440
    model_info: 
      version: 2
```
  
We get an answer from our proxy despite the `no_proxy` and `NO_PROXY` envs being set, so the code seems to ignore them.  So supporting the no_proxy envs will be needed by every locally hosted openai compatible api server.
  
Thanks for listening :)  

### Relevant log output

```shell
We got an http response from the proxy which shouldn't be requested.
```

**Comment by ghost** [comment]
@VfBfoerst what is NO_PROXY? can you share more re: requested implementation?

**Comment by VfBfoerst** [comment]
> @VfBfoerst what is NO_PROXY? can you share more re: requested implementation? 

@krrishdholakia no_proxy environment variable in Linux is used to define exceptions (IPs, URLs) to Not use the Proxy for. 

e.g. in a typical Corporate Network Setup, the Packet flow for an application (in this Case litellm) which wants to Connect to the Internet (in this Case openai):

LiteLLM -> Corporate Proxy/Firewall -> OpenAI

When a Proxy ist Set as in the mentioned issue, the Proxy will be used for every http request.
Since the Proxy is only for outgoing requests, it typically won't "forward" to internal IPs/URLs. So you need to Set exceptions. Lets say we host an openai compatible API on 172.30.2.2;

Without no_proxy:

LiteLLM -> Corporate Proxy/Firewall -> Dead, cant Route to 172.30.2.2

With no_proxy:

export no_proxy=172.30.2.2

LiteLLM -> 172.30.2.2

(I ignored a few steps, that Workflow is sumed Up)

TL;Dr:

If you Set a Proxy, all http requests will be sent to the Proxy.
So you need to define exceptions for internal addresses. For this the no_proxy and NO_PROXY Environment variables exist. 
The application should Accept both, no_proxy and NO_PROXY.

**Comment by ghost** [comment]
```
  - model_name: vllm-models
    litellm_params:
      model: openai/facebook/opt-125m # the `openai/` prefix tells litellm it's openai compatible
      api_base: http://123.123.123.123:8000
      rpm: 1440
      no_proxy: true
    model_info: 
      version: 2
```
