### ISSUE TITLE
[Bug]: Fail to health check the with customized api_base

### ISSUE THREAD

**Issue by prd-tuong-nguyen** [BerriAI/litellm#2157]
### What happened?

I have a selfhosted OpenAI API server.
Although the api_base is exist in config but the health check always call to offical OpenAI API
I checked and make sure that there is not request send to custom api_base
Here is the config:
```
model_list:
- litellm_params:
    model: openai/Open-Orca/Mistral-7B-OpenOrca
    api_base: http://localhost:80/v1
  model_name: selfhost
```

This line show that the health check not call to custom api_base: https://github.com/BerriAI/litellm/blob/2c378d96b776d512cdec7d87bccceab1189f95e9/litellm/main.py#L3353

### Relevant log output

```shell
Health check response:

{
    "healthy_endpoints": [],
    "unhealthy_endpoints": [
        {
            "model": "openai/Open-Orca/Mistral-7B-OpenOrca",
            "api_base": "http://localhost:80/v1",
            "error": "Error code: 400 - {'error': {'message': 'invalid model ID', 'type': 'invalid_request_error', 'param': None, 'code': None}}"
        }
    ],
    "healthy_count": 0,
    "unhealthy_count": 1
}
```
```


### Twitter / LinkedIn details

_No response_
