### ISSUE TITLE
[Bug]: token cost of config.yaml not being obeyed

### ISSUE THREAD

**Issue by bitnom** [BerriAI/litellm#2233]
### What happened?

```yaml
general_settings:
  master_key: sk-

model_list:
  - model_name: openrouter/mistralai/mixtral-8x7b-instruct
    litellm_params:
      model: openai/mistralai/mixtral-8x7b-instruct
      api_base: https://openrouter.ai/api/v1/
      api_key: "os.environ/OPENROUTER_API_KEY"

  - model_name: openrouter/auto
    litellm_params:
      model: openai/openrouter/auto
      api_base: https://openrouter.ai/api/v1/
      api_key: "os.environ/OPENROUTER_API_KEY"

  - model_name: gpt-4-turbo-preview
    litellm_params:
      model: openai/gpt-4-1106-preview
      input_cost_per_token: 0.000002
      output_cost_per_token: 0.000006
      api_base: https://api.acloudapp.com/v1/
      api_key: "os.environ/ACLOUD_API_KEY"
      max_retries: 0

  - model_name: gpt-4-1106-preview
    litellm_params:
      model: openai/gpt-4-1106-preview
#      base_model: gpt-4-1106-preview
#      input_cost_per_token: 0.00001
#      output_cost_per_token: 0.00003
      api_base: https://openrouter.ai/api/v1/
      api_key: "os.environ/OPENROUTER_API_KEY"
      max_retries: 0

  - model_name: gpt-4-turbo-preview
    litellm_params:
      model: openai/gpt-4-turbo-preview
#      base_model: gpt-4-turbo-preview
#      input_cost_per_token: 0.00001
#      output_cost_per_token: 0.00003
      api_base: https://openrouter.ai/api/v1/
      api_key: "os.environ/OPENROUTER_API_KEY"
      max_retries: 0
```

and then I see: 

![image](https://github.com/BerriAI/litellm/assets/14287229/6db782d0-a012-4b9b-9825-e12a10f6a74e)
