### ISSUE TITLE
[Bug]: LiteLLM.LoggingError ClickhouseLogger

### ISSUE THREAD

**Issue by bgoosmanviz** [BerriAI/litellm#2297]
### What happened?

After a successful generation, a clickhouse error: `No module named 'litellm.proxy.enterprise'`

My docker-compose.yml:
```
version: "3.9"
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    volumes:
      - ./config.yaml:/app/proxy_server_config.yaml
    ports:
      - "38383:4000"
    restart: always
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USERNAME=...
      - CLICKHOUSE_PASSWORD=...
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=...
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always
  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_DB=litellm
      - CLICKHOUSE_USER=...
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=...
    ports:
      - "8123:8123"
      - ```

### Relevant log output

```shell
litellm-1     | 19:02:24 - LiteLLM:DEBUG: LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging with integrations Traceback (most recent call last):
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1461, in success_handler
litellm-1     |     clickHouseLogger = ClickhouseLogger()
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/integrations/clickhouse.py", line 248, in __init__
litellm-1     |     _start_clickhouse()
litellm-1     |   File "/usr/local/lib/python3.9/site-packages/litellm/integrations/clickhouse.py", line 236, in _start_clickhouse
litellm-1     |     from litellm.proxy.enterprise.utils import _create_clickhouse_aggregate_tables
litellm-1     | ModuleNotFoundError: No module named 'litellm.proxy.enterprise'
```
