### ISSUE TITLE
[Bug]: REDIS_SSL does not work

### ISSUE THREAD

**Issue by olad32** [BerriAI/litellm#2332]
### What happened?

When i set REDIS_SSL var env i get this error : 
(i also have REDIS_HOST, REDIS_PORT, REDIS_USERNAME and REDIS_PASSWORD)

Setting Cache on Proxy
Cache Type: redis
Cache Host: **masked**
Cache Port: 6379
Cache Password: **masked**
redis_kwargs: {'host': '**masked**', 'port': '6379', 'password': '**masked**', 'ssl': True, 'username': '**masked**'}
redis_kwargs: {'host': '**masked**', 'port': '6379', 'password': '**masked**', 'ssl': True, 'username': '**masked**'}
Traceback (most recent call last):
File "/usr/local/bin/litellm", line 8, in <module>
sys.exit(run_server())
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_cli.py", line 428, in run_server
_, _, general_settings = asyncio.run(
File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1544, in load_config
f"{blue_color_code}Set Cache on LiteLLM Proxy: {vars(litellm.cache.cache)}{reset_color_code}"
File "/usr/local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 1026, in __repr__
f"<{self.connection_class(**self.connection_kwargs)!r}>"
File "/usr/local/lib/python3.9/site-packages/redis/asyncio/connection.py", line 635, in __init__
super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'

**config.yaml :** 
```
    model_list:
    ...
    router_settings: 
      cache_responses: true
    litellm_settings:
      set_verbose: true
      callbacks: custom-logger-callback.proxy_handler_instance
      drop_params: true
      cache: true
      cache_params:
        type: "redis"

```
