### ISSUE TITLE
[Bug]: Error with Bedrock Mistral Models & LibreChat

### ISSUE THREAD

**Issue by adamrb** [BerriAI/litellm#2464]
### What happened?

When trying to use Mistral models through Bedrock with Librechat, I receive an error.  This doesn't seem to happen with any of the other supported models.

LiteLLM output shows a response from the model, but nothing appears in LibreChat.

Proxy configuration is minimal.

```
  - model_name: mistral-8x7b
    litellm_params:
      model: bedrock/mistral.mixtral-8x7b-instruct-v0:1
  - model_name: mistral-7b-instruct
    litellm_params:
      model: bedrock/mistral.mistral-7b-instruct-v0:2
```

### Relevant log output

```shell
Something went wrong. Here's the specific error message we encountered: Error: request ended without sending any chunks

-----

LibreChat         | 2024-03-12 00:48:47 warn: [OpenAIClient.chatCompletion][stream] Unhandled error type
LibreChat         | 2024-03-12 00:48:47 warn: [OpenAIClient.chatCompletion][finalChatCompletion] Unhandled error type
LibreChat         | 2024-03-12 00:48:47 error: [OpenAIClient.chatCompletion] Unhandled error type Error: request ended without sending any chunks
LibreChat         | 2024-03-12 00:48:47 error: [handleAbortError] AI response error; aborting request: Error: request ended without sending any chunks

-------

self.sent_first_chunk: False
PROCESSED CHUNK POST CHUNK CREATOR: None
PROCESSED CHUNK PRE CHUNK CREATOR: {'chunk': {'bytes': b'{"outputs":[{"text":"","stop_reason":"stop"}],"amazon-bedrock-invocationMetrics":{"inputTokenCount":298,"outputTokenCount":96,"invocationLatency":1314,"firstByteLatency":357}}'}}
model_response finish reason 3: None; response_obj={'text': '', 'is_finished': False, 'finish_reason': ''}
model_response.choices[0].delta: Delta(content=None, role=None, function_call=None, tool_calls=None); completion_obj: {'content': ''}
self.sent_first_chunk: False
PROCESSED CHUNK POST CHUNK CREATOR: None
```
