### ISSUE TITLE
[Feature]: Allow turning of request/response logging for langfuse/lunary/etc.

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2586]
### The Feature

Allow user to turn off logging the request / response when setting a callback

```python
litellm.turn_off_message_logging = True 
```

### Motivation, pitch

user request

**Comment by ishaan-jaff** [comment]
This is done: https://github.com/BerriAI/litellm/pull/3330 @tjbck @Michelklingler @ianawilson

Here's how to enable it on the proxy: https://docs.litellm.ai/docs/proxy/logging#redacting-messages-response-content-from-langfuse-logging

```yaml
model_list:
 - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
litellm_settings:
  success_callback: ["langfuse"]
  turn_off_message_logging: True
```


 @tjbck @Michelklingler @ianawilson curious, would you find it helpful if we managed your LiteLLM proxy deployment? 

e.g. if it was available through aws marketplace
