### ISSUE TITLE
[Feature]: Support for Cohere's Rerank API endpoint

### ISSUE THREAD

**Issue by andaldanar** [BerriAI/litellm#2691]
### The Feature

I would like that `litellm` could support Cohere's Rerank API endpoint, https://docs.cohere.com/reference/rerank-1

### Motivation, pitch

Rerankers have become a key component in my RAG pipelines, and it would be great to manage this endpoint with `litellm`

### Twitter / LinkedIn details

https://www.linkedin.com/in/andresaldana/

**Comment by rodion-m** [comment]
Yes, a very intuitive feature. I was surprised to know that LiteLLM doesn't support this endpoint.

**Comment by ghost** [comment]
+1 user asked for this + a cohere-compatible rerank endpoint

**Comment by edisonzf2020** [comment]
+1

**Comment by fff196** [comment]
+1

**Comment by ishaan-jaff** [comment]
Hi @fff196 @edisonzf2020 @rodion-m @andaldanar do you want this on the litellm python SDK or the proxy server ?

**Comment by rodion-m** [comment]
Hi @ishaan-jaff ! Thanks for a fast response. I need it on the proxy server.

**Comment by ishaan-jaff** [comment]
@rodion-m - what format do you want it in ? should it be in the cohere API format on the proxy server

**Comment by rodion-m** [comment]
Hi @ishaan-jaff ! Thanks for the fast response. I need it on the proxy server.

**Comment by rodion-m** [comment]
Yes, I believe that Cohere's format is the best choice at the moment.

**Comment by ishaan-jaff** [comment]
okay looking into how we can support this as a pass through endpoint, do you use the litellm virtual keys / auth @rodion-m ?

**Comment by rodion-m** [comment]
At the moment I use LiteLLM only with virtual keys.

**Comment by andaldanar** [comment]
Thanks for picking this request, @ishaan-jaff!

I'd like it to be available in the proxy server, and I also think Cohere's [format](https://docs.cohere.com/reference/rerank) is appropriate ([Jina's Reranker API uses a similar one](https://jina.ai/reranker/))

**Comment by ishaan-jaff** [comment]
FYI - planning on addressing this by allowing users to make passthrough endpoints on the proxy server (since there is no need to standardize to any format) . Lmk if that makes sense @andaldanar @rodion-m

**Comment by ishaan-jaff** [comment]
PR here : https://github.com/BerriAI/litellm/pull/4462  😄

**Comment by spammenotinoz** [comment]
Wow, great feature.
Does the LiteLLM passthrough endpoint honour LiteLLM keys\authentication or just straight passthrough with the Optional Auth Header?

**Comment by ghost** [comment]
Hey @spammenotinoz what does 'honor LiteLLM keys\authentication' mean? 


you define the headers (e.g. keys) in the config - 

e.g. 
```yaml
general_settings:
  master_key: sk-1234
  pass_through_endpoints:
    - path: "/v1/rerank"                                  # route you want to add to LiteLLM Proxy Server
      target: "https://api.cohere.com/v1/rerank"          # URL this route should forward requests to
      headers:                                            # headers to forward to this URL
        Authorization: "bearer os.environ/COHERE_API_KEY" # (Optional) Auth Header to forward to your Endpoint
        content-type: application/json                    # (Optional) Extra Headers to pass to this endpoint 
        accept: application/json
```




docs - https://docs.litellm.ai/docs/proxy/pass_through#tutorial---pass-through-cohere-re-rank-endpoint


code - https://github.com/BerriAI/litellm/blob/1ee18ce6714152cdbf68fe433683a1feb115a403/litellm/proxy/pass_through_endpoints/pass_through_endpoints.py#L81
