### ISSUE TITLE
[Feature]: Allow hiding (but not disabling) specific models from `/v1/models`

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#2835]
### The Feature

So this is what `/v1/models` returns for me right now:

```json
{
  "data": [
    {
      "id": "gemini-1.0-pro",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gemini-1.0-pro-vertex",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

But I actually want `/v1/models` to return this (without disabling access to `gemini-1.0-pro-vertex`):

```json
{
  "data": [
    {
      "id": "gemini-1.0-pro",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

And I think it would make sense for my config to look like this:

```yaml
litellm_settings:
  fallbacks: [{"gemini-1.0-pro": ["gemini-1.0-pro-vertex"]}] # fallback to Vertex if call fails num_retries

model_list:
  - model_name: gemini-1.0-pro-vertex
    litellm_params:
      model: vertex_ai/gemini-1.0-pro
      vertex_project: epic-project
      vertex_location: us-east4
      hide_from_model_list: True

  - model_name: gemini-1.0-pro
    litellm_params:
      model: gemini/gemini-1.0-pro
```

### Motivation, pitch

Having "too many" models is confusing for other developers on our team.

In the example above, I want them to use `gemini-1.0-pro` by default; I still want to allow them to use `gemini-1.0-pro-vertex` manually without needing to switch (or modify) their API key through.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
