### ISSUE TITLE
[Bug]: Update Cohere to use `cohere_chat/command-r` (not `cohere/command-r`)

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#2875]
### What happened?

Related to https://github.com/BerriAI/litellm/issues/2496. Right now the docs don't mention that there's a `cohere_chat`.

When using `cohere/command-r`, I get this error as expected:

```
litellm.llms.cohere.CohereError: {"message":"invalid request: model 'command-r' is not supported by the generate API"}
```

(What's odd, is that `cohere/command-r-plus` works fine. Not sure I see why that happens, but whatever. =P )

Bad:
```yaml
model_list:
  - model_name: command-r
    litellm_params:
      model: cohere/command-r

  - model_name: command-r-plus
    litellm_params:
      model: cohere/command-r-plus
```

https://github.com/BerriAI/litellm/blob/30f57e7aa501781d5c501b7fda18cb6c5416536b/model_prices_and_context_window.json#L1185-L1194

https://github.com/BerriAI/litellm/blob/30f57e7aa501781d5c501b7fda18cb6c5416536b/model_prices_and_context_window.json#L1204-L1213

After I switched to this, both endpoints worked fine.

Good:
```yaml
model_list:
  - model_name: command-r
    litellm_params:
      model: cohere_chat/command-r

  - model_name: command-r-plus
    litellm_params:
      model: cohere_chat/command-r-plus
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
