### ISSUE TITLE
[Bug]: High Traffic Error, Using `athina` as the `success_callback` will cause CPU usage to reach 90%

### ISSUE THREAD

**Issue by Caixiaopig** [BerriAI/litellm#2884]
### What happened?

In config.yaml, I set litellm_settings: success_callback to athina and found that the CPU usage was abnormal, even reaching up to 90%. Meanwhile, I also tested other success_callback providers like langfuse and promptlayer, and they did not encounter this issue.

code example
```
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
litellm_settings:
  success_callback: ["athina"]
```
