### ISSUE TITLE
[Bug]: Supabase with Litellm with docker (compose)

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#3164]
### What happened?

the docker installs the supabase modules, but returns an error (maybe the supabase url is not captured from the env, or it is not supported - I can't find any example to set this callback for supabase)?

config .yaml
```
litellm_settings: # module level litellm settings - https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py
  drop_params: True
  num_retries: 3 # retry call 3 times on each model_name (e.g. zephyr-beta)
  request_timeout: 50 # raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout 
#  fallbacks: [{"zephyr-beta": ["gpt-3.5-turbo"]}] # fallback to gpt-3.5-turbo if call fails num_retries 
#  context_window_fallbacks: [{"zephyr-beta": ["gpt-3.5-turbo-16k"]}, {"gpt-3.5-turbo": ["gpt-3.5-turbo-16k"]}] # fallback to gpt-3.5-turbo-16k if context window error
  allowed_fails: 3 # cooldown model if it fails > 1 call in a minute. 

  set_verbose: True
  cache: False          # set cache responses to True, litellm defaults to using a redis cache

  output_parse_pii: true
  success_callback: ["supabase"]

  callbacks: ["detect_prompt_injection"]
  prompt_injection_params:
    heuristics_check: true
    similarity_check: true

```

for the docker, I used the env:

- SUPABASE_URL <- mapped to a self hosted supabase
- SUPABASE_KEY

### Relevant log output

```shell
litellm-litellm-1  | 
litellm-litellm-1  | Installing collected packages: strenum, websockets, deprecation, realtime, supafunc, storage3, postgrest, gotrue, supabase
litellm-litellm-1  | Successfully installed deprecation-2.1.0 gotrue-2.4.2 postgrest-0.16.3 realtime-1.0.4 storage3-0.7.4 strenum-0.4.15 supabase-2.4.3 supafunc-0.4.5 websockets-12.0
litellm-litellm-1  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
litellm-litellm-1  | ERROR:    Traceback (most recent call last):
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
litellm-litellm-1  |     async with self.lifespan_context(app) as maybe_state:
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 608, in __aenter__
litellm-litellm-1  |     await self._router.startup()
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 709, in startup
litellm-litellm-1  |     await handler()
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3138, in startup_event
litellm-litellm-1  |     proxy_logging_obj._init_litellm_callbacks()  # INITIALIZE LITELLM CALLBACKS ON SERVER STARTUP <- do this to catch any logging errors on startup, not when calls are being made
litellm-litellm-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 155, in _init_litellm_callbacks
litellm-litellm-1  |     litellm.utils.set_callbacks(callback_list=callback_list)
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6609, in set_callbacks
litellm-litellm-1  |     raise e
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6595, in set_callbacks
litellm-litellm-1  |     supabaseClient = Supabase()
litellm-litellm-1  |                      ^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/integrations/supabase.py", line 26, in __init__
litellm-litellm-1  |     self.supabase_client = supabase.create_client(
litellm-litellm-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/supabase/_sync/client.py", line 299, in create_client
litellm-litellm-1  |     return SyncClient.create(
litellm-litellm-1  |            ^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/supabase/_sync/client.py", line 102, in create
litellm-litellm-1  |     return cls(supabase_url, supabase_key, options)
litellm-litellm-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/supabase/_sync/client.py", line 57, in __init__
litellm-litellm-1  |     raise SupabaseException("Invalid URL")
litellm-litellm-1  | supabase._sync.client.SupabaseException: Invalid URL
```
