### ISSUE TITLE
[Bug - Investigation]: Redis url is 25 rps vs. using redis_port, redis_host, etc. (100 rps) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3188]
### What happened?

When using the redis async client for usage-based-routing-v2, when initializing the redis cache via 'redis_url' it's significantly slower than using redis_port, host, etc. 

```yaml
router_settings:
  routing_strategy: usage-based-routing-v2 
  # redis_url: "os.environ/REDIS_URL"
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD
````

  | usage-based-routing-v2 w/ redis ssl | usage-based-routing-v2 w/ redis host name, port, etc. | simple-shuffle w/ no redis
-- | -- | -- | --
RPS | 25.4 | 109.7 | 161.6
