### ISSUE TITLE
[Feature]: Support upstream batching on OpenAI

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3247]
### The Feature

Basically supporting `native_batching: True`. =) 

Blocked by #3246 (which should/can be done before this ticket imo).

```yaml
litellm_settings:
  cache: True
  s3_batching_params: # non-optional if using batching; no bucket, no batching
    s3_bucket_name: os.environ/BATCHING_S3_BUCKET_NAME
    s3_region_name: os.environ/BATCHING_AWS_DEFAULT_REGION
    s3_aws_access_key_id: os.environ/BATCHING_AWS_ACCESS_KEY_ID
    s3_aws_secret_access_key: os.environ/BATCHING_AWS_SECRET_ACCESS_KEY
    s3_endpoint_url: os.environ/BATCHING_AWS_ENDPOINT_URL_S3

model_list:
  - model_name: gpt-4-turbo-2024-04-09
    litellm_params:
      model: openai/gpt-4-turbo-2024-04-09
      api_key: os.environ/OPENAI_API_KEY
      rpm: 50
      batching_params:
        native_batching: True # default is False
        completion_window: 86400
        enforce_completion_window: True # default is True if native_batching is True
```

### Motivation, pitch

Cost savings!

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
