### ISSUE TITLE
[Bug]: 500 error when embedding 

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#3458]
### What happened?

after a few minutes when trying to use the embedding endpoint I 500 error

I am on version v1.35.38-stable, and this happens with any embedding model that I use.  

### Relevant log output

```shell
`{"error":{"message":"AsyncEmbeddings.create() got an unexpected keyword argument 'messages'","type":"None","param":"None","code":500}}`
```

**Comment by ncecere** [comment]
when the issue you starts I can't find anything in the litellm logs, If you have somewhere I should look please let me know and I will.  the response/error is from me running a curl command

**Comment by ishaan-jaff** [comment]
Does this occur in 1.35.38 @ncecere (non-stable tag)?

**Comment by ncecere** [comment]
yes it does @ishaan-jaff , it happens in the non stable tag too.  I have tried every version from 1.35.36 - 1.35.38

**Comment by ncecere** [comment]
I am adding the model using this pattern

```
- model_name: SFR-Embedding-Mistral
    litellm_params: 
      model: openai/Salesforce/SFR-Embedding-Mistral
      api_key: sk-1234
      api_base: http://server.example.com/
    model_info:
      mode: embedding
```
