### ISSUE TITLE
[Feature]: Gemini 1.5 flash Day-1 support 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3636]
### The Feature

support https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini

### Motivation, pitch

easily call different LLM providers

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/4e30d7cf5ec9ced3d3bf12d1c2c0094616543b1a

**Comment by ventz** [comment]
Running into:

```
litellm_1          | 	status = StatusCode.INVALID_ARGUMENT
litellm_1          | 	details = "Unable to submit request because the model does not support the presencePenalty parameter. Remove it and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview"
litellm_1          | 	debug_error_string = "UNKNOWN:Error received from peer ipv4:<redacted>:443 {grpc_message:"Unable to submit request because the model does not support the presencePenalty parameter. Remove it and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview", grpc_status:3, created_time:"2024-05-15T19:08:26.13621094+00:00"}"
```

with model:
> gemini-1.5-flash-preview-0514

(model and access works directly with LangChain so not auth/access/etc)

**Comment by ghost** [comment]
> Unable to submit request because the model does not support the presencePenalty parameter. Remove it and try again. Learn more: https://cloud.google.com

@ventz your request contains an unsupported parameter, can you drop presence penalty and try again?

**Comment by ventz** [comment]
@krrishdholakia Thanks --  it looks like it's somehow coming from LibreChat. Will investigate there.

Stood up a standalone LiteLLM container to test, and it works! Please ignore, and thanks for the quick comment!

**Comment by danny-avila** [comment]
@krrishdholakia the parameter is being dropped on LibreChat's end, going to investigate this.

**Comment by ventz** [comment]
Just wanted to update for anyone coming by/running into this - it looks like it's needed in the `librechat.yaml` block under the LiteLLM config:

```
baseURL: "http://host.docker.internal:4000"
      models:
        default: ["..."]
        fetch: true
      dropParams: ['stop', 'user', 'frequency_penalty', 'presence_penalty']
```

Edit: from what I can tell, both `frequency_penalty` and `presence_penalty` are needed.



Even if you already have `drop_params: True` in the `litellm-config.yaml`
```
...
litellm_settings:
  success_callback: ["langfuse"]
  cache: True
  drop_params: True
```

**Comment by ventz** [comment]
@krrishdholakia It seems the `litellm_settings:` -> `drop_params: True` in the litellm config is not dropping params?

As soon as I configured it upstream (in LibreChat) it started working.

**Comment by ghost** [comment]
i believe? gemini does support presence penalty, so i'm confused why it raises this error. 
<img width="546" alt="Screenshot 2024-05-15 at 2 27 58 PM" src="https://github.com/BerriAI/litellm/assets/17561003/bfebe8aa-ef7f-4add-848e-ec8c587296f7">

@ventz do you mind sharing the curl request being sent to litellm, for repro

**Comment by ventz** [comment]
If I send a manual curl request (plain) it works, but no extra params:

```
curl --location 'https://fqdn-of-litellm/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "google-gemini-flash-1.5-preview",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ]
    }'
```
    
with this config:
    
```
 - model_name: google-gemini-flash-1.5-preview
    litellm_params:
      model: vertex_ai/gemini-1.5-flash-preview-0514
      vertex_project: <redacted>
      vertex_location: us-central1
```
      
As far as what's being sent from LibreChat -- that may be a better question for @danny-avila :)
