### ISSUE TITLE
[Feature]: Wait for the first model to return from cooldown instead of failing request

### ISSUE THREAD

**Issue by anterart** [BerriAI/litellm#3646]
### The Feature

Hello!
As I understood from the Router's code, if all deployments of the model are in a cooldown state, the previous failed completion request will cause an exception to be raised that isn't caught by the Router's logic.
I would be happy if somebody confirms this behavior.

### Motivation, pitch

I think that LiteLLM should be resilient and handle such a case by waiting for the first deployment to comeback from cooldown and then proceed retrying the request if still have an extra retry attempt.

**Comment by ishaan-jaff** [comment]
@anterart is the feedback here that:

- if all models are in cooldown, try the first model that was added to cooldown ?

**Comment by anterart** [comment]
@ishaan-jaff 
It's possible that the first deployment that was added to cooldown is still in cooldown state.
I think that the Router should wait until one of the deployments is not in cooldown state anymore, and then proceed with the completion request.

**Comment by ishaan-jaff** [comment]
@anterart so you'd like the router to `sleep(x)` and then re-check if there are any available deployments ?

**Comment by anterart** [comment]
The router can check how much time is left until one of the deployments will stop being in the cooldown state, then exactly when this happens use that deployment.
This behavior can also be configurable (maybe somebody will prefer a different behavior).

**Comment by ghost** [comment]
yep - i believe this is how it should work with num_retries + request_timeout 

@anterart do you have a sample code snippet to repro when it doesn't behave as expected?

**Comment by anterart** [comment]
@krrishdholakia 
I'm working with deployments I have in the Azure OpenAI of gpt4-turbo model.
There is a 80 kTPM rate limit on it for me, if I raise the `max_parallel_requests` too high, then when debugging the code I've seen it goes to the following code area: https://github.com/BerriAI/litellm/blob/1a3b0014325340c321143daf0bacb5514df30ddb/litellm/router.py#L1655

and then raises the Rate Error status code 429.

And this is my code:

```
import yaml
import logging

# Read the YAML file
with open('config.yaml', 'r') as file:
    data = yaml.safe_load(file)

# Convert YAML data to Python list
model_list = data['model_list']

print(model_list)

from litellm import Router
router = Router(model_list=model_list, num_retries=1, cooldown_time=30, retry_after=10, routing_strategy="usage-based-routing-v2", allowed_fails=2)

from tqdm.asyncio import tqdm

final = list_to_process

answers_dict = {}
model_names = ['gpt4-turbo']
for model_name in model_names:
    print(model_name)
    tasks = [router.acompletion(model=model_name, messages=message) for message in final]
    results = await tqdm.gather(*tasks)
    answers = [results[i].choices[0].message.content for i in range(len(results))]
    answers_dict[f'{model_name}'] = answers
```

Here is the configuration file:

```
model_list:
  - model_name: gpt4-turbo # user-facing model alias
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: ___
      api_base: ___
      api_key: ___
      api_version: ___
      tpm: 40000
      max_parallel_requests: 10
  - model_name: gpt4-turbo # user-facing model alias
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: ___
      api_base: ___
      api_key: ___
      api_version: 2023-12-01-preview
      tpm: 40000
      max_parallel_requests: 10
```

And the litellm version is: 1.37.5
