### ISSUE TITLE
[Bug]: Azure OpenAI with azure_ad_token not using correct key 

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#3695]
### What happened?

During my troubleshooting of #3644, I discovered that `OPENAI_API_KEY` seems to be sent Azure OpenAI by accident. 😬  This is a new regression I believe, introduced sometime between v1.37.0 to v1.37.9. This is pretty bad, since we're sending a private API key to the wrong provider.

```
model_list:
  - model_name: gpt-4-0125-preview
    litellm_params:
      model: azure/gpt-4-0125-preview
      api_version: "2024-04-01-preview"
      azure_ad_token: "oidc/google/https://example.com"
      api_base: "https://gateway.ai.cloudflare.com/v1/removed/removed/azure-openai/removed-removed"
    model_info:
      base_model: azure/gpt-4-0125-preview
```

What's odd, is if I remove `OPENAI_API_KEY`, I see that we're actually using the non-Azure path...?

```
router.py:2610 - Initializing OpenAI Client for azure/gpt-4-0125-preview
```

https://github.com/BerriAI/litellm/blob/2179598d1d36153dd9d1b1fe40cd3eccd62353f0/litellm/router.py#L2611

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
