### ISSUE TITLE
[Feature]: LM Studio support

### ISSUE THREAD

**Issue by mrdjohnson** [BerriAI/litellm#3755]
### The Feature

To be able to use litellm with first party support for LM Studio! 

### Motivation, pitch

LM Studio is a very popular platform and they're the best way to get access to hugging face models locally. If possible having access to the LM Studio server through lite llm would be amazing

**Comment by ghost** [comment]
Hey @mrdjohnson can't you already do this via - https://docs.litellm.ai/docs/providers/openai_compatible

```
model_list:
  - model_name: my-model
    litellm_params:
      model: openai/<your-model-name>  # your lm studio model name
      api_base: <model-api-base>       # lm studio api base
      api_key: api-key                 # lm-studio api key if required (else put a fake key here)
```

unclear on what first-party support here looks like?
