### ISSUE TITLE
[Bug]: Ollama behing HTTPS with self signed CA

### ISSUE THREAD

**Issue by Lunik** [BerriAI/litellm#3794]
### What happened?

Hi,

We have deployed an instance of Ollama and put it behind a reverse proxy to expose it with HTTPS (TLS)

I havn't found any configuration to provide my own CA in the Proxy config

Here is my config :
```yaml
  model_list:
    - model_name: ihe-mistral-7b-q4
      litellm_params:
        model: ollama/mistral-7b-instruct-v0.2.Q4:latest
        api_base: https://my-ollama.example.org
      model_info:
        mode: chat
```

used version : main-v1.37.19
