### ISSUE TITLE
[Bug]: Continue.dev VSC and vertex gemini proxy - error: ProtoType object has no attribute 'DESCRIPTOR'

### ISSUE THREAD

**Issue by azdolinski** [BerriAI/litellm#3799]
### What happened?

I have latest litellm in docker... **litellm-database:main-latest**
```
LiteLLM: Current Version = 1.38.1
```
I'm using https://continue.dev/ VSC extension...
This tool is configured to use configuration of lite LLM which is set to have Gemini via vertex...
```
### LiteLLM Config:
  - model_name: google-gemini-1.5-pro-preview-0514
    litellm_params:
      model: vertex_ai/gemini-1.5-pro-preview-0514
      timeout: 300
      stream_timeout: 120
      max_retries: 5
      stream: True     <-- (i check also with False... same problem)
```
```
### continue.dev Config:
{
  "models": [
    {
      "title": "LiteLLM [Google Gemini 1.5 Pro (0514)]",
      "model": "google-gemini-1.5-pro-preview-0514",
      "apiBase": "http://litellm.lan/v1/",
      "provider": "openai",
      "apiKey": "sk-xxxxxxx"
    },
[...]
```
when i send 1st message.. it is respondng... when i send 2nd message - i got 500 error from litellm
**"message":"'ProtoType' object has no attribute 'DESCRIPTOR'\nNumber Retries = 1"**

if looks like it is only problem with vertex as i checked also continue.dev with openai gpt4o proxy - litellm config:
```
### OpenAI
  - model_name: openai-gpt-4o
    litellm_params:
        model: openai/gpt-4o
```
and with this mode,  continue.dev is working fine.

I have also OpenWebUI which is connected to lite llm... and via OpenWebUI - connection is working fine with problematic vertex google model.

**PS.** Im sure that it was working before... i mean something like week ago - si it looks like it stop working few days ago. Some protobuf version change on LiteLLM/vertex side?

### Relevant log output

```shell
message: {
  "msg": {
    "messageId": "0a8f63c4-ee72-4520-bff5-9272eaf0c74b",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "hi"
            }
          ]
        },
        {
          "role": "assistant",
          "content": [
            {
              "type": "text",
              "text": "Hi! 👋  How can I help you today? 😊 \n"
            }
          ]
        },
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "hi 2nd time"
            }
          ]
        }
      ],
      "title": "LiteLLM [Google Gemini 1.5 Pro (0514)]",
      "completionOptions": {}
    }
  }
}

Error:
notificationsAlerts.ts:42 Error: HTTP 500 Internal Server Error from http://litellm.lan/v1/chat/completions  {"error":{"message":"'ProtoType' object has no attribute 'DESCRIPTOR'\nNumber Retries = 1","type":null,"param":null,"code":500}}
```
