### ISSUE TITLE
[Bug]: proxy did not fallback to another model in same group

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#3884]
### What happened?

In below `proxy-config.yaml`, we had `azure/gpt-old-ptu` which is a PTU instance set with high rpm so the proxy would be biased towards it. It so happened that this model instance was deleted from our Azure portal. So all requests to `model_name: gpt-old` via the proxy began to fail with a `404` error code:
```
Message: LLM API call failed: AzureException
Error code: 404
{
   "error":{
      "code":"DeploymentNotFound",
      "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
   }
}
```
What I'd have expected is that if this model instance became unhealthy, proxy would automatically fallback to another model instance within same group, as you can see in the below config, there were 2 other model instances `azure/gpt-old` which could have fulfilled the requests successfully, but the proxy did not go to either of those and instead just kept returning `404` error because of the removal of the first model instance from the Azure portal.

`proxy-config.yaml`
```
# gpt-old
  - model_name: gpt-old
    litellm_params:
      model: azure/gpt-old-ptu # PTU instance
      api_base: https://xyz.openai.azure.com/
      api_key: os.environ/AOAI_KEY
      rpm: 9000
  - model_name: gpt-old
    litellm_params:
      model: azure/gpt-old
      api_base: os.environ/AOAI_BASE_1
      api_key: os.environ/AOAI_KEY_1
  - model_name: gpt-old
    litellm_params:
      model: azure/gpt-old
      api_base: os.environ/AOAI_BASE_2
      api_key: os.environ/AOAI_KEY_2
```
cc: @msabramo

**Comment by ghost** [comment]
@taralika unable to repro - here's me calling a model group with 1 bad and 1 good endpoint (ran this 5 times to sanity check it)

<img width="867" alt="Screenshot 2024-05-28 at 8 11 27 PM" src="https://github.com/BerriAI/litellm/assets/17561003/ec01b696-5027-4856-bbda-392ca2587ebc">


```yaml
model_list:
- litellm_params: # 👈 BAD MODEL
    api_base: http://0.0.0.0:8080
    api_key: ''
    model: openai/my-fake-model
  model_name: gpt-3.5-turbo-fake-model
- litellm_params: # 👈 GOOD MODEL
    api_base: https://my-endpoint-europe-berri-992.openai.azure.com/
    api_key: os.environ/AZURE_EUROPE_API_KEY
    model: azure/gpt-35-turbo
  model_name: gpt-3.5-turbo-fake-model
```
