### ISSUE TITLE
[Bug]: VertexAIException - Unknown field for Schema: additionalProperties

### ISSUE THREAD

**Issue by li-dennis** [BerriAI/litellm#3891]
### What happened?

Hi all,

Thanks for the great work on litellm! Apologies if this isn't a bug and just user error, but I've been unsure of what to make of this exception. I've been trying to get gemini via the vertexai api to play nice with litellm. However, I run into this issue pretty quickly:

```
04:30:34 - LiteLLM Proxy:DEBUG: proxy_server.py:3716 - An error occurred: VertexAIException - Unknown field for Schema: additionalProperties 
Model: gemini-1.5-flash-preview-0514
Messages: ...
deployment: gemini-1.5-flash-preview-0514

vertex_location: us-west1
````

I'm using litellm proxy (v1.36.1) with the openai api python sdk (1.30.4).

This is my litellm config
```
...
  - model_name: gemini-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro-preview-0514
      vertex_project: os.environ/GCP_PROJECT_ID
      vertex_location: os.environ/GCS_REGION
  - model_name: gemini-flash
    litellm_params:
      model: gemini-1.5-flash-preview-0514
      vertex_project: os.environ/GCP_PROJECT_ID
      vertex_location: os.environ/GCS_REGION
```

I haven't changed my messages in any way, and my requests work just fine with openai/anthropic models. Perhaps the error is due to missing `additionalProperties` in the tool call schemas? Or from https://cloud.google.com/vertex-ai/docs/ml-metadata/system-schemas ?
