### ISSUE TITLE
[Feature]: to add messages corresponding to each LLM given in the fallback list. 

### ISSUE THREAD

**Issue by Aviral-Cactus** [BerriAI/litellm#3893]
### The Feature

As each LLM interprets the same prompt differently, it quite possible that messages will be different for different LLMs. So, the feature request is that each LLM given in the fallback list should have a provision to attach messages along with each LLM.

### Motivation, pitch

For my use case, I have observed that the same prompt gives different results in different LLMs, therefore if my primary LLM fails, I would like to fallback to some other LLM and with a different prompt as per the fallback LLM.
Something like below:
fallbacks=[{"model":"anthropic.claude-3-haiku-20240307-v1:0", "messages":messages_1},{"model":"gpt-3.5-turbo", "messages":messages_2}]

### Twitter / LinkedIn details

www.linkedin.com/in/aviral-jain-6190b9133

**Comment by ghost** [comment]
hey @Aviral-Cactus that's a great request - won't the message change based on incoming request? how would you do this 

some mock implementation code of how you plan to use this would help

**Comment by ghost** [comment]
following up here @Aviral-Cactus how would you want to do this?

**Comment by Aviral-Cactus** [comment]
Hey @krrishdholakia - apologies for the late reply, simple put, fallback LLMs should have their own prompt, hyper params like max_tokens, temperature etc. Implementation wise, instead of a list. It can be a dict, something like this:

fallbacks=[
    {
        "model": "anthropic.claude-3-haiku-20240307-v1:0",
        "messages":[
            {
                "role":"user",
                "content":"what is the capital of France?"
            }
        ],
        "max_tokens":2048,
        "temperature":0.7
    },
    {
        "model": "gpt-3.5-turbo",
        "messages":[
            {
                "role":"user",
                "content":"Pls reply in one word, what is the capital of France?"
            }
        ],
        "max_tokens":1000,
        "temperature":0.1
    }
]

**Comment by ghost** [comment]
is this on the router? @Aviral-Cactus

**Comment by Aviral-Cactus** [comment]
No, This is in [Reliability - Retries, Fallbacks](https://docs.litellm.ai/docs/completion/reliable_completions)

```
response = completion(model="bad-model", messages=messages, 
    fallbacks=["gpt-3.5-turbo" "command-nightly"])
```

**Here the fallbacks, instead of a list, could be a dict as shared above**

```
fallbacks=[
{
"model": "anthropic.claude-3-haiku-20240307-v1:0",
"messages":[
{
"role":"user",
"content":"what is the capital of France?"
}
],
"max_tokens":2048,
"temperature":0.7
},
{
"model": "gpt-3.5-turbo",
"messages":[
{
"role":"user",
"content":"Pls reply in one word, what is the capital of France?"
}
],
"max_tokens":1000,
"temperature":0.1
}
]
```

**Comment by aleksandrphilippov** [comment]
@Aviral-Cactus @krrishdholakia Hey, any updates here? I have the same problem, and it would be nice to have a callback to update the prompt during the fallback or to allow config to set the specific prompt per each model.

**Comment by ghost** [comment]
would you add the fallback message to the one sent in, just set at the start of the message list?

**Comment by aleksandrphilippov** [comment]
@krrishdholakia Yes, it is possible to add a fallback message near the message body with a specific model name for a callback.

The goal is to replace / update / alter the prompt based on the model. There are a other approaches:

1. Implement a callback similar to async_post_call_failure_hook, but one that allows modifying the input (message). In this callback, you could check the model and potentially additional parameters from the request, then select the appropriate prompt accordingly.
2. A better approach, in my opinion, would be to allow specifying a fallback_prompt directly in the config.yaml under model_list. This way, each model can have its own fallback prompt configured. For example:
```yaml
model_list:
  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    fallback_prompt: "Your custom prompt with query here: {query}"
  - model_name: gpt-3.5-turbo
    fallback_prompt: "Another prompt with query here: {query}"
```
Then I can define the required models in the configuration with the appropriate prompts and call them accordingly. During a fallback, it will automatically switch to another model with the correct prompt.

Key Requirement: The query from the original request should be inserted into the fallback prompt, either as a parameter or at the end of the prompt. For example: `fallback_prompt = f"Your fallback context. Query: {original_query}"`

**Comment by ghost** [comment]
how would we extract 'query' from the request? 

Would it be similar to the langfust prompt management flow - https://docs.litellm.ai/docs/proxy/prompt_management

```python
completion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "ignore this"}], prompt_id="test_id", prompt_variables={"query": "<insert_text>"}) 
```

```yaml
model_list:
  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    prompt_templates: 
         - prompt_id: test_id
            prompt_str: "Your custom prompt with query here: {query}" 
            {{optional_pull_from_langfuse_somehow}}
```

**Comment by aleksandrphilippov** [comment]
@krrishdholakia Yes, this would be similar, it would be nice to use it like this. 

Now we can only send prompt_id and params as a metadata in request and it is applied to all models, right?

```bash
curl -L -X POST 'http://0.0.0.0:4000/v1/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-d '{
    "model": "gpt-4",
    "messages": [
        {
            "role": "user",
            "content": "THIS WILL BE IGNORED"
        }
    ],
    "metadata": {
        "langfuse_prompt_id": "value",
        "langfuse_prompt_variables": { # [OPTIONAL]
            "key": "value"
        }
    }
}'
```

It would be great to set the langfuse_prompt_id and langfuse_prompt_variables per model in the config.yaml.

**Comment by ghost** [comment]
> It would be great to set the langfuse_prompt_id and langfuse_prompt_variables per model in the config.yaml

can you give an example of how you'd want to pass this? 

and when this would be used?

**Comment by sfarthin** [comment]
While this API might be useful, my preference would be to grab all the model details from the `config` on langfuse. In addition to the prompt, I would likely want to run experiments or change the specific model (e.g. from gpt-4o to gpt4o-mini finetune) from langfuse instead of making changes to the application. I suggest having a special "model type" like `langfuse/<prompt-id>`.

![image](https://github.com/user-attachments/assets/c9cd00c5-4a8a-47ad-bc4c-b1391b0c4ed6)
![image (11)](https://github.com/user-attachments/assets/f7003c86-5936-4b58-9be3-850ea6cda9d0)

**Comment by aleksandrphilippov** [comment]
@krrishdholakia As I see it, we have 3 possible solutions.

1. We might have specific parameters in the config.yaml per each model, like:
```
model_list:
  - model_name: openai-default-model
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
    langfuse_prompt_variables:
      llm_extra_instruction: "Provide concise and accurate responses."
      llm_based_extra_rules: "Return response in JSON format."

  - model_name: claude-default-model
    litellm_params:
      model: claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
    langfuse_prompt_variables:
      llm_extra_instruction: "Provide detailed and structured responses."
      llm_based_extra_rules: "Return response in JSON format. Do not include any notes or additional information – strictly JSON only."
```

This will allow us to set model-based rules and instructions. In the Langfuse in the prompt, they must be added, and if the fallback occurs - those langfuse_prompt_variables are taken and sent to Langfuse as part of the variables in the request. In that case, I will be able to add several models with specific instructions and rules, which will help me configure the model's specific response issues.


2. We might not change the config.yaml, but change the request:
```
curl -L -X POST 'http://0.0.0.0:4000/v1/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-d '{
  "model": "gpt-4",
  "messages": [
    {
      "role": "user",
      "content": "THIS WILL BE IGNORED"
    }
  ],
  "metadata": {
    "langfuse_prompt_id": "value",
    "langfuse_prompt_variables": {
      "key": "value"
    },
    "langfuse_fallback_rules": {
      "openai-default-model": {
        "llm_extra_instruction": "Provide concise and accurate responses.",
        "llm_based_extra_rules": "Return response in JSON format."
      },
      "claude-default-model": {
        "llm_extra_instruction": "Provide detailed and structured responses.",
        "llm_based_extra_rules": "Return response in JSON format. Do not include any notes or additional information – strictly JSON only."
      }
    }
  }
}'
```
This also will allow us to set model-based rules and instructions for the fallback.

3. Change the fallback settings:
```
router_settings:
    fallbacks=[
  {
    "claude-2": [
      {
        "model": "claude-default-model",
        "llm_extra_instruction": "Provide detailed and structured responses.",
        "llm_based_extra_rules": "Return response in JSON format. Do not include any notes or additional information – strictly JSON only."
      }
    ]
  }
]
```

In that case, llm_extra_instruction and llm_based_extra_rules must replace the original values from the request if they exist.


FYI: I use the proxy server with docker image and docker compose, so I am working with config.yaml and requests; I do not work with Python code to make a request.
