### ISSUE TITLE
[Feature]: Allow setting multiple orgs for an openai call (Router) 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#3949]
### The Feature

> specify multiple orgs to load balance all in couple lines of yaml instead of a huge file

```yaml
  - model_name: *
    litellm_params:
      model: openai/*
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1
      organization:
       - org-1 
       - org-2 
       - org-3
```

### Motivation, pitch

not need to duplicate multiple models in the yaml
