### ISSUE TITLE
[Bug]: Litellm can't log traces into langfuse when using ChatOpenAI.invoke sequentially

### ISSUE THREAD

**Issue by databill86** [BerriAI/litellm#4093]
### What happened?

A follow up on this bug: https://github.com/BerriAI/litellm/issues/4059

When we define `ChatOpenAI` like this:

```
ChatOpenAI(
    openai_api_base="http://0.0.0.0:4000",
    model = "gpt-3.5-turbo",
    temperature=0.1,
    extra_body={
        "metadata": {
            "generation_name": "ishaan-generation-langchain-client",
            "generation_id": "langchain-client-gen-id22",
            "trace_id": "langchain-client-trace-id22",
            "trace_user_id": "langchain-client-user-id2"
        }
    }
)
```

and then use `.invoke()` for the generations, we kind of lose traces in case we use `invoke` more than one time, sequentially. 

I used two consecutive invoke(), and I got the trace only for the first one. 

Is there something I'm missing here ? 

I also tried to overwrite the extra_body, so I can personalize the second trace with a new name, but no chance. Here is what I did: 
```

chat_openai = ChatOpenAI(
    openai_api_key="sk-xxxxx",
    openai_api_base="http://0.0.0.0:4004",
    model="openai",
    model_kwargs={
        "extra_body": {
            "metadata": {
                "generation_name": "gen-test-fuse",
                "generation_id": f"clangchain-client-gen-{g_id}",
                "trace_id": f"langchain-client-trace-{g_id}",
                "trace_user_id": "sum-test",
                "team_id": "rag-tests-project",
                "session_id": f"session-test-fuse-{g_id}", 
                "tags": ["tag1", "tag2"]
            }
        }
    }
).configurable_fields(
    model_kwargs=ConfigurableField(
        id="model_kwargs",
        name="model_kwargs",
        description="model kwargs for langfuse",
    )
)

messages = [
    HumanMessage(
        content="what model are you"
    )
]

print(chat_openai.invoke(messages))

# **should wait before the call to make the trace appear in langfuse**
# import time
# time.sleep(60)

messages_2 = [
    HumanMessage(
        content="who are you exactly?"
    )
]

print(chat_openai.bind(extra_body={

        "metadata": {
            "generation_name": "gen-test-fuse2",
            "generation_id": f"clangchain-client-gen-{g_id+1}",
            "trace_id": f"clangchain-client-trace--{g_id+1}",
            "trace_user_id": "sum-test",
            "team_id": "rag-tests-project",
            "session_id": f"session-test-fuse--{g_id+1}",  
            "tags": ["tag3"]
        }

}
).invoke(messages_2))
```

And the weird thing, is when I used breakpoints to debug, I waited about 60 seconds before the second call, and only then it worked. So it seems that it only work when the time between two calls is significant. 

edit: Even when I use one invoke, I should wait some time before rerunning again to get the trace appear into langfuse. It seems the second trace is not flushed or something.

### Relevant log output
So I went through the litellm logs to see what's really happening, and I think this is a bug. 
I confirm that only the first call and trace are logged into langfuse: 

```shell


10:17:59 - LiteLLM:DEBUG: utils.py:1781 - reaches langfuse for success logging!
10:17:59 - LiteLLM:DEBUG: utils.py:1105 - Langfuse Logging - Enters logging function for model
....
10:17:59 - LiteLLM:DEBUG: utils.py:1105 - Langfuse Layer Logging - logging to langfuse v2 
10:17:59 - LiteLLM:DEBUG: utils.py:1105 - Logging Details LiteLLM-Async Success Call
10:17:59 - LiteLLM:DEBUG: utils.py:1105 - trace: 2.95e-05
10:17:59 - LiteLLM:DEBUG: utils.py:1494 - Model=gpt-3.5-turbo-0125;
10:17:59 - LiteLLM:DEBUG: utils.py:1105 - Langfuse Layer Logging - final response object: ModelResponse(id='chatcmpl-9YWO7mgvzwIKWSCvdZFMayxiI3gi0', choices=[Choices(finish_reason='stop', index=0, message=Message(content='I am a language model AI created by OpenAI called GPT-3.', role='assistant'))], created=1718014679, model='gpt-3.5-turbo-0125', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=16, prompt_tokens=11, total_tokens=27))
10:17:59 - LiteLLM:DEBUG: utils.py:4620 - completion_response response ms: 697.681 
10:17:59 - LiteLLM:INFO: langfuse.py:182 - Langfuse Layer Logging - logging success
```

```
There is no log about the second call at all.

**Comment by ghost** [comment]
is the 2nd call even being received by litellm proxy? 

If so, can you share the full server logs?

**Comment by databill86** [comment]
Yes it was received, but only when I wait some time after the first call. I will share the log.

**Comment by databill86** [comment]
This is the log for two calls. I hope I didn't forget any api key :D 

https://pastebin.com/MSqKkrjU

Edit: I actually left the api key. I already revoked it. Maybe it would be better to have these api keys replaced in the logs.

**Comment by ghost** [comment]
i see just 1 call to litellm 

> 14:36:00 - LiteLLM:DEBUG: utils.py:1105 - Request to litellm:


where's call #2?

**Comment by databill86** [comment]
Sorry, I didn't see that there was no second call.
Here is a new log, with both requests: https://pastebin.com/DJVUz6VQ

this is the answer:

```
content='I am a language model AI designed to assist and provide information to users.' response_metadata={'token_usage': {'completion_tokens': 15, 'prompt_tokens': 11, 'total_tokens': 26}, 'model_name': 'openai', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None} id='run-7fa04a0d-f8eb-4817-ae82-3216382ad2cd-0'
content='I am a language model AI developed by OpenAI, designed to assist with answering questions and engaging in conversation on a wide range of topics. How can I help you today?' response_metadata={'token_usage': {'completion_tokens': 35, 'prompt_tokens': 12, 'total_tokens': 47}, 'model_name': 'openai', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None} id='run-3b9f4075-b481-4587-9b3c-9e96ee1eb322-0'
```

Only this trace is logged into `langfuse`: `langchain-client-trace-99999999999222`

**Comment by databill86** [comment]
Actually, I can confirm that this bug is not specific to `ChatOpenAI`, even simple requests can't be logged to `langfuse`, if we run them sequentially. Only the first request is logged to `langfuse`
Here is another example: 
```

import openai


def get_response(m):
    res = client.chat.completions.create(
        model="openai-gpt4-o",
        messages=m,
        temperature=1,
    )
    return res


client = openai.OpenAI(
    api_key="sk-4DAMCXUPt6mv5oQh53kwBw",
    base_url="http://0.0.0.0:4004",
)

system = """You are a helful assistant
"""

user_text_1 = "Hello who are you"
messages = [
    {
        "role": "system",
        "content": system,
    },
    {"role": "user", "content": user_text_1},
]

response = get_response(messages)

r = response.choices[0].message.content
print("###########################################")
m1 = {"role": "assistant", "content": r}
messages.append(m1)
print(m1)
print("###########################################")
user_text_2 = "are you sure about that?"
m2 = {"role": "user", "content": user_text_2}
messages.append(m2)
print(m2)
r2 = get_response(messages)
print("###########################################")
m3 = {"role": "assistant", "content": r2.choices[0].message.content}
messages.append(m3)
print(m3)

```

I really don't understand why only the first call is logged into `langfuse`.

**Comment by ghost** [comment]
@databill86 in https://pastebin.com/DJVUz6VQ

there is still just 1 call made to litellm 

> 06:56:47 - LiteLLM:DEBUG: utils.py:1105 - Request to litellm:

i see just 1 of this

**Comment by databill86** [comment]
pastebin kept trimming my logs! sorry about that. Here is the file attached for the second example. 
[litellm-logs.log](https://github.com/user-attachments/files/15791142/litellm-logs.log)

**Comment by ghost** [comment]
@databill86 unable to repro. Ran your script, and i see both tracked 
<img width="1491" alt="Screenshot 2024-06-11 at 8 07 44 AM" src="https://github.com/BerriAI/litellm/assets/17561003/9371e3e3-5b8c-4df9-96c4-8ea5c201f5d2">

<img width="1100" alt="Screenshot 2024-06-11 at 8 08 14 AM" src="https://github.com/BerriAI/litellm/assets/17561003/a11496c5-9fbf-440b-b2eb-dd6eddbdcc62">

<img width="1033" alt="Screenshot 2024-06-11 at 8 08 22 AM" src="https://github.com/BerriAI/litellm/assets/17561003/39f63473-b8dd-466e-8ce9-84a763e69efa">




Config 
```yaml
model_list: 
- litellm_params:
    api_base: https://openai-gpt-4-test-v-1.openai.azure.com
    api_key: os.environ/AZURE_API_KEY
    api_version: 2024-02-15-preview
    model: azure/chatgpt-v-2
  model_name: gpt-3.5-turbo

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
```

**Comment by ghost** [comment]
Closing as unable to repro - happy to help debug this over a call though @databill86 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ghost** [comment]
Looking at your logs - i don't even see it entering langfuse for the 2nd call 

> reaches langfuse for success logging!

What does your config look like?

**Comment by databill86** [comment]
this is the config of litellm, related to langfuse

```
  default_team_settings:
    - team_id: rag-tests-project
      success_callback: ["langfuse"]
      langfuse_public_key: pk-lf-2a673c2e-2ad8-4cc8-b6b8 
      langfuse_secret: sk-lf-999d477c-ac8e-4424-9f1f 
    - team_id: litellm-test-project
      success_callback: ["langfuse"]
      langfuse_public_key: pk-lf-0160b8f5-5e49-4305-bfcd
      langfuse_secret: sk-lf-3ccd40bd-7439-4d64-8ff4
    - team_id: rag-tests-xxx-project
      success_callback: ["langfuse"]
      langfuse_public_key: pk-lf-362d98e7-a5ad-4467-ac51
      langfuse_secret: sk-lf-0825a322-2c01-4ca0-bdc3
```

and in docker compose: 
```    
command: [ "--config", "/app/proxy_server_config.yaml", "--port", "4000", "--num_workers", "2", "--detailed_debug"]
environment:
      - LANGFUSE_HOST=http://172.18.0.1:3000
```

**Comment by databill86** [comment]
I have multiple projects, so I would like to keep the traces separated in langfuse. That's why the logging is project based.

**Comment by ghost** [comment]
reopening - got it - i'll test with that flow instead 

thanks @databill86

**Comment by ghost** [comment]
hey @databill86 can we do a 10min call this/next week? 

I can do whatever time works best for you. Want to learn how we can improve litellm for you 

attaching calendly, for convenience - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by databill86** [comment]
Hey @krrishdholakia, yeah sure. I'm filled the form.

**Comment by databill86** [comment]
Did you had time to investigate what's going on the langfuse traces ?

**Comment by ghost** [comment]
picking this up today again

**Comment by databill86** [comment]
FYI,  without the project based logging in the litellm config, and with using a default langfuse logging, traces are correctly being logged in langfuse.

**Comment by ghost** [comment]
Unable to repro @databill86 
<img width="758" alt="Screenshot 2024-06-14 at 5 33 39 PM" src="https://github.com/BerriAI/litellm/assets/17561003/8a764f94-0128-4dd3-859e-e9043864e1b8">


I ran your script with team-based logging to langfuse and it worked (screenshot attached, see timestamps for top 2 calls) 

can you please confirm you're on the latest version of litellm. 

If so, could you add `LANGFUSE_DEBUG = "True"` to your .env and share the error logs. 

Closing for now as unable to repro. Can reopen post-call if we can achieve a repro for this 

here's my config 

```yaml
litellm_settings:
  default_team_settings:
    - team_id: litellm-client-id-1
      success_callback: ["langfuse"]
      langfuse_public_key: pk-lf-b3db7e8e-c2f6-4fc7-825c
      langfuse_secret: sk-lf-b11ef3a8-361c-4445-9652
    - team_id: litellm-client-id-2
      success_callback: ["langfuse"]
      langfuse_public_key: pk-lf-b3db7e8f-c2f6-4fc7-825c
      langfuse_secret: sk-lf-b11ef3a8-361c-4445-9652
    - team_id: litellm-client-id-1
      success_callback: ["langfuse"]
      langfuse_public_key: pk-lf-b3db7e8g-c2f6-4fc7-825c
      langfuse_secret: sk-lf-b11ef3a8-361c-4445-9652
```
