### ISSUE TITLE
Multiple Azure OpenAI endpoints

### ISSUE THREAD

**Issue by hsleiman1** [BerriAI/litellm#4122]
Hello, 

Knowing that model deployments on Azure OpenAI are region based, is there a way to use models from different region deployments ?

this means that the we have multiple endpoints.

Thanks!

**Comment by rrajp** [comment]
You can add multiple model of Azure, each with different API Base. For your own convenience you can keep public name with region prefix e.g. useast-gpt35 / uksouth-gpt35 etc

**Comment by ishaan-jaff** [comment]
@hsleiman1 here's how to set it on the config.yaml

```yaml
model_list:
  - model_name: gpt-3.5-turbo ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: azure/gpt-turbo-small-eu ### MODEL NAME sent to `litellm.completion()` ###
      api_base: https://my-endpoint-europe-berri-992.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY_EU" # does os.getenv("AZURE_API_KEY_EU")
      rpm: 6      # [OPTIONAL] Rate limit for this deployment: in requests per minute (rpm)
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-turbo-small-ca
      api_base: https://my-endpoint-canada-berri992.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY_CA"
      rpm: 6
```
