### ISSUE TITLE
[Bug]: Mapping error for Azure TTS model

### ISSUE THREAD

**Issue by lalineanegra** [BerriAI/litellm#4127]
### What happened?

The azure version of the tts model seems not to be supported, it returns an error after an attempt to use

Config used:
````
 
 - model_name: azure/tts-1
    litellm_params:
      model: azure/tts-1
      api_base: "os.environ/AZURE_API_BASE_TTS"
      api_key: "os.environ/AZURE_API_KEY_TTS"
```

### Relevant log output

```shell
Error output

litellm.exceptions.APIConnectionError: Unable to map the custom llm provider=azure_text to a known provider=['openai', 'custom_openai', 'text-completion-openai', 'cohere', 'cohere_chat', 'clarifai', 'anthropic', 'replicate', 'huggingface', 'together_ai', 'openrouter', 'vertex_ai', 'palm', 'gemini', 'ai21', 'baseten', 'azure', 'azure_text', 'sagemaker', 'bedrock', 'vllm', 'nlp_cloud', 'petals', 'oobabooga', 'ollama', 'ollama_chat', 'deepinfra', 'perplexity', 'anyscale', 'mistral', 'groq', 'deepseek', 'maritalk', 'voyage', 'cloudflare', 'xinference', 'fireworks_ai', 'watsonx', 'triton', 'predibase', 'databricks', 'custom'].
```
```


### Twitter / LinkedIn details

_No response_
