### ISSUE TITLE
[Feature]: Manually allow running CircleCI unit tests on PRs (safely)

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4157]
### The Feature

This ticket is for writing down notes before I forget. If you're not me, you can ignore this for now.

Self notes:

https://stackoverflow.com/a/62602611/2079814

And then I should filter on:

```yaml
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED' && github.event.review.user.login == "Manouchehri" && github.event.sender.login == "Manouchehri"
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
```

https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request_review

### Motivation, pitch

Let's not give everybody a heart attack when merging into main.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
