### ISSUE TITLE
[Feature]: Support wildcard name for model_name in model_list

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4238]
### The Feature

```
model_list:
  - model_name: "vertex_ai/*"
    litellm_params:
      model: "vertex_ai/*"
      vertex_project: os.environ/VERTEXAI_PROJECT
  - model_name: "anthropic/*"
    litellm_params:
      model: "anthropic/*"
      api_key: os.environ/ANTHROPIC_API_KEY      
  - model_name: "gemini/*"
    litellm_params:
      model: "gemini/*"
      api_key: os.environ/GEMINI_API_KEY
```

### Motivation, pitch

user request

### Twitter / LinkedIn details

cc: @ggallotti

**Comment by jbohnslav** [comment]
This seems like it should already be possible, [e.g. the example config: ](https://github.com/BerriAI/litellm/blob/dd048cf342557b9d713ce32a87f7c51c86b57cfa/proxy_server_config.yaml#L84). However, using the latest docker image, the model shows up as "*", and obviously doesn't work.

**Comment by ghost** [comment]
hey @jbohnslav the * implies any openai model should just work - can you try that and let mek now if you see it? 

The ask on this ticket is having it work for other providers too

**Comment by ggallotti** [comment]
Currently, this feature is not functional.

I would love the ability to dynamically call any model from any given provider without the need to predefine it in the config YAML file.

thank you

**Comment by ghost** [comment]
hey @ggallotti can you give me a v0 scope we need to cover here? 


Will help for my e2e testing. currently this should work for any openai models

**Comment by ghost** [comment]
Hey @ggallotti i can confirm this already works across models/providers 

1. Setup config.yaml
```
model_list:
  - model_name: "*"             # all requests where model not in your config go to this deployment
    litellm_params:
      model: "openai/*"           # passes our validation check that a real provider is given
```

2. Start LiteLLM proxy 

```
litellm --config /path/to/config.yaml
```

3. Try claude 3-5 sonnet from anthropic 

```bash
curl -X POST 'http://0.0.0.0:4000/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-D '{
  "model": "claude-3-5-sonnet-20240620",
  "messages": [
        {"role": "user", "content": "Hey, how'\''s it going?"},
        {
            "role": "assistant",
            "content": "I'\''m doing well. Would like to hear the rest of the story?"
        },
        {"role": "user", "content": "Na"},
        {
            "role": "assistant",
            "content": "No problem, is there anything else i can help you with today?"
        },
        {
            "role": "user",
            "content": "I think you'\''re getting cut off sometimes"
        }
    ]
}
'
```

Expected Response

<img width="1192" alt="Screenshot 2024-07-01 at 2 12 27 PM" src="https://github.com/BerriAI/litellm/assets/17561003/65fb7c3f-ace4-4fbb-874d-fbfb048d5eac">
