### ISSUE TITLE
[Bug]: not logging to langfuse with multiple projects

### ISSUE THREAD

**Issue by themrzmaster** [BerriAI/litellm#4281]
### What happened?

```
default_team_settings: 
    - team_id: proj1
      success_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
      langfuse_secret: os.environ/LANGFUSE_SECRET_KEY
    - team_id: proj2
      success_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE2_PUBLIC_KEY
      langfuse_secret: os.environ/LANGFUSE2_SECRET_KEY
```

This works great on v1.40.14
on v1.40.17 it does not log to langfuse. nothing changed. using the token genereated for each team. no error logs
