### ISSUE TITLE
[Bug]: Embedding output missing from langfuse

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4319]
### What happened?

The output seems to always be `null`.
<img width="786" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/6d5ce077-d065-484c-a934-89c65b909aa0">

```sh
curl -v "$OPENAI_API_BASE/embeddings" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "input": "LiteLLM is cool.",
    "model": "text-embedding-3-small"
  }'
```

### Relevant log output

```yaml
model_list:
  - model_name: text-embedding-3-small
    litellm_params:
      model: azure/text-embedding-3-small
      api_version: "2024-05-01-preview"
      azure_ad_token: "oidc/google/https://example.com"
      user: litellm
      api_base: "https://gateway.ai.cloudflare.com/v1/account_id_removed/gateway_name_removed/azure-openai/example"
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
