### ISSUE TITLE
[Bug]: `traceparent` causes `extra_headers` on config to be ignored/overwritten

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4448]
### What happened?

I believe b16b846711937a1145e8519693f23310cfb885ad introduced a problem where whenever `traceparent` is present, it completely overrides/replaces the `extra_headers` configs I have in my yaml.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ishaan-jaff** [comment]
from looking at the code it does not look like it's override any other extra_header when traceparent is present

**Comment by Manouchehri** [comment]
`if "extra_headers" not in data:` kinda sounds like it's only checking the incoming request and not the config.

**Comment by ishaan-jaff** [comment]
it should not check the config that is intended

**Comment by Manouchehri** [comment]
But... now this is overriding my config unexpectedly.

**Comment by ishaan-jaff** [comment]
is this how you set it on your config ? 

```
model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
      extra_headers: {"X-Custom-Header": "value"}
```
