### ISSUE TITLE
[Feature]: Support Groq Whisper model

### ISSUE THREAD

**Issue by huyhandes** [BerriAI/litellm#4514]
### The Feature

support calling groq whisper model
```yaml
model_list:
  - model_name: whisper
      litellm_params:
        model: groq/whisper-large-v3
        api_key: gsk_***
     model_info:
        mode: audio_transcription
```

### Motivation, pitch

The Whisper Large V3 is now free and easy access from groq. Please support to easy call setup in proxy config.
If there any one wonder is the any work around, here it is:
```yaml
model_list:
  - model_name: whisper
      litellm_params:
        model: openai/whisper-large-v3
        api_key: gsk_***
        api_base: https://api.groq.com/openai/v1
     model_info:
        mode: audio_transcription

```

**Comment by huyhandes** [comment]
Anyway I wonder why we need to parse /v1 in the URL?
Same as my another stt endpoint (which compatible to openai)
```yaml
model_list:
  - model_name: whisper
      litellm_params:
        model: openai/Systran/faster-whisper-medium
        api_key: EMPTY
        api_base: https://sst.openai-compatible.example/v1
        timeout: 60
        rpm: 50
      model_info:
        mode: audio_transcription
```
