### ISSUE TITLE
[Bug]: Wrong price per token on UI

### ISSUE THREAD

**Issue by delfer** [BerriAI/litellm#4542]
### What happened?

ghcr.io/berriai/litellm:main-v1.41.6
<img width="1265" alt="image" src="https://github.com/BerriAI/litellm/assets/3233181/811fd781-ce3f-47d0-b3e5-694cef43ea8d">
<img width="1264" alt="image" src="https://github.com/BerriAI/litellm/assets/3233181/055bab0d-7995-48ae-b26c-cc58bb04eec2">
I've set custom `input_cost_per_token` and `output_cost_per_token` but in UI i see default.

**Comment by ishaan-jaff** [comment]
@delfer where did you set custom `input_cost_per_token` and `output_cost_per_token` ?

**Comment by delfer** [comment]
@ishaan-jaff in proxy config.yaml

**Comment by ghost** [comment]
unable to repro @delfer

**Comment by ghost** [comment]
I see: 
<img width="1541" alt="Screenshot 2024-07-04 at 3 39 58 PM" src="https://github.com/BerriAI/litellm/assets/17561003/2af08aeb-ba4d-46ea-92b2-8693b4648116">

For a model in my config, set like this 

```yaml
- litellm_params:
    api_base: http://0.0.0.0:8080
    api_key: ''
    model: openai/my-fake-model
    rpm: 800
    input_cost_per_token: 300
  model_name: gpt-3.5-turbo-fake-model
```
