### ISSUE TITLE
[Bug]: health check cannot get Azure Studio AI Models to run: Phi3

### ISSUE THREAD

**Issue by deliciousbob** [BerriAI/litellm#4653]
### What happened?

Cannot get Azure Studio AI Models to run: Phi3
I've tried multiple variants of the local config, but it always tells me that the model does not exist:

This is my config:
```
- model_name: Azure-Phi3-Medium-128K
  litellm_params:
    api_base: https://Phi-3-medium-128k-instruct-<additional5figueres>-serverless.swedencentral.inference.ai.azure.com/v1
    api_key: <api-key>
    model: azure_ai/Phi-3-medium-128k-instruct-<additional5figures>
```
    
I've tried it without the additional 5 figures at the end (azure_ai/Phi-3-medium-128k-instruct), 
I've tried with another api_base ending without /v1 and also /v1/ but i always get the following ERROR on the health check:

```
"error": "litellm.NotFoundError: NotFoundError: Azure_aiException - The model `Phi-3-medium-128k-instruct-<additional5figures>` does not exist. stack trace: Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/main.py\", line 388, in acompletion\n    response = await init_response\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py\", line 1019, in acompletion\n    raise e\n  File \"/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py\", line 1002, in acompletion\n    headers, response = await self.make_openai_chat_completion_request(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py\", line 783, in make_openai_chat_completion_request\n    raise e\n  File \"/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py\", line 778, in make_openai_chat_completion_request\n    response = await openai_aclient.chat.completions.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/openai/resources/chat/co"
```

I probably made an mistace somewhere, but i tried every kind of combination and always fale....

Here is the Endpoint Info from Azrue Studio AI:
![image](https://github.com/BerriAI/litellm/assets/13135271/c0df71bd-7168-4a59-9955-2d67d6aaefb6)

Thank you for your help!

**Comment by ghost** [comment]
@deliciousbob this looks like it's being raised by azure. 

- Can you run the query with `--detailed_debug` and share the raw query
- confirm if the raw query matches what a successful curl to azure ai with your phi model should look like

**Comment by ghost** [comment]
> following ERROR on the health check

does it work when you call it via `/chat/completions` on the proxy?

**Comment by ghost** [comment]
Also dm'ed on linkedin to setup a direct support channel

**Comment by ghost** [comment]
Unable to repro. Works for me. 
<img width="1168" alt="Screenshot 2024-07-11 at 10 20 54 AM" src="https://github.com/BerriAI/litellm/assets/17561003/5f2e4447-3cb2-4857-8343-3ceaa28dffaa">


**config**

```yaml
model_list:
  - model_name: azure-ai-mistral
    litellm_params:
      api_base: os.environ/AZURE_AI_MISTRAL_API_BASE
      api_key: os.environ/AZURE_AI_MISTRAL_API_KEY
      model: azure_ai/Mistral-large-nmefg
  - model_name: azure-ai-phi
    litellm_params:
      api_base: os.environ/AZURE_AI_PHI_API_BASE
      api_key: os.environ/AZURE_AI_PHI_API_KEY
      model: azure_ai/Phi-3-medium-128k-instruct-fpmvj
```
