### ISSUE TITLE
[Feature]: Support key RPM limits on pass through endpoints 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4698]
### The Feature

Allow setting rpm limits on pass through endpoints 

```yaml
general_settings:
  master_key: sk-1234
  pass_through_endpoints:
    - path: "/v1/rerank"
      target: "https://api.cohere.com/v1/rerank"
      auth: true # 👈 Key change to use LiteLLM Auth / Keys
      headers:
        Authorization: "bearer os.environ/COHERE_API_KEY"
        content-type: application/json
        accept: application/json
```

### Motivation, pitch

User request
