### ISSUE TITLE
triton embedding support

### ISSUE THREAD

**Issue by riyajatar37003** [BerriAI/litellm#4770]
### What happened?

Hi 

could anyone explain what all are the parameters exactly we need to pass?

```
from litellm import embedding
import os

response = await litellm.aembedding(
    model="triton/<your-triton-model>",                                                       
    api_base="https://your-triton-api-base/triton/embeddings", # /embeddings endpoint you want litellm to call on your server
    input=["good morning from litellm"],
)
```

</TabItem>
<TabItem value="proxy" label="PROXY">

1. Add models to your config.yaml

  ```yaml
  model_list:
    - model_name: my-triton-model
      litellm_params:
        model: triton/<your-triton-model>"
        api_base: https://your-triton-api-base/triton/embeddings
  ```

above what is model-name value,and model value?  is this something like this """
https://ip:/v2/models/mymodel/infer"""

please give one example 
bcz i am getting  No deployments available for selected model,
thanks
