### ISSUE TITLE
[Feature]: ollama tool usage

### ISSUE THREAD

**Issue by imaurer** [BerriAI/litellm#4812]
### The Feature

Ollama project now officially supports tools:
https://github.com/ollama/ollama/pull/5284

I noticed using the proxy server this is not how it currently works in LiteLLM. apologies if I am doing something incorrectly.  

### Motivation, pitch

Tool usage is a critical feature!

### Twitter / LinkedIn details

@imaurer

**Comment by ghost** [comment]
That's awesome. Excited to add native support!

**Comment by ghost** [comment]
Just added support. 

Add like this @imaurer 
```yaml
model_list:
  - model_name: "llama3.1"             
    litellm_params:
      model: "ollama_chat/llama3.1"
    model_info:
      supports_function_calling: true # 👈 KEY CHANGE
```


Is this what you wanted here? 


Not all ollama models (e.g. mistral) support tool calling, in those cases we default to the previous logic. You can override this, by setting the flag i mentioned above.
