### ISSUE TITLE
[Bug]: Azure OpenAI Deployment Key Misuse in LiteLLM Proxy

### ISSUE THREAD

**Issue by seonghobae** [BerriAI/litellm#4817]
### What happened?

# Azure OpenAI Deployment Key Misuse in LiteLLM Proxy

## Description

When registering Azure OpenAI with LiteLLM Proxy, an issue arises where different deployments are incorrectly using the same API key. Specifically, if the Azure Deployment API Base URL is different but the Azure Deployment Model Name is the same, the model A-2 attempts to call the Azure OpenAI API Base using the key of model A-1. This behavior is observed in both embedding models and chat completions.

## Environment

- LiteLLM Proxy Version: 1.41.26
- Tested Models: text-embedding-3-small, text-embedding-ada-002, and gpt-4o

## Issue Details

This issue leads to failures when tracking errors with Langfuse, as it causes the CPU load to spike to 100%, resulting in Langfuse becoming unresponsive. The error log from the LiteLLM_ErrorLogs table indicates the following error:

```
litellm.APIError: AzureException APIError - Resource not found
```

The corresponding status code is 404.

## Steps to Reproduce

1. Register Azure OpenAI with different Deployment API Base URLs but the same Deployment Model Name in LiteLLM Proxy.
2. Attempt to use both models (A-1 and A-2).
3. Observe the incorrect API key usage and the resulting errors.

## Expected Behavior

Each deployment should utilize its own API key based on the unique Deployment API Base URL, regardless of the Deployment Model Name.

## Additional Information

This issue has been consistently reproducible across multiple models and deployments.

Thank you for your attention to this matter. I look forward to your prompt response and resolution.

**Comment by ghost** [comment]
@seonghobae how are you assigning the keys? 

Please give a script for repro. 

> Register Azure OpenAI with different Deployment API Base URLs

This doesn't sound like different keys are being assigned.

**Comment by ghost** [comment]
Unable to repro. 

## PROXY

```yaml
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_key: os.environ/AZURE_EUROPE_API_KEY
      api_base: os.environ/AZURE_EUROPE_API_BASE
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_key: os.environ/AZURE_CANADA_API_KEY
      api_base: os.environ/AZURE_CANADA_API_BASE
```

curl 
<img width="1198" alt="Screenshot 2024-07-22 at 2 22 07 PM" src="https://github.com/user-attachments/assets/db475be0-fb2a-44b7-898f-51e3ac2edb62">




## SDK 

```python
from litellm import Router 
import os

router = Router(
    model_list = [
        {
          "model_name": "gpt-3.5-turbo",
          "litellm_params": {
              "model": "azure/gpt-35-turbo", 
              "api_key": os.getenv("AZURE_EUROPE_API_KEY"),
              "api_base": "https://my-endpoint-europe-berri-992.openai.azure.com/"
          }
        },
        {
          "model_name": "gpt-3.5-turbo",
          "litellm_params": {
              "model": "azure/gpt-35-turbo", 
              "api_key": os.getenv("AZURE_CANADA_API_KEY"),
              "api_base": "https://my-endpoint-canada-berri992.openai.azure.com/"
          }
        }
                  ]
)

router.completion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey!"}])
```
<img width="1626" alt="Screenshot 2024-07-22 at 2 17 36 PM" src="https://github.com/user-attachments/assets/ff2d2f87-2f69-420c-9251-6ab4867a4777">
