### ISSUE TITLE
[Bug]: prometheus metrics *-total ignored last status after restart

### ISSUE THREAD

**Issue by johnnychen94** [BerriAI/litellm#4849]
### What happened?

The following is the query from the Grafana dashboard for `litellm_spend_metric_total`.
I restart the litellm with `docker-compose restart litellm`, and then the Prometheus history shows a drop.
Apparently, this forgets the last non-null records and has been re-initialized since 0.

![image](https://github.com/user-attachments/assets/2efaf13f-5b78-4946-867e-5790556dec68)

The relevant config I use is:

```yaml
litellm_settings:
  set_verbose: False
  json_logs: False
  success_callback: ["langfuse", "prometheus"]
  failure_callback: ["prometheus"]
  service_callback: ["prometheus_system"]
  cache: True
  cache_params:
    type: redis
    namespace: "litellm_caching"
    ttl: 600
```

For reference, here's a simplified docker-compose file I've used, the database and redis were not restarted or re-created:

```yaml
version: "3.7"

services:
  litellm:
    image: ghcr.io/berriai/litellm-database:main-v1.41.23 
    restart: unless-stopped
    ports:
      - 4000:4000
    command: ["--config", "/app/config.yml"]
    volumes:
      - /data/litellm/config/litellm.yml:/app/config.yml
    environment:
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/litellm
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - /data/litellm/data/postgresql:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:7.0
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - /data/litellm/data/redis:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
```
