### ISSUE TITLE
[Feature]: Support `/*` for multiple providers - OpenAI, Anthropic, Mistral etc 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#4863]
### The Feature

```yaml
- model_name: "anthropic/*"
  litellm_params:
    model: "anthropic/*"
    api_key: os.environ/ANTHROPIC_API_KEY
 ```

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
currently - we only support this for `openai/*` but users are using `openai/*`, `anthropic/*` etc. we should support this for all providers

**Comment by ghost** [comment]
closing as this is now supported with 

```
model_list:
  - model_name: "*"             # all requests where model not in your config go to this deployment
    litellm_params:
      model: "*"           # passes our validation check that a real provider is given
```

docs: https://docs.litellm.ai/docs/proxy/configs#wildcard-model-name-add-all-models-from-env

**Comment by James4Ever0** [comment]
I would like to configure all model names routed to a single model, but currently it does not work.

```yaml
model_list:
  - model_name: "*"       
    litellm_params:
      model: <model_name>
      api_base: <api_base>
      api_key: <api_key>
```

Is there any configuration equivalent to this command line?

```bash
env OPENAI_API_KEY=<api_key> litellm --drop_params --api_base <api_base> --model <model_name> --port <litellm_port> --host 0.0.0.0

```
