### ISSUE TITLE
[Bug]: llama3-405b-instruct-maas streaming doesn't work

### ISSUE THREAD

**Issue by 04cfb1ed** [BerriAI/litellm#4885]
### What happened?

Hello!

llama3-405b-instruct-maas streaming doesn't work, if I use another model it works correctly

`litellm[proxy]~=1.42.1`

Model configuration

```yaml
- model_name: llama3-405b-instruct-maas
    litellm_params:
      model: vertex_ai/meta/llama3-405b-instruct-maas
      vertex_location: "us-central1"
```

Sample code
```python
from langchain_openai import ChatOpenAI

# Works
example_dict = {"model": "gpt-4o", "temperature": 0.3}
# Works
example_dict = {"model": "claude-3-5-sonnet", "temperature": 0.3}
# Doesn't work
example_dict = {"model": "llama3-405b-instruct-maas", "temperature": 0.3}

token = "test"

model = ChatOpenAI(
    openai_api_key=token,
    openai_api_base="http://localhost:4000",
    **example_dict,
)

chunks = []
async for chunk in model.astream("hello. tell me something about yourself"):
    chunks.append(chunk)
    print(chunk.content, end="|", flush=True)
```

Thank you

### Relevant log output

```
Traceback (most recent call last):
  File "\.venv\lib\site-packages\litellm\proxy\proxy_server.py", line 2358, in async_data_generator
    async for chunk in response:
TypeError: 'async for' requires an object with __aiter__ method, got ModelResponse
```
