### ISSUE TITLE
[Bug]: STT and TTS models health check doesn't work correctly

### ISSUE THREAD

**Issue by 04cfb1ed** [BerriAI/litellm#4886]
### What happened?

Hello

I'm using the health endpoint to test all the models in config file (previously I added the mode for required models)

But in whisper or tts model the health shows an error besides that the model works correctly

```json
{
	"healthy_endpoints": ["Removed"],
	"unhealthy_endpoints": [
		{
			"model": "whisper-1",
			"error": "mode not set stack trace: Traceback (most recent call last):\n  File \"\\.venv\\lib\\site-packages\\litellm\\main.py\", line 4813, in ahealth_check\n    response = await openai_chat_completions.ahealth_check(\n  File \"\\.venv\\lib\\site-packages\\litellm\\llms\\openai.py\", line 1874, in ahealth_check\n    raise Exception(\"mode not set\")\nException: mode not set\n"
		},
		{
			"model": "openai/tts-1",
			"error": "mode not set stack trace: Traceback (most recent call last):\n  File \"\\.venv\\lib\\site-packages\\litellm\\main.py\", line 4813, in ahealth_check\n    response = await openai_chat_completions.ahealth_check(\n  File \"\\.venv\\lib\\site-packages\\litellm\\llms\\openai.py\", line 1874, in ahealth_check\n    raise Exception(\"mode not set\")\nException: mode not set\n"
		},
		{
			"model": "openai/tts-1-hd",
			"error": "mode not set stack trace: Traceback (most recent call last):\n  File \"\\.venv\\lib\\site-packages\\litellm\\main.py\", line 4813, in ahealth_check\n    response = await openai_chat_completions.ahealth_check(\n  File \"\\.venv\\lib\\site-packages\\litellm\\llms\\openai.py\", line 1874, in ahealth_check\n    raise Exception(\"mode not set\")\nException: mode not set\n"
		}
	],
	"healthy_count": 30,
	"unhealthy_count": 3
}
```

Sample model config used
```yaml
  # OpenAI Speech to Text Models
  - model_name: whisper
    litellm_params:
      model: whisper-1
      api_key: "os.environ/OPENAI_API_KEY"
    model_info:
      mode: audio_transcription

  # OpenAI Text to Speech Models
  - model_name: tts
    litellm_params:
      model: openai/tts-1
      api_key: "os.environ/OPENAI_API_KEY"
    model_info:
      mode: audio_speech

  - model_name: tts-hd
    litellm_params:
      model: openai/tts-1-hd
      api_key: "os.environ/OPENAI_API_KEY"
    model_info:
      mode: audio_speech
```
