### ISSUE TITLE
[Feature]: Allow listing underlying models when using a wildcard

### ISSUE THREAD

**Issue by merlijn** [BerriAI/litellm#4903]
### The Feature

Hi there. I am using this config
```
model_list:
  - model_name: "*"
    litellm_params:
      model: "openai/*"
      api_key: os.environ/OPENAI_API_KEY
```  

It works in that I can call `/chat/completions` for example. However if I query `/models` or `/v1/models` I just get back a single model
```
{"data":[{"id":"*","object":"model","created":1677610602,"owned_by":"openai"}],"object":"list"}
```

It would be great if it would list the models available from openai so that I don't have to maintain that list in the UI app.

### Motivation, pitch

It would be very convenient to auto populate available models in a UI. you can proxy the call to /models on the open ai (or other vendor) API and return the response.

**Comment by ghost** [comment]
Hey @merlijn is this infering the models based on credentials in environment? 

Can we do a 10min call to understand your use-case better? https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by lowspace** [comment]
I would like to suggest a similar feature that allows users to set keys in a configuration file and load these keys using the function `litellm.load_keys(fpath)`. This feature offers several advantages:

1. **Enhanced Security**: By storing keys in a configuration file that is not uploaded, users can minimize the risk of key leakage.
2. **Reduced Redundancy**: This feature would eliminate the need to copy and paste keys across multiple files, which can be particularly cumbersome when using multiple providers.
3. **Simplified Key Management**: Centralizing key management in a single configuration file makes it easier for users to maintain and update their keys.

**Configuration File Example:**

```yaml
- provider: "openai"
  models: [] # List of model names; if specified, only these models will be accessible
  api_keys: [] # List of API keys for redundancy and different budgets
  api_version: ... # Specify API version, if applicable
  api_base: ... # Specify API base URL, if applicable
  location: [] # List of locations, if applicable
  project: ... # Project identifier, if applicable
```

**Justification:**

1. **`models`:** This field allows users to specify a list of models. If models are specified, the API will be restricted to calling only these models. If not specified, the API can call any model available from the provider. This provides greater control over the resources being used.

2. **`api_keys`:** Users may have multiple API keys, either due to different budgets or to ensure availability in case one service is down. By allowing a list of keys, users can switch between them automatically as needed.

3. **Additional Fields:** The `api_version`, `api_base`, `location`, and `project` fields provide additional configuration options to tailor the setup to specific requirements, ensuring flexibility and comprehensive control over the API usage.
