### ISSUE TITLE
[Feature]: Use a config file to set keys

### ISSUE THREAD

**Issue by lowspace** [BerriAI/litellm#4906]
## The Feature
 
I would like to suggest a similar feature that allows users to set keys in a configuration file and load these keys using the function `litellm.load_keys(fpath)`. 

**Configuration File Example:**

```yaml
- id: .... # A unique string generated by the user
  provider: .... # Model provider, such as openai
  models: [] # List of model names; if specified, only these models will be accessible
  api_keys: [] # List of API keys for redundancy and different budgets
  api_version: ... # Specify API version, if applicable
  api_base: ... # Specify API base URL, if applicable
  location: [] # List of locations, if applicable
  project: ... # Project identifier, if applicable
```

**Justification:**

1. **`models`:** This field allows users to specify a list of models. If models are specified, the API will be restricted to calling only these models. If not specified, the API can call any model available from the provider. This provides greater control over the resources being used.

2. **`api_keys`:** Users may have multiple API keys, either due to different budgets or to ensure availability in case one service is down. By allowing a list of keys, users can switch between them automatically as needed.

3. **Additional Fields:** The `api_version`, `api_base`, `location`, and `project` fields provide additional configuration options to tailor the setup to specific requirements, ensuring flexibility and comprehensive control over the API usage.

## Motivation, pitch

1. **Enhanced Security**: By storing keys in a configuration file that is not uploaded, users can minimize the risk of key leakage.
2. **Reduced Redundancy**: This feature would eliminate the need to copy and paste keys across multiple files, which can be particularly cumbersome when using multiple providers.
3. **Simplified Key Management**: Centralizing key management in a single configuration file makes it easier for users to maintain and update their keys.

## Twitter / LinkedIn details

No response

_Originally posted by @lowspace in https://github.com/BerriAI/litellm/issues/4903#issuecomment-2253279836_
