### ISSUE TITLE
[Feature]: Helm chart don't set Master Key in plain text

### ISSUE THREAD

**Issue by chris-sanders** [BerriAI/litellm#4911]
### The Feature

I spent a while trying to figure out why I couldn't authenticate. Since it's open source I was able to work it out. My master key didn't match, even though I'm using:

```yaml
  environmentSecrets:
    - api-keys

    general_settings:
      master_key: os.environ/PROXY_MASTER_KEY
```

It took some digging before I found that if the MASTER_KEY isn't set _in plain _text__ one is generated. And that overrides the one that's set in my secret.

I was able to work around it once I got this far. I renamed the MASTER_KEY in my secret and used that in the environ call and it's happy now.

You could just document how to do that, but encouraging the MASTER_KEY to be in plain text doesn't seem great. Maybe consider telling people to set it in the secret and only auto-generate if no secret is used?

### Motivation, pitch

Make it easier for people not deeply familiar with helm to do the right thing and avoid accidental leaks of their secrets.
