### ISSUE TITLE
[Bug]: Logs not always going to Langfuse default project, and sometimes wrong project completely

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4944]
### What happened?

I currently have this config, but it seems like when I use a key _without_ setting a team, nothing is sent to Langfuse. I was expecting that it would go to my default vars that were set like this:

```sh
export LANGFUSE_SECRET_KEY="sk-lf-1234567890abcdef"
export LANGFUSE_PUBLIC_KEY="pk-lf-1234567890abcdef"
export LANGFUSE_HOST="https://langfuse.example.com
```

```yaml
litellm_settings:
  drop_params: True
  redact_messages_in_exceptions: True
  cache: True
  cache_params:
    type: s3
    s3_bucket_name: os.environ/CACHING_S3_BUCKET_NAME
    s3_region_name: os.environ/CACHING_AWS_DEFAULT_REGION
    s3_aws_access_key_id: os.environ/CACHING_AWS_ACCESS_KEY_ID
    s3_aws_secret_access_key: os.environ/CACHING_AWS_SECRET_ACCESS_KEY
    s3_endpoint_url: os.environ/CACHING_AWS_ENDPOINT_URL_S3
  failure_callback: ["sentry", "langfuse"]
  num_retries: 0
  allowed_fails: 2
  request_timeout: 3600
  success_callback: ["langfuse", "s3"]
  s3_callback_params:
    s3_bucket_name: os.environ/LOGGING_S3_BUCKET_NAME
    s3_region_name: os.environ/LOGGING_AWS_DEFAULT_REGION
    s3_aws_access_key_id: os.environ/LOGGING_AWS_ACCESS_KEY_ID
    s3_aws_secret_access_key: os.environ/LOGGING_AWS_SECRET_ACCESS_KEY
    s3_endpoint_url: os.environ/LOGGING_AWS_ENDPOINT_URL_S3
  default_team_settings:
    - team_id: example_team
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_EXAMPLE
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_EXAMPLE
```

The user key I created was done with:

```sh
curl -v -H "content-type: application/json" -H 'accept: application/json' -H 'Authorization: Bearer removed' 'https://litellm-epic-uk.a.run.app/key/generate' --data '{"key_alias": "example-worker"}' | jq
```

```json
{
  "models": [],
  "spend": 0.0,
  "max_budget": null,
  "user_id": null,
  "team_id": null,
  "max_parallel_requests": null,
  "metadata": {},
  "tpm_limit": null,
  "rpm_limit": null,
  "budget_duration": null,
  "allowed_cache_controls": [],
  "soft_budget": null,
  "key_alias": "example-worker",
  "duration": null,
  "aliases": {},
  "config": {},
  "permissions": {},
  "model_max_budget": {},
  "send_invite_email": null,
  "key": "sk-REMOVED",
  "key_name": "sk-...VED",
  "expires": null,
  "token_id": "REMOVED"
}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
