### ISSUE TITLE
[Bug]: `anthropic/` causes cost calc error

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4972]
### What happened?

This is with using Anthropic directly (*not* via Bedrock or Vertex AI).

<img width="653" alt="image" src="https://github.com/user-attachments/assets/8c8e6cff-98cc-45bf-809e-c011a8123ded">

Running LiteLLM v1.42.5.

### Relevant log output

```shell
See the screenshot
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
This is happening with both `claude-3-haiku-20240307` and `claude-3-5-sonnet-20240620` for sure. Have not looked at other models.

**Comment by ghost** [comment]
@Manouchehri 

1. what do your server logs show? 
2. do you see a response cost in the response headers when you make a curl request to the proxy?

**Comment by ghost** [comment]
This works for me 
<img width="1209" alt="Screenshot 2024-07-30 at 3 04 31 PM" src="https://github.com/user-attachments/assets/d95469a2-4b03-4a0d-acf9-c1450b50f652">

**Comment by ghost** [comment]
Just tested the langfuse logging - it worked for me as well. Closing for now as unable to repro, feel free to reopen / bump me if you have a reproducible example for this @Manouchehri 

Trace - https://us.cloud.langfuse.com/project/clwzdwzvp0007uffstxzg8u0h/traces/5a84124f-e497-40dd-9330-b270dba84490?observation=time-15-06-56-159615_chatcmpl-68203351-8c14-4e4a-9934-30bce17dde53

<img width="425" alt="Screenshot 2024-07-30 at 3 08 16 PM" src="https://github.com/user-attachments/assets/c48466f2-70a2-48c6-aee6-b61600eb341f">

**Comment by Manouchehri** [comment]
```sh
curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "claude-3-haiku-20240307",
    "messages": [
      {
        "role": "user",
        "content": "Hi there!"
      }
    ]
  }'
```


```
> Host: litellm.example.com
> User-Agent: curl/8.6.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer sk-REMOVED
> Content-Length: 140
>
< HTTP/2 200
< date: Wed, 31 Jul 2024 00:04:56 GMT
< content-type: application/json
< content-length: 394
< cf-ray: 8ab95573680fda57-MIA
< cf-cache-status: MISS
< cache-control: private, max-age=31536000, stale-while-revalidate=31536000, stale-if-error=31536000, s-maxage=0
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< alt-svc: h3=":443"; ma=86400
< x-cloud-trace-context: 891ba5d9c34934a56e78f6951d5687d7;o=1
< x-content-type-options: nosniff
< x-litellm-call-id: f9bc59d4-f958-4c4e-9782-61172619501c
< x-litellm-key-rpm-limit: None
< x-litellm-key-tpm-limit: None
< x-litellm-model-api-base: https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/anthropic/v1/messages
< x-litellm-model-id: REMOVED
< x-litellm-version: 1.42.5
< x-frame-options: DENY
< cross-origin-resource-policy: same-origin
< cross-origin-opener-policy: same-origin
< cross-origin-embedder-policy: require-corp
< x-robots-tag: noindex, notranslate, noarchive, noimageindex, nosnippet, nositelinkssearchbox, nocache, nopagereadaloud
< origin-agent-cluster: ?1
< server: cloudflare
<

{"id":"chatcmpl-50ba1bae-c6a7-42cf-9488-2e3952111a9f","choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I assist you today?","role":"assistant","tool_calls":[],"function_call":null}}],"created":1722384296,"model":"claude-3-haiku-20240307","object":"chat.completion","system_fingerprint":null,"usage":{"prompt_tokens":10,"completion_tokens":12,"total_tokens":22}}
```

The `x-litellm-response-cost` header is completely missing, presumably because the cost is incorrectly reported as 0.

**Comment by Manouchehri** [comment]
```yaml
model_list:
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      max_tokens: 4096
      api_base: https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/anthropic/v1/messages
      extra_headers: {"cf-skip-cache": "true"}
```

**Comment by ghost** [comment]
hey @Manouchehri i believe our curl's are pretty similar, yet i'm unable to repro. Can you share server logs? 

If response cost is missing, then there might be an error calculating the cost. Any logs here would be helpful.

**Comment by ghost** [comment]
can you also try **without cloudflare** to help isolate the issue

**Comment by ghost** [comment]
Tried with cloudflare gateway - i'm still not able to repro @Manouchehri 

<img width="1169" alt="Screenshot 2024-07-30 at 5 35 02 PM" src="https://github.com/user-attachments/assets/a1fa01a6-2802-4e01-a5c5-a72610aed1c6">


my config: 

```yaml
model_list:
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: claude-3-haiku-20240307
      max_tokens: 4096
      api_base: https://gateway.ai.cloudflare.com/v1/REDACTED/test/anthropic/v1/messages
      extra_headers: {"cf-skip-cache": "true"}

```
