### ISSUE TITLE
Image generation reports error litellm.NotFoundError

### ISSUE THREAD

**Issue by guleng** [BerriAI/litellm#5024]
I have an image generation model that is of the FastAPI interface type. I want to call it through Litellm, but after configuration, it cannot be used properly. Does it not support the FastAPI interface?
```
model_list:
  - model_name: image
    litellm_params:
      model: "openai/turbovisionxl.safetensors"
      api_base: http://zbe0968824ff9-7860.us-west-a.proxy.gpu.com/
      api_key: my-fake-key
    model_info:
      mode: image_generation
```
request method：
```
curl 'https://127.0.0.1:4000/v1/images/generations' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-7TKke_a-J5RFKZ8oSJF6Sg' \
--data '{
  "model": "images",
  "prompt": "A cute baby sea otter",
  "n": 1,
  "size": "1024x1024"
}'

{"error":{"message":"litellm.NotFoundError: NotFoundError: OpenAIException - Error code: 404 - {'detail': 'Not Found'}\nReceived Model Group=images\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"404"}}%
```

Error log:
```
litellm-1  | 18:14:27 - LiteLLM Proxy:ERROR: proxy_server.py:3671 - litellm.proxy.proxy_server.image_generation(): Exception occured - litellm.NotFoundError: NotFoundError: OpenAIException - Error code: 404 - {'detail': 'Not Found'}
```

Whether I add/v1 after the URL or not, the same error message will appear

Who can help me take a look at this issue? Thank you.
