### ISSUE TITLE
Pass through endpoints do not have a way to pass through original request headers

### ISSUE THREAD

**Issue by byrongrogan** [BerriAI/litellm#5060]
### What happened?

When using pass-through endpoints, all headers from the original request are replaced with the headers defined in the static pass-through configuration. It's not clear to me whether this is a bug or just a by-design limitation.

See here, the original request headers are fully replaced with the statically-defined headers: https://github.com/BerriAI/litellm/blob/107c468d05a5db484da117724a218dafd07312dd/litellm/proxy/pass_through_endpoints/pass_through_endpoints.py#L256

Ideally, users could have control over this behavior, e.g. any of the following may work:
1. An option to pass through all headers from the original request
2. A way to specify just specific headers that should be passed through and merged with other custom pre-defined headers

The current behavior limits the use cases for pass-through endpoints. For example, it prevents forwarding authentication headers or other custom, per-user headers that might be required by the target service.

**Comment by ishaan-jaff** [comment]
Something like this @byrongrogan,  where `forward_headers=True` means the request headers get forwarded ?  open to feedback on what you think the best interface would be 

```yaml
general_settings:
  master_key: sk-1234
  pass_through_endpoints:
    - path: "/v1/rerank"                                  # route you want to add to LiteLLM Proxy Server
      target: "https://api.cohere.com/v1/rerank"          # URL this route should forward requests to
      headers:                                            # headers to forward to this URL
        Authorization: "bearer os.environ/COHERE_API_KEY" # (Optional) Auth Header to forward to your Endpoint
        content-type: application/json                    # (Optional) Extra Headers to pass to this endpoint 
        accept: application/json
      forward_headers: True
```
