### ISSUE TITLE
[Feature] Add gpt-4o-mini pricing for Azure OpenAI

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5072]
Please checkout Azure GPT-4o-mini ;) https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/openai-s-gpt-4o-mini-now-available-in-api-with-vision/ba-p/4200640

_Originally posted by @seonghobae in https://github.com/BerriAI/litellm/issues/4922#issuecomment-2262822864_

**Comment by ghost** [comment]
this is live already @Manouchehri https://github.com/BerriAI/litellm/blob/2a95484a83a2d16ae3180b5459ecd204c537b9ae/model_prices_and_context_window.json#L499

**Comment by ghost** [comment]
any reason you thought it wasn't supported yet? 

asking to improve here

**Comment by Manouchehri** [comment]
I was expecting `azure/gpt-4o-mini-2024-07-18`, not `azure/gpt-4o-mini`. =)

**Comment by Manouchehri** [comment]
@krrishdholakia Am I making an obvious mistake here...? It seems like the cost is always zero, even after changing to `azure/gpt-4o-mini`.

<img width="338" alt="image" src="https://github.com/user-attachments/assets/2c70f31d-72a0-4000-8c06-4edab6720ce2">

**Comment by Manouchehri** [comment]
```yaml
model_list:
  - model_name: gpt-4o-mini-2024-07-18
    litellm_params:
      model: azure/gpt-4o-mini-2024-07-18
      api_version: "2024-06-01"
      azure_ad_token: "oidc/google/https://example.invalid"
      additional_drop_params: ["user"]
      api_base: "https://gateway.ai.cloudflare.com/v1/REMOVED/litellm/azure-openai/REMOVED"
      seed: 1337
      max_tokens: 4096
      logprobs: True
      top_logprobs: 5
      frequency_penalty: 0
      presence_penalty: 0
      n: 1
      temperature: 1
      top_p: 1
      extra_headers: {"cf-skip-cache": "true"}
    model_info:
      base_model: azure/gpt-4o-mini
```

**Comment by ghost** [comment]
Nope. Works just fine. Tested on braintrust + langfuse + checked the response cost on curl 

If you're seeing issues with cost calc - i'd recommend bumping version, and if the issue persists create a new issue w/ complete server logs so we can debug.

<img width="474" alt="Screenshot 2024-08-06 at 4 23 32 PM" src="https://github.com/user-attachments/assets/32c0738a-bdce-44c7-91a5-fff8e8077959">

<img width="555" alt="Screenshot 2024-08-06 at 4 23 36 PM" src="https://github.com/user-attachments/assets/40a57141-5e5b-4acf-9b2e-bddeceb32f90">


<img width="917" alt="Screenshot 2024-08-06 at 4 24 06 PM" src="https://github.com/user-attachments/assets/0c940ce5-d907-469b-8910-28b4de79a7ac">

**Comment by ghost** [comment]
Here's my config for repro - 

```yaml
model_list:
  - model_name: "gpt-4o-mini"
    litellm_params:
      model: "azure/my-gpt-4o-mini"
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
    model_info:
      base_model: azure/gpt-4o-mini

litellm_settings:
  success_callback: ["langfuse"]
  
```
