### ISSUE TITLE
[Bug]: virtual key auth error user doesn't exists

### ISSUE THREAD

**Issue by umuthopeyildirim** [BerriAI/litellm#5111]
### What happened?

We use Virtual Keys assigned to a Team not users. After the last auto update this bug occurred. We rolled back to the previous version for now. 

### Relevant log output

```shell
{
    "error": {
        "message": "Authentication Error, User doesn't exist in db. 'user_id'=admin. Create user via `/user/new` call.",
        "type": "auth_error",
        "param": "None",
        "code": "401"
    }
}
```

**Comment by madpin** [comment]
I'm getting the same error.

**Comment by johnson-liang-appier** [comment]
This issue draws my attention because we are also evaluating LiteLLM's team and virtual key capabilities. However, I am not able to reproduce this issue. Mind providing more information? @umuthopeyildirim @madpin 

## My reproduction setup
- Use the docker-compose file https://github.com/BerriAI/litellm/blob/main/docker-compose.yml but with some modifications (attached below)
- Use config:
    ```yaml
    model_list:
      - model_name: "*"
        litellm_params:
        model: "*"
    ```
- `.env`: populate `LITELLM_MASTER_KEY` and `OPENAI_API_KEY`
- `docker-compose up` to spin up the fresh DB and LiteLLM proxy

## My reproduction steps
```bash
# 1. Create team
curl -XPOST 'http://localhost:4000/team/new' \
    --header 'Content-Type: application/json' \
    -H 'Authorization: Bearer <Master key>' \
    --data '{
        "team_alias": "Test team"
    }'

# 2. Create team-based virtual key
curl -XPOST 'http://localhost:4000/key/generate' \
    --header 'Content-Type: application/json' \
    -H 'Authorization: Bearer <Master key>' -i \
    --data '{
    "team_id": "<Team ID from last call>",
    "key_alias": "Team key via API"
}'

# 3. Test proxy completion endpoints
curl --location 'http://localhost:4000/chat/completions' \
    --header 'Content-Type: application/json' \
    -H 'Authorization: Bearer <Team key from above>' -i \
    --data '{
    "model": "gpt-4o",
    "messages": [
        {
        "role": "user",
        "content": "what llm are you"
        }
    ]
}'
```

Test result: LiteLLM can proxy my completion request to OpenAI and gets the response.
Did not encounter the Authentication Error.

<details>
<summary>My edited docker-compose file</summary>

```yaml
version: "3.11"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    # image: ghcr.io/berriai/litellm:main-latest # build from source instead of images
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml"]
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
        DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
        # STORE_MODEL_IN_DB: "True" # just use model in config
    env_file:
      - .env # Load local .env file

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
```
</details>
