### ISSUE TITLE
[Bug]: Helm Chart is using redis master even if redis replication is activated

### ISSUE THREAD

**Issue by aschaber1** [BerriAI/litellm#5122]
### What happened?

I'm using the helm chart with enabled redis in replication mode.
Redis deployment creates three services:
- `litellm-redis-headless` (contains all master + replicas)
- `litellm-redis-master` (contains only the mater)
- `litellm-redis-replicas` (contains only the replicas)
Though instead of using either one that also include the replicas. The helm chart supplies the deployment of litellm with `REDIS_HOST=litellm-redis-master`.

This is the code where the variable is set. I'm not familiar enough with redis, to know if it's feasible to just switch to `-headless`.

- https://github.com/BerriAI/litellm/blob/main/deploy/charts/litellm-helm/templates/deployment.yaml#L146-L147
- https://github.com/bitnami/charts/tree/main/bitnami/redis
- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/headless-svc.yaml

here's my config:
```yaml
values.yaml:

proxy_config:
  litellm_settings:
    cache: true
    cache_params:
      type: redis
      ttl: 3600

redis:
  enabled: true
  architecture: replication
  replica:
    replicaCount: 2

```

### Relevant log output

```shell
# env | grep REDIS_HOST
REDIS_HOST=litellm-redis-master
```

### Twitter / LinkedIn details

@aschaber1
