### ISSUE TITLE
[Bug]: Proxy config docs for vLLM are slightly wrong

### ISSUE THREAD

**Issue by fozziethebeat** [BerriAI/litellm#5183]
### What happened?

When using the proxy server connected to a vllm server, the suggested configs aren't totally complete:

```
  - model_name: vllm-models
    litellm_params:
      model: openai/facebook/opt-125m # the `openai/` prefix tells litellm it's openai compatible
      api_base: http://0.0.0.0:4000
      rpm: 1440
    model_info: 
      version: 2
```

this should in fact be

```
  - model_name: vllm-models
    litellm_params:
      model: openai/facebook/opt-125m # the `openai/` prefix tells litellm it's openai compatible
      api_base: http://0.0.0.0:4000/v1
      api_key: something
      rpm: 1440
    model_info: 
      version: 2
```

### Relevant log output

```shell
When running with the original config, two problems are triggered:
  * The `openai` prefix expects an API key to be set.  Hence the `api_key` setting
  * The proxy sends requests to `http://0.0.0.0:4000/completions` or `http:0.0.0.0:4000/chat/completions`.  Neither of these actually exist on vLLM and hence the `v1` suffix.
```

### Twitter / LinkedIn details

@fozziethebeat
