### ISSUE TITLE
[Bug]: Cannot Integrate Locally Hosted VLLM

### ISSUE THREAD

**Issue by kunalchamoli** [BerriAI/litellm#5316]
### What happened?

I am trying to integrate a locally hosted VLLM server to LiteLLM. The curl request(which works alright) that i am using to hit the vllm server directly is:
```
curl --location 'http://0.0.0.0:8080/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer token-abc123' \
--data '{
    "model": "/data/Llama-3-8B-Instruct",
    "messages": [{
        "role": "user",
        "content": "My name is Kunal"
    }],
    "stream": "False",
    "max_tokens": 30,
    "temperature": 0.9,
    "repetition_penalty": 1.3,
    "use_beam_search": "False",
    "top_p": 0.9,
    "top_k": 50,
    "length_penalty": 1,
    "n": 1,
    "early_stopping": "False",
    "stop": ["<|start_header_id|>", "<|end_header_id|>", "<|eot_id|>", "<|reserved_special_token|>"]
}'
```

For integrating into LiteLLM the config that i created was (I have added double "//" because model_name starts with a "/" ) :
```
  - model_name: vllm/llama3-8b-instruct
    litellm_params:
      model: openai//data/Llama-3-8B-Instruct
      api_base: http://0.0.0.0:8080/v1
      api_key: token-abc123
```

Now when calling via LiteLLM
```
curl --location 'http://localhost:4000/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer litellm-master-key' \
--data '{
    "model": "vllm/llama3-8b-instruct",
    "messages": [{
        "role": "user",
        "content": "My name is Kunal"
    }]
}'
```
I get the following error:
```
{
    "error": {
        "message": "litellm.Timeout: APITimeoutError - Request timed out. \nerror_str: Request timed out.\nReceived Model Group=vllm/llama3-8b-instruct\nAvailable Model Group Fallbacks=None",
        "type": null,
        "param": null,
        "code": "408"
    }
}
```

**Comment by ghost** [comment]
hey @kunalchamoli our default timeout is 10mins, is your call taking longer than that? 

If so, you can control this by setting timeout on the config 

```yaml
  - model_name: vllm/llama3-8b-instruct
    litellm_params:
      model: openai//data/Llama-3-8B-Instruct
      api_base: http://0.0.0.0:8080/v1
      api_key: token-abc123
      timeout: 6000 # timeout in seconds
```



to confirm the call is being made, run the proxy with `--detailed_debug`, and you should see the raw request in console logs
