### ISSUE TITLE
[Feature]: Allow more than 1 Azure OpenAI endpoints for batch mode models

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#5396]
### The Feature

`proxy-config.yaml` would have a section like this:
```
batch_model_list:
  - model_name: gpt-4-turbo-2024-04-09-batch
    litellm_params:
      model: azure/gpt-4-turbo-2024-04-09-batch-us-e
      api_base: os.environ/AOAI_BASE_US_E
      api_key: os.environ/AOAI_KEY_US_E
    model_info:
      mode: batch
  - model_name: gpt-4-turbo-2024-04-09-batch
    litellm_params:
      model: azure/gpt-4-turbo-2024-04-09-batch-us-w
      api_base: os.environ/AOAI_BASE_US_W
      api_key: os.environ/AOAI_KEY_US_W
    model_info:
      mode: batch
  - model_name: gpt-4o-batch
    litellm_params:
      model: azure/gpt-4o-batch-us-w3
      api_base: os.environ/AOAI_BASE_US_W3
      api_key: os.environ/AOAI_KEY_US_W3
    model_info:
      mode: batch
  - model_name: gpt-4o-batch
    litellm_params:
      model: azure/gpt-4o-batch-ca-w
      api_base: os.environ/AOAI_BASE_CA_W
      api_key: os.environ/AOAI_KEY_CA_W
    model_info:
      mode: batch
```
You should not need to specify the `files_settings` section in `proxy-config.yaml` for batch api feature.

When client makes the request to upload the batch job input file, the proxy would parse the model group name from the first line of the `.jsonl` so that proxy can figure out which Azure endpoint to use to upload this file:
```
curl http://localhost:4000/azure/v1/files \
    -H "Authorization: Bearer sk-1234" \
    -F purpose="batch" \
    -F file="@mydata.jsonl"
```
Assuming the model group name is `gpt-4o-batch`, proxy will pick/load-balance between the 2 possible Azure endpoints where `gpt-4o-batch` is available: either `AOAI_BASE_US_W3` or `AOAI_BASE_CA_W`. Proxy should persist the endpoint it picked for this file as a tuple in the database `(input_file_id, batch_id, azure_endpoint)`
Proxy will also need to modify the `.jsonl` to replace the `model` field with the actual azure deployment_name so e.g., if the proxy picked `AOAI_BASE_US_W3` in this example, then it'd replace `"model": "gpt-4o-batch"` in each line of the input `.jsonl` file with `"model": "gpt-4o-batch-us-w3"` so that Azure understands which deployment to use to serve that line request.

Next, request to fetch status of the file upload will be:
```
curl https://localhost:4000/azure/v1/files/file-id123 \
  -H "Authorization: Bearer sk-1234"
```
proxy will use the `file-id123` passed on this request to lookup which `azure_endpoint` to use to pass along this request, and get the file upload status.

Next, request to create a batch:
```
curl http://localhost:4000/azure/v1/batches \
  -H "Authorization: Bearer sk-1234" \
  -H "Content-Type: application/json" \
  -d '{
    "input_file_id": "file-id123",
    "endpoint": "/chat/completions",
    "completion_window": "24h"
  }'
```
Augment the entry in the database with the `batch_id` returned in the response to the above "create batch" request, so that subsequent calls to retrieve batch job status and batch job output that pass the `batch_id` on the request can be used by proxy to look up appropriate `azure_endpoint` to pass the request to.

It'd be fine to clean up the entry in database after a week or so of the batch request, whatever's reasonable.
For more context, see the conversation here: https://github.com/BerriAI/litellm/issues/5279#issuecomment-2308423442

### Motivation, pitch

The way https://docs.litellm.ai/docs/batches#azure-batches-api is set up currently, it points to a single Azure endpoint/api-base for all batch models. What if I wanted to add another or even a few more Azure endpoints where I have different batch models. I can imagine in future Azure might release certain batch models in certain regions needing us to use more than 1 endpoints to get coverage.
