### ISSUE TITLE
[Feature]: Support setting 'weight' for weighted-pick loadbalancing 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5410]
### The Feature

currently it uses rpm and tpm to calculate weight, maybe we can have a declarative way to add weight

### Motivation, pitch

what I need is that provider-1 load 1/3 traffic ,  and provider-2 load 2/3 traffic
like this:
```yaml
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: key1
      api_base: provider-1
      weight: 1

  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: key2
      api_base: provider-2
      weight: 2
```

### Twitter / LinkedIn details

@arvinxx
