### ISSUE TITLE
[Bug]: Langfuse callback only works with environmental variables defined from the command line

### ISSUE THREAD

**Issue by EthanZoneCoding** [BerriAI/litellm#5487]
### What happened?

If I set the variables in the config, I get an error
```
litellm_settings:
  success_callback: ["langfuse"]

model_list:
  - model_name: ollama_chat/llama3.1
    litellm_params:
      model: ollama_chat/llama3.1

environment_variables:
  LANGFUSE_PUBLIC_KEY: pk-whateverthecringe
  LANGFUSE_SECRET_KEY: sk-whateverthecringe
  LANGFUSE_HOST: http://cloud.langfuse.com
```

However, when I run
```
set LANGFUSE_PUBLIC_KEY=pk-whateverthecringe
set LANGFUSE_SECRET_KEY=sk-whateverthecringe
set LANGFUSE_HOST=https://cloud.langfuse.com
```
It works just fine (assuming I remove the `environment_variables` section from the config

### Relevant log output

```shell
httpx.ConnectError: [Errno 11001] getaddrinfo failed
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/ethan-porcaro/

**Comment by ghost** [comment]
@EthanZoneCoding the error has to do with your langfuse_host value 

in the yaml you're setting:

>   LANGFUSE_HOST: http://cloud.langfuse.com

Note: `http://`

vs. in env you set:

> LANGFUSE_HOST=https://cloud.langfuse.com

Note: `https://`

**Comment by ethanporcaro** [comment]
Oops, I think I missed that when I rewrote it for the issue without including the keys. I believe it caused the same problem, let me check

**Comment by ethanporcaro** [comment]
Yep, same issue

**Comment by ghost** [comment]
unable to repro. this works as expected @EthanZoneCoding 

Just tested with this config: 
```yaml
model_list:
  - model_name: "gpt-3.5-turbo"
    litellm_params:
      model: "gpt-3.5-turbo"


litellm_settings:
  success_callback: ["langfuse"]
  
environment_variables:
  LANGFUSE_SECRET_KEY: "sk-lf-..."
  LANGFUSE_PUBLIC_KEY: "pk-lf-..."
  LANGFUSE_HOST: "https://us.cloud.langfuse.com"
```

**Comment by ghost** [comment]
Not sure on next best steps open to suggestions

**Comment by deepio-oc** [comment]
I am facing the same issue with latest litellm package. my config.yaml

```
environment_variables:
  LANGFUSE_HOST: "http://langfuse-web:3000"
  LANGFUSE_PUBLIC_KEY: lf_pk_x1234567890
  LANGFUSE_SECRET_KEY: lf_sk_x1234567890

litellm_settings:
  success_callback: ["langfuse"]
```

I am getting with above config.
```
httpx.ConnectError: [Errno -2] Name or service not known
```

When I added additional print lines, I can see it is trying to connect to "http://None/..."

when I export above variables on command line and rerun, It is able to connect to langfuse server.
