### ISSUE TITLE
[Feature]: FIM endpoint for Mistral

### ISSUE THREAD

**Issue by azdolinski** [BerriAI/litellm#5502]
### The Feature

there is now: "text-completion-<b>codestral</b>" prefix to use fim/completions 
but there is no way to use FIM endpoint: https://api.mistral.ai/v1/fim/completions

proposal: add <b>"text-completion-mistral"</b> which will point to https://api.mistral.ai/v1/fim/completions

Mistra FIM docs: [Link](https://docs.mistral.ai/capabilities/code_generation/#instruct-endpoint)

### Motivation, pitch

use new models from mistral for fim tab autocomplete

Mistral models: [Link](https://docs.mistral.ai/getting-started/models/#overview)

### Twitter / LinkedIn details

https://www.linkedin.com/in/artur-zdolinski/

**Comment by nomarek** [comment]
Are there any plans for implementing this?

**Comment by azdolinski** [comment]
@nomarek 
my workaround:

```yaml
  - model_name: text-completion-mistral-open-codestral-mamba
    litellm_params:
        model: text-completion-codestral/open-codestral-mamba
        api_base: https://api.mistral.ai/v1/fim/completions
        api_key: os.environ/MISTRAL_API_KEY

  - model_name: text-completion-mistral-codestral-latest
    litellm_params:
        model: text-completion-codestral/codestral-latest
        api_base: https://api.mistral.ai/v1/fim/completions
        api_key: os.environ/MISTRAL_API_KEY
```
