### ISSUE TITLE
[Bug]: Fallback not working for anthropic streaming

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5512]
### What happened?

When Anthropic returns `Overloaded`, it seems like my fallbacks aren't used.

`"mock_testing_fallbacks": true` works.. I already had trust issues with that flag, and this confirms it more. =P IIRC Azure OpenAI had the same/similar issue with failovers in LiteLLM.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
This is what Anthropic returns:

```json
{
  "type": "error",
  "error": {
    "type": "overloaded_error",
    "message": "Overloaded"
  }
}
```

**Comment by ghost** [comment]
@Manouchehri how did you set up your fallbacks? 

This ticket doesn't have clear steps to reproduce the issue.

**Comment by Manouchehri** [comment]
https://discord.com/channels/@me/1177306749770928249/1263562976905138217

Basically just change `azure/gpt-4-turbo-2024-04-09` to `anthropic/claude-3-5-sonnet-20240620`, and make the test url return the message I put in https://github.com/BerriAI/litellm/issues/5512#issuecomment-2329607123.

The fallback code is really hard to read; I can't tell if this is going to do a retry or not.

https://github.com/BerriAI/litellm/blob/e32d4a15b2eda2d7cd1a3a38966056d03dc2c431/litellm/utils.py#L6670-L6679

**Comment by ghost** [comment]
I'm confused - what fallbacks did you setup?

**Comment by ghost** [comment]
so it looks like this was the curl: 

```bash
curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "anthropic/claude-3-5-sonnet-20240620",
    "max_tokens": 4,
    "seed": 124222222,
    "stream": true,
    "temperature": 1.9,
    "messages": [
      {
        "role": "user",
        "content": "Think of 10 random colors. Then combine them in your head. Then tell me what color you have. You must only say one word."
      }
    ]
  }'
```

and this was the model_list:

```yaml
model_list:
  - model_name: anthropic/claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
```

but then where was `anthropic/*` set?

**Comment by Manouchehri** [comment]
> but then where was anthropic/* set?

Nowhere. I meant that the bug probably applies to all models on anthropic.

**Comment by ghost** [comment]
Can you share what your fallbacks looked like so i can repro the issue (ideally share the config.yaml)

**Comment by ghost** [comment]
> The fallback code is really hard to read; I can't tell if this is going to do a retry or not.

The fallback logic is here - https://github.com/BerriAI/litellm/blob/08976370a320b07fe2e409ba19625d791a804d6b/litellm/router.py#L2865

**Comment by ghost** [comment]
unable to repro this error. @Manouchehri what did your client-side exception say? it should have the debug details on why a fallback didn't happen.

**Comment by ghost** [comment]
Steps I ran to test this: 

1. Setup fake Anthropic fastapi server:

Raise the same error code as anthropic's overloaded error - https://docs.anthropic.com/en/api/errors

```python
@app.post("/messages")
@app.post("/v1/messages")
async def anthropic_completion(request: Request):
    raise HTTPException(status_code=529, detail="Overloaded Error!", headers={"retry-after": 30})

```

2. Setup config.yaml with fake anthropic server + fallbacks 

```yaml
model_list:
  - model_name: "anthropic/claude-3-5-sonnet-20240620"
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_base: http://0.0.0.0:9000 
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo

litellm_settings:
  fallbacks: [{"anthropic/claude-3-5-sonnet-20240620": ["gpt-3.5-turbo"]}]
```

3. Test with curl

```bash
curl -L -X POST 'http://0.0.0.0:4000/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-d '{
    "model": "anthropic/claude-3-5-sonnet-20240620",
    "messages": [
      {
        "role": "user",
        "content": "Think of 10 random colors. Then combine them in your head. Then tell me what color you have. You must only say one word."
      }
    ]
}'
```
