### ISSUE TITLE
[Bug]: k8s dual stack IPv4/6 helm chart v0.1.413 and later readiness probe

### ISSUE THREAD

**Issue by qdrddr** [BerriAI/litellm#5517]
### What happened?

When I was using Helm Chart v0.1.412, everything was good. But once I tried to update to any version after that, i.e., starting with 0.1.413 but also with 0.1.427, my pods no longer could start correctly. Note that the old helm chart v0.1.412 works fine with the newer version of the app main-v1.44.17-stable.
I have a DualStack k8s cluster with both IPv4 & IPv6 assigned to the LiteLLM pods. While in the logs inside the container, I see it assuming only IPv6.

I believe the issue is that the pod inside can see only IPv6 while the readiness probe is trying to reach IPv4.
Getting this error on the pod:
`Startup probe failed: Get "http://10.42.7.177:4000/health/readiness": dial tcp 10.42.7.177:4000: connect: connection refused`

**I believe the helm chart and probably the LiteLLM container need a fix to be able to run properly in the DualStack k8s clusters properly.**

I have created a kustomization to patch service manifests to include DualStack like this it works with 0.1.412 but it doesn't work for the newer versions with this patch or without this patch.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

- name: litellm-helm
  repo: oci://ghcr.io/berriai
  version: 0.1.413
  releaseName: litellm-proxy

patches:
  - op: replace
    path: /spec/ipFamilies
    value:
      - IPv4
      - IPv6
  - op: replace
    path: /spec/ipFamilyPolicy
    value:
      PreferDualStack
```

### Relevant log output

logs of the pod. Note the pod is running on `http://[::]:4000` meaning it assumed only the IPv6 address. 
While the readiness probe is configured for IPv4. This mismatch probably is the root cause of the problem.

```shell
✔ Generated Prisma Client Python (v0.11.0) to ./../../prisma in 301ms

INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://[::]:4000 (Press CTRL+C to quit)
```
```


### Twitter / LinkedIn details

_No response_

**Comment by laurb9** [comment]
I believe this issue was introduced with https://github.com/BerriAI/litellm/pull/5222, reverting that change resolved the issue for me.

**Comment by ishaan-jaff** [comment]
hi @qdrddr @laurb9 sorry about the regression - hoping to have this resolved this week 

Context: this was merged because #5222 needed  IPv6 (and IPv4) support (cc @ArbitraryCritter) 

1. Do you have feedback on how we can best test our helm charts and prevent regressions like this ? @laurb9 @qdrddr 
2. @ArbitraryCritter do you know why your change caused this error. I'd love to allow IPv6 on our helm while not impacting other users

**Comment by laurb9** [comment]
Surfacing the bind address in the helm chart `values.yaml`, as the PR suggested, can cover many network configurations.

I would look upstream for guidance on IPv6 - I did a quick search and saw https://github.com/encode/uvicorn/discussions/1529#discussioncomment-10044311 which suggests two or more addresses to bind to as a possibility.

**Comment by ishaan-jaff** [comment]
got it, so the suggested fix here is to move to this correct ? 

```
uvicorn.run(app, host=["::", "0.0.0.0"], port=4000)
```

**Comment by ArbitraryCritter** [comment]
@ishaan-jaff 

Hmmm...

By default the Linux kernel will bind on all interfaces with all ipv4 and ipv6 addresses if it's given "::". This behavior can be changed by setting "net.ipv6.bindv6only" to 1 (kernel setting). If that is set, one needs to specify the ipv4 socket specifically.

I'm a bit surprised kubernetes deployments like that exist, but I suppose the world is a big place and I was just being naive. In that case specifying both "::" and "0.0.0.0" is the right move.

Alternatively we could introduce an option to specify the host to listen to, as I also suggested in the PR.

**Comment by ArbitraryCritter** [comment]
Looking at the documentation here:
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server

Specifically this part which is also mentioned in https://github.com/encode/uvicorn/discussions/1529#discussioncomment-10044311

> If host is an empty string or None, all interfaces are assumed and a list of multiple sockets will be returned (most likely one for IPv4 and another one for IPv6).

So it sounds like the correct solution is:
> uvicorn.run(app, host=None, port=4000)

This would be a problem though:
> uvicorn.run(app, host=["::", "0.0.0.0"], port=4000)

It will work in @laurb9 case, but it will fail on any system that uses ipv6 mapped ipv4, like OSX or most linux distributions. (Linux with: net.ipv6.bindv6only: 1)
The problem is that it will try to listen on ipv4 two times, which will fail.

You can check your own system using this test code:

```
import uvicorn

async def app(scope, receive, send):
    assert scope['type'] == 'http'

    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })

if __name__ == "__main__":
    uvicorn.run(app, host=["::", "0.0.0.0"], port=4000)
```

**Comment by ArbitraryCritter** [comment]
Hmmm, actually, after testing on a few different systems it looks like this works the most consistently...
> uvicorn.run(app, host=["::", "0.0.0.0"], port=4000)

There are a lot of cases here, and I haven't tested all of them, but it does look like the best bet.

**Comment by menardorama** [comment]
Made a PR, HOST value should/must be always configurable

**Comment by qdrddr** [comment]
a temporary workaround that works for me using kustomization patch:



```yaml
# kustomizations/kustomization.yaml
# `kustomization.yaml` file in the `kustomizations` folder content:
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

- name: litellm-helm
  repo: oci://ghcr.io/berriai
  version: 0.1.429
  releaseName: litellm-proxy

patches:
  - op: replace
    path: /spec/ipFamilies
    value:
      - IPv4
      - IPv6
  - op: replace
    path: /spec/ipFamilyPolicy
    value:
      PreferDualStack     
  - op: replace
    path: /spec/template/spec/containers/0/env/0
    value:
      name: HOST
      value: 0.0.0.0
```
```shell
kustomize build ./kustomizations --enable-helm > ./kustomizations/litellm.kustimized.yaml
kubectl apply -f ./kustomizations/litellm.kustimized.yaml
```
