### ISSUE TITLE
[Bug]: Missing `hidden_params` on some Azure OpenAI models?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5546]
### What happened?

For some reason, when I use `gpt-4o-2024-08-06` (global standard), `hidden_params` is missing from my Langfuse trace logs. Confusingly, `hidden_params` works fine with `gpt-4o-mini-2024-07-18` (global standard). See my config below:

```yaml
model_list:
  - model_name: gpt-4o-mini-2024-07-18
    litellm_params:
      model: azure/global_gpt-4o-mini-2024-07-18
      api_version: "2024-08-01-preview"
      azure_ad_token: "oidc/google/https://example.com"
      additional_drop_params: ["user"]
      api_base: "https://gateway.ai.cloudflare.com/v1/0399b10e77ac6668c80404a5ff49eb37/litellm-test/azure-openai/REMOVED_RESOURCE_NAME"
      seed: 1337
      max_tokens: 16384
      logprobs: True
      top_logprobs: 20
      frequency_penalty: 0
      presence_penalty: 0
      n: 1
      temperature: 1
      top_p: 1
    model_info:
      base_model: azure/global-standard/gpt-4o-mini

  - model_name: gpt-4o-2024-08-06
    litellm_params:
      model: azure/global_gpt-4o-2024-08-06
      api_version: "2024-08-01-preview"
      azure_ad_token: "oidc/google/https://example.com"
      additional_drop_params: ["user"]
      api_base: "https://gateway.ai.cloudflare.com/v1/0399b10e77ac6668c80404a5ff49eb37/litellm-test/azure-openai/REMOVED_RESOURCE_NAME"
      seed: 1337
      max_tokens: 16384
      logprobs: True
      top_logprobs: 20
      frequency_penalty: 0
      presence_penalty: 0
      n: 1
      temperature: 1
      top_p: 1
    model_info:
      base_model: azure/global-standard/gpt-4o-2024-08-06
```

I looked in LiteLLM's code and don't understand why these two would be treated differently.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
Bump on this? I had an unusual temp performance issue today that I was unable to troubleshoot after the fact because I had no way of correlating Langfuse entries to Azure OpenAI's diagnostic logs. =/

**Comment by ghost** [comment]
checking

**Comment by ghost** [comment]
Unable to repro @Manouchehri - https://us.cloud.langfuse.com/project/clwzdwzvp0007uffstxzg8u0h/traces/9e767658-e860-4c32-ac99-f598bd6bd47c?observation=time-16-37-31-581871_chatcmpl-AEMrkJ3rZI3xGC4OyvANRHJNbz0tM

<img width="820" alt="Screenshot 2024-10-03 at 4 38 19 PM" src="https://github.com/user-attachments/assets/253aed9c-faf6-4fde-812b-29bdc6549d05">

## Config

```yaml
model_list:
  - model_name: gpt-4o-2024-08-06
    litellm_params:
      model: azure/gpt-4o
      api_version: "2024-08-01-preview"
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
      additional_drop_params: ["user"]
      seed: 1337
      max_tokens: 16384
      logprobs: True
      top_logprobs: 20
      frequency_penalty: 0
      presence_penalty: 0
      n: 1
      temperature: 1
      top_p: 1
    model_info:
      base_model: azure/global-standard/gpt-4o-2024-08-06

litellm_settings:
  success_callback: ["langfuse"]
```

**Comment by ghost** [comment]
can you share a log.txt of a call being made to your model which doesn't emit hidden params? 

It would debug what might be causing this

**Comment by Manouchehri** [comment]
```yaml
model_list:
  - model_name: gpt-4o-2024-08-06
    litellm_params:
      model: azure/global_gpt-4o-2024-08-06
      api_version: "2024-09-01-preview"
      azure_ad_token: "oidc/google/https://example.com"
      additional_drop_params: ["user"]
      api_base: "https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/azure-openai/REMOVED"
      seed: 1337
      max_tokens: 16384
      logprobs: True
      top_logprobs: 20
      frequency_penalty: 0
      presence_penalty: 0
      n: 1
      temperature: 1
      top_p: 1
      cooldown_time: 600
    model_info:
      base_model: azure/global-standard/gpt-4o-2024-08-06
```

Langfuse metadata:

```json
{
    "team_id": "librechat",
    "api_base": "https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/azure-openai/REMOVED/global_gpt-4o-2024-08-06/",
    "cache_hit": false,
    "deployment": "azure/global_gpt-4o-2024-08-06",
    "model_info": {
        "id": "REMOVED",
        "db_model": false,
        "base_model": "azure/global-standard/gpt-4o-2024-08-06"
    },
    "model_group": "gpt-4o-2024-08-06",
    "user_api_key": "REMOVED",
    "model_group_size": 13,
    "requester_metadata": {},
    "user_api_key_alias": "librechat",
    "user_api_key_spend": 15942.298433675,
    "litellm_api_version": "1.48.11",
    "requester_ip_address": "",
    "user_api_key_team_id": "librechat",
    "user_api_key_user_id": "REMOVED",
    "litellm_response_cost": 0.0109225,
    "user_api_key_metadata": {}
}
```
