### ISSUE TITLE
[Bug]: Model prices and token info is not coming thru

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#5549]
### What happened?

My `proxy-config.yaml` has:
```
model_list:
  - model_name: gpt-35-turbo-0125-id1
    litellm_params:
      model: azure/gpt35-turbo-0125-east
      api_base: https://xyz-east.openai.azure.com
      api_key: os.environ/AOAI_KEY_US_E_1
    model_info:
      mode: chat
```

This is the response I get from the `GET /model/info` request:
```
    {
      "model_name": "gpt-35-turbo-0125-id1",
      "litellm_params": {
        "api_base": "https://xyz-east.openai.azure.com",
        "model": "azure/gpt35-turbo-0125-east"
      },
      "model_info": {
        "id": "10080240326d6007e59b01a7634532rdd0374000f9a35aec4adcae2d3a",
        "db_model": false,
        "key": "azure/gpt35-turbo-0125-east",
        "max_tokens": null,
        "max_input_tokens": null,
        "max_output_tokens": null,
        "input_cost_per_token": 0,
        "input_cost_per_character": null,
        "input_cost_per_token_above_128k_tokens": null,
        "output_cost_per_token": 0,
        "output_cost_per_character": null,
        "output_cost_per_token_above_128k_tokens": null,
        "output_cost_per_character_above_128k_tokens": null,
        "output_vector_size": null,
        "litellm_provider": "azure",
        "mode": "chat",
        "supported_openai_params": [
          "temperature",
          "n",
          "stream",
          "stop",
          "max_tokens",
          "tools",
          "tool_choice",
          "presence_penalty",
          "frequency_penalty",
          "logit_bias",
          "user",
          "function_call",
          "functions",
          "tools",
          "tool_choice",
          "top_p",
          "logprobs",
          "top_logprobs",
          "response_format",
          "seed",
          "extra_headers"
        ],
        "supports_system_messages": null,
        "supports_response_schema": null,
        "supports_vision": false,
        "supports_function_calling": false,
        "supports_assistant_prefill": false
      }
    }
```
All model info is `null`, but I was expecting the model info to be populated correctly since litellm already knows the specs of `gpt-35-turbo-0125` as listed in [model_prices_and_context_window.json#L687](https://github.com/BerriAI/litellm/blob/7ced9c8c0e3de866d20602c8d85056df7a76d61c/model_prices_and_context_window.json#L687).

**Comment by taralika** [comment]
I think the issue is that you're doing an exact match of the `model` in `model_list` with the `key` in [model_prices_and_context_window.json](https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json)?

**Comment by taralika** [comment]
If there is way to set the canonical name of the model in the `proxy-config.yaml` then this could be fixed, e.g.,
```
model_list:
  - model_name: gpt-35-turbo-0125-id1
    litellm_params:
      model: azure/gpt35-turbo-0125-east
      api_base: https://xyz-east.openai.azure.com
      api_key: os.environ/AOAI_KEY_US_E_1
      canonical_name: azure/gpt-35-turbo-0125
    model_info:
      mode: chat
```
And in your search, if you find `canonical_name` you should use it instead of the `model` name.
