### ISSUE TITLE
[Bug]: Order of team settings seems to matter...

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5564]
### What happened?

So this config works fine:

```yaml
litellm_settings:
  telemetry: False
  drop_params: True
  redact_messages_in_exceptions: True
  cache: True
  cache_params:
    type: s3
    s3_bucket_name: os.environ/REMOVED
    s3_region_name: os.environ/REMOVED
    s3_aws_access_key_id: os.environ/REMOVED
    s3_aws_secret_access_key: os.environ/REMOVED
    s3_endpoint_url: os.environ/REMOVED
  failure_callback: ["sentry", "langfuse"]
  request_timeout: 3600
  success_callback: ["langfuse", "s3"]
  s3_callback_params:
    s3_bucket_name: os.environ/REMOVED
    s3_region_name: os.environ/REMOVED
    s3_aws_access_key_id: os.environ/REMOVED
    s3_aws_secret_access_key: os.environ/REMOVED
    s3_endpoint_url: os.environ/REMOVED
  default_team_settings:
    - team_id: david_dev
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_DAVID
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_DAVID
    - team_id: plzwork
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_PLZWORK
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_PLZWORK
    - team_id: demo-worker
      success_callback: ["s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
```

But when I use this config, suddenly requests to the `plzwork` team seem to randomly go to whatever Langfuse project LiteLLM used last...

```yaml
litellm_settings:
  telemetry: False
  drop_params: True
  redact_messages_in_exceptions: True
  cache: True
  cache_params:
    type: s3
    s3_bucket_name: os.environ/REMOVED
    s3_region_name: os.environ/REMOVED
    s3_aws_access_key_id: os.environ/REMOVED
    s3_aws_secret_access_key: os.environ/REMOVED
    s3_endpoint_url: os.environ/REMOVED
  failure_callback: ["sentry", "langfuse"]
  request_timeout: 3600
  success_callback: ["langfuse", "s3"]
  s3_callback_params:
    s3_bucket_name: os.environ/REMOVED
    s3_region_name: os.environ/REMOVED
    s3_aws_access_key_id: os.environ/REMOVED
    s3_aws_secret_access_key: os.environ/REMOVED
    s3_endpoint_url: os.environ/REMOVED
  default_team_settings:
    - team_id: david_dev
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_DAVID
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_DAVID
    - team_id: demo-worker
      success_callback: ["s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
    - team_id: plzwork
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_PLZWORK
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_PLZWORK
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
