### ISSUE TITLE
[Feature]: JWT-Auth allow specific emails automatic access 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5605]
### The Feature

Allow users who belong to a specific email domain, automatic access - (apply litellm user defaults) 

### Motivation, pitch

improved self-serve flow

**Comment by ghost** [comment]
Potential Ideas:
- custom auth integration
- yaml configuration

**Comment by ghost** [comment]
```yaml
general_settings:
  master_key: sk-1234
  enable_jwt_auth: True
  litellm_jwtauth:
    user_email_jwt_field: "sub" # 👈 CAN BE ANY FIELD
    user_allowed_email_subdomain: "my-co.com" # allows user@my-co.com to call proxy


```
