### ISSUE TITLE
[Bug]: Assistants API not working for Azure

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#5624]
### What happened?

Docs [here](https://docs.litellm.ai/docs/assistants#sdk--proxy) seem to suggest that Assistant API will work with Azure.

Added following in `proxy-config.yaml`:
```
assistant_settings:
  custom_llm_provider: azure
  litellm_params: 
    api_key: os.environ/AZURE_API_KEY
    api_base: os.environ/AZURE_API_BASE
    api_version: os.environ/AZURE_API_VERSION
```

Then made this request to create an assistant:
```
curl "http://localhost:4000/v1/assistants" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-1234" \
  -d '{
    "instructions": "You are a personal math tutor. When asked a question, write and run Python code to answer the question.",
    "name": "Math Tutor",
    "tools": [{"type": "code_interpreter"}],
    "model": "gpt-4-turbo"
  }'
```
Response:
```
{
	"error": {
		"message": "litellm.BadRequestError: LiteLLM doesn't support azure for 'create_assistants'. Only 'openai' is supported.",
		"type": null,
		"param": null,
		"code": "400"
	}
}
```

Comes from https://github.com/BerriAI/litellm/blob/aed48e3badea1f9b9c1112e494a86b5709dbbf79/litellm/assistants/main.py#L338 - looks like Assistants support for Azure is not implemented?
