### ISSUE TITLE
[Bug]: Azure_AI not supported for rerank models

### ISSUE THREAD

**Issue by sergio-u** [BerriAI/litellm#5667]
### What happened?

Attempting to use a rerank model with Azure AI studio, eg by setting:

```yaml
  - model_name: cohere-rerank-v3-english
    litellm_params:
      model: azure_ai/cohere-rerank-v3-english
      api_base: ""
      api_key: ""
    model_info:
      mode: rerank # Not sure if this exists
``` 

Results in the following response:
```json
{
  "error": {
    "message": "Unsupported provider: azure_ai",
    "type": "None",
    "param": "None",
    "code": "500"
  }
```

I have also tried it with the cohere provider as a workaround, but then it seems the auth mechanics are different, as I was getting a 401.
