### ISSUE TITLE
[Bug]: Finetuned Gemini-Pro Models dont work with provider vertex_ai

### ISSUE THREAD

**Issue by the-wdr** [BerriAI/litellm#5678]
#### [Bug]:
Finetuned Gemini-Pro models are not functioning correctly with the `vertex_ai` provider in our setup. When attempting to make a prediction using a finetuned Gemini-Pro model, the following error is returned:

```json
{
    "error": {
        "message": "litellm.InternalServerError: VertexAIException InternalServerError - 400 Gemini cannot be accessed through Vertex Predict/RawPredict API. Please follow https://cloud.google.com/vertex-ai/docs/generative-ai/start/quickstarts/quickstart-multimodal for Gemini usage.\nReceived Model Group=seo-gemini-1-0\nAvailable Model Group Fallbacks=None",
        "type": null,
        "param": null,
        "code": "500"
    }
}
```

#### **Steps to Reproduce:**
1. Use the following configuration in `config.yaml`:
    ```yaml
    - model_name: gemini-pro
      litellm_params:
        model: vertex_ai/gemini-1.5-pro-001
        vertex_project: <PROJECT_ID>
        vertex_location: <LOCATION>
    - model_name: finetuned-gemini
      litellm_params:
        model: vertex_ai/<ENDPOINT_ID>
        vertex_project: <PROJECT_ID>
        vertex_location: <LOCATION>
      model_info:
        base_model: vertex_ai/gemini-pro
    ```
2. Test non Finetuned Model
The Gemini-Pro model should work with the Vertex AI `Predict` or `RawPredict` API as expected, returning predictions without error.
```bash
curl --location 'https://127.0.0.1:4000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: <LITELLM_KEY>' \
--data '{"model": "gemini-pro" ,"messages":[{"role": "user", "content":[{"type": "text", "text": "hi"}]}]}'
```
#### Result
```json
{
    "id": "chatcmpl-5d7c1424-d96e-4089-a319-ffa690ef4477",
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "Hi there! 👋  What can I do for you today? 😊 \n",
                "role": "assistant",
                "tool_calls": null,
                "function_call": null
            }
        }
    ],
    "created": 1726220014,
    "model": "gemini-1.5-pro-001",
    "object": "chat.completion",
    "system_fingerprint": null,
    "usage": {
        "completion_tokens": 16,
        "prompt_tokens": 1,
        "total_tokens": 17
    }
}
```

3. Attempt to run predictions using the `finetuned-gemini` model model via LiteLLM completion-api.
```bash
curl --location 'https://127.0.0.1:4000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: <LITELLM_KEY>' \
--data '{"model": "finetuned_gemini" ,"messages":[{"role": "user", "content":[{"type": "text", "text": "hi"}]}]}'
```

#### **Expected Behavior:**
The finetuned Gemini-Pro model should work with the the vertex_ai Provider as expected, returning predictions without error.

#### **Actual Behavior:**
The API returns a 500 error with the following message:
```json
{
    "error": {
        "message": "litellm.InternalServerError: VertexAIException InternalServerError - 400 Gemini cannot be accessed through Vertex Predict/RawPredict API. Please follow https://cloud.google.com/vertex-ai/docs/generative-ai/start/quickstarts/quickstart-multimodal for Gemini usage.\nReceived Model Group=seo-gemini-1-0\nAvailable Model Group Fallbacks=None",
        "type": null,
        "param": null,
        "code": "500"
    }
}
```

#### **Environment Details:**
- Model: `Finetuned Gemini-Pro Model over GCP Endpoint
- Auth: Provided via ServiceAccount.json into Litellm Enviroment-Variable

#### **Additional Notes:**
- The error seems to indicate that the Gemini models are accessed using the `Predict/RawPredict` API, Instead of the :generateContent Endpoint.
- The error references using an alternative method for Gemini access through the quickstart link, suggesting that the models might need to be accessed differently or that this API is unsupported for these models.

#### **References:**
- [Quickstart Guide for Gemini Models in Vertex AI](https://cloud.google.com/vertex-ai/docs/generative-ai/start/quickstarts/quickstart-multimodal)

---

Please advise on how to resolve this issue, or clarify whether these models require a different approach for usage via Litellm-Proxy.

**Comment by ghost** [comment]
@the-wdr workaround for this is to use the pass-through endpoint - https://docs.litellm.ai/docs/pass_through/vertex_ai

**Comment by ghost** [comment]
Interesting: 
```
- model_name: finetuned-gemini
  litellm_params:
    model: vertex_ai/<ENDPOINT_ID>
    vertex_project: <PROJECT_ID>
    vertex_location: <LOCATION>
  model_info:
    base_model: vertex_ai/gemini-pro
```

i see the use of `base_model`. I believe we can use that to route the call correctly (i believe it's the generateContent endpoint for gemini models)
