### ISSUE TITLE
[Bug]: memory leak on virtual keys 

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#5695]
### What happened?

When I use the master key for requests, the logs are not written to Langfuse, and there is a slight increase in memory. However, when I use the virtual key from the team and simultaneously write to Langfuse, the memory leaks quickly.

litellm/litellm:v1.45.0

config.yaml
```
general_settings:
  master_key: "sk-123"
  alerting: ["webhook"]

litellm_settings:
  database_url: "postgresql://postgres:postgres123456@localhost:5432/litellm"
  store_model_in_db: true

  cache: True
  cache_params:
    type: redis
    namespace: "litellm_caching"
    host: localhost
    port: "6379"
    ttl: 600

  num_retries: 0
  allowed_fails: 10 # cooldown model if it fails > 1 call in a minute. 
  cooldown_time: 30 # how long to cooldown model if fails/min > allowed_fails

  redact_user_api_key_info: false

  default_team_settings: 
    - team_id: "09ae376d-f6c8-42cd-88be-59717135684d"
      success_callbacks: ["langfuse"]
      langfuse_public_key: "pk-lf"
      langfuse_secret: "sk-lf"
      langfuse_host: ""
```
![image](https://github.com/user-attachments/assets/d087f8c8-a727-4f9b-b00e-be40056d50f8)
