### ISSUE TITLE
[Feature]: Allow setting guardrails default on 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#5758]
### The Feature

support `default_on` for Guardrails interface 

### Motivation, pitch

- 
<img width="894" alt="Screenshot 2024-09-17 at 8 37 26 PM" src="https://github.com/user-attachments/assets/4eb96ce2-a0ac-4773-9f5e-bad64b27b1a9">

**Comment by mirodrr2** [comment]
I would also like this feature. Client side should not have to be aware of guardrails they should be enabled server side

**Comment by mirodrr2** [comment]
Is there any way to enable guardrails to be on per-model?

Even if I cannot globally enable them, enabling them for each model in my config.yaml would be fine as well

Ideally something like this would work:

```
- model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      guardrails: ["bedrock-pre-guard"]

guardrails:
  - guardrail_name: "bedrock-pre-guard"
    litellm_params:
      guardrail: bedrock
      mode: "during_call" # supported values: "pre_call", "post_call", "during_call"
      guardrailIdentifier: 6wcr934j0wgu # your guardrail ID on bedrock
      guardrailVersion: "1" # your guardrail version on bedrock
```

Just really trying to avoid making my clients deal with this
