### ISSUE TITLE
[Bug]: wildcard model vendor weight bug

### ISSUE THREAD

**Issue by doudoujay** [BerriAI/litellm#5781]
### What happened?

My litellm config
```
  - model_name: "*"
    litellm_params:
      model: openai/*
      api_key: xxxxxx
      weight: 1
    model_info:
      metadata: xxxxxx
  - model_name: "*"
    litellm_params:
      model: openai/*
      api_key: xxxxxx
      weight: 10
    model_info:
      metadata: xxxxxx
```
why its throwing error?

### Relevant log output

```shell
{"message": "litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': 'Unrecognized request argument supplied: weight', 'type': 'invalid_request_error', 'param': None, 'code': None}}\nReceived Model Group=gpt-4o\nAvailable Model Group Fallbacks=None", "level": "ERROR", "timestamp": "2024-09-18T23:58:26.299703"}
{"message": "Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)", "level": "ERROR", "timestamp": "2024-09-18T23:58:26.303345"}
```
