### ISSUE TITLE
[Bug]: Tag Based Routing not work with wildcard routing

### ISSUE THREAD

**Issue by prd-tuong-nguyen** [BerriAI/litellm#5801]
### What happened?

Config
```
model_list:
- litellm_params:
    api_base: domain1.com
    api_key: anything,
    model: openai/*
    request_timeout: 15000
    max_tokens: 1024
    tags: ["domain-1"]
  model_name: openai/*
- litellm_params:
    api_base: domain2.com
    model: openai/*
    request_timeout: 15000
    max_tokens: 1024
    tags: ["domain-2"]
  model_name: openai/*

router_settings:
  enable_tag_filtering: True
```

Request body:
```
{
  "model":"openai/",
  "tags": ["domain-2"],
  "messages": [
    {
        "role": "user",
        "content": "Who are you?"
    }
  ]
}
```

The request will be randomly routed to domain 1 and domain 2. The expected behavior is to forward the request to domain 2.

### Twitter / LinkedIn details

https://www.linkedin.com/in/huytuong010101/
