### ISSUE TITLE
Dual GPU dual models load balancing with liteLLM, but performance can't be doubled

### ISSUE THREAD

**Issue by Homura2333** [BerriAI/litellm#5835]
## hardware environment
- GPU: 2 A10s
## software environment
- vLLM: 0.5.0
- model: Qwen2-7b
- liteLLM: 1.41.11
## config.yaml file

```
model_list:
  - model_name: qwen2-7b
    litellm_params:
      model: openai//root/qwen
      api_base: http://127.0.0.1:38081/v1
      api_key: token-abc123
  - model_name: qwen2-7b
    litellm_params:
      model: openai//root/qwen
      api_base: http://127.0.0.1:38082/v1
      api_key: token-abc123
router_settings:
  routing_strategy: least-busy
```
## Observations and expected results
I wrote test scripts to test the model throughput and would like to see that the maximum supported throughput should be approximately twice as much when deployed with a dual-card, dual-model as when deployed with a single-card, single-model. However, load balancing using liteLLM did not result in an increase in maximum throughput, **both throughputs were around 1700token/s or so.**
Also, using nvidia-smi shows that both GPUs are indeed being used when load balancing and both are at about 80% utilization, and vLLM's log also shows that both models are working without any errors.
<img width="745" alt="image" src="https://github.com/user-attachments/assets/821ad5e2-1ea5-4712-aa42-0c772472608f">
And it can be observed that liteLLM occupies an entire CPU core, whether there is a performance bottleneck in liteLLM?
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/067a2af9-bb5a-4ada-8303-fe31b86eebc5">
