### ISSUE TITLE
[Feature]: Allow `configurable_clientside_parameters` for switching b/w finetuning models easily 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5843]
### The Feature

in the model_list, having a variable (like clientside_configurable_parameters with a default value of [] that contains a list of which litellm parameters can be overwritten by a client. This preserves the current behavior of no values overwritten by a client, but allows for new behavior of configuring variables that a client can override; this also gives the level of control we would want

```yaml
model_list:
   - model_name: "anthropic/*"
     litellm_params:
       model: "anthropic/*"
#       api_base: "<default_api_base>" # [OPTIONAL]
       clientside_configurable_parameters: ["api_base", "base_url"]
```

### Motivation, pitch

Allows devs to switch between finetuned models easily (changing api base), and allows admin to define which models + which params can have this behaviour (prevents security issues like https://huntr.com/bounties/4001e1a2-7b7a-4776-a3ae-e6692ec3d997) 

### Twitter / LinkedIn details

cc: @nathanluskey
