### ISSUE TITLE
[Bug]: inconsistent `max_tokens` for Bedrock Anthropic Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by billyjanitsch** [BerriAI/litellm#5850]
### What happened?

Given:

```yaml
model_name: "anthropic-claude-v3.5-sonnet"
litellm_params:
  model: "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
```

LiteLLM's `/v1/model/info` claims:

```json
"model_info": {
  "max_tokens": 8192
}
```

But if you call the model with the same value, you get:

```
litellm.BadRequestError: BedrockException - {"message":"The maximum tokens you requested exceeds the model limit of 4096. Try again with a maximum tokens value that is lower than 4096."}
```

The problem is that, as mentioned in https://github.com/BerriAI/litellm/issues/5656#issuecomment-2346957304, the Bedrock version of the model only supports 4096 max tokens, but the parameter is configured unconditionally (independent of host) here:

https://github.com/BerriAI/litellm/blob/d9e798ecda74cf79d134c66064804a4967ed82d1/litellm/model_prices_and_context_window_backup.json#L3864-L3865

This parameter needs to distinguish between Bedrock and other providers to return an accurate value.
