### ISSUE TITLE
[Bug]: Team/Key Based Logging

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#5907]
### What happened?

The first team can write to Langfuse, while the second team has no records of writing to Langfuse.

```yaml
general_settings:
  master_key: "sk-xxx"
  alerting: ["webhook"]

litellm_settings:
  database_url: "postgresql://postgres:difyai123456@localhost:5432/litellm"
  store_model_in_db: true

  cache: True
  cache_params:
    type: redis
    namespace: "litellm_caching"
    host: "localhost"
    port: "6379"
    ttl: 600

  num_retries: 0
  allowed_fails: 10 # cooldown model if it fails > 1 call in a minute.
  cooldown_time: 30 # how long to cooldown model if fails/min > allowed_fails

  fallbacks:
    - claude-3-haiku: ["azure/gpt-4o-mini"]

  redact_user_api_key_info: true

  default_team_settings:
    - team_id: "09ae376d-f6c8-42cd-88be-59717135684d" # team 1
      success_callbacks: ["langfuse"]
      langfuse_public_key: "pk-lf-1"
      langfuse_secret: "sk-lf-1"
      langfuse_host: ""

    - team_id: "e5db79db-d623-4a5b-afd5-162be56074df" # team2
      success_callback: ["langfuse"]
      langfuse_public_key: "pk-lf-2"
      langfuse_secret: "sk-lf-2"
      langfuse_host: ""

router_settings:
  model_group_alias:
    claude-3-haiku: "anthropic.claude-3-haiku-20240307-v1:0"
    claude-3-sonnet: "anthropic.claude-3-sonnet-20240229-v1:0"
    claude-3-5-sonnet: "anthropic.claude-3-5-sonnet-20240620-v1:0"

```
