### ISSUE TITLE
[Feature]: Allow setting `created` 

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#5916]
### The Feature

Right now, `created` is hardcoded to `1677610602`.

https://github.com/BerriAI/litellm/blob/16c0307eab601b238f21021b9cba04b6957ad34c/litellm/proxy/proxy_server.py#L3051-L3056

It would be nice if we could set `created` 

```yaml
model_list:
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      mode: embedding
      base_model: text-embedding-3-small
      created: 441795600
```

### Motivation, pitch

Some applications, like LibreChat (IIRC), sort models by `created`.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
