### ISSUE TITLE
[Bug]: Cache not hit in completion - when namespace + batch get cache

### ISSUE THREAD

**Issue by simonChoi034** [BerriAI/litellm#5917]
### What happened?

When calling the /chat/completion API with the same request parameters twice, the second response is not hitting the cache.

The cache key exists in Redis, and the same cache key is generated with the same input, which is displayed in the Langfuse trace tags. But the server just won't return the cache.

This is the yaml file I used.
```yaml
litellm_settings:
  json_logs: true
  cache: true
  cache_params:
    type: "redis"
    namespace: "litellm_caching"
    ttl: 900
  callbacks: ["batch_redis_requests"]
  success_callback: ["langfuse"]
  langfuse_default_tags: ["cache_hit", "cache_key", "proxy_base_url", "user_api_key_alias", "user_api_key_user_id", "user_api_key_user_email", "user_api_key_team_alias", "semantic-similarity", "proxy_base_url"]
general_settings:
  store_model_in_db: True
  database_connection_pool_limit: 10
```
