### ISSUE TITLE
[Feature]: Support fallbacks for wildcard models 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#5970]
### The Feature

we need to add a separate model entry for each model on Azure. It would be great if we could instead do:

```yaml
model_list:
  - model_name: azure/*
    litellm_params:
      model: azure/*
      api_base: https://zapier-openai.openai.azure.com/
      api_version: 2024-05-01-preview
      api_key: os.environ/AZURE_OPENAI_API_KEY
litellm_settings:
  fallbacks:
    - gpt-4o:
      - azure/gpt-4o
```

### Motivation, pitch

user request
