### ISSUE TITLE
[Bug]: nvidia embeddings does not consider input_type required parameter

### ISSUE THREAD

**Issue by ladrians** [BerriAI/litellm#6001]
### What happened?

Call some of the [nvidia embeddings](https://docs.api.nvidia.com/nim/reference/nvidia-nv-embedqa-e5-v5-infer) such as `nvidia-nv-embedqa-e5-v5-infer`. It requires the `input_type` parameter so by default it does not work.

Minimal example

```
curl --location 'http://0.0.0.0:4000/embeddings' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer something_here' \
--data '{
    "model": "nvidia/nvidia.nv-embedqa-e5-v5",
    "input" : "identify yourself!",
    "input_type": "passage" 
}'
```

Error:

```
litellm.APIError: APIError: OpenAIException - AsyncEmbeddings.create() got an unexpected keyword argument 'input_type'\nReceived Model Group=nvidia/nvidia.nv-embedqa-e5-v5\nAvailable Model Group Fallbacks=None
```

Using this configuration

```
  - model_name: nvidia/nvidia.nv-embedqa-e5-v5
    litellm_params:
      model: openai/nvidia/nv-embedqa-e5-v5
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
    model_info:
      mode: embedding
```

as WA if I change the body like this using `extra_body` worked, but I cannot change how the body is generated.

```
{    
    "model": "nvidia/nvidia.nv-embedqa-e5-v5",
    "input" : "identify yourself!",
    "extra_body": {
        "input_type": "passage" 
    }
}
```

Is there a change to tweak the body equal as detailed on the nvidia docs?

More info on other models [here](https://build.nvidia.com/explore/retrieval); I got the same results with `nv-embedqa-mistral-7b-v2`, `snowflake.arctic-embed-l`. Only `baai.baai.bge-m3` worked (it does not seems to need it).

**Comment by ishaan-jaff** [comment]
working on this

**Comment by ishaan-jaff** [comment]
we needed to add support for nvidia_nim embeddings @ladrians - done here: https://github.com/BerriAI/litellm/pull/6032

**Comment by ishaan-jaff** [comment]
@ladrians - you'll need to define the models as nvidia_nim models. Fix will be out on 1.48.11 - can you let me know if this works for you ? 

```yaml
model_list:
  - model_name: my-model
    litellm_params:
      model: nvidia_nim/<your-model-name>  # add nvidia_nim/ prefix to route as Nvidia NIM provider
      api_key: api-key                 # api key to send your model
```

**Comment by ishaan-jaff** [comment]
did the changes work @ladrians ?

**Comment by ladrians** [comment]
it did work, thanks! We do not have deployed `nvidia_nim`, we still want to use the nvidia public endpoints using our provided api keys, so used the following configuration

```
  - model_name: nvidia/nvidia.nv-embedqa-e5-v5
    litellm_params:
      model: nvidia_nim/nvidia/nv-embedqa-e5-v5
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
```

Updated to version `v1.48.18`. I can confirm the following embeddings worked using the `nvidia_nim` mapping: `baai.bge-m3`, `nv-embed-v1`, `nvclip`, `embed-qa-4`, `nv-embedqa-e5-v5`, `snowflake.arctic-embed-l`, `nvidia.nv-embedqa-mistral-7b-v2`.
