### ISSUE TITLE
[Bug]: cross-region-inferencing `max_tokens_to_sample` being sent to Amazon Bedrock models

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#6003]
### What happened?

After upgrading from to v1.48.2 to v1.48.7, `max_tokens_to_sample` is being sent to models (like Claude 3.5 Sonnet) on AWS Bedrock.

```json
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "text": "Hi"
        }
      ]
    }
  ],
  "additionalModelRequestFields": {
    "max_tokens_to_sample": 1
  },
  "system": [],
  "inferenceConfig": {
    "temperature": 0.31842772478508174
  }
}
```

```yaml
model_list:
  - model_name: claude-3-5-sonnet-20240620-bedrock
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: us-east-1
      max_tokens: 4096
      api_base: https://bedrock-runtime.us-east-1.amazonaws.com
      aws_bedrock_runtime_endpoint: https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/aws-bedrock/bedrock-runtime/us-east-1
      aws_session_name: "litellm"
      aws_role_name: "arn:aws:iam::REMOVED:role/REMOVED"
      aws_web_identity_token: "oidc/google/https://example.com"
      aws_sts_endpoint: "https://sts-fips.us-east-1.amazonaws.com"
```

### Relevant log output

```shell
{
  "message": "The model returned the following errors: Malformed input request: #: extraneous key [max_tokens_to_sample] is not permitted, please reformat your input and try again."
}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/
