### ISSUE TITLE
[Bug]: S3 logging dead again?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#6025]
### What happened?

It seems like around ~v1.44.25, S3 logging died. Our last log event was 1726099373285812 (`Thursday, September 12, 2024 12:02:53.285 AM`).

There are no error messages or anything to indicate that S3 logging isn't working. It just.. stopped working. =/ 

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
when you run the proxy with `--detailed_debug` what do your logs show?

**Comment by ghost** [comment]
Unable to repro the issue. 

When I run this config (from docs) - 

```yaml
model_list:
 - model_name: "gpt-3.5-turbo"
   litellm_params:
       model: gpt-3.5-turbo
litellm_settings:
  success_callback: ["s3"]
  s3_callback_params:
    s3_bucket_name: mytestbucketlitellm   # AWS Bucket Name for S3
    s3_region_name: us-west-2              # AWS Region Name for S3
    s3_aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID  # us os.environ/<variable name> to pass environment variables. This is AWS Access Key ID for S3
    s3_aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY  # AWS Secret Access Key for S3
```

And make a `/chat/completion` request, i can see it logged -
<img width="1400" alt="Screenshot 2024-10-03 at 9 28 55 AM" src="https://github.com/user-attachments/assets/90ef52d5-add6-4b30-98cc-833cbf67178b">
<img width="1099" alt="Screenshot 2024-10-03 at 9 28 49 AM" src="https://github.com/user-attachments/assets/d37dbf8f-b4d5-4977-81e2-fed5e92242e3">

**Comment by Manouchehri** [comment]
What should I be looking for when running `--detailed_debug`? There is a _ton_ of messages and I don't see a single thing that looks like the S3 logging happening. This is the closest thing I see happening, no clue if it's related.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/dcaa0106-74a0-4065-9121-2ff473151620">

**Comment by ghost** [comment]
https://github.com/BerriAI/litellm/blob/9fccb4a0da2aa15f53aed5b40372612e7897fc9d/litellm/integrations/s3.py#L94

"s3 Logging - Enters logging function for model"

**Comment by ghost** [comment]
https://github.com/BerriAI/litellm/blob/9fccb4a0da2aa15f53aed5b40372612e7897fc9d/litellm/integrations/s3.py#L168

"s3 layer error"

OR 

https://github.com/BerriAI/litellm/blob/9fccb4a0da2aa15f53aed5b40372612e7897fc9d/litellm/integrations/s3.py#L165

"s3 Layer Logging - final response object"

**Comment by Manouchehri** [comment]
I get zero hits in my logs for `s3 Layer`.

Langfuse logging/callbacks are working, so not sure what's up.

**Comment by ghost** [comment]
That means s3 logging is probably not enabled. How have you added it on your config?

**Comment by Manouchehri** [comment]
```yaml
litellm_settings:
  telemetry: False
  drop_params: True
  redact_messages_in_exceptions: True
  failure_callback: ["sentry", "langfuse"]
  request_timeout: 3600
  success_callback: ["langfuse", "s3"]
  s3_callback_params:
    s3_bucket_name: os.environ/EXAMPLE_S3_BUCKET_NAME
    s3_region_name: os.environ/EXAMPLE_AWS_DEFAULT_REGION
    s3_aws_access_key_id: os.environ/EXAMPLE_AWS_ACCESS_KEY_ID
    s3_aws_secret_access_key: os.environ/EXAMPLE_AWS_SECRET_ACCESS_KEY
    s3_endpoint_url: os.environ/EXAMPLE_AWS_ENDPOINT_URL_S3
  default_team_settings:
    - team_id: example_dev
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_EXAMPLE
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_EXAMPLE
```
