### ISSUE TITLE
[Feature]: Enable `default_team_settings` control on config.yaml 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#6070]
### The Feature

Allow admin to set max budget, allowed models, etc. for team via `default_team_settings` 

```yaml
default_team_settings:  
   team_member_budget: 10  
   models: [gpt-4, gpt-4o] 
```

### Motivation, pitch

user request
