### ISSUE TITLE
[Feature]: Ability to define default models for internal users

### ISSUE THREAD

**Issue by ncecere** [BerriAI/litellm#6239]
### The Feature

I'm looking for the ability to define default models available to internal users. 

## Current Config Options

```yaml
default_internal_user_params:    # Default Params used when a new user signs in Via SSO
    user_role: "internal_user"     # one of "internal_user", "internal_user_viewer", "proxy_admin", "proxy_admin_viewer". New SSO users not in litellm will be created as this user
    max_budget: 10.00                # Optional[float], optional): $100 budget for a new SSO sign in user
    budget_duration: 30d           # Optional[str], optional): 30 days budget_duration for a new SSO sign in user
```

## Proposed Config Options

```yaml
default_internal_user_params:    # Default Params used when a new user signs in Via SSO
    user_role: "internal_user"     # one of "internal_user", "internal_user_viewer", "proxy_admin", "proxy_admin_viewer". New SSO users not in litellm will be created as this user
    max_budget: 10.00                # Optional[float], optional): $100 budget for a new SSO sign in user
    budget_duration: 30d           # Optional[str], optional): 30 days budget_duration for a new SSO sign in user
    models: ["llama-3.1-8b-instruct","llama-3.1-70b-instruct", "free_teir"]
```

### Motivation, pitch

This way you could have "free" models available to user to create self service keys for.  That way when a user go to create a key in the "Default Team" they only use models defined as default models (or access_group) for internal users.

I think this would greatly improve the Self Service experience and management of the proxy and the UI
