### ISSUE TITLE
Embedding Dimension in qdrant semantic cache should not be static rather derived from the embedding model being used.

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [BerriAI/litellm#6262]
Embedding dimension here is fixed to 1536 which is wrong as different embedding models might have different dimens

https://github.com/BerriAI/litellm/blob/fc5b75d1710ea1ea815746090fb154fc0f7717d8/litellm/caching/qdrant_semantic_cache.py#L135C41-L135C45

Hence the model should be used from config file.

**Comment by ghost** [comment]
is there a way for us to know embedding dim ahead of time? @S1LV3RJ1NX

**Comment by S1LV3RJ1NX** [comment]
We can make an api call to the embedding model defined in the qdrant config with a sample text like `Hello World` the embedding it returns, the length of the list will be it's dimension.

**Comment by henrikalbihn** [comment]
Hello 👋🏼 - I was going to open an issue, but found this related one.

I'm using [Ollama](https://ollama.com) for my backend and the [`nomic-embed-text` model](https://ollama.com/library/nomic-embed-text/blobs/970aa74c0a90).

The ideal case would be deriving the dimensions from the model itself (which as mentioned above could be handled by creating a test call of the model and calculating the embedding's `len`).

That being said, for a fast fix I could suggest two alternatives.

When setting up a proxy server, you usually know the dimensionality of the model so I think it would be logical to simply expose extra options in the `QdrantSemanticCache.__init__` method with defaults (such that the change is backwards compatible).

## Option 1
- pass as individual kwargs
```python
class QdrantSemanticCache(BaseCache):
    def __init__(  # noqa: PLR0915
        self,
        qdrant_api_base=None,
        qdrant_api_key=None,
        collection_name=None,
        similarity_threshold=None,
        quantization_config=None,
        embedding_model="text-embedding-ada-002",
        host_type=None,
        embedding_dimensions=1536,  # <-- Add this
        distance_metric="Cosine",   # <-- Add this
    ):
        ...
        self.embedding_dimensions: int = embedding_dimensions # <-- Add this
        self.distance_metric: str = distance_metric           # <-- Add this
```

then in the call

```python
        ...
        new_collection_status = self.sync_client.put(
                url=f"{self.qdrant_api_base}/collections/{self.collection_name}",
                json={
                    "vectors": {"size": self.embedding_dimensions, "distance": self.distance_metric}, # <-- Change this
                    "quantization_config": quantization_params,
                },
                headers=self.headers,
            )

```
## Option 2
- pass as `vector_config`

```python
class QdrantSemanticCache(BaseCache):
    def __init__(  # noqa: PLR0915
        self,
        qdrant_api_base=None,
        qdrant_api_key=None,
        collection_name=None,
        similarity_threshold=None,
        quantization_config=None,
        embedding_model="text-embedding-ada-002",
        host_type=None,
        vector_config={"size": 1536, "distance": "Cosine"}, # <-- Add this
    ):
        ...
        self.vector_config: dict = vector_config # <-- Add this
```

then in the call

```python
        ...
        new_collection_status = self.sync_client.put(
                url=f"{self.qdrant_api_base}/collections/{self.collection_name}",
                json={
                    "vectors": self.vector_config, # <-- Change this
                    "quantization_config": quantization_params,
                },
                headers=self.headers,
            )

```

These could also be exposed as environment variables for the proxy server / litellm CLI `config.yaml` as below:

```yaml
model_list:
  - model_name: nomic-embed-text
    litellm_params:
      model: ollama/nomic-embed-text:latest

litellm_settings:
  set_verbose: true
  cache: True
  cache_params:
    type: qdrant-semantic
    qdrant_semantic_cache_embedding_model: nomic-embed-text
    qdrant_semantic_cache_embedding_dimensions: 768  # <-- Add this
    qdrant_distance_metric: Cosine                   # <-- Add this
    qdrant_collection_name: litellm-semantic-cache
    qdrant_quantization_config: binary
    similarity_threshold: 0.8
```

Thank you.
