### ISSUE TITLE
[Feature]: disable customer_spend_alert

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#6273]
### The Feature

When I use the webhook, I want to be able to disable the customer_spend_alert.

{"customer_id":"e374ba0d-32f7-4e9b-8e36-062379e231c7","event":"spend_tracked","event_group":"customer","event_message":"Customer spend tracked. Customer=e374ba0d-32f7-4e9b-8e36-062379e231c7, spend=7.305e-05","key_alias":"nlp-pro","max_budget":null,"projected_exceeded_date":null,"projected_spend":null,"spend":0.00007305,"team_alias":null,"team_id":null,"token":"baaeee4d2ba5de5a57e9037cdf4d873ca99b1d3339f45b5656674","user_email":null,"user_id":null}

https://github.com/BerriAI/litellm/blob/v1.49.5/litellm/integrations/SlackAlerting/slack_alerting.py#L681

### Motivation, pitch

There are too many alerting, and I primarily want to focus on the exceptional warnings.

**Comment by langgg0511** [comment]
```yaml
general_settings:
  alerting: ["webhook"]
  alert_types: ["llm_exceptions", "llm_requests_hanging"]
```
