### ISSUE TITLE
[Bug]: Dall-e cost is 0

### ISSUE THREAD

**Issue by desinurch** [BerriAI/litellm#6278]
### What happened?

Hi team,

I'm trying to obtain DALL-E model costs for image generation but it always yields to zero. I am using LiteLLM version 1.46.5.

Python code:
```
client = OpenAI(
    api_key=API_KEY,
    base_url="https://LITELLM_URL/v1/"
)

response = client.images.generate(
  model="dall-e-3",
  prompt="a white siamese cat",
  size="1024x1024",
  quality="standard",
  n=1,
)

print(response)

ImagesResponse(created=1729069095, data=[Image(b64_json=None, revised_prompt='A visually appealing baby sea otter. The otter is partially submerged in turquoise blue water, with the sun gently shimmering on its surface. The otter has soft, wet fur in varying shades of brown - from rich chocolate to subtle caramel. Its expressive eyes are an entrancing charcoal black, full of curiosity and playfulness. Its tiny, webbed paws are raised slightly above the water, indicating it might be in the midst of frolicking or playing. The image radiates a sense of serenity and wonder, capturing the innocence and charm of a baby sea otter in its natural habitat.', url='REDACTED')], usage={'prompt_tokens': 0, 'completion_tokens': 0, 'total_tokens': 0})
```

Below is litellm proxy config:
```
/app# cat config.yaml
model_list:
  #################
  # OpenAI models #
  #################

  - model_name: openai/gpt-4o
    model_info:
      display_name: GPT-4o (medium speed, general purpose)
      description: |
        GPT-4o is OpenAI's flagship model for general-purpose text generation and coding.
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: openai/gpt-4o-mini
    model_info:
      display_name: GPT-4o Mini (fast, general purpose)
      description: |
        GPT-4o Mini is OpenAI's fastest model for general-purpose text generation.
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: dall-e-3
    model_info:
        display_name: OpenAI DALL-E 3 (image generation)
        mode: image_generation
    litellm_params:
      model: openai/dall-e-3
      api_key: os.environ/OPENAI_API_KEY

  - model_name: dall-e-2
    model_info:
        display_name: OpenAI DALL-E 2 (image generation)
        mode: image_generation
    litellm_params:
      model: openai/dall-e-2
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  num_retries: 3
  drop_params: True
  set_verbose: True
  callbacks: custom_callbacks.proxy_handler_instance
```

is there something i'm missing?

### Relevant log output

```shell
Initialized litellm callbacks, Async Success Callbacks: [<bound method Router.deployment_callback_on_success of <litellm.router.Router object at 0x7330bd379b10>>, <custom_callbacks.ZLLMHandler object at 0x7330bd379900>, <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7330be061240>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7330be061210>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7330be0612a0>, <litellm._service_logger.ServiceLogging object at 0x7330bd379ba0>]
ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
INFO:     10.3.82.1:32814 - "GET /health/liveliness HTTP/1.1" 200 OK
INFO:     10.3.82.1:32816 - "GET /health/readiness HTTP/1.1" 200 OK
RAW RESPONSE:
{"created": 1729069095, "data": [{"b64_json": null, "revised_prompt": "A visually appealing baby sea otter. The otter is partially submerged in turquoise blue water, with the sun gently shimmering on its surface. The otter has soft, wet fur in varying shades of brown - from rich chocolate to subtle caramel. Its expressive eyes are an entrancing charcoal black, full of curiosity and playfulness. Its tiny, webbed paws are raised slightly above the water, indicating it might be in the midst of frolicking or playing. The image radiates a sense of serenity and wonder, capturing the innocence and charm of a baby sea otter in its natural habitat.", "url": "URL OBFUSCATED"}]}


Post-API Call
Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x7330bcf8c8b0>>
Logging Details LiteLLM-Success Call: Cache_hit=None
success callbacks: Running Custom Callback Function
InMemoryCache: set_cache. current size= 16
On Success
INFO:     10.2.134.0:46930 - "POST /v1/images/generations HTTP/1.1" 200 OK
Logging Details LiteLLM-Async Success Call, cache_hit=None
InMemoryCache: set_cache. current size= 17
InMemoryCache: set_cache. current size= 18
On Async Success!
On Success
Looking up model=openai/dall-e-3 in model_cost_map
Success: model=openai/dall-e-3 in model_cost_map
prompt_tokens=0; completion_tokens=0
Returned custom cost for model=openai/dall-e-3 - prompt_tokens_cost_usd_dollar: 0, completion_tokens_cost_usd_dollar: 0
Litellm Call ID: 5e2186da-cdc3-4941-86cc-f83a45e3e13e
Litellm Call ID: 5e2186da-cdc3-4941-86cc-f83a45e3e13e
```
