### ISSUE TITLE
[Bug]: Microsoft SSO login fails for user with role "proxy_admin" when ui_access_mode is "admin_only"

### ISSUE THREAD

**Issue by domg8man** [BerriAI/litellm#6286]
### What happened?

When attempting to login to the UI, I am greeted with the following error message:
```json
{"detail":{"error":"User not allowed to access proxy. User role=proxy_admin, proxy mode=admin_only"}}
```

and HTTP response code 401 Unauthorized.

**Steps to reproduce:**
1. Start with a fresh postgresql database.
2. Use the following initial settings:
```yaml
general_settings:
  # ui_access_mode: admin_only
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 120
  enable_jwt_auth: true
  litellm_jwtauth:
    admin_jwt_scope: "litellm_proxy_endpoints_access"
    admin_allowed_routes:
      - openai_routes
      - info_routes
    end_user_id_jwt_field: "appid"
    public_key_ttl: 600
model_list:
  ...
litellm_settings:
  max_internal_user_budget: 10
  internal_user_budget_duration: "1mo"
  default_internal_user_params:
    user_role: "internal_user"
    max_budget: 10
    budget_duration: "1mo"
  default_key_generate_params:
    max_budget: 10
    models: ["gpt-4o-mini", "gpt-4o"]
    duration: "14d"
  upperbound_key_generate_params:
    max_budget: 10
    duration: "14d"
  drop_params: true
  num_retries: 3
  request_timeout: 10
  telemetry: false
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
```
3. Login with your user and introspect the user id (via UI or psql database query)
4. Redeploy the service with changed config and environment variables:
```yaml
general_settings:
      ui_access_mode: admin_only
      ...
...
```
```bash
export PROXY_ADMIN_ID="9a45cabf-47ff-4ffa-8fcf-e04c3459b902"
```
5. Login to the UI and see the error:
```json
{"detail":{"error":"User not allowed to access proxy. User role=proxy_admin, proxy mode=admin_only"}}
```

Basically this process is broken:
https://docs.litellm.ai/docs/proxy/ui#step-2-set-it-in-your-env-as-the-proxy_admin_id

I have done this once before on an older version and it used to work.

**Expected behavior:**
Since I assigned myself admin access via the env var and clearly see the role was applied to my user row in the "LiteLLM_UserTable", I should be allowed to login.

Here's what my database query says:
```bash
psql $DATABASE_URL
litellm=> SELECT * FROM "LiteLLM_UserTable";
```
```markdown
| user_id                               | user_alias | team_id | organization_id | password | teams | user_role   | max_budget | spend | user_email        | models | metadata                                                                                       | max_parallel_requests | tpm_limit | rpm_limit | budget_duration | budget_reset_at         | allowed_cache_controls | model_spend | model_max_budget |
|---------------------------------------|------------|---------|-----------------|----------|-------|-------------|------------|-------|-------------------|--------|------------------------------------------------------------------------------------------------|-----------------------|-----------|-----------|-----------------|------------------------|------------------------|-------------|------------------|
| default_user_id                       |            |         |                 |          | {}    | proxy_admin |            | 0     |                   | {}     | {"model_rpm_limit": {}, "model_tpm_limit": {}}                                                 |                       |           |           |                 |                        | {}                     | {}          | {}               |
| 9a45cabf-47ff-4ffa-8fcf-e04c3459b902  |            |         |                 |          | {}    | proxy_admin | 10         | 0     | me@example.com | {}     | {"auth_provider": "microsoft"}                                                                 |                       |           |           | 1mo             | 2024-11-17 14:05:11.69 | {}                     | {}          | {}               |
(2 rows)
```

**Here's the debug logs:**
```ndjson
...
{"message": "user_info: user_id='9a45cabf-47ff-4ffa-8fcf-e04c3459b902' user_alias=None team_id=None organization_id=None password=None teams=[] user_role='proxy_admin' max_budget=10.0 spend=0.0 user_email='me@example.com' models=[] metadata={'auth_provider': 'microsoft'} max_parallel_requests=None tpm_limit=None rpm_limit=None budget_duration='1mo' budget_reset_at=datetime.datetime(2024, 11, 17, 14, 5, 11, 690000, tzinfo=TzInfo(UTC)) allowed_cache_controls=[] model_spend={} model_max_budget={} litellm_organization_table=None organization_memberships=None invitations_created=None invitations_updated=None invitations_user=None; litellm.default_internal_user_params: {'user_role': 'internal_user', 'max_budget': 10, 'budget_duration': '1mo'}", "level": "DEBUG", "timestamp": "2024-10-17T14:24:13.136893"}
...
{"message": "user_role: proxy_admin; ui_access_mode: admin_only", "level": "DEBUG", "timestamp": "2024-10-17T14:24:13.189885"}
{"message": "EXCEPTION RAISED", "level": "DEBUG", "timestamp": "2024-10-17T14:24:13.190045"}
...
```
\* I redacted my uuid, email and model endpoints.

I was using this image version: `ghcr.io/berriai/litellm-non_root:main-v1.49.6`

### Relevant log output

```shell
{"detail":{"error":"User not allowed to access proxy. User role=proxy_admin, proxy mode=admin_only"}}
```
