### ISSUE TITLE
[Bug]: LiteLLM Performance Degradation Over Time Fixed by Service Restart

### ISSUE THREAD

**Issue by yigitkonur** [BerriAI/litellm#6345]
### What happened?

When using LiteLLM on a self-hosted on-premises instance, the performance gradually degrades over time. The issue persists even after disabling router features and Redis. The problem is temporarily resolved by restarting the service or the entire system, with initial requests being faster after a restart. But then after 2-3 hours it is getting slower.

Steps to Reproduce:
1. Set up LiteLLM on a self-hosted, on-premises instance
2. Use the service continuously for an extended period
3. Observe performance degradation, particularly in Time to First Token values

Expected Behavior:
Consistent performance over time without significant degradation

Actual Behavior:
- Performance gradually slows down
- Time to First Token values increase significantly
- Restarting the service temporarily resolves the issue

Additional Information:
- Router features have been disabled
- The issue is most noticeable with the initial requests after extended use
- Restarting the service or system temporarily resolves the problem

Environment:
- LiteLLM version: 1.5
- Hosting environment: GCP
- Operating System: Ubuntu 22
- Hardware specifications: 4 cores, 8 GB RAM (AMD Genoa)

Possible Causes:
- Memory leak (no high memory observed on htop, but full core utilization is observed)
- Resource allocation issues (maybe?)
- Caching problems (I don't have cache)
- Connection pool exhaustion (not sure, but AI recommends that)

### Relevant log output

```shell
Running on `home/root/litellm-production/env/bin/litellm --config config.yaml --num_workers 1 --port 1453` (I've observed on num_workers 4 and decreased to 1 but does not affect)
```

**Comment by ishaan-jaff** [comment]
@yigitkonur 

- after how many hours do you see the performance impacted ? 
- Is the impact on your median response times ? 
- Is this for non-streaming and streaming ? 
- what llm provider was this on ? 
- were any embedding requests running at this time ?

**Comment by yigitkonur** [comment]
1. After how many hours do you see the performance impacted?
   I experience this issue on average every 3-4 hours.

2. Is the impact on your median response times?
   The average Time to First Token can reach approximately 7 seconds.

3. Is this for non-streaming and streaming?
   All requests are streaming, not non-streaming.

4. What LLM provider was this on?
   I use many LLM providers, 10+ different providers. (gpt-4-turbo, gpt-4o, gpt-4o-mini, o1-mini, o1-preview, claude-3.5-sonnet, claude-3-opus, claude-3-haiku, llama3-1-405b, mistral-large-2, command-r-plus, gemini-1.5-pro, gemini-1.5-flash)

5. Were any embedding requests running at this time?
   No, I don't send any embedding requests.

Additional information:
- Once this issue starts, it affects all requests, and when I monitor it, I see that one core of the four-core machine is constantly at 100%. That's why I've set up a cronjob that automatically restarts the system every two hours.

I'm also sharing my config list:

```
cat config.yaml
router_settings:
  num_retries: 5
  drop_params: True

  model_group_alias:
    "gpt-4-turbo-2024-04-09":
      model: "gpt-4-turbo"
      hidden: true
    "gpt-4-turbo-preview":
      model: "gpt-4-turbo"
      hidden: true
    "gpt-4-1106-preview":
      model: "gpt-4-turbo"
      hidden: true
    "gpt-4-0125-preview":
      model: "gpt-4-turbo"
      hidden: true
    "gpt-4o-2024-08-06":
      model: "gpt-4o"
      hidden: true
    "gpt-4o-2024-05-13":
      model: "gpt-4o"
      hidden: true
    "chatgpt-4o-latest":
      model: "gpt-4o"
      hidden: true
    "gpt-4o-mini-2024-07-18":
      model: "gpt-4o-mini"
      hidden: true
    "o1-mini-2024-09-12":
      model: "o1-mini"
      hidden: true
    "o1-preview-2024-09-12":
      model: "o1-preview"
      hidden: true
    "haiku":
      model: "claude-3-haiku"
      hidden: true
    "opus":
      model: "claude-3-opus"
      hidden: true
    "sonnet":
      model: "claude-3.5-sonnet"
      hidden: true
    "command-r":
      model: "command-r-plus"
      hidden: true
    "gemini-flash":
      model: "gemini-1.5-flash"
      hidden: true
    "gemini-pro":
      model: "gemini-1.5-pro"
      hidden: true
    "llama":
      model: "llama3-1-405b"
      hidden: true
    "mistral":
      model: "mistral-large-2"
      hidden: true

# Model List
model_list:
  # Azure OpenAI Models: gpt-4-turbo
  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: os.environ/AZURE_API_KEY_EAST_US
      api_base: os.environ/AZURE_API_BASE_EAST_US
      api_version: "2024-10-01-preview"

  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: os.environ/AZURE_API_KEY_EAST_US_2
      api_base: os.environ/AZURE_API_BASE_EAST_US_2
      api_version: "2024-10-01-preview"

  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: os.environ/AZURE_API_KEY_NORTH_CENTRAL_US
      api_base: os.environ/AZURE_API_BASE_NORTH_CENTRAL_US
      api_version: "2024-10-01-preview"

  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: os.environ/AZURE_API_KEY_SWEDEN_CENTRAL
      api_base: os.environ/AZURE_API_BASE_SWEDEN_CENTRAL
      api_version: "2024-10-01-preview"

  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: os.environ/AZURE_API_KEY_WEST_US
      api_base: os.environ/AZURE_API_BASE_WEST_US
      api_version: "2024-10-01-preview"

  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/gpt-4-turbo
      api_key: os.environ/AZURE_API_KEY_WEST_US_3
      api_base: os.environ/AZURE_API_BASE_WEST_US_3
      api_version: "2024-10-01-preview"


# Azure OpenAI Models: gpt-4o
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_key: os.environ/AZURE_API_KEY_EAST_US
      api_base: os.environ/AZURE_API_BASE_EAST_US
      api_version: "2024-10-01-preview"

  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_key: os.environ/AZURE_API_KEY_SWEDEN_CENTRAL
      api_base: os.environ/AZURE_API_BASE_SWEDEN_CENTRAL
      api_version: "2024-10-01-preview"

  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_key: os.environ/AZURE_API_KEY_WEST_US_3
      api_base: os.environ/AZURE_API_BASE_WEST_US_3
      api_version: "2024-10-01-preview"

  # Azure OpenAI Models: gpt-4o-mini
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_key: os.environ/AZURE_API_KEY_EAST_US_2
      api_base: os.environ/AZURE_API_BASE_EAST_US_2
      api_version: "2024-10-01-preview"

  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_key: os.environ/AZURE_API_KEY_NORTH_CENTRAL_US
      api_base: os.environ/AZURE_API_BASE_NORTH_CENTRAL_US
      api_version: "2024-10-01-preview"

  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_key: os.environ/AZURE_API_KEY_SWEDEN_CENTRAL
      api_base: os.environ/AZURE_API_BASE_SWEDEN_CENTRAL
      api_version: "2024-10-01-preview"

  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_key: os.environ/AZURE_API_KEY_WEST_US
      api_base: os.environ/AZURE_API_BASE_WEST_US
      api_version: "2024-10-01-preview"

  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_key: os.environ/AZURE_API_KEY_WEST_US_3
      api_base: os.environ/AZURE_API_BASE_WEST_US_3
      api_version: "2024-10-01-preview"

  # OpenAI Models: o1-preview
  - model_name: o1-mini
    litellm_params:
      model: azure/o1-mini
      api_key: os.environ/AZURE_API_KEY_EAST_US_2
      api_base: os.environ/AZURE_API_BASE_EAST_US_2
      api_version: "2024-10-01-preview"
      max_retries: 5

  - model_name: o1-preview
    litellm_params:
      model: azure/o1-preview
      api_key: os.environ/AZURE_API_KEY_EAST_US_2
      api_base: os.environ/AZURE_API_BASE_EAST_US_2
      api_version: "2024-10-01-preview"
      max_retries: 5
  # Anthropic Models: Claude 3.5 - Sonnet
  - model_name: claude-3.5-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY_1
      max_retries: 5

  # Anthropic Models: Claude 3.0 - Opus
  - model_name: claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY_1
      max_retries: 5

  # Anthropic Models: Claude 3.0 - Haiku
  - model_name: claude-3-haiku
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY_1
      max_retries: 5

  # Groq Models: Mistral Large 2 (24.07)
  - model_name: llama3-1-405b
    litellm_params:
      model: bedrock/meta.llama3-1-405b-instruct-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: us-west-2
      max_retries: 5

  # Groq Models: Mistral Large 2 (24.07)
  - model_name: mistral-large-2
    litellm_params:
      model: bedrock/mistral.mistral-large-2402-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: us-west-2
      max_retries: 5

  # AWS Bedrock Models: Cohere Command R Plus
  - model_name: command-r-plus
    litellm_params:
      model: bedrock/cohere.command-r-plus-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: us-west-2
      max_retries: 5
  # Google Vertex AI Studio: Gemini 1.5 Pro
  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro-latest
      api_key: os.environ/GEMINI_API_KEY
      max_retries: 5

  # Google Vertex AI Studio: Gemini 1.5 Flash
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash-latest
      api_key: os.environ/GEMINI_API_KEY
      max_retries: 5

# LiteLLM Global Settings
litellm_settings:
  cache: false
  redact_user_api_key_info: false
  success_callback: ["langfuse","sentry"]
  failure_callback: ["langfuse","sentry"]
  turn_off_message_logging: true
  redact_messages_in_exceptions: false
  log_raw_request_response: false
  context_window_fallbacks: [{"bedrock-sonnet":["gemini-1.5-pro"]},{"claude-3-haiku":["gemini-1.5-pro"]},{"claude-3-opus":["gemini-1.5-pro"]},{"claude-3.5-sonnet":["gemini-1.5-pro"]},{"command-r-plus":["gemini-1.5-pro"]},{"gemini-1.5-flash":["gemini-1.5-pro"]},{"gemini-1.5-pro":["gemini-1.5-pro"]},{"gpt-4-turbo":["gemini-1.5-pro"]},{"gpt-4o":["gemini-1.5-pro"]},{"gpt-4o-mini":["gemini-1.5-pro"]},{"llama3-1-405b":["gemini-1.5-pro"]},{"mistral-large-2":["gemini-1.5-pro"]},{"o1-mini":["gemini-1.5-pro"]},{"o1-preview":["gemini-1.5-pro"]}]
  fallbacks: [{"bedrock-sonnet":["claude-3-haiku","claude-3-opus","gpt-4o","gpt-4o-mini"]},{"claude-3-haiku":["claude-3-sonnet","claude-3-opus","gpt-4o","gpt-4o-mini"]},{"claude-3-opus":["claude-3-sonnet","claude-3-haiku","gpt-4o","gpt-4o-mini"]},{"claude-3.5-sonnet":["claude-3-haiku","claude-3-opus","gpt-4o","gpt-4o-mini"]},{"command-r-plus":["gpt-4o","gpt-4o-mini"]},{"gemini-1.5-flash":["gemini-1.5-pro","gpt-4o","gpt-4o-mini"]},{"gemini-1.5-pro":["gemini-1.5-flash","gpt-4o","gpt-4o-mini"]},{"gpt-4-turbo":["gpt-4o","gpt-4o-mini"]},{"gpt-4o":["gpt-4o-mini","gpt-4-turbo"]},{"gpt-4o-mini":["gpt-4o","gpt-4-turbo"]},{"llama3-1-405b":["gpt-4o","gpt-4o-mini"]},{"mistral-large-2":["gpt-4o","gpt-4o-mini"]},{"o1-mini":["o1-preview","gpt-4o","gpt-4o-mini"]},{"o1-preview":["o1-mini","gpt-4o","gpt-4o-mini"]}]
# General Settings
general_settings:
  database_connection_pool_limit: 10000
  health_check_interval: 600
  alerting: ["discord"]
  alerting_threshold: 1 # (Seconds) set an artifically low threshold for testing alerting
  alert_to_webhook_url: {
    "llm_exceptions": "https://discord.com/api/webhooks/1296060616984756264/jKIAVKjB3uIeGUBRCGaq6dwgOokhE",
    "llm_too_slow": "https://discord.com/api/webhooks/1296060229976457216/uNLZkSOHIG1hZo6L1bdfaCnOSO8Eq",
    "llm_requests_hanging": "https://discord.com/api/webhooks/1296060186204573748oGPeZf8WHDp1gKQKX0q01_EmXUZ61S",
    "budget_alerts": "https://discord.com/api/webhooks/1296060711025512498/t66wUvcn5Ukcf9etjL9dhJ3Clsdwr",
    "db_exceptions": "https://discord.com/api/webhooks/1296062092885102623/nIOSYx23x9ie6sITuQJGediPJTMKs",
    "daily_reports": "https://discord.com/api/webhooks/1296061355744301066/FH4lgFul_u72Z1ojtau7NQIOmsE5Q",
    "spend_reports": "https://discord.com/api/webhooks/1296061141453246515/pZKa2W7_AGUEUg9bhvftOwYiPYX-I",
    "cooldown_deployment": "https://discord.com/api/webhooks/1296062092885102623/nrUDPSb-Y9ie6sITuQJGediPJTMKs",
    "new_model_added": "https://discord.com/api/webhooks/1296062092885102623/nIOSJ-2-Y9ie6sITuQJGediPJTMKs",
    "outage_alerts": "https://discord.com/api/webhooks/1296061224177500190/sulOQO3NiMRLu6iUEef7C9_4VQGNw",
  }
  database_url: os.environ/DATABASE_URL
  database_type: "postgresql"
  master_key: os.environ/MASTER_API_KEY
```
