### ISSUE TITLE
`max_retries` is logged for Anthropic models on Vertex AI by mistake

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#6383]
@krrishdholakia @ishaan-jaff Do you have any idea why `max_retries` is being added onto Vertex AI requests?
<img width="846" alt="image" src="https://github.com/user-attachments/assets/33c6c3fb-1f88-41c9-b8a4-337c737f1e5f">

_Originally posted by @Manouchehri in https://github.com/BerriAI/litellm/issues/6380#issuecomment-2429944431_

**Comment by Manouchehri** [comment]
This seems to only have appeared on the new `claude-3-5-sonnet-v2@20241022`, which confuses me. I have `LITELLM_LOCAL_MODEL_COST_MAP: True` too, so it shouldn't be pulling anything from main.

**Comment by ghost** [comment]
Trying to repro. thanks for this @Manouchehri

**Comment by ghost** [comment]
<img width="1682" alt="Screenshot 2024-10-22 at 12 17 47 PM" src="https://github.com/user-attachments/assets/f6e885bd-dd71-4ef6-b87b-59180d2a4590">

looking at the raw request - no max_retries are being sent

**Comment by Manouchehri** [comment]
It's being sent to Cloudflare AI Gateway though?

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/cdf45aef-2929-4683-98b4-5e01fd0a5b1f">

**Comment by ghost** [comment]
can i see your request?

**Comment by Manouchehri** [comment]
What's the easiest way to log it with the least amount of log spam? :)

**Comment by ghost** [comment]
what is the request you're making to the proxy + what is your config (just need to see how you setup anthropic)

**Comment by Manouchehri** [comment]
I think this should work:

```yaml
litellm_settings:
  telemetry: False
  drop_params: True
  return_response_headers: True
  redact_messages_in_exceptions: True
  litellm_settings:

general_settings: 
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  database_connection_pool_limit: 1
  disable_spend_logs: True

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  cooldown_time: 10
  allowed_fails: 2
  num_retries_per_request: 5

model_list:
  - model_name: claude-3-5-sonnet-20241022-vertex-us-east5
    litellm_params:
      model: vertex_ai/claude-3-5-sonnet-v2@20241022
      vertex_project: REMOVED_PROJECT_ID
      vertex_location: us-east5
      max_tokens: 8192
      api_base: https://gateway.ai.cloudflare.com/v1/0399b10e77ac6668c80404a5ff49eb37/litellm-test/google-vertex-ai/v1beta1/projects/REMOVED_PROJECT_ID/locations/us-east5/publishers/anthropic/models/claude-3-5-sonnet-v2@20241022
```

```sh
curl -v "${OPENAI_API_BASE}/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "claude-3-5-sonnet-20241022-vertex-us-east5",
    "max_tokens": 1,
    "messages": [
      {
        "role": "user",
        "content": "Hello"
      }
    ]
  }'
```

**Comment by ghost** [comment]
not seeing this @Manouchehri 
<img width="1340" alt="Screenshot 2024-10-22 at 12 34 31 PM" src="https://github.com/user-attachments/assets/242507c2-c83f-45c6-8272-630bffd1fcc1">

**Comment by ghost** [comment]
```
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Hello!"
        }
      ]
    }
  ],
  "anthropic_version": "vertex-2023-10-16",
  "system": [
    {
      "type": "text",
      "text": "You are a helpful assistant."
    }
  ],
  "max_tokens": 4096
}
```

**Comment by ghost** [comment]
what version of litellm are you on?

**Comment by Manouchehri** [comment]
1.50.1 with cherry-picked commits for the model pricing of 3.5 Sonnet v2.

**Comment by ghost** [comment]
nope - not seeing this on v1.50.1 either - 

```bash
{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Hello!"
        }
      ]
    }
  ],
  "anthropic_version": "vertex-2023-10-16",
  "system": [
    {
      "type": "text",
      "text": "You are a helpful assistant."
    }
  ],
  "max_tokens": 4096
}
```

**Comment by ghost** [comment]
if you can share a log.txt with all the logs, it might help trace the issue. 

Besides that, not sure what the diff might be

**Comment by ghost** [comment]
for context - here's where we make the call for vertex anthropic - https://github.com/BerriAI/litellm/blob/24a0d26eb16fc9de8a6eeee6d639fd90efb78c5a/litellm/llms/anthropic/chat/handler.py#L384

**Comment by Manouchehri** [comment]
Could you share your YAML? 

There is half a million characters of logs generated in 60 seconds.. it's a lot of work to sanitize. =/

**Comment by Manouchehri** [comment]
```
LiteLLM completion() model= claude-3-5-sonnet-v2@20241022; provider = vertex_ai
[92m20:53:16 - LiteLLM:DEBUG[0m: utils.py:2743 - 
LiteLLM: Params passed to completion() {'model': 'claude-3-5-sonnet-v2@20241022', 'functions': None, 'function_call': None, 'temperature': None, 'top_p': None, 'n': None, 'stream': False, 'stream_options': None, 'stop': None, 'max_tokens': 1, 'max_completion_tokens': None, 'modalities': None, 'audio': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'custom_llm_provider': 'vertex_ai', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': 0, 'logprobs': None, 'top_logprobs': None, 'extra_headers': None, 'api_version': None, 'parallel_tool_calls': None, 'drop_params': None, 'additional_drop_params': None, 'messages': [{'role': 'user', 'content': 'Hello'}], 'vertex_project': 'REMOVED', 'vertex_location': 'us-east5'}
[92m20:53:16 - LiteLLM:DEBUG[0m: utils.py:2746 - 
LiteLLM: Non-Default params passed to completion() {'stream': False, 'max_tokens': 1, 'max_retries': 0}
[92m20:53:16 - LiteLLM:DEBUG[0m: utils.py:256 - Final returned optional params: {'stream': False, 'max_tokens': 1, 'max_retries': 0, 'vertex_project': 'REMOVED', 'vertex_location': 'us-east5'}
[92m20:53:16 - LiteLLM:DEBUG[0m: litellm_logging.py:385 - self.optional_params: {'stream': False, 'max_tokens': 1, 'max_retries': 0, 'vertex_project': 'REMOVED', 'vertex_location': 'us-east5'}
[92m20:53:22 - LiteLLM:DEBUG[0m: litellm_logging.py:469 - PRE-API-CALL ADDITIONAL ARGS: {'complete_input_dict': {'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': 'Hello'}]}], 'max_tokens': 1, 'max_retries': 0, 'anthropic_version': 'vertex-2023-10-16'}, 'api_base': 'https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/google-vertex-ai/v1beta1/projects/REMOVED/locations/us-east5/publishers/anthropic/models/claude-3-5-sonnet-v2@20241022:rawPredict', 'headers': {'accept': 'application/json', 'anthropic-version': '2023-06-01', 'content-type': 'application/json', 'x-api-key': 'REMOVED', 'x-zone': 'REMOVED', 'x-forwarded-for': 'REMOVED,172.70.83.147', 'x-forwarded-proto': 'https', 'x-client-port': '64992', 'x-colo-id': '368', 'x-forwarded-host': 'REMOVED', 'x-metal-id': '228', 'x-request-version': 'HTTP/2', 'x-server-ip': '104.18.1.141', 'x-server-port': '443', 'x-serverless-authorization': 'bearer REMOVED.SIGNATURE_REMOVED_BY_GOOGLE', 'x-threat-score': '0', 'x-verified-bot': 'false', 'x-cloud-trace-context': '1eef8c236c870661b6836e70066447e6/9441063472314849361;o=1', 'Authorization': 'Bearer REMOVED'}}
[92m20:53:22 - LiteLLM:DEBUG[0m: utils.py:256 - [92m
POST Request Sent from LiteLLM:
curl -X POST \
https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/google-vertex-ai/v1beta1/projects/REMOVED/locations/us-east5/publishers/anthropic/models/claude-3-5-sonnet-v2@20241022:rawPredict \
-H 'accept: *****' -H 'anthropic-version: *****' -H 'content-type: *****' -H 'x-api-key: REMOVED********************************************' -H 'x-zone: *****' -H 'x-forwarded-for: *****' -H 'x-forwarded-proto: *****' -H 'x-client-port: *****' -H 'x-colo-id: *****' -H 'x-forwarded-host: *****' -H 'x-metal-id: *****' -H 'x-request-version: *****' -H 'x-server-ip: *****' -H 'x-server-port: *****' -H 'x-serverless-authorization: bearer REMOVED********************************************' -H 'x-threat-score: *****' -H 'x-verified-bot: *****' -H 'x-cloud-trace-context: 1eef8c236c87********************************************' -H 'Authorization: Bearer REMOVED********************************************' \
-d '{'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': 'Hello'}]}], 'max_tokens': 1, 'max_retries': 0, 'anthropic_version': 'vertex-2023-10-16'}'
[0m
[92m20:53:22 - LiteLLM:DEBUG[0m: main.py:5314 - _is_function_call: False
[92m20:53:22 - LiteLLM:DEBUG[0m: utils.py:256 - RAW RESPONSE:
Client error '400 Bad Request' for url 'https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/google-vertex-ai/v1beta1/projects/REMOVED/locations/us-east5/publishers/anthropic/models/claude-3-5-sonnet-v2@20241022:rawPredict'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
[92m20:53:22 - LiteLLM:DEBUG[0m: exception_mapping_utils.py:2145 - Logging Details: logger_fn - None | callable(logger_fn) - False
[92m20:53:22 - LiteLLM:DEBUG[0m: litellm_logging.py:1839 - Logging Details LiteLLM-Failure Call: ['sentry', 'langfuse', <bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7f672e2c57d0>>, <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7f6732455d90>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7f6730dd91d0>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7f6731938f10>, <litellm._service_logger.ServiceLogging object at 0x7f672e0d9990>]
```

Do you see what you're looking for?

**Comment by ghost** [comment]
> LiteLLM: Non-Default params passed to completion() {'stream': False, 'max_tokens': 1, 'max_retries': 0}
�[92m20:53:16 - LiteLLM:DEBUG�[0m: utils.py:256 - Final returned optional params: {'stream': False, 'max_tokens': 1, 'max_retries': 0, 'vertex_project': 'REMOVED', 'vertex_location': 'us-east5'}

the error happens here 

---
For context this is what the final returned optional params for me looks like: 

```
LiteLLM: Non-Default params passed to completion() {'stream': False, 'max_tokens': 8192, 'max_retries': 0}
Final returned optional params: {'stream': False, 'max_tokens': 8192}
```

Config: 
```yaml
model_list:
  - model_name: claude-3-5-sonnet-20241022-vertex-us-east5
    litellm_params:
      model: vertex_ai/claude-3-5-sonnet-v2@20241022
      max_tokens: 8192

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  cooldown_time: 10
  allowed_fails: 2
  num_retries_per_request: 5

```
