### ISSUE TITLE
[Bug]: Langfuse not working using litellm client through LiteLLM Proxy

### ISSUE THREAD

**Issue by eliorc** [BerriAI/litellm#6423]
### What happened?

I am using the LiteLLM proxy, and also using the `litellm` python SDK to interact with the proxy.
In my `config.yaml`, I have `langfuse` configered
```yaml
... some other configurations

litellm_settings:
  num_retries: 3
  cooldown_time: 30
  cache: true
  cache_params:
      ....
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  langfuse_default_tags: ["cache_hit"]
```

I do **NOT** have `langfuse` configured as a callback in the client - only in the proxy.

What happens, is that everything gets logged on langfuse, but all the metadata sent, `session_id`, `trace_user_id`, `trace_id` and `generation_name` are all ignored. So I can find all my traces in `langfuse` eventually but without the metadata.
