### ISSUE TITLE
[Feature]: Add anthropic new model Haiku 3.5: claude-3-5-haiku-20241022

### ISSUE THREAD

**Issue by bofeng** [BerriAI/litellm#6589]
### The Feature

Anthropic just released Claude 3.5 Haiku: `claude-3-5-haiku-20241022` . It should be added to Litellm.

### Motivation, pitch

Claude 3.5 Haiku `claude-3-5-haiku-20241022` was just released by Anthropic and you can see it in this page https://docs.anthropic.com/en/docs/about-claude/models . LiteLLM should add it to the supported model list.

**Comment by ZhuoRoger** [comment]
The Stream mode doesn't work.

**Comment by mvrodrig** [comment]
Related to this:

**Issue:** `max_tokens` parameter unsupported for AWS Bedrock Claude 3.5 Haiku model.

It appears that the parameter `max_tokens` is not accepted in the request body. When including this parameter, I receive an error message indicating that it is an extraneous key. Here is an example of the request and the error response:

**Request Body:**

```
{
  "model": "awsbedrock/anthropic.claude-3.5-haiku",
  "messages": [
    {
      "role": "user", 
      "content": "hello in french"
    }
  ],
  "max_tokens": 500
}

```

**Error Response:**
```
{
  "error": {
    "message": "litellm.BadRequestError: BedrockException - {\"message\":\"Malformed input request: #: subject must not be valid against schema {\\\"required\\\":[\\\"messages\\\"]}#: extraneous key [max_tokens_to_sample] is not permitted, please reformat your input and try again.\"}\nReceived Model Group=awsbedrock/anthropic.claude-3.5-haiku\nAvailable Model Group Fallbacks=None",
    "type": null,
    "param": null,
    "code": "400"
  }
}
```

**Comment by hongbo-miao** [comment]
Met same issue for what @mvrodrig posted on Claude Haiku 3.5.
Tested on latest LiteLLM v1.52.0

**Comment by curvedinf** [comment]
Please add this! There is also the new Claude 3.5 Sonnet 2024-10-22 that needs to be added.

**Comment by bofeng** [comment]
> Please add this! There is also the new Claude 3.5 Sonnet 2024-10-22 that needs to be added.

@curvedinf the claude 3.5 Sonnet 2024-10-22 has been added already, see it here: https://github.com/BerriAI/litellm/issues/6377

**Comment by josperrod9** [comment]
Also having issues to connect from bedrock using **[cross-region inferencing](https://docs.litellm.ai/docs/providers/bedrock#cross-region-inferencing)**, here is an example of how I have added:
```yaml
model_list:
  - model_name: bedrock-claude-haiku-3-5
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
```
And here is the error response:
```json
{
  "error": {
    "message": "litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.anthropic.claude-3-5-haiku-20241022-v1:0\nReceived Model Group=bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0\nAvailable Model Group Fallbacks=None",
    "type": null,
    "param": null,
    "code": "404"
  }
}
```

**Comment by gemnioo** [comment]
have "The provided model identifier is invalid" error here for Haiku model. I can get response in bedrock playground. but can't access in liteLLM 

update: I could success request bedrock claude models in other application. but still get error in liteLLM PROXY ""The provided model identifier is invalid" 

litellm_config.yaml   
```
  - model_name: bedrock-claude-3-5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
  - model_name: bedrock-claude-3-haiku
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240620-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
```

```
docker run \
    -v $(pwd)/litellm_config.yaml:/app/config.yaml \
    --env-file litellm.env \
    -p 4000:4000 \
    ghcr.io/berriai/litellm:main-latest \
    --config /app/config.yaml --detailed_debug
```

KEYS and SECRET_ACCESS and REGION_NAM in litellm.env file double checked the region in us-east-1

and get error below 
```
root@user 
curl --location 'http://127.0.0.1:4000/chat/completions' \ons' \
    --header 'Content-Type: application/json' \
    --data '{
    "model": "bedrock-claude-3-haiku",
    "messages": [
        {
        "role": "user",
        "content": "who is sam altman"
        }
    ]
}'
{"error":{"message":"litellm.BadRequestError: BedrockException - {\"message\":\"The provided model identifier is invalid.\"}\nReceived Model Group=bedrock-claude-3-haiku\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"400"}}
```

**Comment by ajinkyaT** [comment]
Can confirm still not working with LiteLLM v1.52.0, 

`litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, 
model=us.anthropic.claude-3-5-haiku-20241022-v1:0
`

**Comment by gemnioo** [comment]
the "us.anthropic.claude-3-5-sonnet-20241022-v2:0" cross-region inference support in us-east-1 also have issue in some direct request bedrock api chat applications. 

https://github.com/lobehub/lobe-chat/issues/4458
https://github.com/danny-avila/LibreChat/discussions/4571
https://github.com/cline/cline/issues/689

**Comment by ubbikk** [comment]
I just found your lib, was happy, started refactoring/migrating, and then it turns out I always should wait before you add a new model? WTF? It's just parameter to call to Anthropic, why do you need manually whitelist it every time? Give me ability to just pass whatever model I want!
Your docs state: LiteLLM supports all anthropic models. WTF?

**Comment by gemnioo** [comment]
And test Vertex AI  Claude models. I can success request Vertex Gemini models, but can't get through Claude. looks this 429 error is GCP Vertex AI Quota exceeded bugs:

```
root@user:~# curl --location 'http://127.0.0.1:4000/chat/completions' \
    --header 'Authorization: Bearer jason678' \
    --header 'Content-Type: application/json' \
    --data '{
    "model": "vertex-claude-3-5-haiku",
    "messages": [
        {
        "role": "user",
        "content": "who is sam altman"
        }
    ]
}'
{"error":{"message":"litellm.RateLimitError: litellm.RateLimitError: VertexAIException - {\n  \"error\": {\n    \"code\": 429,\n    \"message\": \"Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: anthropic-claude-3-5-haiku. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.\",\n    \"status\": \"RESOURCE_EXHAUSTED\"\n  }\n}\n\nReceived Model Group=vertex-claude-3-5-haiku\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"429"}}
```
config in litellm_config.yaml
```
  - model_name: gemini-flash
    litellm_params:
      model: vertex_ai/gemini-1.5-flash-002
      vertex_project: "project_name"
      vertex_location: "us-central1"
      vertex_credentials: "/root/credentials,json"
  - model_name: gemini-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro
      vertex_project: "project_name"
      vertex_location: "us-central1"
      vertex_credentials: "/root/credentials,json"
  - model_name: vertex-claude-3-5-sonnet
    litellm_params:
      model: vertex_ai/claude-3-5-sonnet-v2@20241022
      vertex_project: "project_name"
      vertex_location: "us-east5"
      vertex_credentials: "/root/credentials,json"
  - model_name: vertex-claude-3-5-haiku
    litellm_params:
      model: vertex_ai/claude-3-5-haiku@20241022
      vertex_project: "project_name"
      vertex_location: "us-east5"
      vertex_credentials: "/root/credentials,json"
```

**Comment by gemnioo** [comment]
@josperrod9  I can connect from bedrock via [cross-region inferencing](https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-support.html), 

the correct Inference profile ID aka  'model identifier' is shows in the left corner in aws bedrock 

---Inference--Cross-region inference [Cross-region inference](https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#inference-profiles) 

'us.anthropic.claude-3-5-haiku-20241022-v1:0' and 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'

I could request bedrock in below config. 

```
  - model_name: bedrock-claude-3-5-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
  - model_name: bedrock-claude-3-5-haiku
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_REGION_NAME
```
