### ISSUE TITLE
[Bug]:  Litellm_proxyException - Connection error

### ISSUE THREAD

**Issue by xingyaoww** [BerriAI/litellm#6667]
### What happened?

LiteLLM proxy throwing the following error when sending really large request:

LiteLLM Proxy version `1.52.0`
```
  File "/Users/xingyaow/Projects/litellm/litellm/litellm_core_utils/exception_mapping_utils.py", line 404, in exception_type
    raise APIError(
litellm.exceptions.APIError: litellm.APIError: APIError: Litellm_proxyException - Connection error.
```

Code to repro:
[repro-llama-1.txt](https://github.com/user-attachments/files/17681092/repro-llama-1.txt)

**Comment by xingyaoww** [comment]
Just tried again on 1.52.12 - still not working.

Here's how the Llama model being served on llm-proxy:

```
      - model_name: "Llama-3.1-405b-instruct"
        litellm_params:
            model: "fireworks_ai/accounts/fireworks/models/llama-v3p1-405b-instruct"
            api_key: os.environ/FIREWORKS_AI_API_KEY
        model_info:
          input_cost_per_token: 0.000003
          output_cost_per_token: 0.000003
          supports_function_calling: true
```
