### ISSUE TITLE
[Bug]: Wildcard provider does not list mistral models

### ISSUE THREAD

**Issue by samling** [BerriAI/litellm#6669]
### What happened?

I'm not sure whether this is a bug or (currently) expected behavior, but I get inconsistent behavior between providers when providing a single wildcard model and the appropriate API key environment variables. For example:

```
# .env
OPENAI_API_KEY=(my_openai_key)
MISTRAL_API_KEY=(my_mistral_key)
```

```
# config.yaml
model_list:
  - model_name: "*"
    litellm_params:
      model: "*"
```

Doing a `curl http://localhost:4000/v1/models` will only return openai models. [This issue](https://github.com/BerriAI/litellm/issues/4903) reported the same feature request and was closed with a commit that ostensibly added that functionality, but I'm unclear whether I'm doing something wrong or if certain providers still don't support this.

Thanks in advance!

**Comment by krrishdholakia** [comment]
Unable to repro the regression, this works as expected

## API Response 
<img width="1175" alt="Screenshot 2024-11-11 at 12 36 02 PM" src="https://github.com/user-attachments/assets/fd31df74-4e5c-4c29-a144-da3992ff6014">

## Config 

```yaml
model_list:
  - model_name: "*"
    litellm_params:
      model: "*"
```
