### ISSUE TITLE
[Feature]: Azure True/False environment variable to use completion models

### ISSUE THREAD

**Issue by mohd-jubair** [BerriAI/litellm#6678]
### The Feature

I would be nice to have a azure environment variable which can be given as a bool to identify whether we are using azure operator or openai operator.

### Motivation, pitch

Improve working repository by handling things with environment variables.

**Comment by ghost** [comment]
The provider can be specified in the model name with `<provider>/<model-name>` 

You can also provide this provider via the separate `custom_llm_provider` param 

```
completion(model="<model-name">, custom_llm_provider="openai" or "azure",...) 
```

if this is via proxy, you can set the provider as an env var 

```
model_name: gpt-3.5-turbo
litellm_params: 
   model: gpt-3.5-turbo
   custom_llm_provider: os.environ/PROVIDER 
```
