### ISSUE TITLE
[Bug]: OpenAI's optional `messages[].name` crashes the LiteLLM proxy with mistral api 

### ISSUE THREAD

**Issue by JMLX42** [BerriAI/litellm#6696]
### What happened?

When calling [the `POST /v1/chat/completion/` endpoint](https://platform.openai.com/docs/api-reference/chat/create), the user can add a `name` field to each message:

> `name` `string` Optional
> 
> An optional name for the participant. Provides the model information to differentiate between participants of the same role.

Actually using that optional `messages[].name` property crashes LiteLLM proxy if the backend is not the OpenAI backend.

## How to reproduce

```yml
version: "3.9"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    command: ["--config", "/app/config.yml", --detailed_debug]
```

```yml
---

model_list:
  - model_name: gpt-4o
    litellm_params:
      model: mistral/mistral-large-latest
      api_base: https://api.mistral.ai/v1
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-large
    litellm_params:
      model: mistral/mistral-large-latest
      api_base: https://api.mistral.ai/v1
      api_key: "os.environ/MISTRAL_API_KEY"

litellm_settings:
  drop_params: true

router_settings:
  fallbacks:
    - { "gpt-4o": ["mistral-large"] }
```

```bash
curl --location 'http://0.0.0.0:4000/v1/chat/completions' \
    --header 'Content-Type: application/json' \
    --data '{
  "messages": [
    { "content": "test", "role": "user", "name": "user" }
  ],
  "model": "gpt-4o",
}'
```

## Related

- https://github.com/microsoft/autogen/issues/2989

### Relevant log output

```shell
litellm-1  | 17:30:59 - LiteLLM:DEBUG: utils.py:264 - Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x7f139e4d7210>>
litellm-1  | 17:30:59 - LiteLLM:DEBUG: utils.py:264 - Logging Details LiteLLM-Success Call: Cache_hit=None
litellm-1  | 17:30:59 - LiteLLM Router:INFO: router.py:932 - litellm.acompletion(model=mistral/mistral-large-latest) 200 OK
litellm-1  | 17:30:59 - LiteLLM:DEBUG: litellm_logging.py:880 - success callbacks: [<bound method Router.sync_deployment_callback_on_success of <litellm.router.Router object at 0x7f139e519150>>, <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7f139f19f050>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7f139f966410>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7f139f972a90>, <litellm._service_logger.ServiceLogging object at 0x7f139fc461d0>]
litellm-1  | 17:30:59 - LiteLLM Router:DEBUG: router.py:2675 - Async Response: None
litellm-1  | 17:30:59 - LiteLLM:DEBUG: utils.py:264 - Logging Details LiteLLM-Async Success Call, cache_hit=None
litellm-1  | 17:30:59 - LiteLLM Router:ERROR: router.py:3378 - litellm.router.Router::deployment_callback_on_success(): Exception occured - 'NoneType' object has no attribute 'get'
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 3344, in deployment_callback_on_success
litellm-1  |     _usage_obj = completion_response.get("usage")
litellm-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  | AttributeError: 'NoneType' object has no attribute 'get'
litellm-1  | 17:30:59 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:48 - INSIDE parallel request limiter ASYNC SUCCESS LOGGING
litellm-1  | 17:30:59 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:48 - updated_value in success call: {'current_requests': 0, 'current_tpm': 0, 'current_rpm': 1}, precise_minute: 2024-11-11-17-30
litellm-1  |
litellm-1  | #------------------------------------------------------------#
litellm-1  | #                                                            #
litellm-1  | #       'This feature doesn't meet my needs because...'       #
litellm-1  | #        https://github.com/BerriAI/litellm/issues/new        #
litellm-1  | #                                                            #
litellm-1  | #------------------------------------------------------------#
litellm-1  |
litellm-1  |  Thank you for using LiteLLM! - Krrish & Ishaan
litellm-1  |
litellm-1  |
litellm-1  |
litellm-1  | Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
litellm-1  |
litellm-1  |
litellm-1  | LiteLLM: Proxy initialized with Config, Set models:
litellm-1  |     gpt-4o
litellm-1  |     mistral-large
litellm-1  | INFO:     172.18.0.1:57002 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

### Twitter / LinkedIn details

https://x.com/JMLX42
