### ISSUE TITLE
[Bug]: Support bedrock/stability.stable-image-ultra-v1:0

### ISSUE THREAD

**Issue by rasodu** [BerriAI/litellm#6722]
### What happened?

[ERROR: litellm.BadRequestError: BedrockException - Embedding Error with model stability.stable-image-ultra-v1:0: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: #: required key [prompt] not found, please reformat your input and try again. Received Model Group=sd_ultra_v1 Available Model Group Fallbacks=None]

**My config**
```
  - model_name: sd_ultra_v1
    litellm_params:
      model: bedrock/stability.stable-image-ultra-v1:0
      aws_region_name: us-west-2
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      output_cost_per_image: 0.16
      max_tokens: 10000
      max_input_tokens: 10000                              # Defined on bedrock page
    model_info:
      mode: image_generation
```
