### ISSUE TITLE
[Bug]: Tag Based Routing redirecting to default model

### ISSUE THREAD

**Issue by kunalchamoli** [BerriAI/litellm#6770]
### What happened?

I was trying to do tag based routing in LiteLLM, but it redirects to "default" tag more than the tag that i am passing in the request:

Example Config 
```
  - model_name: mock-llm
    litellm_params:
      model: openai/kunal-llm1
      api_key: kunal-123
      api_base: http://random-ip:4001/v1/
      tags: ["medium"]
  - model_name: mock-llm
    litellm_params:
      model: openai/kunal-llm2
      api_key: kunal-123
      api_base: http://another-random-ip:4001/v1/
      tags: ["default"]      
```      
Can you tell what i am doing wrong, as i can see i am not hitting tpm/rpm limits of any "medium" tagged model.
