### ISSUE TITLE
[Bug]: In LiteLLM Python SDK, `rerank()` only works when `litellm.api_base` is ended with `/rerank`

### ISSUE THREAD

**Issue by dinhanhx** [BerriAI/litellm#6844]
## The problem 

This does **not** work
```python
import litellm

litellm.api_base = "http://localhost:4000"
litellm.set_verbose = True

text = "Hello there!"
list_texts = ["Hello there!", "How are you?", "How do you do?"]

rerank_model = "rerank-multilingual-v3.0"
rerank_response = litellm.rerank(
    model=rerank_model,
    query=text,
    documents=list_texts,
    custom_llm_provider="cohere"
)

```

This works perfectly
```python
import litellm

litellm.api_base = "http://localhost:4000/rerank"
litellm.set_verbose = True

text = "Hello there!"
list_texts = ["Hello there!", "How are you?", "How do you do?"]

rerank_model = "rerank-multilingual-v3.0"
rerank_response = litellm.rerank(
    model=rerank_model,
    query=text,
    documents=list_texts,
    custom_llm_provider="cohere"
)
```
## Why do I think it's a problem?

It's inconsistent with other functions (litellm.embedding, lite.completion). They don't need `/embedding` and `/completion` to accompany the litellm.api_base. 

## My LiteLLM setup

config.yaml
```yml
model_list:
  - model_name: rerank-multilingual-v3.0
    litellm_params:
      model: cohere/rerank-multilingual-v3.0
      api_key: os.environ/COHERE_API_KEY
```

docker run
```bash
docker run -d --env-file .env -v .:/app/ -p 4000:4000 --name litellm --rm  ghcr.io/berriai/litellm:main-latest --config /app/config.yaml --detailed_debug
```
