### ISSUE TITLE
[Feature]: support tracking remaining tpm/rpm for gemini models 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#6914]
### The Feature

Support tracking remaining tpm/rpm for gemini models 

- allows prometheus metrics to capture this information

User config.yaml 

```yaml
model_list: 
   - model_name: gemini/*
      litellm_params: 
         model: gemini/*
```

### Motivation, pitch

allows user to know how often they're hitting their rate limits on gemini
