### ISSUE TITLE
[Bug]: /v1/moderations requires `model` param 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#6946]
### What happened?

This request fails 

```
curl --location 'http://0.0.0.0:4000/moderations' \
    --header 'Content-Type: application/json' \
    --header 'Authorization: Bearer sk-1234' \
    --data '{"input": "Sample text goes here"}'
```

config used:

```
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
  - model_name: fake-anthropic-endpoint
    litellm_params:
      model: anthropic/fake
      api_base: https://exampleanthropicendpoint-production.up.railway.app/

litellm_settings:
  callbacks: ["datadog"] 

```
