### ISSUE TITLE
[Bug]: hardcoded postgres db url when `useExisting: true` for migration job

### ISSUE THREAD

**Issue by justinthelaw** [BerriAI/litellm#6985]
### DESCRIPTION

See [CONTEXT](#context) for exact lines of code.

When `useExisting: true`, the PostgresDB is a hardcoded secret within a values file, that gets consumed by the prisma migration job. This is a K8s anti-pattern. We should instead be using an in-cluster secret that dynamically creates the URL using the `envFrom` key in the job manifest to build the URL of an existing, hosted database.

For future, larger refactors, we should consider encoding the database URL as a secret in a volume mount of the job and deployment pods so that it is not exposed as a transparent value in the rendered manifests, and so that it is not an environment variable that is easily readable from the container's runtime.

### POSSIBLE SOLUTION

Below is the simple solution mentioned in the description above. It is not the larger refactor, as that may require more breaking changes to the Python code and Helm charts:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "litellm.fullname" . }}-migrations
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: Never # keep this resource so we can debug status on ArgoCD
    checksum/config: {{ toYaml .Values | sha256sum }}
spec:
  template:
    spec:
      containers:
        - name: prisma-migrations
          image: ghcr.io/berriai/litellm-database:main-latest
          command: ["python", "litellm/proxy/prisma_migration.py"]
          workingDir: "/app"
          env:
            {{- if .Values.db.useExisting }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: {{ .Values.db.secret.usernameKey }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: {{ .Values.db.secret.passwordKey }}
            - name: DATABASE_HOST
              value: {{ .Values.db.endpoint | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.db.database | quote }}
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_NAME)
            {{- else }}
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql/{{ .Values.postgresql.auth.database }}
            {{- end }}
            - name: DISABLE_SCHEMA_UPDATE
              value: "false" # always run the migration from the Helm PreSync hook, override the value set
      restartPolicy: OnFailure
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}
```

### CONTEXT

Line of code in question: https://github.com/BerriAI/litellm/blob/13e8e94c3f0459876a34d6c4d2dc89fff05f5c9a/deploy/charts/litellm-helm/templates/migrations-job.yaml#L22
