### ISSUE TITLE
[Bug]: "timeout" and "stream_timeout" being reset in prod instance - unclear why

### ISSUE THREAD

**Issue by jeromeroussin** [BerriAI/litellm#7001]
### What happened?

I am setting both "timeout" and "stream_timeout" in my config.yaml like below. 

```yaml
- model_name: "gpt-4o"
    litellm_params:
      model: "azure/gpt-4o"
      api_key: "os.environ/AZURE_API_KEY_EU2"
      api_base: "os.environ/AZURE_API_BASE_EU2"
      api_version: "os.environ/AZURE_API_VERSION"
      timeout: 300
      stream_timeout: 120
      tpm: 5000000
      tags: ["East US 2"]
    model_info:
      mode: "chat"
      base_model: "azure/gpt-4o"
      <truncated>

```

I do not set `request_timeout` under litellm_settings:
```yaml
litellm_settings:
  num_retries: 0
  callbacks: callback.handler
  drop_params: true
  # request_timeout: 120
  # set_verbose: true
```

What I am observing is that some requests (likely hung for a reason or another) do not get timed out until they reach exactly 6000s, which is the default for request_timeout: https://github.com/BerriAI/litellm/blob/04238cd9a97e802b2637924b8eed46c9012878c6/litellm/__init__.py#L297

I therefore question whether `timeout` and `stream_timeout` really do what they are supposed to do: https://docs.litellm.ai/docs/proxy/reliability#custom-timeouts-stream-timeouts---per-model

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.53.1

### Twitter / LinkedIn details

https://www.linkedin.com/in/jeromeroussin/
