### ISSUE TITLE
[Bug]: AzureOpenAI deployment with global standard mode is not detected properly

### ISSUE THREAD

**Issue by pascallim** [BerriAI/litellm#7004]
### What happened?

I am setting the YAML configuration to point to my AzureOpenAI deployments that are set to global standard options. 

```yaml
model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
```
When I check for the cost this is the non global standard prices:
![image](https://github.com/user-attachments/assets/077faac6-082f-43b7-b46b-1baed166f232)

Thank you for the help!

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.52.16
