### ISSUE TITLE
[Bug]: cross-region inferencing for bedrock models not working

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#7029]
### What happened?

Just like reported in past via #5899 facing issue in adding the new amazon nova models which are exclusively available via cross-region inferencing:

```
- model_name: amazon.nova-micro-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-micro-v1:0
      aws_region_name: us-west-2
```
error:
`'error': 'error:litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.amazon.nova-micro-v1:0.`

then tried below as per docs https://litellm.vercel.app/docs/providers/bedrock#set-converse--invoke-route :
```
- model_name: amazon.nova-micro-v1:0
    litellm_params:
      model: bedrock/converse/us.amazon.nova-micro-v1:0
      aws_region_name: us-west-2
```
error:
`{'aws_region_name': 'us-west-2', 'model': 'bedrock/converse/us.amazon.nova-micro-v1:0', 'cache': {'no-cache': True}, 'error': 'error:litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=converse/us, model=converse/us.amazon.nova-micro-v1:0.`

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.52.0
