### ISSUE TITLE
[Bug]: ollama_chat with yi-coder and proxy results in error: LLM Provider NOT provided

### ISSUE THREAD

**Issue by bgeneto** [BerriAI/litellm#7039]
### What happened?

setup a new model like this:

```json
  - model_name: 'yi-coder'
    litellm_params:
      model: 'ollama_chat/yi-coder:latest'
      provider: ollama_chat
      api_base: 'https://your-ollama-server-url'
```

Try to chat with this model via curl and got this error:
```
litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=yi-coder Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)`
```

### Relevant log output

```shell
v
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.7

**Comment by ghost** [comment]
> provider: ollama_chat

there's no field called 'provider'

**Comment by ghost** [comment]
Unable to repro. this works as expected. Please share the full config + request being made to proxy, for repro.

**Comment by bgeneto** [comment]
> Unable to repro. this works as expected. Please share the full config + request being made to proxy, for repro.

01. It follows a minimal `config.yaml` file:

```yaml
general_settings:
  master_key: sk_12345678
  litellm_salt_key: sk_87654321
  database_url: 'postgresql://litellm:litellm@127.0.0.1:5432/litellm'

litellm_settings:
  json_logs: true
  set_verbose: false
  cache: false

model_list:
  - model_name: 'yi-coder'
    litellm_params:
      model: 'ollama_chat/yi-coder:latest'
      api_base: 'http://localhost:11434'
```

02. And a curl request:

```bash
curl --location 'http://127.0.0.1:4000/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data-raw '{
    "stream": false,
    "model": "yi-coder",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful coding assistant"
        },
        {
            "role": "user",
            "content": "A hello world code in your preferred language... you choose!"
        }
    ],
    "num_retries": 0,
    "request_timeout": 3
}'
```

03. And finally the output/error:

```json
{
    "error": {
        "message": "litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=yi-coder\n Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providersNo fallback model group found for original model_group=yi-coder.",
        "type": null,
        "param": null,
        "code": "400"
    }
}
``` 

> **NOTE:** This error also happens with other ollama models like: "granite3-dense:8b", "granite-code:8b"
