### ISSUE TITLE
LiteLLM Server with ollama

### ISSUE THREAD

**Issue by imikod** [BerriAI/litellm#708]
I am running LiteLLM Server locally and I want to use it with ollama that is already running.
What do I need to configure?
The [docs](https://docs.litellm.ai/docs/simple_proxy) only mention about API keys in the Environment.
Is it not possible?

**Comment by ghost** [comment]
hey @imikod just run it with the ollama/<ollama_model_name> no api key required. 

```shell
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "ollama/mistral",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7,
   }'
```

**Comment by imikod** [comment]
Thank you @krrishdholakia for your help.
I think you mean to run `litellm --model ollama/<ollama_model_name>`  but this way the ollama must be in the same machine which is not in my case.
Also there is a notice that the Local OpenAI Proxy Server is [deprecated](https://docs.litellm.ai/docs/proxy_server)
This is why I tried to use [litellm-server](https://github.com/BerriAI/litellm/tree/main/litellm_server#litellm-server).

**Comment by krrishdholakia** [comment]
@imikod 
```python
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "ollama/mistral",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7,
     "api_base": <your_ollama_api_base>
   }'
```

**Comment by ghost** [comment]
@imikod you can do this via config. Give me an hour, i'll have the docs up.

**Comment by imikod** [comment]
Thank you very much @krrishdholakia.
I was really confused for quite some time.

**Comment by ghost** [comment]
Hey @imikod updated the litellm server with instructions. 

Here's how to do it: 

1. Create a `config.yaml` 
```yaml
model_list:
  - model_name: ollama/mistral # name of the model hitting the /chat/completions endpoint
    litellm_params:
      model: ollama/mistral
      api_base: your_ollama_api_base
```

2. Start the server
```shell
docker run -e PORT=8000 -p 8000:8000 -v $(pwd)/config.yaml:/app/config.yaml ghcr.io/berriai/litellm:latest
```

**Comment by ghost** [comment]
Let me know if that solves your issue.

**Comment by imikod** [comment]
I build the docker container with this [Dockerfile](https://github.com/BerriAI/litellm/blob/main/litellm_server/Dockerfile).
Then I made a config.yaml

```
model_list:
  - model_name: mistral
    litellm_params:
      model: ollama/mistral
      api_base: my_ollama_api_base
```

and I started the server
`docker run -e PORT=8000 -p 8000:8000 -v $(pwd)/config.yaml:/app/config.yaml litellm_server:latest`

but when I visit `http://127.0.0.1:8000/models` the list is empty. I think it should list the model.
I am able to use curl like you suggested initially and it works with `"model": "ollama/mistral"` but it does not work with  `"model": "mistral"`.

**Comment by imikod** [comment]
I rebuild the image with the new changes. And it works when I use `"model": "mistral"`. But the models list is empty.

**Comment by ghost** [comment]
does models list being empty mean the curl command for `/models` returns an empty list? 

That's because we infer list from keys. so yea you're right we should update it to also account for the model list you pass in. 

I'll make the change now.

**Comment by imikod** [comment]
Yes this is exactly what I mean.

Also I am not sure where to put `drop_params = true`.

**Comment by ghost** [comment]
@imikod do you have some sort of project you're using this with? it'll be helpful for me to test it against and make sure it's working for that.

**Comment by ghost** [comment]
Just added support for module level settings on litellm via the config - https://github.com/BerriAI/litellm/commit/0ee9c61090f6acaaea27b00aa13a441d2081774b

@imikod pull the latest image and include this snippet in your yaml 

```yaml
# Global settings for the litellm module
litellm_settings:
  drop_params: True
```
