### ISSUE TITLE
[Bug]: Bedrock 'converse/' prefix model is not streamable

### ISSUE THREAD

**Issue by inker610566** [BerriAI/litellm#7120]
### What happened?

I try to config my proxy yaml config 'converse/arn_to_profile_name' model as the follow
config.yaml
```
model_list:
  - model_name: aws-bedrock-custom-with-profile
    litellm_params:
      model: converse/arn_to_profile_name
      custom_llm_provider: bedrock
      aws_access_key_id: ...
      aws_secret_access_key: ...
      aws_region_name: ...

litellm_settings:
  drop_params: True
```

It works for calling normal `/chat/completions` endpoint without streaming option.
But when I specify json payload like
'''
{
"model":"aws-bedrock-custom-with-profile",
"stream": true,
"messages": [{"role": "user", "content": "gm who are u"}]
}
'''

It report this exception:
```
data: {"error": {"message": "'async for' requires an object with __aiter__ method, got ModelResponse\n\nTraceback (most recent call last):\n  File \"/Users/jenwei-kuo/workspace/litellm-jp/ENV311_NEW_litellm/lib/python3.11/site-packages/litellm/proxy/proxy_server.py\", line 2670, in async_data_generator\n    async for chunk in response:\nTypeError: 'async for' requires an object with __aiter__ method, got ModelResponse\n", "type": "None", "param": "None", "code": "500"}}
```

### Relevant log output

```shell
{"error": {"message": "'async for' requires an object with __aiter__ method, got ModelResponse\n\nTraceback (most recent call last):\n  File \"/Users/jenwei-kuo/workspace/litellm-jp/ENV311_NEW_litellm/lib/python3.11/site-packages/litellm/proxy/proxy_server.py\", line 2670, in async_data_generator\n    async for chunk in response:\nTypeError: 'async for' requires an object with __aiter__ method, got ModelResponse\n", "type": "None", "param": "None", "code": "500"}}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.9
