### ISSUE TITLE
[Bug]: UI Dashboard Login Generates Duplicate API Keys

### ISSUE THREAD

**Issue by huangyafei** [BerriAI/litellm#7126]
### What happened?

I'm using Docker to deploy LiteLLM.

However, I noticed that every time I log into the LiteLLM UI Dashboard, it automatically generates a new API Key for default_user.

Current version: 1.54.0

## Steps to Reproduce:

1. GET /key/list

```
"total_count": 10
```

2. Login to UI Dashboard via https://litellm_url/ui

3. GET /key/list

```
"total_count": 11
```

4. Login to UI Dashboard via https://litellm_url/ui

5. GET /key/list

```
"total_count": 12
```

## Reference Information:

Below are my Docker Compose file and config.yaml file:

docker-compose.yaml

```yaml
version: '3.8'

services:
  litellm:
    image: ghcr.io/berriai/litellm-database:main-latest
    expose:
      - 4000
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      DATABASE_URL: ${DB_URL}
      STORE_MODEL_IN_DB: True
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_HOST}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    volumes:
      - ../files/litellm/litellm_config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--detailed_debug"]
```

config.yaml

```yaml
model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: text-embedding-3-large
    litellm_params:
      model: text-embedding-3-large
      api_key: os.environ/OPENAI_API_KEY
  - model_name: text-embedding-3-small
    litellm_params:
      model: text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY
  - model_name: text-embedding-ada-002
    litellm_params:
      model: text-embedding-ada-002
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  default_fallbacks: ["gpt-4o"]
  success_callback: ["langfuse"]

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 3

general_settings: 
  alerting: ["slack"]
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.54.0
