### ISSUE TITLE
Feature: Gemini Flash 2.0

### ISSUE THREAD

**Issue by themrzmaster** [BerriAI/litellm#7188]
Add flash 2.0 to supported models.
There is function calling and web tool, thats kind of perplexity.

**Comment by patricksrail** [comment]
Is there an easy way to self-add models yet? Would be amazing to try new models right away, without waiting for library update, in cases where the only difference is model name without changes to api or prompt etc. Especially with new models coming out daily.

Anyway, +1 to this ask.

**Comment by sammcj** [comment]
```yaml
  # Google Gemini
  - model_name: gemini-2.0-flash-exp
    litellm_params:
      model: "gemini/gemini-2.0-flash-exp"
      api_key: os.environ/GEMINI_API_KEY
```

Seems to work
