### ISSUE TITLE
[Bug]: Added realtime model but fails health check

### ISSUE THREAD

**Issue by taralika** [BerriAI/litellm#7212]
### What happened?

Added in config.yaml:
```
- model_name: gpt-4o-realtime-preview
    litellm_params:
      model: azure/gpt-4o-realtime-preview
      api_base: os.environ/AOAI_BASE
      api_key: os.environ/AOAI_KEY
```

/health:
`error:Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, gpt-4o-realtime-preview. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}. Missing `mode`. Set the `mode` for the model - https://docs.litellm.ai/docs/proxy/health#embedding-models`

Followed these instructions: https://docs.litellm.ai/docs/realtime#add-model-to-config which do not have info on what `mode` to use for realtime model.

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.53.7

**Comment by taralika** [comment]
@krrishdholakia @ishaan-jaff any updates on this issue? I've even tried adding `mode: realtime` but that didn't help. What's the trick to get this working?

**Comment by taralika** [comment]
Also the test script here: https://docs.litellm.ai/docs/realtime#test works fine if I run it directly against azure realtime model, but fails with this error when running it against litellm/proxy: `Error:  Error: Unexpected server response: 403` - I'm passing the litellm proxy api key in `api_key` (instead of the azure resource api key) so not sure what else to do to fix this, would greatly appreciate any help.

**Comment by ishaan-jaff** [comment]
checking, @taralika do you also have an e2e test / script your hoping to use realtime endpoints for ?

**Comment by ishaan-jaff** [comment]
> Also the test script here: https://docs.litellm.ai/docs/realtime#test works fine if I run it directly against azure realtime model,

This works perfectly fine for me @taralika - are you passing the correct api_key in test.js and are you on the latest litellm version ? 

config

```
model_list:
  - model_name: openai-gpt-4o-realtime-audio
    litellm_params:
      model: azure/gpt-4o-realtime-preview
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
```

Test

```js
// test.js
import WebSocket from 'ws';

const url = "ws://0.0.0.0:4000/v1/realtime?model=openai-gpt-4o-realtime-audio";
const ws = new WebSocket(url, {
    headers: {
        "api-key": `sk-1234`,
        "OpenAI-Beta": "realtime=v1",
    },
});

ws.on("open", function open() {
    console.log("Connected to server.");
    ws.send(JSON.stringify({
        type: "response.create",
        response: {
            modalities: ["text"],
            instructions: "Please assist the user.",
        }
    }));
});

ws.on("message", function incoming(message) {
    console.log(JSON.parse(message.toString()));
});

ws.on("error", function handleError(error) {
    console.error("Error: ", error);
});
```
