### ISSUE TITLE
[Bug]: input_cost_per_character not being tracked for Azure TTS in LiteLLM Proxy

### ISSUE THREAD

**Issue by marty-sullivan** [BerriAI/litellm#7223]
### What happened?

When I configure OpenAI tts-1 models like the following, they work fine when called and they show the proper `input_cost_per_character` in the effective model_info in the running proxy as I've shared below.

However, no usage gets tracked for these models (or at least it is not visible on the Usage page). 

All other models I've set up, usage tracking is working fine, including LLM input / output tokens, text-to-image and embedding input tokens.

I would expect that TTS usage is tracked in the same way, given that the code and effective configuration implies usage tracking is supported for TTS models.

config.yml:

```yaml
model_list: 

  - model_name: 'openai.tts'
    litellm_params:
      model: 'azure/tts-1'
      api_base: '<api_base>'
      api_version: '2024-05-01-preview'
      api_key: '<api_key>'

  - model_name: 'openai.tts-hd'
    litellm_params:
      model: 'azure/tts-1-hd'
      api_base: '<api_base>'
      api_version: '2024-05-01-preview'
      api_key: '<api_key>'
```

effective model_info reported by LiteLLM:

```json
{
  "model_name": "openai.tts",
  "litellm_params": {
    "api_base": "<api_base>",
    "api_version": "2024-05-01-preview",
    "model": "azure/tts-1"
  },
  "model_info": {
    "id": "<id>",
    "db_model": false,
    "key": "azure/tts-1",
    "max_tokens": null,
    "max_input_tokens": null,
    "max_output_tokens": null,
    "input_cost_per_token": 0,
    "cache_creation_input_token_cost": null,
    "cache_read_input_token_cost": null,
    "input_cost_per_character": 0.000015,
    "input_cost_per_token_above_128k_tokens": null,
    "input_cost_per_query": null,
    "input_cost_per_second": null,
    "input_cost_per_audio_token": null,
    "output_cost_per_token": 0,
    "output_cost_per_audio_token": null,
    "output_cost_per_character": null,
    "output_cost_per_token_above_128k_tokens": null,
    "output_cost_per_character_above_128k_tokens": null,
    "output_cost_per_second": null,
    "output_cost_per_image": null,
    "output_vector_size": null,
    "litellm_provider": "azure",
    "mode": "audio_speech",
    "supported_openai_params": [
      "temperature",
      "n",
      "stream",
      "stream_options",
      "stop",
      "max_tokens",
      "max_completion_tokens",
      "tools",
      "tool_choice",
      "presence_penalty",
      "frequency_penalty",
      "logit_bias",
      "user",
      "function_call",
      "functions",
      "tools",
      "tool_choice",
      "top_p",
      "logprobs",
      "top_logprobs",
      "response_format",
      "seed",
      "extra_headers",
      "parallel_tool_calls"
    ],
    "supports_system_messages": null,
    "supports_response_schema": null,
    "supports_vision": false,
    "supports_function_calling": false,
    "supports_assistant_prefill": false,
    "supports_prompt_caching": false,
    "supports_audio_input": false,
    "supports_audio_output": false,
    "supports_pdf_input": false,
    "tpm": null,
    "rpm": null
  },
  "provider": "azure",
  "input_cost": 0,
  "output_cost": 0,
  "litellm_model_name": "azure/tts-1",
  "max_tokens": null,
  "max_input_tokens": null,
  "api_base": "<api_base>",
  "cleanedLitellmParams": {
    "api_version": "2024-05-01-preview"
  }
}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.2
