### ISSUE TITLE
Unable to use any Azure AI models with `services.ai.azure.com` url

### ISSUE THREAD

**Issue by semidark** [BerriAI/litellm#7275]
### Discussed in https://github.com/BerriAI/litellm/discussions/7098

<div type='discussions-op-text'>

<sup>Originally posted by **semidark** December  9, 2024</sup>
**Hi Folks,**

I just got started with LiteLLM as a proxy because I needed an OpenAI-compatible API for my Azure AI Service. I began by working with OpenAI models (`gpt-4o` and `gpt-4o-mini`), and everything worked perfectly. So I thought, *why not try some other models?* I attempted to use `Mistral-large`.

Here’s my configuration:

```yaml
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: "https://censored.openai.azure.com/"
      api_key: "censored"
      api_version: "2024-05-01-preview"
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: "https://censored.openai.azure.com/"
      api_key: "censored"
      api_version: "2024-05-01-preview"
  - model_name: Mistral-large
    litellm_params:
      model: azure_ai/Mistral-large
      api_base: "https://censored.services.ai.azure.com/"
      api_key: "censored"
      api_version: "2024-05-01-preview"
```

I tried a few variations of the model string (`mistral-large`,`Mistral-large-latest`,`mistral-large`), but nothing worked. I always receive the following error:

```
23:01:35 - LiteLLM Proxy:DEBUG: proxy_server.py:3494 - An error occurred: litellm.NotFoundError: NotFoundError: Azure_aiException - Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
Received Model Group=Mistral-large
Available Model Group Fallbacks=None
Model: azure_ai/Mistral-large
API Base: `https://censored.services.ai.azure.com/`
Messages: `[{'role': 'user', 'content': '### Task:\nGenerate 1-3 broad tags categorizing the main themes of the'}`
model_group: `Mistral-large`
deployment: `azure_ai/Mistral-large`
```

I checked the Metrics of the deployment under `ai.azure.com` and it has a few succesfull requests, bot no input nor output tokens measured.

**Any ideas on what I might be doing wrong here?**
</div>

**Comment by emerzon** [comment]
Are you using the correct endpoints?

non OpenAI models endpoint normally have an endpoint in the format `<name>.<region>.models.ai.azure.com`

You need to create this endpoint for each model in Azure AI Foundry.

**Comment by semidark** [comment]
I obtained my endpoint from the overview at [https://ai.azure.com/](https://ai.azure.com), specifically from the project I created for this task. The project has the capabilities: `Azure AI Inference`, `Azure OpenAI`, and `Azure AI Services`.

I attempted to use the endpoints listed there, but I received the 404 error I mentioned earlier when using the Azure AI Services endpoint:  
`https://ai-myusername3214234dsf12334.cognitiveservices.azure.com/`

While writing this, I realized I made an error when copying the Azure AI Inference endpoint. It seems I accidentally removed the trailing `/models` string. When I include the `/models` path, I encounter a different error:

`https://ai-myusername3214234dsf12334.services.ai.azure.com/models`

This time, I receive a 401 error:

```
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: Azure_aiException - Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or has expired.'}
```

I'm not sure if this counts as progress. I have quadruple-checked the API key configured in the `litellm` config.

**Comment by emerzon** [comment]
Yes, the issue seems to be that you're trying to use a OpenAI endpoint instead of a AI Studio (or AI foundry) endpoint. Their naming is confusing and they keep changing them. 

You will need an endpoint ending with models.ai.azure.com.

You will also have one endpoint per model.

**Comment by semidark** [comment]
Hi @emerzon, thank you for your patience. I'm sure I've never tried to use the Azure OpenAI endpoint for other models like Mistral-large. I understand these are two separate components in liteLLM and Azure.

My endpoint looks something like this: `https://ai-myusername3214234dsf12334.services.ai.azure.com/models` (just an example). As I mentioned earlier, I'm now receiving a 401 error instead of the previous 404 error.

I've explored all the options in the Azure Web Consoles (https://ai.azure.com and https://portal.azure.com), but they consistently provide the same endpoint URL and API Key everywhere. To test whether I have a fundamental misunderstanding of the configuration or setup of liteLLM, I added the Amazon Bedrock serverless inference endpoints without any issues.

I'm really stuck with the Azure AI backend.

**Comment by emerzon** [comment]
Hi @semidark  - My bad. I just checked out Azure and noticed that now they offer global endpoints for Mistral models.
This was not the case when I deployed, that's why I ended up with regional endpoints like `<name>.<region>.models.ai.azure.com`

My current regional endpoints work fine with LiteLLM.
It's possible that there are some differences on how the global endpoint should be used, so I guess this needs further investigation.

**Comment by semidark** [comment]
Ah, I see. So it really is a bug. Good to know. How can I assist with the investigation? As mentioned in my original post, I've just started working with litellm. The bug is probably located somewhere around here: https://github.com/BerriAI/litellm/tree/888b3a25afa514847deae0307d4b7cc495206564/litellm/llms/azure.

Additionally, this seems to be the official documentation for creating and using Serverless Inference Endpoints: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-deploy-models-serverless?view=azureml-api-2&tabs=azure-studio

**Comment by danrr** [comment]
I think I ran into this issue just now. I might have found the issue: the handler for `azure_ai` models defers to `openai` which initializes a regular `OpenAI` client which passes a bearer token auth header, rather than the `AzureOpenAi` client which passes the `api-key` header.

**Comment by ghost** [comment]
thanks for the issue @semidark + for the work on this @danrr @emerzon 

looking into this now

**Comment by ghost** [comment]
how do you get the `services.ai.azure.com` endpoint? i consistently see the `models.ai.azure.com` endpoint for mistral large 

<img width="725" alt="Screenshot 2024-12-24 at 2 38 32 PM" src="https://github.com/user-attachments/assets/4259b8f1-4f92-4ac3-98ac-5df0bcaaacf5" />

**Comment by ghost** [comment]
tried via azure ml too, following the tutorial linked by @semidark, still seeing `models.ai.azure.com` 

<img width="742" alt="Screenshot 2024-12-24 at 2 49 33 PM" src="https://github.com/user-attachments/assets/c33d88ce-8bb6-4d5b-a475-3b5394959a95" />

**Comment by danrr** [comment]
Hi, I deployed a model using https://ai.azure.com/. Specifically, I deployed an instance of Llama 3.3 https://ai.azure.com/explore/models/Llama-3.3-70B-Instruct/version/4/registry/azureml-meta.
<img width="622" alt="image" src="https://github.com/user-attachments/assets/6a943e3b-515c-426d-beb3-0f53dce3d529" />

This created an endpoint like https://\<name\>-francecentral.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview.

**Comment by szerintedmi** [comment]
I have the same issue - I can't configure Azure AI models. 
As a workaround I was able to get them work as regular Azure model setup. I set the API Base to my Azure AI endpoint. The drawback that somehow the pricing is not coming through even if I set the base model correctly. (Llama-3.3-70B-Instruct)

**Comment by ghost** [comment]
@szerintedmi can you share your config? 

And thanks for confirming the `azure/` route solves it, while i can't seem to deploy the global standard version i can try and mock this to make sure it works as expected

**Comment by ghost** [comment]
I'll work on a beta version w/ testing (gated behind `litellm.enable_preview_features`) - if it works for y'all as expected we can roll it out more broadly

**Comment by danrr** [comment]
I forgot to mention that what worked for me was commenting out the api key and adding the header manually:

```yaml
#      api_key: "<key>"
      extra_headers: {"api-key": <key>}
```

**Comment by ghost** [comment]
Hey @szerintedmi can you share your config / sdk code for repro of the cost tracking issue? (any logs here would be great as well)

**Comment by ghost** [comment]
reopening - i was able to get a global standard deployment and repro the issue. it's not yet fixed.

**Comment by jlnde** [comment]
Any updates on this problem? Just want to share the tests I have done so far.

LiteLLM version: Same with v1.63.2-stable and v1.63.6.dev1

Whether I use azure/ or azure_ai/ for Azure OpenAI model configs, the path in the HTTP request will be `/openai/deployments/gpt-4o/chat/completions?api-version=[API-VERSION]`. But for the new Azure AI inference endpoint, the correct path is just `/chat/completions?api-version=[API-VERSION]`.

The following config sends requests to `/openai/deployments/gpt-4/chat/completions?api-version=2024-10-21`, instead of `/chat/completions?api-version=2024-10-21`.

```yaml
- model_name: gpt-4o
  litellm_params:
    model: azure_ai/gpt-4o
    api_base: "https://aihubxyz323530456852.services.ai.azure.com/models"
    api_key: "os.environ/AZURE_API_KEY"
    api_version: "2024-10-21"
```

The following config sends requests to the correct path `/chat/completions`, but api-version is missing. Therefore not usable with Azure Foundry endpoints.

```yaml
- model_name: gpt-4o
  litellm_params:
    model: openai/gpt-4o
    api_base: "https://aihubxyz323530456852.services.ai.azure.com/models"
    api_key: "os.environ/AZURE_API_KEY"
    api_version: "2024-10-21"
    extra_headers: {"api-key": os.environ/AZURE_API_KEY}
```

The following config with api_base: openai.azure.com endpoint works for Azure Foundry OpenAI Models, but not for third-party models.

```yaml
  - model_name: gpt-4o
    litellm_params:
      model: azure_ai/gpt-4o
      api_base: "https://aihubxyz323530456852.openai.azure.com"
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "2024-10-21"
```

I would like to use third-party models via the Azure Foundry inference endpoint `https://aihubxyz323530456852.services.ai.azure.com/models`. **This is currently not possible because the api-version query parameter is not part of the request sent by LiteLLM.** For e.g. response_format parameter in combination with some models, the specific api-version must be set appropriate.

```yaml
  - model_name: phi-4
    litellm_params:
      model: azure_ai/phi-4
      api_base: "https://aihubxyz323530456852.services.ai.azure.com/models"
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "2024-05-01-preview" # BUG: NOT SENT IN REQUEST !
```

**Comment by ghost** [comment]
able to repro api version not being sent, working on a fix

**Comment by karoltheguy** [comment]
I've been having the same problem for many months and thought I was crazy. I also couldn't find the specifics in the documentation even though this was marked as completed.

Here is how I got it working:
```
- litellm_params:
    api_key: xxxxxxxxxxxxxxxxxxxxxxx
    api_version: 2024-05-01-preview
    model: azure_ai/Meta-Llama-3-3-70B-Instruct
    api_base: https://xxxxxxxxxx.services.ai.azure.com/models
  model_name: "Meta-llama3.3-70b"
```
