### ISSUE TITLE
[Bug]: Unable to drop additional param for vertex_ai/mistral-large-2411@001

### ISSUE THREAD

**Issue by razyon** [BerriAI/litellm#7309]
### What happened?

Hi, 

I face an issue integrating the last mistral large model with LiteLLM.

When I call my endpoint like this:
``` bash
curl --request POST \
  --url http://localhost:4000/chat/completions \
  --header 'content-type: application/json' \
  --header 'user-agent: ' \
  --data '{
  "model": "mistral",
  "stream": true,
  "stream_options": {
    "include_usage": true
  },
  "additional_drop_params": ["stream_options"],
  "messages":
  [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Hi, how are you ?"
        }
      ]
    }
  ]
}'
```

I got an answer from LiteLLM:

> litellm.APIConnectionError: Vertex_aiException - b'{\"detail\":[{\"type\":\"extra_forbidden\",\"loc\":[\"body\",\"function-after[has_tool_execution_data_for_all_tools(), ChatCompletionRequest]\",\"stream_options\"],\"msg\":\"Extra inputs are not permitted\",\"input\":{\"include_usage\":true}},{\"type\":\"missing\",\"loc\":[\"body\",\"FIMCompletionRequest\",\"prompt\"],\"msg\":\"Field required\",\"input\":{\"model\":\"mistral-large-2411\",\"messages\":[{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"Hi, how are you ?\"}]}],\"stream_options\":{\"include_usage\":true},\"stream\":true}},{\"type\":\"extra_forbidden\",\"loc\":[\"body\",\"FIMCompletionRequest\",\"messages\"],\"msg\":\"Extra inputs are not permitted\",\"input\":[{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":\"Hi, how are you ?\"}]}]},{\"type\":\"extra_forbidden\",\"loc\":[\"body\",\"FIMCompletionRequest\",\"stream_options\"],\"msg\":\"Extra inputs are not permitted\",\"input\":{\"include_usage\":true}}]}'\nReceived Model Group=mistral\nAvailable Model Group Fallbacks=None

Clearly the param `stream_options` is not allowed for this mistral version so I tried to drop it (with `"additional_drop_params": ["stream_options"],`) in the request above and in the proxy configuration with:

``` yaml
model_list:
  - litellm_params:
      model: vertex_ai/mistral-large-2411@001
      vertex_location: gcp-location
      vertex_project: gcp-project
      additional_drop_params: ["stream_options"]  # 👈 drop param
    model_name: mistral

litellm_settings:
    json_logs: true
    modify_params: true
```

I don't think the `additional_drop_params` works for this mistral model.

Thank you for all your work on this amazing llm proxy :)
Best Regards

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.1-stable
