### ISSUE TITLE
[Bug]: duplicate spend report

### ISSUE THREAD

**Issue by elvis-cai** [BerriAI/litellm#7389]
### What happened?

Hi Team

not sure if it's expected, but it seems Litellm is generating reports per instance, there will be 5 copies of msg if we have 5 pods in k8s.

<img width="627" alt="image" src="https://github.com/user-attachments/assets/f7aab653-e9d0-47cc-9ea0-13646fad7174" />

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.50.2

**Comment by ghost** [comment]
@elvis-cai this only happens if you don't have a redis cache on proxy. this is since each instance is maintaining it's own state of spend (not an issue if there's a central cache - e.g. redis to maintain state)

**Comment by elvis-cai** [comment]
HI @krrishdholakia  we did have redis cache enabled on litellm, is there any config we miss here? 
```
    litellm_settings:
      cache: True
      cache_params:
        type: redis
        ttl: 600
```
