### ISSUE TITLE
[Feature]: use litellm python SDK to validate models on proxy config.yaml 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#7525]
### The Feature

sample config

```
proxy_config:
  model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key:  os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key:  os.environ/OPENAI_API_KEY
```

if the service is provided a model name gpt-4o or gpt-4o-mini , then it would be validated. however, if the service was provided a model name gpt-100x , then it wouldn't be validated since it doesn't exist in the proxy config

i was trying to use utils.get_valid_models() like this:

```
valid_models = utils.get_valid_models()
if model_name not in valid_models:
     logger.error(f"Invalid model name: {model_name}. Valid models are: {valid_models}")
     
```

### Motivation, pitch

- 

### Are you a ML Ops Team?

Yes
