### ISSUE TITLE
[Bug]: Invalid parameters being sent in Amazon Titan requests

### ISSUE THREAD

**Issue by viniciuspinto** [BerriAI/litellm#7548]
### What happened?

When sending a request to the `amazon.titan-embed-text-v2:0` model with the following configuration, LiteLLM is sending the `aws_bedrock_runtime_endpoint` field in the request body, which generates an error from AWS Bedrock.

```
  - model_name: titan-v2
    litellm_params:
      model: "bedrock/amazon.titan-embed-text-v2:0"
      aws_bedrock_runtime_endpoint: "<URL>"
      aws_region_name: "<REGION>"
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.56.9
