### ISSUE TITLE
[Feature]: set my Vertex AI and gemini api_base

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#7578]
### The Feature

Set my Vertex AI and gemini api_base.

```yaml
model_list:
  - model_name: gemini-vision
    litellm_params:
      model: vertex_ai/gemini-1.5-pro
      api_base: "my-aiplatform-googleapis.com"
      vertex_project: "project-id"
      vertex_location: "us-central1"
      vertex_credentials: "/app/my-vertex-credentials.json"
```
https://github.com/BerriAI/litellm/blob/main/litellm/llms/vertex_ai/common_utils.py#L75

When I provide my own API base, I want to replace aiplatform.googleapis.com with my own my-aiplatform-googleapis.com.

### Motivation, pitch

Set my Vertex AI and gemini api_base.

### Are you a ML Ops Team?

No
