### ISSUE TITLE
When I making api_key, It's user_id is null

### ISSUE THREAD

**Issue by ppippi-dev** [BerriAI/litellm#7911]
I'm using self-host kubernetes deploy.

When I making api_key, It's user_id is null, so User can't see api_key anymore...

It's known issue? or my env is wrong??

More Imformation

I'm using v1.59.0 and tried v1.59.1 

```
general_settings:
  master_key:  admin
  store_prompts_in_spend_logs: true
model_list: []
```
