### ISSUE TITLE
 v1.59.5 issue with Tracing on Langfuse v3.13.0 + prompt

### ISSUE THREAD

**Issue by qymab** [BerriAI/litellm#7938]
After upgrading from v1.57.1 to v1.59.5, prompt traces are no longer being recorded in Langfuse, despite using the same Langfuse version (v3.13.0).  

Here are my LiteLLM settings (Docker-based):

```
model_list:
  # groq
  - model_name: llama-3.3-70b-versatile
    litellm_params:
      model: groq/llama-3.3-70b-versatile

# liteLLM settings
litellm_settings:
  drop_params: true
  cache: true
  cache_params:
    type: redis
  #   supported_call_types: ["acompletion", "completion", "embedding", "aembedding"]
  success_callback: ["langfuse"]
  # failure_callback: ["langfuse"]
```
