### ISSUE TITLE
Langfuse client is disabled

### ISSUE THREAD

**Issue by hugobritobh** [BerriAI/litellm#7948]
I use version ( Litellm v1.59.5 and Latest version of the Helm chart langfuse-0.12.1.tgz )

I'm following this tutorial to have two teams sending data to two different Langfuse instances: https://docs.litellm.ai/docs/proxy/team_logging

In the ConfigMap, I included the two variables related to Langfuse.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
    model_list:
      - model_name: yyyyyyy
        litellm_params:
          model: yyyyyyyyyyyyy-v1:0
          aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
          aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY   
          aws_region_name: os.environ/CUSTOM_AWS_REGION_NAME
        model_info:
          team_id: "api"
      - model_name: xxxxxxxx
        litellm_params:
          model: xxxxxxxx-v1:0
          aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
          aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY   
          aws_region_name: os.environ/CUSTOM_AWS_REGION_NAME
        model_info:
          team_id: "api2"
    litellm_settings:
      default_team_settings:
        - team_id: "api"
          success_callback: ["langfuse"]
          langfuse_public_key: yyyyy
          langfuse_secret: yyyyyy
          langfuse_host: yyyyy
        - team_id: "api2"
          success_callback: ["langfuse"]
          langfuse_public_xxxx
          langfuse_secret: xxxxxx
          langfuse_host: xxxxx
    general_settings: 
      default_team_disabled: false 
```

However, when I start the LiteLLM pod, the following issue occurs:
_Langfuse client is disabled since no public_key was provided as a parameter or environment variable 'LANGFUSE_PUBLIC_KEY'. See our docs: https://langfuse.com/docs/sdk/python/low-level-sdk#initialize-client_

I ran a test by adding the required variable directly in the Deployment. However, LiteLLM did not switch configurations based on the team and only sent data using the variables defined in the Deployment, completely ignoring the ConfigMap.

Why is this error occurring if the variables are in the ConfigMap and there are two separate configurations depending on the team? 

How can this issue be resolved?
