### ISSUE TITLE
[Bug]: prisma cannot connect to local postgres

### ISSUE THREAD

**Issue by jacethemagician** [BerriAI/litellm#7968]
### What happened?

running litellm using docker

`export DATABASE_URL=postgresql://admin:123456@localhost:5432/litellm_db`

```
docker run \
  --network host \
  -p 4000:4000 \
  --name litellm \
  -v $(pwd)/litellm_config.yaml:/app/config.yaml \
  --restart always \
  ghcr.io/berriai/litellm-database:main-latest \
  --config /app/config.yaml --detailed_debug
```

with config 

```
model_list:
  - model_name: <model_name>
    litellm_params:
      model: <model>
      api_base: <api_base>
      api_key: <api_key>
      
general_settings:
  master_key: <master_key>
  database_url: "postgresql://admin:123456@localhost:5432/litellm_db"
```

however, it has the error

`Datasource "client": PostgreSQL database "litellm_db", schema "public" at "localhost:5432"
Error: ERROR: permission denied for schema public`

I've already tried

```
GRANT USAGE, CREATE ON SCHEMA public TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin;
```

but none of them worked

### Relevant log output

```shell
prisma:warn Prisma doesn't know which engines to download for the Linux distro "wolfi". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "wolfi". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "litellm_db", schema "public" at "localhost:5432"
Error: ERROR: permission denied for schema public
   0: sql_schema_connector::apply_migration::migration_step
           with step=CreateTable { table_id: TableId(0) }
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:21
   1: sql_schema_connector::apply_migration::apply_migration
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:10
   2: schema_core::state::SchemaPush
             at schema-engine/core/src/state.rs:436
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

latest
