### ISSUE TITLE
[Bug]: Huggingface models not fully functional

### ISSUE THREAD

**Issue by DarioArena87** [BerriAI/litellm#7969]
### What happened?

Hi, i'm using litellm as a proxy to centralize LLM access from different applications. I have deployed it locally on my computer using a docker compose file (if you want you can even add this to the documentation since i've found only docker and litellm CLI commands in it):
```yaml
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - LITELLM_MASTER_KEY="sk-1234"
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/litellm_db
      - UI_USERNAME=admin   # username to sign in on UI
      - UI_PASSWORD=admin   # password to sign in on UI
      - STORE_MODEL_IN_DB=True
    command: --config /app/config.yaml

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: litellm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```
In my config.yaml file i have configured several models via different endpoints that works flawlessly (gemini-2.0 via google and openrouter, mistral, codestral...) but for hugging face models i have a strange behaviour that i'm not sure if it's a bug or if i am missing something obvious. To make a quick test i've configured Qwen-2.5 via the free hugging face inference endpoint:
```yaml
model_list:
  # ... other models ...
  - model_name: qwen2.5-coder-32b-instruct
    litellm_params:
      model: huggingface/Qwen/Qwen2.5-Coder-32B-Instruct
      api_key: MY_HF_API_KEY
```
When i call the model it seems to not respect the prompt formatting/tokenizer.json that is present in the repository and in the output i get a "<|im_end|>" at the end of every response:

![Image](https://github.com/user-attachments/assets/fdde991a-5cfe-4437-bf93-c94da2439791)

Ive tried manually specifying the prompt template via a [custom prompt template](https://docs.litellm.ai/docs/proxy/configs#set-custom-prompt-templates) and also tried other models from Huggingface but i get the same behaviour. 
No errors are printend in the logs (see attachment).
Is there something i'm doing wrong?

### Relevant log output

```shell
INFO:     172.19.0.1:41774 - "POST /chat/completions HTTP/1.1" 200 OK
2025-01-24T10:22:08.631620905Z 10:22:08 - LiteLLM:WARNING: logging_utils.py:113 - `logging_obj` not found - unable to track `llm_api_duration_ms
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

latest version

**Comment by marceldev89** [comment]
Same issue here trying to use huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B or huggingface/Qwen/Qwen2.5-Coder-32B-Instruct. Setting `eos_token` in the config does nothing at all.

**Comment by marceldev89** [comment]
Hmm I figured out a workaround. Instead of using the huggingface provider you can use the openai compatible endpoint. This seems to filter out the special tokens and stuff properly. :)

```
model_list:
  - model_name: Meta-Llama-3-8B-Instruct
    litellm_params:
      model: openai/meta-llama/Meta-Llama-3-8B-Instruct
      api_base: https://api-inference.huggingface.co/v1
      api_key: hf_xxxxxxx
```
