### ISSUE TITLE
[Bug]: the > main-v1.57.0 It's not work In my k8s env

### ISSUE THREAD

**Issue by gumutianqi** [BerriAI/litellm#7971]
### What happened?

I got a crash loop exception form the litellm proxy server, on k8s.

// this the error
```
CrashLoopBackOff (back-off 10s restarting failed container=mojito-litellm-01 pod=mojito-litellm-578fbbfd69-lhkl5_mojito(c7ed1978-3a29-473d-b933-9e6e4e417af2)) | Last state: Terminated with 128: StartError (failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: &quot;docker/prod_entrypoint.sh&quot;: stat docker/prod_entrypoint.sh: no such file or directory: unknown), started: 1970-01-01 08:00:00, finished: 2025-01-24 19:21:28
```

// this is the main content in k8s yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-mojito-mojito-litellm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2025-01-07T11:13:14Z'
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-mojito-mojito-litellm
      namespace: mojito
    spec:
      containers:
        - args:
            - '--config=/app/proxy_config.yaml'
          envFrom:
            - secretRef:
                name: mojito-llm-secret
                optional: false
          image: ghcr.io/berriai/litellm:main-v1.59.6   // It's work when the version is 'main-v1.57.0'
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /app
              name: mojito-litellm-config-vol
              readOnly: true
          workingDir: /app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: mojito-litellm-env
            optional: false
          name: mojito-litellm-config-vol
```

### Relevant log output

```shell
CrashLoopBackOff (back-off 10s restarting failed container=mojito-litellm-01 pod=mojito-litellm-578fbbfd69-lhkl5_mojito(c7ed1978-3a29-473d-b933-9e6e4e417af2)) | Last state: Terminated with 128: StartError (failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: &quot;docker/prod_entrypoint.sh&quot;: stat docker/prod_entrypoint.sh: no such file or directory: unknown), started: 1970-01-01 08:00:00, finished: 2025-01-24 19:21:28
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

main-v1.59.6

**Comment by ghost** [comment]
> docker/prod_entrypoint.sh: no such file or directory: unknown

it looks like you're unable to get this file - https://github.com/BerriAI/litellm/blob/main/docker/prod_entrypoint.sh

cc: @ishaan-jaff

**Comment by maximevalette** [comment]
Hello,

I have the same issue on my k8s deployment.

**Comment by rmarku** [comment]
Same issue here on GKE:
```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker/prod_entrypoint.sh": stat docker/prod_entrypoint.sh: no such file or directory: unknown
```

**Comment by bodzebod** [comment]
While using docker-compose without kubernetes, I also have the same error since I just pulled the latest image "ghcr.io/berriai/litellm:main-latest" as of today: _executable file `docker/prod_entrypoint.sh` not found in $PATH: No such file or directory ._

**Comment by insajd** [comment]
You might have issue with mounting /app to volume.
          volumeMounts:
            - mountPath: /app
              name: mojito-litellm-config-vol
You're mounting /app instead of /app/proxy_config.yaml to file in host system.

**Comment by bodzebod** [comment]
@insajd , this is not an issue with the config mount. This is the latest image "ghcr.io/berriai/litellm:main-latest" that doesn't seem to contain the container entry point, it's completely different.
However, I just found that the image "litellm/litellm:latest" is actually working fine.

If "ghcr.io/berriai/litellm:main-latest" is no longer valid, then the doc https://docs.litellm.ai/docs/proxy/deploy needs to be updated.

**Comment by insajd** [comment]
@bodzebod latest tag gets you 1-year-old version: https://github.com/berriai/litellm/pkgs/container/litellm/141957650?tag=latest . You must use main-latest which is 2 days old version: https://github.com/berriai/litellm/pkgs/container/litellm/344303413?tag=main-latest
Problem with mounting /app to volume is that you're overriding whatever is in the /app folder with your data in the volume, and /app folder contains docker/prod_entrypoint.sh in it (your volume does not).
To quickly test - remove the mount completely, you will have issue not with prod_entrypoint.sh missing, but with config missing. Then add file mapping instead.

**Comment by bodzebod** [comment]
@insajd I will give more details about my context. Here is the litellm service description in my docker-compose.yml:

  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      - XXX_API_KEY=XXXX
    command: ["--port", "4000", "--config", "/app/config.yaml"]
    volumes:
      - ./litellm-config:/app


You can see that I already use main-latest tag. It's been running like that for a few weeks until this morning where I updated my image, but without changing anything in configurations. After updating the image, the container no longer starts and raise the error:

`Error response from daemon: crun: executable file `docker/prod_entrypoint.sh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found`

This is really a problem with the image as it used to start successfully before I update the image.

**Comment by insajd** [comment]
@bodzebod I hear you. The image has changed and it stopped working after an update, I had the same issue. I also had /litellm-config mapped to /app - that's folder to folder mapping. Now we must not mount folder, but config file instead. 
For example here https://docs.litellm.ai/docs/proxy/deploy only file-file mounts are shown:
```
    volumes:
      - ./litellm-config.yaml:/app/config.yaml # Mount the local configuration file
```
Here how you should mount it.
```
litellm:
  container_name: litellm
  image: ghcr.io/berriai/litellm:main-latest
  restart: unless-stopped
  ports:
    - "127.0.0.1:4000:4000"
  environment:
    - XXX_API_KEY=XXXX
  command: ["--port", "4000", "--config", "/app/config.yaml"]
  volumes:
    - ./litellm-config/config.yaml:/app/config.yaml
```

**Comment by bodzebod** [comment]
@insajd I have tested various tags, and it appears the last one that was working for me was main-v1.57.0. It started failing from main v1.57.1.

And I'm sorry, I didn't see that I was mounting the whole folder indeed. You were right, I modified my docker-compose that way:

    volumes:
      - ./litellm-config/config.yaml:/app/config.yaml

And now it starts successfully! Thank you very much!

**Comment by Vladimir-Dedijer-HTEC** [comment]
I have the same issue in k8s with the latest version.

**Comment by ghost** [comment]
hey @insajd thank you for your contribution. Would you recommend we just call this out on docs? or are there any further changes required on our end?

**Comment by insajd** [comment]
@krrishdholakia I think calling this out in doc should be enough. BTW here is related issue where I saw the solution first: https://github.com/BerriAI/litellm/issues/7649
`docker/prod_entrypoint.sh: no such file or directory` is what is common to both of these.
This can be fixed either by creating file-file mount, or moving config to some subfolder where only this config.yaml file would be.

**Comment by larrykoo711** [comment]
I know how to make it works. we should use the details `volumeMounts` for config.yaml,
when we use the versions >= main-v1.57.0
Like this:
```
volumeMounts:
    - mountPath: /app/proxy_config.yaml
      name: mojito-litellm-config-vol
      subPath: proxy_config.yaml
    - mountPath: /etc/localtime
      name: volume-localtime
    - mountPath: /app/vertex_key.json
      name: mojito-litellm-config-vol
      subPath: vertex_key.json
```
@maximevalette @rmarku  @Vladimir-Dedijer-HTEC 

@krrishdholakia @insajd Thanks for this case to give suggestion, perhaps I was incorrect at first on K8S.
sorry, that's my bad, It's not a bug.
