### ISSUE TITLE
[Bug]: latency-based routing fails on openai embedders with "Object of type timedelta is not JSON serializable"

### ISSUE THREAD

**Issue by micahjsmith** [BerriAI/litellm#8025]
### What happened?

Latency-based routing fails for openai embedders.
- this occurs only with embedding endpoints and not with completion endpoints
- it is still occurring on 1.57.8 and 1.58.2

See error in the logs

Relevant litellm config snippet (elided):

```
router_settings:
  routing_strategy: latency-based-routing
  routing_strategy_args:
    lowest_latency_buffer: 0.25
    ttl: 300
    max_latency_list_size: 200

model_list:
  - model_name: text-embedding-3-small-8k
    litellm_params:
      model: openai/text-embedding-3-small
```

### Relevant log output

```shell
LiteLLM Redis Caching: async set() - Got exception from REDIS Object of type timedelta is not JSON serializable, Writing value={"text-embedding-3-small-8k":{"2025-01-21-18-35":{"rpm":0,"tpm":0},"2025-01-21-18-38":{"rpm":1,"tpm":0},"2025-01-21-18-45":{"rpm":1,"tpm":0},"2025-01-21-18-48":{"rpm":1,"tpm":0},"2025-01-21-18-51":{"rpm":2,"tpm":0},"2025-01-21-18-57":{"rpm":2,"tpm":0},"2025-01-21-18-59":{"rpm":1,"tpm":0},"2025-01-21-19-01":{"rpm":1,"tpm":0},"2025-01-21-19-08":{"rpm":1,"tpm":0},"2025-01-21-19-10":{"rpm":1,"tpm":0},"2025-01-21-19-14":{"rpm":1,"tpm":0},"2025-01-21-19-15":{"rpm":1,"tpm":0},"2025-01-21-19-17":{"rpm":2,"tpm":0},"2025-01-21-19-18":{"rpm":1,"tpm":0},"2025-01-21-19-24":{"rpm":1,"tpm":0},"2025-01-21-19-25":{"rpm":1,"tpm":0},"2025-01-21-19-26":{"rpm":1,"tpm":0},"2025-01-21-19-28":{"rpm":1,"tpm":0},"2025-01-21-19-29":{"rpm":1,"tpm":0},"2025-01-21-19-32":{"rpm":2,"tpm":0},"2025-01-21-19-33":{"rpm":1,"tpm":0},"2025-01-21-19-34":{"rpm":1,"tpm":0},"latency":[0,"datetime.timedelta(microseconds=183331)","datetime.timedelta(microseconds=625509)","datetime.timedelta(microseconds=207349)","datetime.timedelta(microseconds=857669)","datetime.timedelta(microseconds=201552)","datetime.timedelta(microseconds=206705)","datetime.timedelta(microseconds=201223)","datetime.timedelta(microseconds=420940)","datetime.timedelta(microseconds=167972)","datetime.timedelta(microseconds=191755)","datetime.timedelta(microseconds=174823)","datetime.timedelta(microseconds=200396)","datetime.timedelta(microseconds=228687)","datetime.timedelta(microseconds=190199)","datetime.timedelta(microseconds=220752)","datetime.timedelta(microseconds=243372)","datetime.timedelta(microseconds=169139)","datetime.timedelta(microseconds=176702)","datetime.timedelta(microseconds=168918)","datetime.timedelta(microseconds=257657)","datetime.timedelta(microseconds=262806)","datetime.timedelta(microseconds=218784)","datetime.timedelta(microseconds=337701)","datetime.timedelta(microseconds=428396)","datetime.timedelta(microseconds=206356)"]}
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.58.2

**Comment by ghost** [comment]
Hi @micahjsmith is this still an issue? 

I'm not able to repro the error log

**Comment by ghost** [comment]
Config:
```yaml
router_settings:
  routing_strategy: latency-based-routing
  routing_strategy_args:
    lowest_latency_buffer: 0.25
    ttl: 300
    max_latency_list_size: 200

model_list:
  - model_name: text-embedding-3-small-8k
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  cache: true
  cache_type: redis
```

console logs:
```bash
19:14:26 - LiteLLM Proxy:INFO: parallel_request_limiter.py:68 - Current Usage of key in this minute: {'current_requests': 1, 'current_tpm': 0, 'current_rpm': 2}
19:14:26 - LiteLLM Proxy:INFO: parallel_request_limiter.py:68 - Current Usage of user in this minute: {'current_requests': 1, 'current_tpm': 0, 'current_rpm': 2}
19:14:26 - LiteLLM Router:INFO: router.py:5699 - get_available_deployment for model: text-embedding-3-small-8k, Selected deployment: {'model_name': 'text-embedding-3-small-8k', 'litellm_params': {'api_key': 'sk**********', 'use_in_pass_through': False, 'model': 'openai/text-embedding-3-small'}, 'model_info': {'id': '8f71bb21d91844f9d9e9c0bbd47714ef9387c4ba3645fdba1b6adc19d99be579', 'db_model': False}} for model: text-embedding-3-small-8k
19:14:26 - LiteLLM Router:INFO: router.py:2464 - litellm.aembedding(model=openai/text-embedding-3-small) 200 OK
INFO:     127.0.0.1:57488 - "POST /embeddings HTTP/1.1" 200 OK
```
