### ISSUE TITLE
[Bug]: 'Mode batch not supported' when trying to set up an Azure GlobalBatch deployment.

### ISSUE THREAD

**Issue by antisilent** [BerriAI/litellm#8040]
### What happened?

- add a new [batch deployment model](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/batch?tabs=standard-input&pivots=programming-language-python#global-batch-deployment) in Azure OpenAI
- Make a new entry in proxy-config.yaml of litellm proxy for the newly added batch model:
```
model_name: gpt-4o-2024-11-20-batch-no-filter
    litellm_params:
      model: azure/gpt-4o-2024-11-20-batch-no-filter
      api_base: <API_BASE>
      api_key: <API_KEY>
    model_info:
      base_model: azure/global-standard/gpt-4o-2024-11-20
      mode: batch

```
- Run health checks

### Relevant log output

```shell
"unhealthy_endpoints": [
    {
      "api_base": <API_BASE>,
      "model": "azure/gpt-4o-2024-11-20-batch-no-filter",
      "cache": {
        "no-cache": true
      },
      "error": "Mode batch not supported. See modes here: https://docs.litellm.ai/docs/proxy/health\nHave you set 'mode' - https://docs.litellm.ai/docs/proxy/health#embedding-models\nstack trace: Traceback (most recent call last):\n  File \"/usr/lib/python3.13/site-packages/litellm/main.py\", line 5363, in ahealth_check\n    raise Exception(\n        f\"Mode {mode} not supported. See modes here: https://docs.litellm.ai/docs/proxy/health\"\n    )\nException: Mode batch not supported. See modes here: https://docs.litellm.ai/docs/proxy/health\n"
    }
  ]
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.58.4
