### ISSUE TITLE
[Bug]: Google API Keys are leaked in stack traces

### ISSUE THREAD

**Issue by Galaco** [BerriAI/litellm#8075]
### What happened?

We recently found that when LiteLLM logs an exception for Gemini models, it leaks our API key in plain text in the stack trace.

I've attached an example log output (I redacted our key, search for `<REDACTED>` to find where it was leaked). This example is occuring often at the moment with `gemini-1.5-pro-002` models, which are regularly returning 503 errors.

The cause is pretty obvious; for whatever reason google expect the API key in the request URL parameters, not somewhere secure, so the stack trace logs the request URL including parameters, leaking the key.

Here is our config:
```
model_list:
  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro-002
      api_key: "os.environ/GEMINI_API_KEY"
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash-002
      api_key: "os.environ/GEMINI_API_KEY"
    litellm_params:
      model: gemini/gemini-2.0-flash-exp
      api_key: "os.environ/GEMINI_API_KEY"

litellm_settings:
  drop_params: True
  json_logs: False
  vertex_ai_safety_settings:
    - category: HARM_CATEGORY_HARASSMENT
      threshold: BLOCK_NONE
    - category: HARM_CATEGORY_HATE_SPEECH
      threshold: BLOCK_NONE
    - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
      threshold: BLOCK_NONE
    - category: HARM_CATEGORY_DANGEROUS_CONTENT
      threshold: BLOCK_NONE
```

Enabling `json_logs` exhibits the same issue.

Reading the documentation, I don't believe that we have misconfigured anything. 

For reference we are using the prebuilt docker image. Apologies for not having the time to detail the affected version, but we have tested with v1.57.0 and older

### Relevant log output

```shell
"litellm.proxy.proxy_server.async_data_generator(): Exception occured - litellm.InternalServerError: litellm.InternalServerError: VertexAIException - b'{\n  "error": {\n    "code": 503,\n    "message": "The model is overloaded. Please try again later.",\n    "status": "UNAVAILABLE"\n  }\n}\n'"
stacktrace: "Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 839, in make_call
    response = await client.post(api_base, headers=headers, data=data, stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/litellm/llms/custom_httpx/http_handler.py", line 219, in post
    raise e
  File "/usr/local/lib/python3.13/site-packages/litellm/llms/custom_httpx/http_handler.py", line 177, in post
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-002:streamGenerateContent?key=<REDACTED>&alt=sse'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1531, in __anext__
    await self.fetch_stream()
  File "/usr/local/lib/python3.13/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1515, in fetch_stream
    self.completion_stream = await self.make_call(
                             ^^^^^^^^^^^^^^^^^^^^^
        client=litellm.module_level_aclient
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 843, in make_call
    raise VertexAIError(
    ...<3 lines>...
    )
litellm.llms.vertex_ai.common_utils.VertexAIError: b'{\n  "error": {\n    "code": 503,\n    "message": "The model is overloaded. Please try again later.",\n    "status": "UNAVAILABLE"\n  }\n}\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/litellm/proxy/proxy_server.py", line 2833, in async_data_generator
    async for chunk in response:
    ...<14 lines>...
            yield f"data: {str(e)}\n\n"
  File "/usr/local/lib/python3.13/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1745, in __anext__
    raise exception_type(
          ~~~~~~~~~~~~~~^
        model=self.model,
        ^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        extra_kwargs={},
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2189, in exception_type
    raise e
  File "/usr/local/lib/python3.13/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 1185, in exception_type
    raise litellm.InternalServerError(
    ...<4 lines>...
    )
litellm.exceptions.InternalServerError: litellm.InternalServerError: litellm.InternalServerError: VertexAIException - b'{\n  "error": {\n    "code": 503,\n    "message": "The model is overloaded. Please try again later.",\n    "status": "UNAVAILABLE"\n  }\n}\n'"
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.57.0
