### ISSUE TITLE
[Bug]: Output Token Price of 0 Not Displayed in WebUI

### ISSUE THREAD

**Issue by ZeroClover** [BerriAI/litellm#8110]
### What happened?

When the token output cost for certain models is specified as 0, it is not displayed as 0 on the WebUI, but the input cost is correctly shown as 0.

![Image](https://github.com/user-attachments/assets/b2e7bfe5-635b-4998-826e-b8804765e358)

Config:

```YAML
model_list:
  - model_name: deepseek-r1
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_key: os.environ/DEEPSEEK_API_KEY
      api_base: os.environ/DEEPSEEK_API_BASE
      max_tokens: 8192
  - model_name: deepseek-r1
    litellm_params:
      model: openai/<REDACTED>
      api_base: <REDACTED>
      api_key: <REDACTED>
      input_cost_per_token: 0
      output_cost_per_token: 0
  - model_name: deepseek-r1
    litellm_params:
      model: github/DeepSeek-R1
      api_key: os.environ/GITHUB_API_KEY
      input_cost_per_token: 0
      output_cost_per_token: 0
  - model_name: deepseek-r1
    litellm_params:
      model: openrouter/deepseek/deepseek-r1
      api_key: os.environ/OPENROUTER_API_KEY
      input_cost_per_token: 0.000008
      output_cost_per_token: 0.000008
  - model_name: deepseek-r1
    litellm_params:
      model: perplexity/sonar-reasoning
      api_key: os.environ/PERPLEXITY_API_KEY
      input_cost_per_token: 0.000001
      output_cost_per_token: 0.000005
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.59.9
