### ISSUE TITLE
[Bug]: UI Logs page - Expand is crossing screen limit

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#8123]
### What happened?

UI Logs page - Expand is crossing screen limit 

Use this config set `store_prompts_in_spend_logs` True

```
model_list:
  - model_name: bedrock/*
    litellm_params:
      model: openai/*

general_settings:
  store_prompts_in_spend_logs: true


```

how to repro 
- make llm request 
- go to experimental -> go to logs -> click a log -> see the log cross over the screen limit. Ideally the entire table data does not over flow when u click expand 

<img width="1140" alt="Image" src="https://github.com/user-attachments/assets/1e305e9b-325c-4cd5-b9dc-8e49320b45cf" />

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.59.10
