### ISSUE TITLE
[Bug]: AWS Bedrock imported DeepSeek-R1-Distill-Llama-8B not working with proxy

### ISSUE THREAD

**Issue by CodeOfCloud** [BerriAI/litellm#8176]
### What happened?

AWS Bedrock imported DeepSeek-R1-Distill-Llama-8B not working with proxy model
config as per document 
```yaml
  - model_name: DeepSeek-R1-Distill-Llama-8B
    litellm_params:
      model: bedrock/llama/arn:aws:bedrock:us-west-2:1234567890:imported-model/xxxxxxxx
      aws_region_name: us-west-2
      temperature: 0.2
```

showing model not find error when call the endpoint

```json
{"error":{"message":"litellm.NotFoundError: BedrockException - Bedrock Invoke HTTPX: Unknown provider=llama/arn:aws:bedrock:us-west-2:411578039387:imported-model/y5kcalhbqbo3, model=llama/arn:aws:bedrock:us-west-2:411578039387:imported-model/y5kcalhbqbo3. Try calling via converse route - `bedrock/converse/<model>`.\nReceived Model Group=DeepSeek-R1-Distill-Llama-8B\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"404"}
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

LiteLLM: Current Version = 1.59.12
