### ISSUE TITLE
[Bug]: additional_drop_params not working in proxy mode

### ISSUE THREAD

**Issue by uzhao** [BerriAI/litellm#8199]
### What happened?

After I upgrade to 1.60, this param no longer working for me.
In my proxy config, I have

```
  - model_name: o3-mini
    litellm_params:
      model: github/o3-mini
      api_key: "minimini"
      max_completion_tokens: 100000
      reasoning_effort: "high"
      additional_drop_params: ["max_tokens", "temperature", "top_p"]
    model_info:
      id: github-o3-mini

litellm_settings:
  drop_params: true
  request_timeout: 300
  set_verbose: true

```
Then
```
curl http://127.0.0.1:4000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer bigbig" \
  -d '{
    "model": "o3-mini",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "max_completion_tokens": 100000,
    "reasoning_effort": "high"
  }'
```
I got such a return 
`{"error":{"message":"litellm.BadRequestError: GithubException - Error code: 400 - {'error': {'message': \"Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.\", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'...`

I tried downgrade to 1.59.10 but this still not solved. I remember I modified proxy_server.py in older version and manually removed these params but this no longer working

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.60

**Comment by gfmaster** [comment]
Having same problem with 1.61.16. I think additional_drop_params is parsed as list of char.

My model is defined like this in config.yml.
```
model_list:
  - model_name: "phi4"
    litellm_params:
      model: "phi4:14b"
      api_base: "http://ollama-macmini:11434"
      custom_llm_provider: ollama
      additional_drop_params: ["presence_penalty"]
```

log output from litellm
```
03:15:33 - LiteLLM Proxy:DEBUG: proxy_server.py:1507 - loaded config={
"model_list": [
{
"model_name": "phi4",
"litellm_params": {
"model": "phi4:14b",
"api_base": "http://ollama-macmini:11434",
"custom_llm_provider": "ollama",
"additional_drop_params": [
0=p 1=r 2=e 3=s 4=e 5=n 6=c 7=e 8=_ 9=p 10=e 11=n 12=a 13=l 14=t 15=y 
]
}
},
```

**Comment by YikaiHu** [comment]
Same here

In version v1.70.1-stable https://github.com/BerriAI/litellm/releases/tag/v1.70.1-stable


```
model_list:
  - model_name: claude3.5-v2
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      additional_drop_params: ["chat_template_kwargs"]
      aws_region_name: us-east-2
      rpm: 10

router_settings:
  routing_strategy: usage-based-routing
  num_retries: 0
  timeout: 120

litellm_settings:
  drop_params: true
```
