### ISSUE TITLE
[Bug]: Titan Embeddings fails when using the aws_bedrock_runtime_endpoint parameter

### ISSUE THREAD

**Issue by mwl38765** [BerriAI/litellm#8219]
### What happened?

When specifying the aws_bedrock_runtime_endpoint parameter in the proxy settings for accessing the Titan Embedding model through Bedrock, the request fails.  It looks like for some reason the aws_bedrock_runtime_endpoint parameter is being passed in the request to Titan, and therefore causes a validation error because that's not a valid parameter.

I even tried using the drop_params parameter, but that did not fix the error.

Here is the config.yaml file that I used (just using the regular bedrock-runtime URL as an example of this failing, but had same issue with other values):

```
litellm_settings:
    drop_params: True
model_list:
  - model_name: titan-embedding
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0
      aws_region_name: us-east-1
      aws_bedrock_runtime_endpoint: https://bedrock-runtime.us-east-1.amazonaws.com
```

### Relevant log output

```shell
{"error":{"message":"litellm.BadRequestError: BedrockException - {\"message\":\"Malformed input request: extraneous key [aws_bedrock_runtime_endpoint] is not permitted, please reformat your input and try again.\"}\nReceived Model Group=titan-embedding\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"400"}}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.60.0
