### ISSUE TITLE
[Bug]: turn_off_message_logging is not always respected

### ISSUE THREAD

**Issue by ante-maric** [BerriAI/litellm#8315]
### What happened?

When using Open WebUI with LiteLLM and Langfuse, some responses are logged even though turn_off_message_logging is set to True.

All prompts from Open WebUI have content set to redacted-by-litellm, but responses are still logged. On the other hand, for prompts that Open WebUI sends automatically (like generating a title for a chat or generating tags), both user prompt and response have content set to redacted-by-litellm. I also made a C# test app to call models through litellm and everything is redacted as expected.

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.59.6

**Comment by ishaan-jaff** [comment]
can you give clear steps to repro @ante-maric  ?

**Comment by ante-maric** [comment]
I am currently in evaluation phase, so in docker I have deployed latest version of these services:
- postgresql with pgvector
- clickhouse
- minio
- redis
- langfuse-worker
- langfuse
- litellm
- ollama
- open-webui

For litellm these are the environment variables that I have set:
```
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      DATABASE_URL: ${LITELLM_DATABASE_URL}
      STORE_MODEL_IN_DB: "True"
      LANGFUSE_HOST: "http://langfuse-web:3000"
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY}
```

litellm config.yaml:

```
      litellm_settings:
          turn_off_message_logging: True
          log_raw_request_response: False
          success_callback: ["langfuse"]
          failure_callback: ["langfuse"]
```

I have pulled two models with ollama and added them to litellm. Then in open-webui I have added litellm as OpenAI API connection.
Those two models are then visible in open-webui. When I try to chat, I can see logs in langfuse it's just that turn_off_message_logging only applies to prompts, responses always get logged.
