### ISSUE TITLE
[Bug]: Error after deleting fallback using UI

### ISSUE THREAD

**Issue by vargacypher** [BerriAI/litellm#8332]
### What happened?

We're testing litllm proxy server to helped us with fallbacks, and we're facing a problem when trying to delete a fallback rule and recreating it.

- Docker deployment using **litellm:main-latest**
- **Postgres** DB

**config.yaml**
```yaml
model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY     
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY   
  - model_name: gemini-pro
    litellm_params:
      model: vertex_ai/gemini-2.0-flash-001 
      vertex_project: "project"
      vertex_location: "us-central1"
      vertex_credentials: "/app/user.json" 
  ```

## How to replicate:
In UI panel >> router settings >> add falbacks >> test

<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/382a2f26-479c-47f9-8250-0b299ccc71c2" />

**Success**

In UI panel >> router settings >> delete falbacks >> add (updated) fallback >> test 

<img width="1473" alt="Image" src="https://github.com/user-attachments/assets/230be720-10ac-4e04-9d3e-f615de30ca39" />

**Error**

### Relevant log output

```shell
Error occurred while generating model response. Please try again. Error: Error: 500 litellm.InternalServerError: This is a mock exception for model=gemini-pro, to trigger a fallback. Fallbacks=[{}, {'gemini-pro': ['gpt-4o-mini']}] Received Model Group=gemini-pro Available Model Group Fallbacks=None Error doing the fallback: list index out of range
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

latest
