### ISSUE TITLE
[Feature]: Allow specifying a default "reasoning_effort" setting in proxy model list

### ISSUE THREAD

**Issue by byrongrogan** [BerriAI/litellm#8370]
### The Feature

It would be helpful if we had a way to add a model with a **default reasoning effort**, allowing for a config either like:

```
 - model_name: o3-mini-high
    litellm_params:
      model: "azure/o3-mini"
      default_reasoning_effort: "high"
 - model_name: o3-mini
    litellm_params:
      model: "azure/o3-mini"
```

**Or** more generically, allow setting arbitrary default params on requests, including the reasoning_effort:

```
 - model_name: o3-mini-high
    litellm_params:
      model: "azure/o3-mini"
      default_params:
        reasoning_effort: "high"
 - model_name: o3-mini
    litellm_params:
      model: "azure/o3-mini"
```
I would suggest still passing through any explicit `reasoning_effort` setting if it's sent in a request on one of these params with a default. 

Either case would enable various thin clients to expose the different reasoning effort params as a different model without having model-specific knowledge baked in.

### Motivation, pitch

The LiteLLM proxy already supports passing through `reasoning_effort` to OpenAI's new reasoning models (`o1`, `o3-mini`, and so on), but many clients have poor support for this. Clients that are built with support for arbitrary models generally want to avoid encoding model-specific knowledge like this into them. So for example, when interfacing with LiteLLM via various popular web UIs, IDE plugins, agentic coding tools, and so on that don't have model-specific knowledge - the default (`medium`) can only be used.

This would provide a way to expose the power of e.g. `o3-mini-high` or `o1-high` to such clients, while still allowing clients to override these params.

### Are you a ML Ops Team?

No

### Twitter / LinkedIn details

https://www.linkedin.com/in/byrongrogan/
