### ISSUE TITLE
[Feature]: Auto-Mode for Guardrails

### ISSUE THREAD

**Issue by hxtomer** [BerriAI/litellm#8485]
### The Feature

It would be great if users can set the "mode" of a certain guardrail to "auto" instead of defining it multiple time for each mode.
Taking this configuration as an example:

```yaml
guardrails:
  - guardrail_name: aim-pre
    litellm_params:
      guardrail: aim
      mode: pre_call
      api_key: os.environ/AIM_API_KEY
  - guardrail_name: aim-during
    litellm_params:
      guardrail: aim
      mode: during_call
      api_key: os.environ/AIM_API_KEY
  - guardrail_name: aim-post
    litellm_params:
      guardrail: aim
      mode: post_call
      api_key: os.environ/AIM_API_KEY
```
Would be replaced with

```yaml
  - guardrail_name: aim
    litellm_params:
      guardrail: aim
      mode: auto
      api_key: os.environ/AIM_API_KEY
```

### Motivation, pitch

Aim Security's guardrails can be configured in the Aim Admin Dashboard, allowing security teams to quickly adjust guardrails based on changing company policies and new guardrails abilities. When integrated to LiteLLM, users need to hardly define the guardrail mode at their first use and future policy changes will require LiteLLM configuration adjustment. An "auto" model will allow MLOps teams to pass the responsibility for choosing a phase to run in, to the guardrail itself to happen dynamically. 

### Are you a ML Ops Team?

No

### Twitter / LinkedIn details

https://www.linkedin.com/company/aimsecurity

**Comment by ghost** [comment]
Hi @hxtomer 

we support mode as a List[str] 

this should already solve the multiple guardrail creation problem - 

```yaml
guardrails:
  - guardrail_name: aim-pre
    litellm_params:
      guardrail: aim
      mode: ["pre_call", "during_call", "post_call"] 
      api_key: os.environ/AIM_API_KEY
```

Does that solve your problem? @hxtomer
