### ISSUE TITLE
[Bug]: Message Redaction on OTEL impacts logging output on s3

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#8489]
### What happened?

- User is setting redaction on otel but seeing content redacted on s3 inputs for streaming requests to OpenAI 

they switch on redaction like this but are seeing content redacted for s3. Even though they have excplicitly only redacted for otel 

```
litellm_settings:
  callbacks: ["otel", "s3"]

callback_settings:
  otel:
    message_logging: False
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.61.1
