### ISSUE TITLE
[Bug]: api_base is none while accessing model analytics page

### ISSUE THREAD

**Issue by mgnisia** [BerriAI/litellm#8505]
### What happened?

We have set up litellm in a ECS Cluster with AWS Bedrock. We are running into the issue that the _api_base variable is `None` when accessing the Model Analytics Page, the page is empty and no results are returned. 

Config: 

```
model_list:
  - model_name: bedrock-claude-v3.5
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: eu-central-1
```

### Relevant log output

```shell
February 13, 2025 at 06:59 (UTC+1:00)
	
File "/usr/lib/python3.13/site-packages/litellm/proxy/proxy_server.py", line 6473, in model_metrics
	
server
February 13, 2025 at 06:59 (UTC+1:00)
	
if "https://" in _api_base:
	
server
February 13, 2025 at 06:59 (UTC+1:00)
	
^^^^^^^^^^^^^^^^^^^^^^^
	
server
February 13, 2025 at 06:59 (UTC+1:00)
	
TypeError: argument of type 'NoneType' is not iterable
	
server
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.1
