### ISSUE TITLE
[Bug]: Model hub not showing customized costs

### ISSUE THREAD

**Issue by xmcp** [BerriAI/litellm#8573]
### What happened?

The "model hub" page in the UI shows costs from the built-in cost map instead of `litellm_params`. This leads to the displayed costs do not match the actual costs when calling the API.

In the model hub page:

![Image](https://github.com/user-attachments/assets/e8d6f809-51eb-4a1f-bf9b-78e6f3b8534c)

In `config.yaml`:

```yaml
  - model_name: azure/gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      input_cost_per_token: 0.00000015
      output_cost_per_token: 0.0000006
      ...

  - model_name: ali/qwen-turbo
    litellm_params:
      model: openai/qwen-turbo
      input_cost_per_token: 0.000000042
      output_cost_per_token: 0.000000084
      ...
```

### Relevant log output

```shell
N/A
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.61.3-stable

**Comment by YaofengMai** [comment]
it not only impacts the display, the cost calculation also does not work. For example, if we use the "ali/qwen-turbo", no matter what customized cost value is input (and no matter the model is from config file or from db), the model hub always shows 0 and hence the API call always has 0 cost (x-litellm-response-cost is never returned and the UI shows 0 for total cost).

**Comment by YaofengMai** [comment]
Possible one of the root cause that why cost calcuation does not take customized pricing into consideration:
In _response_cost_calculator (https://github.com/BerriAI/litellm/blob/v1.61.13-stable/litellm/litellm_core_utils/litellm_logging.py#L778), it only passes "custom_pricing" parameter (**which is a bool to indicate only whether to do custom pricing or not**) to response_cost_calculator  (https://github.com/BerriAI/litellm/blob/v1.61.13-stable/litellm/cost_calculator.py#L774). And hence, there is no way to pass additional information (the detail setting, say custom_cost_per_token and custom_cost_per_second) to completion_cost.  


The similar problem exists for /spend/calculate API:
* for the "Calculate spend **before** making call", it works ok as it will pass such additional info to completion_cost method
* but for the "Calculate spend **after** making call", it does not so that it will try to look for such info from external

**Comment by ghost** [comment]
Thanks for the work @xmcp @YaofengMai picking this up now

**Comment by ghost** [comment]
able to see custom pricing working with `gemini/` 

<img width="708" alt="Image" src="https://github.com/user-attachments/assets/79190eb8-22f4-4596-af99-62ad573935b4" />

<img width="1250" alt="Image" src="https://github.com/user-attachments/assets/26911d17-f382-4b3a-b9d3-80e56cb9cbaf" />

**Comment by ghost** [comment]
Tried with azure/gpt-4o for stream + non-stream

This works 

<img width="682" alt="Image" src="https://github.com/user-attachments/assets/fc4c6898-1107-4316-8fe4-b1fbb405d66f" />

<img width="1630" alt="Image" src="https://github.com/user-attachments/assets/2ae38260-ab06-446c-9db8-0e2bf8652420" />

**Comment by ghost** [comment]
Closing as unable to repro - let me know if i missed something. 

Let me know if this issue can be reproduced on the latest version of litellm

**Comment by ghost** [comment]
<img width="395" alt="Image" src="https://github.com/user-attachments/assets/596a7257-6c02-4c7f-a3cf-32f2d79fa400" />

**Comment by ghost** [comment]
Works on model cost hub as well

**Comment by xmcp** [comment]
The issue persists on `litellm-non_root:main-v1.65.4-stable`.

Note that I am setting `LITELLM_LOCAL_MODEL_COST_MAP=True`, so that may a possible reason.

Config:
```yaml
...
model_list:
  - model_name: ali/qwen-turbo
    litellm_params:
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-xxx
      model: openai/qwen-turbo
      input_cost_per_token: 0.000000042
      output_cost_per_token: 0.000000084
...
```

Model hub UI:
![Image](https://github.com/user-attachments/assets/baf1126f-eed3-43c1-bd23-fcf4eee08609)

GET /model_group/info:
![Image](https://github.com/user-attachments/assets/6b051923-7990-4550-95c2-0047cf27db74)

**Comment by ghost** [comment]
able to repro on your model @xmcp

**Comment by ghost** [comment]
This needs to be inside `model_info` 

```yaml
  - model_name: ali/qwen-turbo
    litellm_params:
      api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-xxx
      model: openai/qwen-turbo
    model_info:
      input_cost_per_token: 0.000000042
      output_cost_per_token: 0.000000084
```

<img width="367" alt="Image" src="https://github.com/user-attachments/assets/013e8c4f-227f-41c3-82a2-dcab492a402a" />

I'll update our docs to use consistent guidance (put custom pricing inside model_info, not litellm_params)
