### ISSUE TITLE
[Bug]: Restricting models by Virtual Key does not work

### ISSUE THREAD

**Issue by josegalarceh** [BerriAI/litellm#8616]
### What happened?

We set up a simple version of litellm server proxy (version v1.56.5) as a deployment on an EKS, with a RDS (postgresql) database in aws. The master key was created and the variable was exposed to be able to connect to the database. The service works and routes to 2 bedrock models:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
data:
  config.yaml: |
    model_list:
      - model_name: model_1
        litellm_params:
          model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
          aws_bedrock_runtime_endpoint: https://<sensitive information>.bedrock-runtime.<sensitive information>.vpce.amazonaws.com
      - model_name: model_2
        litellm_params:
          model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
          aws_bedrock_runtime_endpoint: https://<sensitive information>.bedrock-runtime.<sensitive information>.vpce.amazonaws.com
```

The situation happens that when we create virtual key to restrict the access to all models or to one in particular, the access is allowed to any model, it is as if there is no restriction to 1 model in particular. We have tried creating users, who belong to 1 particular team and a key associated to this user to access 1 particular model, but still, he can access the 2 models. We want to know if there is something missing in the configuration or we are doing something wrong.

a virtual key was created to only access model 1
and another one was created to access only model 2:
- VIRTUAL_KEY_MODEL_1=sk-xxxx...xxxx
- VIRTUAL_KEY_MODEL_2=sk-yyyy...yyyy

```bash

curl -X GET "$ENDPOINT/v1/models" \
--header "Authorization: Bearer $VIRTUAL_KEY_MODEL_1" \
--data '' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132  100   132    0     0    429      0 --:--:-- --:--:-- --:--:--   429
{
  "data": [
    {
      "id": "model_1",
      "object": "model",
      "created": <sensitive information>,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}

curl -X GET "$ENDPOINT/v1/models" \
--header "Authorization: Bearer $VIRTUAL_KEY_MODEL_2" \
--data '' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132  100   132    0     0    429      0 --:--:-- --:--:-- --:--:--   429
{
  "data": [
    {
      "id": "model_2",
      "object": "model",
      "created": <sensitive information>,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}

```

here is an example of when I try to access model 1 using the key of model 2:
```bash
curl -v --no-buffer -X POST "$ENDPOINT/chat/completions" \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $VIRTUAL_KEY_MODEL_2" \
--data ' {
      "model": "model_1",
      "messages": [
        {
          "role": "user",
          "content": "Tell me a short joke"
        }
      ],
    }
' | jq
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying <sensitive information>:80...
* Connected to <sensitive information> (<sensitive information>) port 80
> POST /chat/completions HTTP/1.1
> Host: <sensitive information>
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer VIRTUAL_KEY_MODEL_2
> Content-Length: 188
> 
} [188 bytes data]
100   188    0     0  100   188      0    163  0:00:01  0:00:01 --:--:--   163< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 541
< Connection: keep-alive
< date: Mon, 17 Feb 2025 16:30:34 GMT
< server: uvicorn
< x-litellm-call-id: <sensitive information>
< x-litellm-model-id: <sensitive information>
< x-litellm-version: 1.56.5
< x-litellm-response-cost: 0.000426
< x-litellm-key-tpm-limit: None
< x-litellm-key-rpm-limit: None
< x-litellm-model-group: model_1
< X-Accel-Buffering: no
< X-Kong-Upstream-Latency: 1050
< X-Kong-Proxy-Latency: 0
< Via: kong/3.6.1
< X-Kong-Request-Id: <sensitive information>
< 
{ [541 bytes data]
100   729  100   541  100   188    404    140  0:00:01  0:00:01 --:--:--   544
* Connection #0 to host <sensitive information> left intact
{
  "id": "<sensitive information>",
  "created": <sensitive information>,
  "model": "model_1",
  "object": "chat.completion",
  "system_fingerprint": null,
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Here's a short joke for you:\n\nWhy don't scientists trust atoms?\nBecause they make up everything!",
        "role": "assistant",
        "tool_calls": null,
        "function_call": null
      }
    }
  ],
  "usage": {
    "completion_tokens": 26,
    "prompt_tokens": 12,
    "total_tokens": 38,
    "completion_tokens_details": null,
    "prompt_tokens_details": null
  }
}

```

It is expected that access will not be allowed, that we can control access to the models by virtual keys.

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.56.5

### Twitter / LinkedIn details

https://cl.linkedin.com/in/josegalarceh
