### ISSUE TITLE
[Feature]: Add Support for Requesty.ai in LiteLLM

### ISSUE THREAD

**Issue by ViezeVingertjes** [BerriAI/litellm#8659]
### The Feature

Enable support for Requesty.ai as a router in LiteLLM, similar to OpenRouter. This would allow developers to integrate Requesty.ai seamlessly into applications that rely on LiteLLM, such as OpenHands.

### Motivation, pitch

Requesty.ai is a powerful AI router with diverse model support, similar to OpenRouter. Without LiteLLM integration, applications like OpenHands cannot leverage its benefits. Adding support would expand options for developers, enhance flexibility, and improve model routing efficiency.

### Are you a ML Ops Team?

No

**Comment by Thibaultjaigu** [comment]
Happy to help here (from the Requesty Team) ! We're an Openai compatible router. Do you have any documentation on how to add new providers? If not, I can just add a PR as well.

the only changes to be made to add Requesty:
base_url="https://router.requesty.ai/v1"

you can find our docs here:
https://docs.requesty.ai/quickstart

My email:
thibault@requesty.ai

**Comment by Nasreddine** [comment]
I tried to use requesty with dspy that uses litellm in the backend; but without success.

```
ROUTER_API_KEY = os.getenv("REQUESTY_API_KEY")
google_gemini_2_5_flash_preview_04_17 = dspy.LM(
    api_key=ROUTER_API_KEY, 
    base_url="https://router.requesty.ai/v1",
    model="google/gemini-2.5-flash-preview-04-17",
    max_tokens=4096)
```

I get the error : 

> litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=google/gemini-2.5-flash-preview-04-17

**Comment by gesman** [comment]
To add requesty.ai support, if using LiteLLM proxy, add this to litellm_config.yaml :

```
  # See: https://docs.litellm.ai/docs/providers/openai_compatible
  - model_name: requesty/*
    litellm_params:
      model: openai/*                             # add openai/ prefix to route as OpenAI provider: 
      api_base: https://router.requesty.ai/v1     # add api base for OpenAI compatible provider. Make sure api_base has the /v1 postfix
      api_key: "os.environ/REQUESTY_API_KEY"      # api key to send your model

```
