### ISSUE TITLE
[Feature]: Ability to set `max_parallel_requests` for a model

### ISSUE THREAD

**Issue by anton164** [BerriAI/litellm#8680]
### The Feature

In the model config we should be able to specify `max_parallel_requests` to limit the amount of requests going to a deployment.

### Motivation, pitch

Some LLM services may not be able to handle high load. It would be great if we would be able to control this through the proxy.

### Are you a ML Ops Team?

Yes

**Comment by ghost** [comment]
This is already possible - https://docs.litellm.ai/docs/routing#max-parallel-requests-async

**Comment by anton164** [comment]
@krrishdholakia How can this be set in the proxy config?

I tried the following but it's not respected:
```
  - model_name: <internal-model>
    litellm_params:
      model: <internal-model>
      input_cost_per_minute: 0
      output_cost_per_minute: 0
      api_base: <model-url>
      rpm: 6 # 1 request every 10 seconds
      max_parallel_requests: 1
```

With this config I can send up to 6 requests at once. On the 7th request I get an RPM rate-limit error
