### ISSUE TITLE
[Feature]: Add o3 Data Zone model prices

### ISSUE THREAD

**Issue by jasonpnnl** [BerriAI/litellm#8692]
### The Feature

Microsoft has added Data Zone support for o3. Pricing can be found [here](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/#pricing). Please add the model and pricing to the model_prices_and_context_window.json file.

### Motivation, pitch

This will allow correct pricing for new models. In particular the cache_read_input_token_cost can't be overridden. 

### Are you a ML Ops Team?

No

**Comment by ghost** [comment]
Hey @jasonpnnl 

>  In particular the cache_read_input_token_cost can't be overridden

this can be overriden in the model_info, by just setting the value 

```yaml
- model_name:
   litellm_params:
      ...
   model_info:
     cache_read_input_token_cost: my-custom-value
```
