### ISSUE TITLE
[Bug]: Caching on litellm proxy does not work when using structured output (response_format)

### ISSUE THREAD

**Issue by dalssoft** [BerriAI/litellm#8706]
### What happened?

When using client.beta.chat.completions.parse() with a response_format schema, the litellm proxy cache is bypassed and a new request is made every time. This can be seen in the example below where two identical requests are made, but the second one always misses the cache.

```python
if __name__ == "__main__":
    start_time = time.time()

    messages = [
        {
            "role": "system",
            "content": "You are an assistant that can answer questions about the weather of a city.",
        },
        {
            "role": "user",
            "content": "What is the city with the best weather in January?",
        },
    ]

    client = OpenAI()
    response = client.chat.completions.create(
        model="gemini-2.0-flash",
        messages=messages,
    )
    print(response.choices[0].message.content)
    end_time = time.time()
    print(f"Generation time: {end_time - start_time:.2f} seconds")

    class City(BaseModel):
        name: str
        state: str

    class Weather(BaseModel):
        temperature: float
        humidity: float
        description: str

    class WeatherCity(BaseModel):
        city: City
        weather: Weather

    start_time = time.time()
    response = client.beta.chat.completions.parse(
        model="gemini-2.0-flash",
        messages=messages,
        response_format=WeatherCity,
    )
    print(response.choices[0].message.parsed)
    end_time = time.time()
    print(f"Generation time with response format: {end_time - start_time:.2f} seconds")
```

Cache settings:
```yaml
# litellm_config.yaml
model_list:
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GOOGLE_LLM_API_KEY
litellm_settings:
  set_verbose: True
  cache: true 
  cache_params:        
    type: redis
    namespace: "litellm.caching.caching"
    host: "redis"
    port: "7001"
    ttl: 31536000
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.3
