### ISSUE TITLE
[Bug]: Embeddings request fails on /v1/embeddings

### ISSUE THREAD

**Issue by deepanshululla** [BerriAI/litellm#8744]
### What happened?

A bug happened!

```
curl --request POST \
  --url https://dev-shared-llmgateway.dev.billdot.io/v1/embeddings \
  --header 'Authorization: Bearer {{ api_key }}' \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: insomnia/10.3.0' \
  --data '{
	"input": "Your text string goes here",
	"model": "text-embedding-3small"
}'

```
This returns
```
{
	"error": {
		"message": "litellm.APIError: APIError: OpenAIException - coroutine already executing\nReceived Model Group=text-embedding-3small\nAvailable Model Group Fallbacks=None\nError doing the fallback: list index out of range",
		"type": null,
		"param": null,
		"code": "500"
	}
}
```

This is only true for open ai models. it works for bedrock models though.

The underlying openai key I am using works with the openai endpoint.

More config

```yml
litellm_settings:
  json_logs: true # if true, logs will be in json format
  ssl_verify: false # 👈 KEY CHANGE
  success_callback: ["s3", "datadog_llm_observability"] # logs llm success logs on datadog
  failure_callback: ["s3", "datadog_llm_observability"] # logs llm success logs on datadog
  store_audit_logs: false

model_list:
  - model_name: bedrock/*
    litellm_params:
      model: bedrock/*
  - model_name: gpt-4o-custom
    litellm_params:
      model: openai/gpt-4o
  - model_name: gpt-4o-custom
    litellm_params:
      model: openai/gpt-4o-mini
  - model_name: text-embedding-3large
    litellm_params:
      model: openai/text-embedding-3-large
    model_info:
      mode: embedding
  - model_name: text-embedding-3small
    litellm_params:
      model: openai/text-embedding-3-small
    model_info:
      mode: embedding

general_settings:
  ssl_verify: false # 👈 KEY CHANGE
  allow_requests_on_db_unavailable: True
  proxy_batch_write_at: 60 # Batch write spend updates every 60s
  store_prompts_in_spend_logs: False
  database_connection_pool_limit: 20 # limit the number of database connections to = MAX Number of DB Connections/Number of instances of litellm proxy (Around 10-20 is good number)

router_settings:
  routing_strategy: simple-shuffle # Literal["simple-shuffle", "least-busy", "usage-based-routing","latency-based-routing"], default="simple-shuffle"
  model_group_alias: {"gpt-4": "gpt-4o-custom"} # all requests with `gpt-4` will be routed to models with `gpt-3.5-turbo`
  num_retries: 2

```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

main-v1.61.1
