### ISSUE TITLE
[Feature]: Add suport for Claude Sonnet 3.7 thinking parameters

### ISSUE THREAD

**Issue by scaramouche1** [BerriAI/litellm#8768]
### The Feature

In `litellm-config.yaml`, it would be useful to be able to create a model that calls Claude Sonnet 3.7 with specific thinking parameters.  For example, that something like this:

    - model_name: claude-3.7-sonnet-thinking
      litellm_params:
        model: anthropic/claude-3-7-sonnet-latest
        thinking_type: enabled
        thinking_budget_tokens: 16000

... made an API call passing these parameters:

    thinking={
        "type": "enabled",
        "budget_tokens": 16000
    }

### Motivation, pitch

This would make it easy to call Claude 3.7 with different parameters.   It is a similar rationale for how the parameter `reasoning_effort` was added to configuration after OpenAI added this parameter in their API.

### Are you a ML Ops Team?

No

**Comment by scaramouche1** [comment]
From looking at the issue that is marked as closing this one (#8778) it is not clear what to put in `litellm-config.yaml` to configure the thinking type and budget.  Can you provide an example of the yaml file?

**Comment by ghost** [comment]
Hey @scaramouche1 it's the exact same param as anthropic 

```yaml
- model_name: claude-3-7-sonnet-20250219
  litellm_params:
    model: anthropic/claude-3-7-sonnet-20250219
    api_key: os.environ/ANTHROPIC_API_KEY
    thinking: {"type": "enabled", "budget_tokens": 1024} 👈 CAN BE SET EITHER HERE or in request body
```
