### ISSUE TITLE
[Feature]: Make `AWS Access Key ID` and `AWS Secret Access Key` optional in the `Add new model` UI

### ISSUE THREAD

**Issue by mirodrr2** [BerriAI/litellm#8811]
### The Feature

Make AWS Access Key ID and AWS Secret Access Key optional in the Add new model UI

### Motivation, pitch

I deploy Litellm on AWS on both ECS and EKS. The IAM role of my deployment already has access to Bedrock. So, in my config.yaml, I do not specify an `AWS Access Key ID` or `AWS Secret Access Key`, and it "just works"

I should not be forced to provide credentials for this

And also, the option to provide `os.environ/MY_SECRET_KEY` and `os.environ/MY_SECRET_KEY` does not fix this issue, as ECS/EKS assuming a role also relies on a session token

![Image](https://github.com/user-attachments/assets/5b24533b-80fb-4cd9-b7f7-6b1ec43de4fd)

### Are you a ML Ops Team?

No

**Comment by wagnerjt** [comment]
I also run into this from the frontend, so I do it programmatically and use the `aws_role_name` instead of these two in the body of the model creation.

Maybe the enhancement should be to choosing between ACCESS_KEY + SECRET_KEY or this ROLE_NAME.

**Comment by mirodrr2** [comment]
> I also run into this from the frontend, so I do it programmatically and use the `aws_role_name` instead of these two in the body of the model creation.
> 
> Maybe the enhancement should be to choosing between ACCESS_KEY + SECRET_KEY or this ROLE_NAME.

That would be a okay option, but the ideal for me would be the option to specify neither (just like I can in my config.yaml), so my admins do not need to be aware of the underlying AWS infrastructure

**Comment by ishaan-jaff** [comment]
<img width="704" alt="Image" src="https://github.com/user-attachments/assets/f34bf5b9-512f-497a-9110-05885c76659f" />

should the ui just allow all these params as optional ? @mirodrr2 / @wagnerjt

**Comment by mirodrr2** [comment]
Yes, all of them should be optional in my opinion. If you're running on AWS, this is all already taken care of for you via ECS/EKS assumed IAM roles

**Comment by mirodrr2** [comment]
For reference, this is what my config.yaml looks like for bedrock models, and it works just fine:

```
- model_name: amazon.nova-pro-v1:0
    litellm_params:
      model: bedrock/amazon.nova-pro-v1:0
  - model_name: amazon.nova-lite-v1:0
    litellm_params:
      model: bedrock/amazon.nova-lite-v1:0
  - model_name: amazon.nova-canvas-v1:0
    litellm_params:
      model: bedrock/amazon.nova-canvas-v1:0
  - model_name: amazon.nova-reel-v1:0
    litellm_params:
      model: bedrock/amazon.nova-reel-v1:0
```
