### ISSUE TITLE
[Bug]: Bedrock Claude Sonnet 3.7 inference profile support

### ISSUE THREAD

**Issue by jleatham** [BerriAI/litellm#8851]
### What happened?

The model selection in the UI only allows for `anthropic.claude-3-7-sonnet-20250219-v1:0
`.  However, the API call requires a selection of an inference profile, e.g., `us.anthropic.claude-3-7-sonnet-20250219-v1:0`

### Relevant log output

```shell
400: litellm.BadRequestError: BedrockException - {"message":"Invocation of model ID anthropic.claude-3-7-sonnet-20250219-v1:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model."}. Received Model Group=anthropic.claude-3-7-sonnet-20250219-v1:0
Available Model Group Fallbacks=None
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.16
litellm-database:v1.61.16

**Comment by goodtiger** [comment]
I got the same Error.

**Comment by NorthIsUp** [comment]
you need to have the inference region set. so in the US like this:

```
  - model_name: us.anthropic.claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: us-west-2
```
