### ISSUE TITLE
[Bug]: bedrock claude 3.7 sonnet proxy request will drop thinking param in invoke request

### ISSUE THREAD

**Issue by lyajedi** [BerriAI/litellm#8892]
### What happened?

my config:
```
model_list:
  - model_name: claude-3-7-sonnet-20250219
    litellm_params:
      model: bedrock/invoke/anthropic.claude-3-7-sonnet-20250219-v1:0
      api_base: "http://litellm-aws"  # my internal proxy server

litellm_settings:
  drop_params: true
```
the request body:
```
{
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Explain what is GPT"
                }
            ]
        }
    ],
    "thinking": {
        "type": "enabled",
        "budget_tokens": 14000
    },
    "max_tokens": 26000,
    "stream": false
}
```

From the proxy server logging, the thinking param is dropped, what ever the `drop_params` is set to true or false.
LiteLLM also put `max_tokens_to_sample` (not supported in /invoke endpoint) to the param instead of the `max_tokens'

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.20.rc
