### ISSUE TITLE
[Bug]: Deepseek-r1's reasoning content is missing in latest version v1.61.20.rc

### ISSUE THREAD

**Issue by v3i1y** [BerriAI/litellm#8909]
### What happened?

"reasoning_content" is no longer returned from deepseek/deepseek-reasoner model.

It seems to work on `v1.61.15-nightly`.

Starting from `v1.61.16-nightly`, `reasoning_content` is returned from deepseek if `stream` in the completion request is set to `false`. However, in the latest version, `reasoning_content` content is missing even if `stream` is set to false.

I suspect something got broken when claude's thinking was added.

I am using official deepseek API... following is my configuration
``` yaml
model_list:
  - model_name: deepseek-reasoner
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_key: sk-123
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.20.rc
