### ISSUE TITLE
[Bug]: Error with aws_region_name with Bedrock Stability models

### ISSUE THREAD

**Issue by marty-sullivan** [BerriAI/litellm#8946]
### What happened?

I'm trying to use the following configuration in LiteLLM proxy v1.61.20-stable that works fine in v1.60.4:

```yaml
  - model_name: 'stability.stable-diffusion-3.5-large'
    litellm_params:
      model: 'bedrock/stability.sd3-5-large-v1:0'
      aws_region_name: 'us-west-2'

  - model_name: 'stability.stable-image-ultra'
    litellm_params:
      model: 'bedrock/stability.stable-image-ultra-v1:1'
      aws_region_name: 'us-west-2'
```

This is causing an error when calling these models in the newer version, saying that `aws_region_name` is an invalid field

### Relevant log output

```shell
{'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"{\\"detail\\":\\"Invalid field \'aws_region_name\' in request. Available fields for ultra are: prompt, negative_prompt, mode, strength, seed, output_format, image, aspect_ratio\\"}"}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.20-stable
