### ISSUE TITLE
[Bug]: response error incomplete with bedrock/us.anthropic.claude-3-7-sonnet thinking and librechat

### ISSUE THREAD

**Issue by tangr** [BerriAI/litellm#8951]
### What happened?

From: https://github.com/danny-avila/LibreChat/issues/6123

bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0 is works well without **_thinking_**

### What happened?

Something went wrong. Here's the specific error message we encountered: The response is incomplete; it's either still processing, was cancelled, or censored. Refresh or try a different prompt.

enable claude-3-7-sonnet-v1 with : 
thinking: {"type": "enabled", "budget_tokens": 1024}

https://docs.litellm.ai/docs/providers/bedrock#usage---thinking--reasoning-content

### Version Information

docker images | grep librechat:

ghcr.io/danny-avila/librechat-dev                2293cd667e3052b44cc27c3efc18f951859d4a9a   997e48c9ed50   7 hours ago     881MB

### Steps to Reproduce

librechat.yaml
```yaml
endpoints:
  custom:
    - name: "LiteLLM"
      # A place holder - otherwise it becomes the default (OpenAI) key
      # Provide the key instead in each "model" block within "litellm/litellm-config.yaml"
      apiKey: "sk-from-config-file"
      # See the required changes above in "Start LiteLLM Proxy Server" step.
      baseURL: "http://host.docker.internal:4000"
      # A "default" model to start new users with. The "fetch" will pull the rest of the available models from LiteLLM
      # More or less this is "irrelevant", you can pick any model. Just pick one you have defined in LiteLLM.
      models:
        default:
          - "claude-3-7-sonnet-v1"
        fetch: false
      titleConvo: true
      titleModel: "current_model"
      titleMessageRole: "user"
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "Lite LLM"
```

litellm-config.yaml
```yaml
model_list:
  - model_name: claude-3-7-sonnet-v1
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: ""
      aws_access_key_id: ""
      aws_secret_access_key: ""
      thinking: {"type": "enabled", "budget_tokens": 1024}
```

### Relevant log output

error log:
```shell

2025-03-01 00:13:06 warn: [OpenAIClient.chatCompletion][stream] Unhandled error type
2025-03-01 00:13:06 error:
2025-03-01 00:13:06 warn: [OpenAIClient.chatCompletion][finalChatCompletion] Unhandled error type
2025-03-01 00:13:06 error:
2025-03-01 00:13:06 error: [OpenAIClient.chatCompletion] Unhandled error type Error: missing choices[0].tool_calls[0].id
{"id":"chatcmpl-f5240f1a-cfa8-4393-9f4d-9600ab0d74fa","created":1740787986,"model":"us.anthropic.claude-3-7-sonnet-20250219-v1:0","object":"chat.completion.chunk","provider_specific_fields":{},"choices":[{"finish_reason":"stop","index":0,"message":{"reasoning_content":"ise","thinking_blocks":[{"type":"thinking"}],"provider_specific_fields":{"reasoningContent":{"signature":"EqoBCkgIARABGAIiQBUp0giEOrDWRgwP856KU6uKHm1MP47XvkmPDnU4Ti9HH88TwP6Nt+dmzJRszgd9rmYB+ZQcDzyKm3ED6evlfDgSDEExSHFVTHzD6ijTRBoM1EdCjMEZQ4ctiq93IjBXlfB7qTGbl981DHTAn0rojxlNOjF7ZZEPi5lZ6zREraxOFPgJrJN1dQWdQFNRW24qEOYGj8ZJld1YfugqhSrIj2c="}},"role":"assistant","tool_calls":[{"type":"function","function":{"name":"","arguments":"{}"}},{"type":"function","function":{"name":"","arguments":"{}"}}]},"logprobs":null},{"index":1,"message":{"content":"Hello again! I notice you're saying hi multiple times. I'm here and fully responsive.\n\nSometimes it can be hard to know where to start a conversation. Would you like to:\n\n- Ask me a question about a topic you're curious about?\n- Get help with something specific?\n- Just chat about something interesting?\n\nFeel free to let me know how I can be helpful to you today!"},"logprobs":null}]}
2025-03-01 00:13:06 error: [handleAbortError] AI response error; aborting request: Error: missing choices[0].tool_calls[0].id
{"id":"chatcmpl-f5240f1a-cfa8-4393-9f4d-9600ab0d74fa","created":1740787986,"model":"us.anthropic.claude-3-7-sonnet-20250219-v1:0","object":"chat.completion.chunk","provider_specific_fields":{},"choices":[{"finish_reason":"stop","index":0,"message":{"reasoning_content":"ise","thinking_blocks":[{"type":"thinking"}],"provider_specific_fields":{"reasoningContent":{"signature":"EqoBCkgIARABGAIiQBUp0giEOrDWRgwP856KU6uKHm1MP47XvkmPDnU4Ti9HH88TwP6Nt+dmzJRszgd9rmYB+ZQcDzyKm3ED6evlfDgSDEExSHFVTHzD6ijTRBoM1EdCjMEZQ4ctiq93IjBXlfB7qTGbl981DHTAn0rojxlNOjF7ZZEPi5lZ6zREraxOFPgJrJN1dQWdQFNRW24qEOYGj8ZJld1YfugqhSrIj2c="}},"role":"assistant","tool_calls":[{"type":"function","function":{"name":"","arguments":"{}"}},{"type":"function","function":{"name":"","arguments":"{}"}}]},"logprobs":null},{"index":1,"message":{"content":"Hello again! I notice you're saying hi multiple times. I'm here and fully responsive.\n\nSometimes it can be hard to know where to start a conversation. Would you like to:\n\n- Ask me a question about a topic you're curious about?\n- Get help with something specific?\n- Just chat about something interesting?\n\nFeel free to let me know how I can be helpful to you today!"},"logprobs":null}]}
2025-03-01 00:13:06 error: [handleAbortError] error while trying to abort message Cannot set headers after they are sent to the client

```

### Screenshots

![Image](https://github.com/user-attachments/assets/1f23f25e-0ac9-4ec4-81ea-66d6fe533b93)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

main-v1.61.20.rc

**Comment by Shishizonzon** [comment]
I have got the same issue.

**Comment by Shishizonzon** [comment]
Which platform are you using? I integrated Claude-3.7-sonnect with Open-WebUI, but I noticed the reasoning_content parameter in the log. I'm not sure if Open-WebUI fully supports the thinking mode of Claude-3.7-sonnect. Can anyone clarify?

**Comment by tangr** [comment]
> Which platform are you using? I integrated Claude-3.7-sonnect with Open-WebUI, but I noticed the reasoning_content parameter in the log. I'm not sure if Open-WebUI fully supports the thinking mode of Claude-3.7-sonnect. Can anyone clarify?

librechat + bedrock Claude-3.7-sonnect with thinking

**Comment by Classic298** [comment]
> Which platform are you using? I integrated Claude-3.7-sonnect with Open-WebUI, but I noticed the reasoning_content parameter in the log.

Did you implement Claude 3.7 Sonnet with thinking via LiteLLM into OpenWebUI?
Is that right?
How?

When I set the thinking parameter in the proxy, I feel like it doesn't work. The model itself is being called, but I am never getting returned any reasoning/thinking. Never.

```
  - model_name: claude-3-7-sonnet-low # Reasoning
    litellm_params:
      anthropic_version: vertex-2024-06-20
      model: vertex_ai/claude-3-7-sonnet@20250219
      thinking: {"type": "enabled", "budget_tokens": 16000}
      max_tokens: 32000
```

> I'm not sure if Open-WebUI fully supports the thinking mode of Claude-3.7-sonnect. Can anyone clarify?

So, no, it doesn't as far as I know. But even if it would, it would only support it via direct integration, not if we go via another middleware like LiteLLM

**Comment by adamrb** [comment]
I have the same bug with the same setup as @tangr.

**Comment by Shishizonzon** [comment]
> > Which platform are you using? I integrated Claude-3.7-sonnect with Open-WebUI, but I noticed the reasoning_content parameter in the log.
> 
> Did you implement Claude 3.7 Sonnet with thinking via LiteLLM into OpenWebUI? Is that right? How?
> 
> When I set the thinking parameter in the proxy, I feel like it doesn't work. The model itself is being called, but I am never getting returned any reasoning/thinking. Never.
> 
> ```
>   - model_name: claude-3-7-sonnet-low # Reasoning
>     litellm_params:
>       anthropic_version: vertex-2024-06-20
>       model: vertex_ai/claude-3-7-sonnet@20250219
>       thinking: {"type": "enabled", "budget_tokens": 16000}
>       max_tokens: 32000
> ```
> 
> > I'm not sure if Open-WebUI fully supports the thinking mode of Claude-3.7-sonnect. Can anyone clarify?
> 
> So, no, it doesn't as far as I know. But even if it would, it would only support it via direct integration, not if we go via another middleware like LiteLLM

I can show you my setup in LiteLLM @Classic298 :

```- model_name: Claude-3.7-Sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: your_access_key_id
      aws_secret_access_key: your_secret_access_key
      aws_region_name: us-west-2
      thinking: {"type": "enabled", "budget_tokens": 4096}
```


I'm not sure if you're using the same model from AWS. I encountered an issue where I lost _us_ in the model name during the setup process. Could you confirm if this is expected or if I might have misconfigured something?

**Comment by Classic298** [comment]
@Shishizonzon i don't use bedrock, but no I've never had ... parts of my model name disappear from the model name?

**Comment by tinuva** [comment]
I also have the same issue as @tangr 

Bedrock + Claude 3.7 in litellm and LibreChat as the app connecting to litellm.

What I see on screen is, the thinking starts showing LibreChat but then get replaced by an error that,
> Assistant used
> {}{}

LiteLLM proxy recorded this:
* Request:
```json
{
  "model": "bedrock-claude-3-7-sonnet-thinking",
  "stream": true,
  "stream_options": {
    "include_usage": true
  },
  "messages": [
    {
      "role": "system",
      "content": "Think step by step, but only keep a minimum draft for each thinking step, with 5 words at most. Return the answer at the end of the response after a separator ####."
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "12-9+8"
        }
      ]
    }
  ]
}
```

* Response
```json
{
  "id": "chatcmpl-4a27902e-5057-45f3-83de-93f38885b845",
  "model": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
  "usage": {
    "total_tokens": 155,
    "prompt_tokens": 53,
    "completion_tokens": 102,
    "prompt_tokens_details": null,
    "completion_tokens_details": null
  },
  "object": "chat.completion",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Starting with 12-9=3.\nThen 3+8=11.\n\n#### 11",
        "tool_calls": [
          {
            "id": "4dd82dfc-acdd-4591-870d-1255b6da9405",
            "type": "function",
            "function": {
              "name": null,
              "arguments": "{}{}"
            }
          },
          {
            "id": "77a2da9f-74b5-4bfb-bbc1-11322aae6168",
            "type": "function",
            "function": {
              "name": null,
              "arguments": "{}"
            }
          }
        ],
        "function_call": null
      },
      "finish_reason": "stop"
    }
  ],
  "created": 1741155896,
  "system_fingerprint": null
}
```

**Comment by tinuva** [comment]
So it looks like this is working in openwebui, though it seems a bit weird.

![Image](https://github.com/user-attachments/assets/9eaa031a-0a3e-4cd8-9830-e98eb480d1ed)

The screenshot shows how it was "thinking" but there is this strange tool use 

On litellm I see 3 requests.
![Image](https://github.com/user-attachments/assets/469fcde2-b565-4a72-85a3-f45780c707f3)

Request1:
```json
{
  "stream": true,
  "model": "bedrock-claude-3-7-sonnet-thinking",
  "messages": [
    {
      "role": "user",
      "content": "12-9+8"
    }
  ]
}
```
Response1:
```json
{
  "id": "chatcmpl-62642681-4d12-4584-a2ac-70c745a744cc",
  "model": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
  "usage": {
    "total_tokens": 130,
    "prompt_tokens": 12,
    "completion_tokens": 118,
    "prompt_tokens_details": null,
    "completion_tokens_details": null
  },
  "object": "chat.completion",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "I'll calculate the expression 12-9+8 following the order of operations:\n\n12-9+8 = 3+8 = 11\n\nThe answer is 11.",
        "tool_calls": [
          {
            "id": "cfc46604-edfc-437f-bf78-d7dfd0e35948",
            "type": "function",
            "function": {
              "name": null,
              "arguments": "{}{}"
            }
          },
          {
            "id": "c0d78ff6-c6a2-484a-8b76-3045744e41e3",
            "type": "function",
            "function": {
              "name": null,
              "arguments": "{}"
            }
          }
        ],
        "function_call": null
      },
      "finish_reason": "stop"
    }
  ],
  "created": 1741166710,
  "system_fingerprint": null
}
```

Request2 failed so no response. Looking at the request, this just caused that the conversation has no title in the UI which I am not too concerned about right now in this bug.
```json
{
  "model": "bedrock-claude-3-7-sonnet-thinking",
  "messages": [
    {
      "role": "user",
      "content": "### Task:\nGenerate a concise, 3-5 word title with an emoji summarizing the chat history.\n### Guidelines:\n- The title should clearly represent the main theme or subject of the conversation.\n- Use emojis that enhance understanding of the topic, but avoid quotation marks or special formatting.\n- Write the title in the chat's primary language; default to English if multilingual.\n- Prioritize accuracy over excessive creativity; keep it clear and simple.\n### Output:\nJSON format: { \"title\": \"your concise title here\" }\n### Examples:\n- { \"title\": \"📉 Stock Market Trends\" },\n- { \"title\": \"🍪 Perfect Chocolate Chip Recipe\" },\n- { \"title\": \"Evolution of Music Streaming\" },\n- { \"title\": \"Remote Work Productivity Tips\" },\n- { \"title\": \"Artificial Intelligence in Healthcare\" },\n- { \"title\": \"🎮 Video Game Development Insights\" }\n### Chat History:\n<chat_history>\nUSER: 12-9+8\nASSISTANT: I'll calculate the expression 12-9+8 following the order of operations:\n\n12-9+8 = 3+8 = 11\n\nThe answer is 11.\n\n<details type=\"tool_calls\" done=\"true\" content=\"[{&quot;function&quot;: {&quot;arguments&quot;: &quot;{}&quot;}, &quot;type&quot;: &quot;function&quot;, &quot;index&quot;: 0}, {&quot;function&quot;: {&quot;arguments&quot;: &quot;{}&quot;}, &quot;type&quot;: &quot;function&quot;, &quot;index&quot;: 1}]\" results=\"[{&quot;tool_call_id&quot;: &quot;&quot;, &quot;content&quot;: null}, {&quot;tool_call_id&quot;: &quot;&quot;, &quot;content&quot;: null}]\">\n<summary>Tool Executed</summary>\n\n> : None\n> : None\n</details>\n</chat_history>"
    }
  ],
  "stream": false,
  "max_tokens": 1000
}
```

Request3:
```json
{
  "model": "bedrock-claude-3-7-sonnet-thinking",
  "messages": [
    {
      "role": "user",
      "content": "### Task:\nGenerate 1-3 broad tags categorizing the main themes of the chat history, along with 1-3 more specific subtopic tags.\n\n### Guidelines:\n- Start with high-level domains (e.g. Science, Technology, Philosophy, Arts, Politics, Business, Health, Sports, Entertainment, Education)\n- Consider including relevant subfields/subdomains if they are strongly represented throughout the conversation\n- If content is too short (less than 3 messages) or too diverse, use only [\"General\"]\n- Use the chat's primary language; default to English if multilingual\n- Prioritize accuracy over specificity\n\n### Output:\nJSON format: { \"tags\": [\"tag1\", \"tag2\", \"tag3\"] }\n\n### Chat History:\n<chat_history>\nUSER: 12-9+8\nASSISTANT: I'll calculate the expression 12-9+8 following the order of operations:\n\n12-9+8 = 3+8 = 11\n\nThe answer is 11.\n\n<details type=\"tool_calls\" done=\"true\" content=\"[{&quot;function&quot;: {&quot;arguments&quot;: &quot;{}&quot;}, &quot;type&quot;: &quot;function&quot;, &quot;index&quot;: 0}, {&quot;function&quot;: {&quot;arguments&quot;: &quot;{}&quot;}, &quot;type&quot;: &quot;function&quot;, &quot;index&quot;: 1}]\" results=\"[{&quot;tool_call_id&quot;: &quot;&quot;, &quot;content&quot;: null}, {&quot;tool_call_id&quot;: &quot;&quot;, &quot;content&quot;: null}]\">\n<summary>Tool Executed</summary>\n\n> : None\n> : None\n</details>\n</chat_history>"
    }
  ],
  "stream": false
}
```
The error:
```
Type:
BadRequestError
Message:
litellm.BadRequestError: BedrockException - {"message":"The model returned the following errors: max_tokens must be greater than thinking.budget_tokens"}
```
I guess this is a configuration error on my part, just not sure what yet.

Response3:
```json
{
  "id": "chatcmpl-74911adc-09ac-4ab7-9333-64417355da5f",
  "model": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
  "usage": {
    "total_tokens": 700,
    "prompt_tokens": 479,
    "completion_tokens": 221,
    "prompt_tokens_details": null,
    "completion_tokens_details": null
  },
  "object": "chat.completion",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "```json\n{\n  \"tags\": [\"Education\", \"Mathematics\", \"Arithmetic\"]\n}\n```",
        "tool_calls": null,
        "function_call": null,
        "thinking_blocks": [
          {
            "type": "thinking",
            "thinking": "I need to analyze the chat history and generate broad tags categorizing the main themes, along with more specific subtopic tags.\n\nIn this chat history, there's only one interaction:\n1. User asked: \"12-9+8\"\n2. Assistant solved the arithmetic expression: 12-9+8 = 3+8 = 11\n\nThis is a simple arithmetic calculation. The conversation is very short (just one exchange) and focused entirely on elementary mathematics - specifically basic arithmetic involving addition and subtraction.\n\nFor the high-level domain, this falls under \"Mathematics\" or \"Education\".\nFor subtopics, this would be \"Arithmetic\" or \"Basic Calculations\".\n\nSince the content is very brief (just one exchange), I could use only [\"General\"], but since the content is clearly focused on mathematics/arithmetic, it makes more sense to use those tags.",
            "signature_delta": "EqoBCkgIARABGAIiQCWjGxhold9l2NBPE+Z62bFb3ph/RyvQbiiysbC4JEg39aOzsXRgj8d2enVk+Zu770AhI0uzlbZwnOFINT5xUysSDAFh9gnQt4dcxfs8RxoM8Qs9COYvpLZ4kdQcIjDIyatfOxDz99Bti/9HSV8XkH1n+o40cpVPOJtBQpF9IhwAu/uiz+cveIGm9OY68qUqEJut4g50B1j8B/+DEfYowPQ="
          }
        ],
        "reasoning_content": "I need to analyze the chat history and generate broad tags categorizing the main themes, along with more specific subtopic tags.\n\nIn this chat history, there's only one interaction:\n1. User asked: \"12-9+8\"\n2. Assistant solved the arithmetic expression: 12-9+8 = 3+8 = 11\n\nThis is a simple arithmetic calculation. The conversation is very short (just one exchange) and focused entirely on elementary mathematics - specifically basic arithmetic involving addition and subtraction.\n\nFor the high-level domain, this falls under \"Mathematics\" or \"Education\".\nFor subtopics, this would be \"Arithmetic\" or \"Basic Calculations\".\n\nSince the content is very brief (just one exchange), I could use only [\"General\"], but since the content is clearly focused on mathematics/arithmetic, it makes more sense to use those tags."
      },
      "finish_reason": "stop"
    }
  ],
  "created": 1741166722,
  "system_fingerprint": null
}
```

**Comment by Classic298** [comment]
@tinuva  how did you get it to work? Do you use LiteLLM via OpenAI connection directly in the Connections setting in OpenWebUI or do you have a custom pipeline for this? And could you share your LiteLLM setup for claude? Thanks

**Comment by tinuva** [comment]
> [@tinuva](https://github.com/tinuva) how did you get it to work? Do you use LiteLLM via OpenAI connection directly in the Connections setting in OpenWebUI or do you have a custom pipeline for this? And could you share your LiteLLM setup for claude? Thanks

To be honest, I think part of it is, there was a new version of openwebui released today. I have watchtower configured to automatically pull the latest container in docker once a day.

Litellm config that is relevant:
```yaml
  - model_name: bedrock-claude-3-7-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: us-east-2
      aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY

  - model_name: bedrock-claude-3-7-sonnet-thinking
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: us-east-2
      aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY
      thinking:
        type: enabled
        budget_tokens: 1024
      max_tokens: 16384
```

This give me 2 models to use. One with and one without thinking configured.

And in Openwebui, it is just a single openai connection directly in the connections settings to http://litellm:4000/ without any models manually configured, to let it auto populate all my litellm models for me.
