### ISSUE TITLE
[Feature]: Enhance Helm Chart

### ISSUE THREAD

**Issue by mknet3** [BerriAI/litellm#8954]
### The Feature

Improve the Helm Chart with some features to make it more extensible. In my opinion, these features are necessary:

- [ ] Avoid forcing environment variables to follow `key: value` convention (see [this](https://github.com/BerriAI/litellm/blob/db83cbe5c04875032e2fc754800172ceb46baed0/deploy/charts/litellm-helm/templates/deployment.yaml#L94-L98)). This issue prevents the user to configure environment variables for the deployment in this way:
```yaml
- name: DD_ENV
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/env']
- name: DD_SERVICE
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/service']
- name: DD_VERSION
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['tags.datadoghq.com/version']
- name: DD_AGENT_HOST
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

- [ ] Avoid forcing the user to create the masterkey in the `values.yaml` file to allow people use other secret mechanisms like [Secret Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/) where secrets are created directly from external secrets storage like Hashicorp Vault.
- [ ] Publish the Chart with the proper version (now the version of the chart is [0.4.1](https://github.com/BerriAI/litellm/blob/db83cbe5c04875032e2fc754800172ceb46baed0/deploy/charts/litellm-helm/Chart.yaml#L21) but we are releasing `0.1.626` and it has to be used in this way being harder to follow the changes:
```yaml
  - name: litellm-helm
    version: 0.1.604
    repository: oci://ghcr.io/berriai
    condition: litellm-helm.enabled
```

Also, as other optional improvements that I think could be good:
- [ ] Sometimes integration tests are not possible or are not necessary. Unit tests are better in many cases and we can configure them with [helm-unittest](https://github.com/helm-unittest/helm-unittest).
- [ ] Create JSON Schema  (see [Backstage example](https://github.com/backstage/charts/blob/main/charts/backstage/values.schema.json))
- [ ] Create a separated repository for charts like is done in other open source / CNCF projects (e.g. [backstage](https://github.com/backstage/charts), [open-webui](https://github.com/open-webui/helm-charts/tree/main), [keda](https://github.com/kedacore/charts))

Of course, I can collaborate but I wanted to open the issue first to discuss if you have some concerns @ishaan-jaff @krrishdholakia 

### Motivation, pitch

Improve the helm chart to make it more extensible and follow community conventions.

### Are you a ML Ops Team?

No

### Twitter / LinkedIn details

https://www.linkedin.com/in/mcaneteubeda/
