### ISSUE TITLE
[Bug]: Very long answer processing

### ISSUE THREAD

**Issue by markowanga** [BerriAI/litellm#8965]
### What happened?

I connected multiple completable OpenAI API (OpenAI, Hyperbolic, Azure) and I have similar problem with very small call (normally executed in 2-3 seconds) -- sometimes I have response in over 20-30 second, something hangs

I have this deployment (also api key in .env). I'm not using cache:
```
services:
  litellm:
    image: ghcr.io/berriai/litellm:litellm_stable_release_branch-v1.61.20-stable
    container_name: litellm_app
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
      STORE_MODEL_IN_DB: "True"
    env_file:
      - .env

  db:
    image: postgres
    container_name: litellm_db
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db_data:
```

### Relevant log output

```shell
I have no error logs from app -- I looks like something hang in application. I have speed server for deployment litellm
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.20
