### ISSUE TITLE
[Bug]: If a request is received where max_tokens is less than thinking budget

### ISSUE THREAD

**Issue by tinuva** [BerriAI/litellm#9001]
### What happened?

 If a request is received where max_tokens is less than thinking budget, either thinking needs to be disabled or the max tokens needs to be increased, or an appropriate errors needs to be responded with instead of sending the request to the upstream provider.

Example.
* LiteLLM config
```yaml
  - model_name: bedrock-claude-3-7-sonnet-thinking
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: us-east-2
      aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY
      thinking:
        type: enabled
        budget_tokens: 1024
      max_tokens: 16384
```

Note, budget_tokens can't be set lower than 1024.

### Relevant log output

```shell
* Request created by Openwebui / Librechat for conversation name

{
  "model": "bedrock-claude-3-7-sonnet-thinking",
  "messages": [
    {
      "role": "user",
      "content": "### Task:\nGenerate a concise, 3-5 word title with an emoji summarizing the chat history.\n### Guidelines:\n- The title should clearly represent the main theme or subject of the conversation.\n- Use emojis that enhance understanding of the topic, but avoid quotation marks or special formatting.\n- Write the title in the chat's primary language; default to English if multilingual.\n- Prioritize accuracy over excessive creativity; keep it clear and simple.\n### Output:\nJSON format: { \"title\": \"your concise title here\" }\n### Examples:\n- { \"title\": \"📉 Stock Market Trends\" },\n- { \"title\": \"🍪 Perfect Chocolate Chip Recipe\" },\n- { \"title\": \"Evolution of Music Streaming\" },\n- { \"title\": \"Remote Work Productivity Tips\" },\n- { \"title\": \"Artificial Intelligence in Healthcare\" },\n- { \"title\": \"🎮 Video Game Development Insights\" }\n### Chat History:\n<chat_history>\nUSER: 12-9+8\nASSISTANT: \n</chat_history>"
    }
  ],
  "stream": false,
  "max_tokens": 1000
}


Error:

Type: BadRequestError
Message: litellm.BadRequestError: BedrockException - {"message":"The model returned the following errors: thinking.enabled.budget_tokens: Input should be greater than or equal to 1024"}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

docker image ghcr.io/berriai/litellm:main-latest updates daily, so version released before or on  2025-03-05
