### ISSUE TITLE
[Bug]: Got exception from REDIS Connection closed by server

### ISSUE THREAD

**Issue by langgg0511** [BerriAI/litellm#9024]
### What happened?

```yaml
general_settings:
  disable_master_key_return: true
  disable_reset_budget: true
  disable_retry_on_max_parallel_request_limit_error: true
  master_key: "sk-123"
  alerting: ["slack"]
  alert_types: ["llm_exceptions", "llm_requests_hanging"]
  database_url: ""
  database_connection_pool_limit: 5
  database_connection_timeout: 60
  proxy_batch_write_at: 60
  store_model_in_db: true
litellm_settings:
  ssl_verify: false
  json_logs: true
  cache: True
  cache_params:
    type: redis
    namespace: "litellm_caching"
    host: "redis.db"
    port: 6379
    ttl: 86400
    supported_call_types: ["acompletion", "atext_completion", "aembedding", "atranscription"]
  drop_params: true
  num_retries: 0
  redact_user_api_key_info: true
```

### Relevant log output

```shell
{"message": "LiteLLM Redis Caching: async set_cache_pipeline() - Got exception from REDIS Connection closed by server., Writing value=None", "level": "ERROR", "timestamp": "2025-03-06T09:31:49.040450"}
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.61.3
