### ISSUE TITLE
[Feature]: Support reusing provider credentials

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#9114]
### The Feature

make it easy for user on ui to store provider credentials, and chose to reuse them 

### Motivation, pitch

when user needs to add new models via ui - this can be quite painful to have to keep getting keys and reusing them 

### Are you a ML Ops Team?

No

**Comment by ghost** [comment]
Could start with just allowing provider credentials to be configured in a file (like for finetuning / files apis) - 

1. configure default provider credentials 

```yaml
credential_list:
  - credential_name: azure-credentials
    api_base: https://exampleopenaiendpoint-production.up.railway.app
    api_key: os.environ/AZURE_API_KEY
    api_version: "2023-03-15-preview"
  - credential_name: openai-credentials
    api_key: os.environ/OPENAI_API_KEY
  - credential_name: vertex_ai-credentials
    vertex_project: "adroit-crow-413218"
    vertex_location: "us-central1"
    vertex_credentials: "/Users/ishaanjaffer/Downloads/adroit-crow-413218-a956eef1a2a8.json"
```

2. reference them when adding new model 

```yaml
model_list:
   - model_name: gpt-3.5-turbo
      litellm_params:
         model: gpt-3.5-turbo
         litellm_credentials: azure-credentials
```

3. Test it! 

```bash
curl -L -X POST 'http://0.0.0.0:4000/v1/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-PIp1h0RekR' \
-d '{
   "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "ping"
    }
  ]
}'
```

**Comment by ghost** [comment]
Considering variants: 

Variant 1: all in 1 flat dict 
```yaml
credential_list:
  - credential_name: azure-credentials
    api_base: https://exampleopenaiendpoint-production.up.railway.app
    api_key: os.environ/AZURE_API_KEY
    api_version: "2023-03-15-preview"
  - credential_name: openai-credentials
    api_key: os.environ/OPENAI_API_KEY
  - credential_name: vertex_ai-credentials
    vertex_project: "adroit-crow-413218"
    vertex_location: "us-central1"
    vertex_credentials: "/Users/ishaanjaffer/Downloads/adroit-crow-413218-a956eef1a2a8.json"
```

Variant 2: nested dict

```yaml
credential_list: 
  - credential_name: str
     credential_data: dict # contains "api_key", "api_base", etc.
     credential_info: # additional metadata that can be attached and shown on a potential CRUD endpoint for this 
```
