### ISSUE TITLE
[Bug]: azure o3-mini OperationNotSupported?

### ISSUE THREAD

**Issue by nathanwong91** [BerriAI/litellm#9122]
### What happened?

When trying to use o3-mini from Litellm proxy I get the following
```
litellm.exceptions.BadRequestError: litellm.BadRequestError: AzureException - Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The chatCompletion operation does not work with the specified model, o3-mini. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}. Received Model Group=batch-azure/o3-mini
```
Current config is 
```
    - model_name: batch-azure/o3-mini
      litellm_params:
        model: azure/o_series/o3-mini
        api_base: os.environ/AZURE_O3_MINI_BASE
        api_version: "2024-12-01-preview"
        api_key: os.environ/AZURE_O3_MINI_API_KEY
      model_info:
        mode: batch
```

I saw a merged PR to add support for o3-mini. Does it not include a batch deployment in Azure?

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.63.3
