### ISSUE TITLE
[Feature]: Error: This model isn't mapped yet. model=us.deepseek.r1-v1:0

### ISSUE THREAD

**Issue by tinuva** [BerriAI/litellm#9126]
### The Feature

After adding this model to my config I get this error:

```
  - model_name: bedrock-deepseek-r1
    litellm_params:
      model: bedrock/converse/us.deepseek.r1-v1:0
      aws_region_name: us-east-2
      aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY
```

Error:
```
litellm                | 04:31:18 - LiteLLM:DEBUG: utils.py:2066 - Model not found or error in checking supports_tool_choice support. You passed model=us.deepseek.r1-v1:0, custom_llm_provider=bedrock_converse. Error: This model isn't mapped yet. model=us.deepseek.r1-v1:0, custom_llm_provider=bedrock_converse. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
```

### Motivation, pitch

I am sure I am not the only user that would use AWS Bedrock Deepseek R1 serverless model.

### Are you a ML Ops Team?

No

**Comment by roey-navina** [comment]
> ### The Feature
> After adding this model to my config I get this error:
> 
> ```
>   - model_name: bedrock-deepseek-r1
>     litellm_params:
>       model: bedrock/converse/us.deepseek.r1-v1:0
>       aws_region_name: us-east-2
>       aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
>       aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY
> ```
> 
> Error:
> 
> ```
> litellm                | 04:31:18 - LiteLLM:DEBUG: utils.py:2066 - Model not found or error in checking supports_tool_choice support. You passed model=us.deepseek.r1-v1:0, custom_llm_provider=bedrock_converse. Error: This model isn't mapped yet. model=us.deepseek.r1-v1:0, custom_llm_provider=bedrock_converse. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
> ```
> 
> ### Motivation, pitch
> I am sure I am not the only user that would use AWS Bedrock Deepseek R1 serverless model.
> 
> ### Are you a ML Ops Team?
> No
> 
> ### Twitter / LinkedIn details
> _No response_

You need to make sure it's enabled in your Bedrock console, it's not enabled by default.

**Comment by tinuva** [comment]
> 
> You need to make sure it's enabled in your Bedrock console, it's not enabled by default.

It is, I can use it. Not sure why I get that message.

**Comment by sa-** [comment]
I can confirm that the model is enabled but I get this error
```
litellm.NotFoundError: BedrockException - Bedrock Invoke HTTPX: Unknown provider=None, model=us.deepseek.r1-v1:0
```

This is how I've configured it
```
      - model_name: bedrock/deepseek.r1-v1:0
        litellm_params:
          model: bedrock/us.deepseek.r1-v1:0
          aws_region_name: "us-west-2"
```
