### ISSUE TITLE
[Feature]: Support llama.cpp as a provider

### ISSUE THREAD

**Issue by jagusztinl** [BerriAI/litellm#9138]
### The Feature

Support llama.cpp as a provider

### Motivation, pitch

llama.cpp is very popular and the most advanced runtime for inference

### Are you a ML Ops Team?

No

**Comment by ghost** [comment]
This is already possible via openai compatible provider route - https://docs.litellm.ai/docs/providers/openai_compatible

**Comment by jagusztinl** [comment]
Why you are not listing llama.cpp as a directly supported provider?

**Comment by vaclcer** [comment]
What about rankers served by llama.cpp? Afaik ranking is not part of openai api, hence cannot be integrated into litellm?

**Comment by itlackey** [comment]
+1 in how to use llama.cpp ranking

**Comment by winstonma** [comment]
llama.cpp support [Anthropic API](https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md). I tried the following setting in `config.yaml` and it works:

```
model_list:
  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/${MODEL}     # Use the 'anthropic/' prefix
      api_base: http://localhost:${PORT}      # Your llama-server address
      api_key: "${API_KEY}"                 # Still required by LiteLLM syntax

# This section ensures LiteLLM handles the headers correctly
litellm_settings:
  drop_params: True 
  success_callback: []                      # Minimize overhead
```

And then on claude code I called:

```bash
# Point to your LiteLLM user service
export ANTHROPIC_BASE_URL="http://localhost:4000"

# This is the "Magic" variable that bypasses the login screen
export ANTHROPIC_AUTH_TOKEN="local-bypass"

# Standard model name matching your LiteLLM config
export ANTHROPIC_MODEL="claude-haiku-4-5"

# Optional: suppress telemetry to Anthropic
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1

claude
```
