### ISSUE TITLE
[Bug]: Retrieving a batch fails with error about incorrect provider

### ISSUE THREAD

**Issue by msabramo** [BerriAI/litellm#9189]
### What happened?

Using the following to create a batch in Azure OpenAI:

```shell
$ cat file-68dbd7ff214c4f53b0059b6ff59838ed.jsonl
{"custom_id": "task-0", "method": "POST", "url": "/chat/completions", "body": {"model": "gpt-4o-2024-11-20-batch-no-filter", "messages": [{"role": "user", "content": "what llm are you"}]}}

$ jq < file-68dbd7ff214c4f53b0059b6ff59838ed.jsonl
{
  "custom_id": "task-0",
  "method": "POST",
  "url": "/chat/completions",
  "body": {
    "model": "gpt-4o-2024-11-20-batch-no-filter",
    "messages": [
      {
        "role": "user",
        "content": "what llm are you"
      }
    ]
  }
}

$ curl -i -sSL 'http://localhost:4000/v1/files' \
    -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
    -F purpose="batch" \
    -F file="@file-68dbd7ff214c4f53b0059b6ff59838ed.jsonl"
HTTP/1.1 200 OK
date: Thu, 13 Mar 2025 00:16:33 GMT
server: uvicorn
content-length: 210
content-type: application/json
x-litellm-version: 1.63.7
x-litellm-key-spend: 0.0

{"id":"file-f2676ac5b0554102b8a3a60ab1c47218","bytes":188,"created_at":1741824996,"filename":"modified_file.jsonl","object":"file","purpose":"batch","status":"processed","expires_at":null,"status_details":null}
```

```shell
curl -i -sSL 'http://localhost:4000/v1/batches' \
    -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
    -H "Content-Type: application/json" \
    -d '{
        "input_file_id": "file-f2676ac5b0554102b8a3a60ab1c47218",
        "endpoint": "/v1/chat/completions",
        "completion_window": "24h",
        "model": "gpt-4o-2024-11-20-batch-no-filter"
    }'
```

```shell
$ curl -i -sSL 'http://localhost:4000/v1/batches' \
    -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
    -H "Content-Type: application/json" \
    -d '{
        "input_file_id": "file-f2676ac5b0554102b8a3a60ab1c47218",
        "endpoint": "/v1/chat/completions",
        "completion_window": "24h",
        "model": "gpt-4o-2024-11-20-batch-no-filter"
    }'
HTTP/1.1 200 OK
date: Thu, 13 Mar 2025 00:53:09 GMT
server: uvicorn
content-length: 699
content-type: application/json
x-litellm-model-id: edfc4f8b120c218e12b7e50f1cba1506ec39c3b8b4db1c0b0c1bab02bb31fc1f
x-litellm-model-api-base: https://us-w-0008.openai.azure.com
x-litellm-version: 1.63.7
x-litellm-key-spend: 0.0

{"id":"batch_990fe845-4ff9-49d8-a3da-a5dcedcc8526","completion_window":"24h","created_at":1741827194,"endpoint":"/chat/completions","input_file_id":"file-f2676ac5b0554102b8a3a60ab1c47218","object":"batch","status":"validating","cancelled_at":null,"cancelling_at":null,"completed_at":null,"error_file_id":"","errors":null,"expired_at":null,"expires_at":1741913593,"failed_at":null,"finalizing_at":null,"in_progress_at":null,"metadata":{"model_group":"gpt-4o-2024-11-20-batch-no-filter","model_group_size":"1","deployment":"azure/gpt-4o-2024-11-20-batch-no-filter","api_base":"https://us-w-0008.openai.azure.com"},"output_file_id":"","request_counts":{"completed":0,"failed":0,"total":0},"usage":null}
```

So now I have an Azure OpenAI batch...

..but then when I try to get the newly created batch, it fails with a strange error about bedrock, which is super weird because we're using Azure OpenAI:

```shell
$ curl -sSL 'http://localhost:4000/v1/batches/batch_990fe845-4ff9-49d8-a3da-a5dcedcc8526' \
    -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
    -H "Content-Type: application/json" \
    | jq '.'
{
  "error": {
    "message": "Internal Server Error, litellm.BadRequestError: LiteLLM doesn't support bedrock for 'create_batch'. Only 'openai' is supported.",
    "type": "internal_server_error",
    "param": null,
    "code": "500"
  }
}
```

Relevent config.yaml snippets:

```yaml
model_list:
  - model_name: gpt-4o-2024-11-20-batch-no-filter
    litellm_params:
      model: azure/gpt-4o-2024-11-20-batch-no-filter
      api_base: os.environ/AOAI_BASE_US_W_0008
      api_key: os.environ/AOAI_KEY_US_W_0008
      api_version: 2024-12-01-preview
    model_info:
      mode: batch
```

```yaml
files_settings:
  - custom_llm_provider: azure
    api_base: os.environ/AOAI_BASE_US_E_0008
    api_key: os.environ/AOAI_KEY_US_E_0008
    api_version: 2024-12-01-preview
```

```yaml
litellm_settings:
  turn_off_message_logging: True
  drop_params: True
  enable_loadbalancing_on_batch_endpoints: true
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

main

**Comment by ghost** [comment]
> enable_loadbalancing_on_batch_endpoints: true


please remove this and retry @msabramo 

loadbalancing batch endpoints is in beta

**Comment by msabramo** [comment]
> > enable_loadbalancing_on_batch_endpoints: true
> 
> please remove this and retry [@msabramo](https://github.com/msabramo)
> 
> loadbalancing batch endpoints is in beta

Thanks! When I remove that I get a different error:

```json
{
  "error": {
    "message": "Error code: 500 - {'error': {'message': 'The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable', 'type': 'None', 'param': 'None', 'code': '500'}}",
    "type": "None",
    "param": "None",
    "code": "500"
  }
}
```

which I think brings me to the point that I don't actually understand how batch support works in LiteLLM.

Like which Azure OpenAI deployment does it route to with this setting off and to which with it on?

To compare, let's take the assistants support, which I think is documented better (at https://docs.litellm.ai/docs/assistants) and I understand better. The docs right off the bat give this configuration example:

```yaml
assistant_settings:
  custom_llm_provider: azure
  litellm_params: 
    api_key: os.environ/AZURE_API_KEY
    api_base: os.environ/AZURE_API_BASE
    api_version: os.environ/AZURE_API_VERSION
```

So it's pretty clear to me where assistants API requests are going to be routed to and authenticated.

With batches, can you not do something like this?

```yaml
batch_settings:
  custom_llm_provider: azure
  litellm_params: 
    api_key: os.environ/AZURE_API_KEY
    api_base: os.environ/AZURE_API_BASE
    api_version: os.environ/AZURE_API_VERSION
```

I don't see anything like that. So how does LiteLLM decide which Azure OpenAI endpoint to forward my batch requests to? If I do this:

```shell
$ curl -sSL 'http://localhost:4000/v1/batches/batch_990fe845-4ff9-49d8-a3da-a5dcedcc8526' \
    -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
    -H "Content-Type: application/json" \
    | jq '.'
{
  "error": {
    "message": "Internal Server Error, Error code: 500 - {'error': {'message': 'Internal Server Error, The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable', 'type': 'internal_server_error', 'param': 'None', 'code': '500'}}",
    "type": "internal_server_error",
    "param": "None",
    "code": "500"
  }
}
```

**where** do I need to `api_key`?

I think my assumption was that LiteLLM would route to the only model I have configure that has `model_info.mode` set to `batch`:

```yaml
  - model_name: gpt-4o-2024-11-20-batch-no-filter
    litellm_params:
      model: azure/gpt-4o-2024-11-20-batch-no-filter
      api_base: os.environ/AOAI_BASE_US_W_0008
      api_key: os.environ/AOAI_KEY_US_W_0008
      api_version: 2024-12-01-preview
    model_info:
      mode: batch
```

but I don't know if that's correct as I do have an `api_key` set here, so I'm guessing LiteLLM is looking somewhere else?

Maybe what's needed is to improve the docs?
