### ISSUE TITLE
[Feature]: Snowflake Cortex QA Items

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#9231]
### The Feature

- Allow me to pass `snowflake_account_id` and `snowflake_jwt` as dynamic params (via config) 
- allow me to pass an api_base and append the `api/v2/cortex/inference:complete` to my api base (like openai does) 

In the code, it looks like `api_key` dynamic param = `SNOWFLAKE_JWT` env var, this is confusing because the names are different, and it's not immediately apparent by looking at docs. 

### Motivation, pitch

Make it easier to use the Snowflake integration. 

Currently the docs are quite confusing - as the sdk example != the proxy example 

<img width="1078" alt="Image" src="https://github.com/user-attachments/assets/d0515c58-756d-45af-b7fb-b2a83f0a7394" />
<img width="1091" alt="Image" src="https://github.com/user-attachments/assets/d59a86ba-43b0-4d35-8959-309c4ed89300" />

### Are you a ML Ops Team?

No

**Comment by ghost** [comment]
Hey @SunnyWan59 can you look into simplifying this 

I think Azure, Bedrock and VertexAI are relevant examples here. I trust how you end up solving this, it's just confusing right now. 

cc: @ishaan-jaff

**Comment by SunnyWan59** [comment]
@krrishdholakia I'll get started on this!

**Comment by ghost** [comment]
Thanks!

**Comment by SunnyWan59** [comment]
Hey @krrishdholakia do you mean something like this for the config.yaml?
```
model_list:
  - model_name: mistral-7b
    litellm_params:
        model: snowflake/mistral-7b
        snowflake_jwt: <JWT>
        snowflake_account_id: <ACCOUNT-ID>
        api_base: snowflakecomputing.com
```
