### ISSUE TITLE
[Feature]: Supprt for Vertex AI with global region

### ISSUE THREAD

**Issue by simonChoi034** [BerriAI/litellm#9234]
### The Feature

Add `global` as the supprted region / location

### Motivation, pitch

Vertex AI has added a `global` region for the Gemini API, which uses `https://aiplatform.googleapis.com/` as the base URL instead of `https://{vertex_location}-aiplatform.googleapis.com/`. One single API configuration should route to different regions by Google itself instead of manually configuring the Gemini model for multiple locations.

### Are you a ML Ops Team?

No

**Comment by AllanXiang** [comment]
@simonChoi034  you can set the api_base in the config
the global region is only available for gemini-2.0-flash-001 and gemini-2.0-flash-lite-001(ref: https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/global-endpoint/intro_global_endpoint.ipynb)

for example:
``` 
- model_name: gemini-2.0-flash
  litellm_params:
      model: vertex_ai/gemini-2.0-flash-001
      api_base: "https://aiplatform.googleapis.com/v1/projects/{YOUR_PROJECT}/locations/global/publishers/google/models/gemini-2.0-flash-001"
      vertex_credentials: "{YOUR_AUTH_JSON}"
```
