### ISSUE TITLE
[Feature]: Multiple callbacks with configuration for redaction

### ISSUE THREAD

**Issue by wagnerjt** [BerriAI/litellm#9245]
### The Feature

It would be great to add and configure multiple callback settings to redact the request and response body across those.

In our case, we are looking to redact the body and only show traces via otel/langfuse and retain the body within s3. 

This is an example of how otel is configured, and it should be easy to keep this same pattern.

```yaml
litellm_settings:
  callbacks: ["otel", "s3"]

callback_settings:
  otel:
    message_logging: False
```

There was a topic with the rearchitected for redaction in #8489. 

### Motivation, pitch

Configuring the redaction callbacks keeps separation on traces and more hardened locations like s3 for containing private information 

### Are you a ML Ops Team?

No
