### ISSUE TITLE
Parameter supports_vision: True is ignored on config.yaml of LiteLLM Proxy

### ISSUE THREAD

**Issue by andrelohmann** [BerriAI/litellm#9297]
Hi there, I'm trying to proxy visual models behind LiteLLM Proxy.

Here is a combination of Settings I tried:

```
model_list:
  - model_name: gemma3:12b-it-q8_0_Node1
    litellm_params:
      model: ollama/gemma3:12b-it-q8_0
      api_base: http://api1.lan:11434
    model_info:
      supports_vision: True
  - model_name: gemma3:12b-it-q8_0_Node2
    litellm_params:
      model: ollama/gemma3:12b-it-q8_0
      api_base: http://api1.lan:11434
    metadata:
      supports_vision: True
  - model_name: gemma3:12b-it-q8_0_Node3
    litellm_params:
      model: ollama/gemma3:12b-it-q8_0
      api_base: http://api1.lan:11434
      supports_vision: True
```

What ever I'm trying, the "supports_vision: True" parameter gets ignored. Neither do I get the feature shown as activated in the "model hub", nor am I able to push Images via OpenWebUI to the model. When directly pointing to the ollama endpoint, without LiteLLM in between, OpenWebUI works fine with visual models.

What am I missing here?

I'm running docker compose from the latest gitlab clone.

**Comment by andrelohmann** [comment]
I'm a step further. It works, if not using the provider ollama but openai instead.

```
model_list:
  - model_name: gemma3:12b-it-q8_0_Node1
    litellm_params:
      model: openai/gemma3:12b-it-q8_0
      api_base: http://api1.lan:11434
    model_info:
      supports_vision: True
```
