### ISSUE TITLE
[Bug]: DeepSeek R1 via Bedrock Converse pricing is not assigned

### ISSUE THREAD

**Issue by marty-sullivan** [BerriAI/litellm#9318]
### What happened?

When configuring DeepSeek R1 like so:

```yaml
  - model_name: 'deepseek.r1'
    litellm_params:
      model: 'bedrock/converse/us.deepseek.r1-v1:0' # with converse
      aws_region_name: 'us-east-1'
```

the model shows up in the list and it works to make calls to it, but the pricing is set to 0 for both input and output tokens

When configuring the model like this instead (without converse):

```yaml
  - model_name: 'deepseek.r1'
    litellm_params:
      model: 'bedrock/us.deepseek.r1-v1:0' # no converse
      aws_region_name: 'us-east-1'
```

The pricing is set properly, however, the model does not work because I think on the AWS side, only the Converse API is supported for this model and not Invoke. Or, either way, it does not work unless configured explicitly with `bedrock/converse/us.deepseek.r1-v1:0`

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.63.11-stable
