### ISSUE TITLE
ollama config disabled, who can help me !

### ISSUE THREAD

**Issue by zmdw** [BerriAI/litellm#9364]
> I want to be able to access the ollama mirror service on an intranet server in the mirror image of a local computer, but the access has been failed, and the code I wrote locally is accessible.
> ` - model_name: "qwen2.5:72b"
>     litellm_params:
>       model: "ollama/qwen2.5:72b"
>       api_base: "http://10.78.97.33:11434"`  `import litellm
> # call async_ollama
> import asyncio
> async def async_ollama():
>     response = await litellm.acompletion(
>         model="ollama/qwen2.5:72b",
>         messages=[{"content": "what's the weather", "role": "user"}],
>         api_base="http://10.78.97.33:11434",
>         stream=True
>     )
>     async for chunk in response:
>         print(chunk)
> 
> 
> asyncio.run(async_ollama())
> ` 

 _Originally posted by @zmdw in [#1517](https://github.com/BerriAI/litellm/issues/1517#issuecomment-2735735719)_

**Comment by bachkukkik** [comment]
this is my working setup

```yaml
  - model_name: ollama_chat/gemma3:12b
    litellm_params:
      model: ollama_chat/gemma3:12b
      api_base: os.environ/OLLAMA_BASE_URL
    model_info:
      supports_vision: True
```
