### ISSUE TITLE
Azure resource not found?

### ISSUE THREAD

**Issue by GeraldPape** [BerriAI/litellm#9406]
Using lite_llm proxy in podman with open webui and ollama.

model shows up in oben webui, however, I receive the error  404: litellm.APIError: AzureException APIError 

Can anyone tell me whats wrong here?

so this is my yaml:
```
model_list: 
  - model_name: gpt-4o 
    litellm_params: 
      model: azure/gpt-4o
      api_base: "https://in-donottell-ai.openai.azure.com/openai/deployments/gpt-4o/chat/completions" 
      api_key: "thekey" 
      api_version: "api-version=2024-10-21"

```

this is a working curl:
`curl -v -g -4 POST "https://in-donottell-ai.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-10-21" -H "api-key: thekey" -H "Content-Type: application/json" -d "{\"messages\": [{\"role\": \"user\",\"content\": \"this is a test request, write a short poem\", \"model\": \"gpt-4o\"}]}"`

this is the error:
 
```
404: litellm.APIError: AzureException APIError - Resource not found. Received Model Group=gpt-4o
Available Model Group Fallbacks=None
```

**Comment by DrFloflo** [comment]
I have multiple error too, i'v try with just the url, with azure/ openai/ azure_ai/, triple check with azure ai. Nothing worked.
My error : 
```
litellm.types.router.RouterRateLimitError: No deployments available for selected model, Try again in 5 seconds. Passed model=gpt-4o-mini. pre-call-checks=False, cooldown_list=[]

12:22:49 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
```

My conf : 
```
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure_ai/gpt-4o-mini
      api_base: "https://secret.openai.azure.com/"
      api_key: "secret"
      api_version: "2024-12-01-preview"
```
And for deepseek (doesn't work too) :
```
  - model_name: deepseekv3-prod
    litellm_params:
      model: azure_ai/deepseekv3-prod
      api_base: "https://secret.services.ai.azure.com/models"
      api_key: "secret"
      api_version: "2024-05-01-preview"
```

I'v tried multiple things, i'm going mad.
