### ISSUE TITLE
[Bug]: Filter out duplicate models from 

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#942]
### What happened?

The `/models` endpoint should only return one result for each name. i.e. don't return this:

```json
{
  "data": [
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "command",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "claude-v2",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "llama2",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "express",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "j2",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

Return this instead:

```json
{
  "data": [
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "command",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "claude-v2",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "llama2",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "express",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "j2",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

Otherwise, applications like LibreChat end up looking quite odd.

<img width="397" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/be503179-5458-47f1-a693-fe15088d4449">

**Comment by ghost** [comment]
interesting @Manouchehri how can i repro this?

**Comment by Manouchehri** [comment]
Just having a config like this and check the `/models` response.

```
model_list:
  - model_name: gpt-4-1106-preview
    litellm_params:
      model: azure/gpt-4-1106-preview
      api_key: os.environ/AZURE_API_KEY_AUSTRALEAST
      api_version: "2023-10-01-preview"
      api_base: "https://australiaeast-aimoda.openai.azure.com/"
  - model_name: gpt-4-1106-preview
    litellm_params:
      model: azure/gpt-4-1106-preview
      api_key: os.environ/AZURE_API_KEY_CANADAEAST
      api_version: "2023-10-01-preview"
      api_base: "https://canadaeast-aimoda.openai.azure.com/"
```
