### ISSUE TITLE
[Bug]: The system prompt is not forwarded correctly to VertexAI API by the proxy (wrong role)

### ISSUE THREAD

**Issue by Dobiasd** [BerriAI/litellm#9501]
### What happened?

First, thanks for LiteLLM being such an amazing tool! There's just one problem I run into.

The VertexAI API [supports system instructions](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions). But the LiteLLM proxy converts messages with role `system` to `user` when using the VertexAI API.

This does make a (negative) difference because Gemini handles system messages differently compared to user messages. I.e., in PROD we ran into problems of a (quite long) system prompt being respected less by Gemini when we use the LiteLLM proxy compared to using the VertexAI API directly.

Here is a minimal example:

`litellm_config.yaml`:

```yaml
model_list:
  - model_name: chatgpt
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ...
  - model_name: gemini
    litellm_params:
      model: vertex_ai/gemini-2.0-flash-lite
      vertex_project: "..."
      vertex_location: "us-central1"
      vertex_credentials: "/app/my-gen-lang-client.json"
general_settings: 
  master_key: sk-1234
```

Running with Docker:

```bash
docker run \
    -v $(pwd)/litellm_config.yaml:/app/config.yaml \
    -v $(pwd)/my-gen-lang-client.json:/app/my-gen-lang-client.json \
    -e LITELLM_LOG="DEBUG"\
    -p 4000:4000 \
    ghcr.io/berriai/litellm:main-v1.63.14-stable \
    --config /app/config.yaml --detailed_debug
```

Sending a request:

```bash
curl -X POST 'http://0.0.0.0:4000/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-d '{
    "model": "gemini",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful math tutor. Guide the user through the solution step by step."
      },
      {
        "role": "user",
        "content": "how can I solve 8x + 7 = -23"
      }
    ]
}'
```

This is from the LiteLLM logs:

```
POST Request Sent from LiteLLM:
curl -X POST \
https://us-central1-aiplatform.googleapis.com/v1/projects/[...]/locations/us-central1/publishers/google/models/gemini-2.0-flash-lite:generateContent \
-H 'Content-Type: ap****on' -H 'Authorization: Be****5z' \
-d '{'contents': [{'role': 'user', 'parts': [{'text': 'You are a helpful math tutor. Guide the user through the solution step by step.'}, {'text': 'how can I solve 8x + 7 = -23'}]}], 'generationConfig': {}}'
```

We can see that the `You are a helpful ...` message is sent as a `user` message. This looks like a bug (or at least a missing feature) to me. It should be sent as `system_instruction`.

For comparison, when setting `"model": "chatgpt"` in the above `curl`, LiteLLM correctly sends a `system` message to the OpenAI API:

```
POST Request Sent from LiteLLM:
curl -X POST \
https://api.openai.com/v1/ \
-H 'Authorization: Be****AA' \
-d '{'model': 'gpt-4o-mini', 'messages': [{'role': 'system', 'content': 'You are a helpful math tutor. Guide the user through the solution step by step.'}, {'role': 'user', 'content': 'how can I solve 8x + 7 = -23'}], 'extra_body': {}}'
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.63.14-stable

### Twitter / LinkedIn details

https://www.linkedin.com/in/t-hermann/

**Comment by ishaan-jaff** [comment]
issue seems isolated to `gemini-2.0-flash-lite`

**Comment by ishaan-jaff** [comment]
Oh I see the issue, we check if the base model `supports_system_messages` and this model is not in our model cost map

**Comment by Dobiasd** [comment]
Thanks for the quick investigation!

> issue seems isolated to `gemini-2.0-flash-lite`

Unfortunately, no. It also happens with `gemini-2.0-flash` (without `-lite`). Example:

config:

```yaml
  - model_name: gemini-flash
    litellm_params:
      model: vertex_ai/gemini-2.0-flash
      vertex_project: "..."
      vertex_location: "us-central1"
      vertex_credentials: "/app/my-gen-lang-client.json"
```

log:

```
POST Request Sent from LiteLLM:
curl -X POST \
https://us-central1-aiplatform.googleapis.com/v1/projects/gen-lang-client-0325803541/locations/us-central1/publishers/google/models/gemini-2.0-flash:generateContent \
-H 'Content-Type: ap****on' -H 'Authorization: Be****po' \
-d '{'contents': [{'role': 'user', 'parts': [{'text': 'You are a helpful math tutor. Guide the user through the solution step by step.'}, {'text': 'how can I solve 8x + 7 = -23'}]}], 'generationConfig': {}}'
```

But (taken from [the Google docs](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions#code_samples)), it should be like this:

![ldThWZo](https://i.imgur.com/ldThWZo.png)

**Comment by Dobiasd** [comment]
I just looked through the files that were modified in the [linked MR](https://github.com/BerriAI/litellm/pull/9523) (`model_prices_and_context_window_backup.json` and `model_prices_and_context_window.json`), and there is no entry for `gemini-2.0-flash` either. So it makes sense that this one does not work too.

However, there are entries for `gemini-2.0-flash-001` (including `"supports_system_messages": true,`), but `gemini-2.0-flash-001` also does not work. Example:

```yaml
  - model_name: gemini-2.0-flash-001
    litellm_params:
      model: vertex_ai/gemini-2.0-flash-001
      vertex_project: "..."
      vertex_location: "us-central1"
      vertex_credentials: "/app/my-gen-lang-client.json"
```

```
POST Request Sent from LiteLLM:
curl -X POST \
https://us-central1-aiplatform.googleapis.com/v1/projects/gen-lang-client-0325803541/locations/us-central1/publishers/google/models/gemini-2.0-flash-001:generateContent \
-H 'Content-Type: ap****on' -H 'Authorization: Be****a3' \
-d '{'contents': [{'role': 'user', 'parts': [{'text': 'how can I solve 8x + 7 = -23'}]}], 'system_instruction': {'parts': [{'text': 'You are a helpful math tutor. Guide the user through the solution step by step.'}]}, 'generationConfig': {}}'
```

So I guess this issue is not yet fixed.
