### ISSUE TITLE
[Bug]: Bedrock Sonnet 3.7 with thinking model - temperature should always be set to 1 

### ISSUE THREAD

**Issue by jorgegarciarey** [BerriAI/litellm#9524]
### What happened?

Hi team!

I'm using LiteLLM as proxy from [Cline](https://github.com/cline/cline) and I'm trying to work with `claude-3-7-sonnet-20250219-v1:0-thinking` model with **thinking** reasoning following the [LiteLLM documentation](https://docs.litellm.ai/docs/providers/bedrock#usage---thinking--reasoning-content) but I find the next error:

`litellm.BadRequestError: BedrockException - validationException {"message":"The model returned the following errors: temperature may only be set to 1 when thinking is enabled."}`

The configuration file I've deployed include the following models:

```bash
  - model_name: claude-3-7-sonnet-20250219-v1:0-thinking
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/BEDROCK_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/BEDROCK_AWS_SECRET_ACCESS_KEY
      aws_session_name: os.environ/BEDROCK_AWS_SESSION_NAME # AWS RoleSessionName
      aws_role_name: os.environ/BEDROCK_AWS_ROLE_NAME # AWS Assume RoleArn. arn:aws:iam::account_id:role/iam_local_role
      aws_region_name: os.environ/BEDROCK_AWS_REGION_NAME
      thinking: {"type": "enabled", "budget_tokens": 3500}
      temperature: 1
  - model_name: claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/BEDROCK_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/BEDROCK_AWS_SECRET_ACCESS_KEY
      aws_session_name: os.environ/BEDROCK_AWS_SESSION_NAME # AWS RoleSessionName
      aws_role_name: os.environ/BEDROCK_AWS_ROLE_NAME # AWS Assume RoleArn. arn:aws:iam::account_id:role/iam_local_role
      aws_region_name: os.environ/BEDROCK_AWS_REGION_NAME
  - model_name: claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_access_key_id: os.environ/BEDROCK_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/BEDROCK_AWS_SECRET_ACCESS_KEY
      aws_session_name: os.environ/BEDROCK_AWS_SESSION_NAME
      aws_role_name: os.environ/BEDROCK_AWS_ROLE_NAME
      aws_region_name: os.environ/BEDROCK_AWS_REGION_NAME
  - model_name: azure-gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: os.environ/AZURE_OPENAI_API_BASE
      api_key: "os.environ/AZURE_OPENAI_API_KEY"
      api_version: "2024-10-21"
```

I've tried with the parameter `temperature: 1` and without including this parameter this parameter but the result is the same 😢 

### Relevant log output

```shell
litellm.BadRequestError: BedrockException - validationException {"message":"The model returned the following errors: temperature may only be set to 1 when thinking is enabled."}
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.63.14-stable.patch1

**Comment by keykbd** [comment]
When setting the API Provider to LiteLLM in Cline, `temperature: 0` is being passed regardless. It seems that parameters passed during Cline's call take precedence over the config.yaml settings. Try setting the API Provider to `OpenAI Compatible` in Cline, which should allow you to change the Temperature.

**Comment by minznerjosh** [comment]
Stumbling into this issue now. Do we know why Cline would [hard-code temperature to `0`](https://github.com/cline/cline/blob/80d53e700f3e1edc0e6a30c1170bff831b124ed7/src/api/providers/litellm.ts#L62-L66) for LiteLLM calls? It seems like the type of thing that should be configurable?

**Comment by marty-sullivan** [comment]
@minznerjosh I would agree, much more needs to be configurable for Cline when using LiteLLM.

There is [this PR](https://github.com/cline/cline/pull/2056) that has been open for a while where I made some additional suggestions yesterday about explicitly configuring "thinking" for claude.

**Comment by ghost** [comment]
Hey! seeing this late, seems like 

> I've tried with the parameter temperature: 1 and without including this parameter this parameter but the result is the same 😢



The issue is that the request body probably contains this, so the dynamic param is being used. You can ignore this by specifying to drop this param - https://docs.litellm.ai/docs/completion/drop_params#specify-params-to-drop

```yaml
- model_name: claude-3-7-sonnet-20250219-v1:0-thinking
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_access_key_id: os.environ/BEDROCK_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/BEDROCK_AWS_SECRET_ACCESS_KEY
      aws_session_name: os.environ/BEDROCK_AWS_SESSION_NAME # AWS RoleSessionName
      aws_role_name: os.environ/BEDROCK_AWS_ROLE_NAME # AWS Assume RoleArn. arn:aws:iam::account_id:role/iam_local_role
      aws_region_name: os.environ/BEDROCK_AWS_REGION_NAME
      thinking: {"type": "enabled", "budget_tokens": 3500}
      additional_drop_params: ["temperature"] # 👈 KEY CHANGE 
     
```
