### ISSUE TITLE
gemini 2.5 pro Error parsing chunk

### ISSUE THREAD

**Issue by qymab** [BerriAI/litellm#9564]
`21:48:21 - LiteLLM Proxy:ERROR: proxy_server.py:3091 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - litellm.APIConnectionError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),`

**Comment by matannahmani** [comment]
bump

**Comment by mitya52** [comment]
same problem with model `gemini/gemini-2.5-pro-exp-03-25`

**Comment by bexelbie** [comment]
saw this with gemini/gemini-2.5-pro-exp-03-25 - any ideas on where to begin to debug?

**Comment by carlitosspot** [comment]
Not sure if this is the right place to ask but I'm curious how your config.yml file looks like. Is it something like:

model_list:
  - model_name: gemini-2.5-pro-exp-03-25
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY # Fetches the API key from environment variables
      api_base: "https://generativelanguage.googleapis.com/v1beta"

?

**Comment by bexelbie** [comment]
```
model_list:
  - model_name: gemini-2.5-pro-exp-03-25
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      litellm_credential_name: google-key

credential_list:
   - credential_name: google-key
     credential_values:
       api_key: keykeykeykeykey
```
