### ISSUE TITLE
[Bug]: Azure OpenAI AD auth no longer works when set via env var

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#9598]
### What happened?

After upgrading to v1.64.1-nightly, my Azure AD auth no longer works at all.

### Relevant log output

```shell
litellm.exceptions.APIError: litellm.APIError: AzureException APIError - Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.64.1-nightly

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
Hi @Manouchehri can you share the full stacktrace? I can't tell 

1. how this is being set 
2. where the error is coming from 

Can you also share what version you bumped from?

**Comment by Manouchehri** [comment]
I'm using https://docs.litellm.ai/docs/providers/azure#entrata-id---use-tenant_id-client_id-client_secret and I have the env variables set globally (not on each model manually though).

v1.63.7 is working for me.

**Comment by ghost** [comment]
can i see how it's set on config? want to make sure i'm mapping your flow 1:1

**Comment by Manouchehri** [comment]
It's not set on the config, and it never was. It's a global env var that was previously working.

```yaml
model_list:
  - model_name: gpt-4o-mini-2024-07-18
    litellm_params:
      model: azure/global_gpt-4o-mini-2024-07-18
      api_version: "2025-02-01-preview"
      additional_drop_params: ["user"]
      api_base: "https://gateway.ai.cloudflare.com/v1/REMOVED/REMOVED/azure-openai/eastus-removed"
      seed: 1337
      max_tokens: 16384
      logprobs: True
      top_logprobs: 20
      frequency_penalty: 0
      presence_penalty: 0
      n: 1
      temperature: 1
      top_p: 1
    model_info:
      base_model: azure/global-standard/gpt-4o-mini
```
