### ISSUE TITLE
[Feature]: Tutorial on deploying proxy on Azure App Service 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#971]
### The Feature

make it easy to deploy proxy on azure app service 

### Motivation, pitch

user request

**Comment by ghost** [comment]
- no docker container
- load secrets from azure key vault 
- launch proxy in python 

Nice to have: 
- load all configs from key vault

**Comment by lackeyi** [comment]
I see this is completed, but I am not finding this in the docs anywhere. I had this working with an env var setting the path of the config file. It appears that is now deprecated. I am not struggling to figure out how to pass a config file to a docker image hosted in an azure app service.

Deprecated CONFIG_FILE_PATH code:
https://github.com/BerriAI/litellm/blob/3a5039e284adac1279964849879619fe2cef309c/litellm/deprecated_litellm_server/main.py#L39C137-L39C138

Any guidance is much appreciated!

**Comment by ghost** [comment]
Hey @lackeyi this should work - https://docs.litellm.ai/docs/proxy/deploy#3-providing-litellm-configyaml-file-as-a-s3-gcs-bucket-objecturl

just store your config on an s3/gcs bucket and pass it to the proxy as env vars

**Comment by lackeyi** [comment]
I do not have approval to use other cloud providers. I must be able to host the solution entirely in Azure. Allowing an ENV variable in addition to the cli --config arg would solve the issue.

**Comment by lackeyi** [comment]
I have managed to work around this for now by using a Docker Compose configuration in the App Service.

```
version: "3.9"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-v1.44.17-stable
    ports:
      - "4000:4000"
    command: [ "--config", "/config/proxy_server_config.yaml", "--port", "4000", "--num_workers", "8" ]
```

I think mount /config to an Azure File Share and upload the config file there. It is not the most straightforward setup, but it appears to be working. If this works as expected, should I submit a PR to update the docs to provide some guidance for Azure?
