### ISSUE TITLE
[Feature]: Add GS support to the new file api

### ISSUE THREAD

**Issue by hongkongkiwi** [BerriAI/litellm#9751]
### The Feature

Currently for the brand new files API Google AI Filemanager is supported. It would be great if we could also support uploading to Google Storage buckets (if configured). This allows us to configure in the backend which we want with appropraite credentials and the user can use the same standardised API.

### Motivation, pitch

Google AI Filemanager is limited to 10gb with a 48hour expiry. It's great for basic use but having a custom bucket allows for much more comprehensive usage in production.

### Are you a ML Ops Team?

Yes

**Comment by ghost** [comment]
Hey @hongkongkiwi how would you want to set this? (example config.yaml would be great)

**Comment by hongkongkiwi** [comment]
Thinking something like this? We already have support for vertex_ai which I think is similar a little bit.

```
files_settings:
  - custom_llm_provider: google-storage
    id: "some_storage" # Optional id to allow mulitple buckets
    google_credentials: os.environ/GOOGLE_APPLICATION_CREDENTIALS
    api_base_uri: "https://storage.googleapis.com"
    bucket: "mybucket" # Required
    prefix: "someprefix" # Optional forces prefix on all files uploaded or retrieved
    hash_path: true
    team_ids:
    - id1
    - id2
    seperate_api_keys: true
    custom_metadata:
    - key1: somevalue
```

Thinking something like above. It can be used for vertex_ai or google gemini.

id, this is optional, but if provided allows multiple storage buckets, the client has to also pass the same id. It's an easy way to allow multiple storage buckets. If id is not passed it becomes the default bucket for clients who don't pass an id (only one default is allowed).

google_credentials passes the path to the google application credentials json file. For the logic of how to handle this we can use the vertex_ai files provider as a reference.

api_base_url is optional, but can be used for local testing or in some cases might want to run it through a proxy. Normally it's just directly to the standard google servers.

bucket name is the google storage bucket, straightforward, required.

prefix is optional but automatically provides a prefix when retrieving or saving files. e.g. abc as a bucket means if we try to save myfile.mp4 it becomes abc/myfile.mp4.

hash_paths means that all user passed paths get hashed before saving, so for example, if the user passes a filename of abc/myfile.mp4 we save this as and sha256sum as the filename in the bucket. This wouldn't include the prefix, so it hashes anything that the user passes in.

team_ids allows us to hardcode the team-ids that can access this read/write. If not specified all teams have access.

seperate_api_keys means that every single api key has their own segregation in the bucket. In practise we would simply do something like generate a hash of the api key and save that as the prefix for all files send/received by this key. This means api keys cannot access any other api keys files. If not defined then any api key in the team could access any file from any other api key, which is also logical.

custom_metadata: sets custom metadata keys on the saved object in google storage, this allows us to append additional data to identify objects created using this config.

After saving a file, we get back the gs://bucket-name/key path that we can pass to google gemini or vertex ai.
