### ISSUE TITLE
[Bug]: Can't use Azure hosted open model, Llama3

### ISSUE THREAD

**Issue by MemmoB** [BerriAI/litellm#9800]
### What happened?

When calling through the LiteLLM proxy I get the following error:
`litellm.BadRequestError: Azure_aiException - {\"detail\":\"Extra parameters ['stream_options'] are not allowed when extra-parameters is not set or set to be 'error'.`

I have set `stream_options: {"include_usage":true}` in the call to the OpenAI Typescript SDK.

It works fine with the Azure OpenAI models through the same proxy and it also works directly against the Llama3 deployment if I use an `AuzreOpenAI` instance in the code but no LiteLLM proxy in-between.

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

Docker image main:latest

**Comment by MemmoB** [comment]
If anyone else runs in to this you can set the following params:
```
       - model_name: llama3
          litellm_params:
            model: azure_ai/Meta-Llama-3-70B-Instruct
            api_base: <base>
            api_key: os.environ/LLAMA3_API_KEY
            headers:
              extra-parameters: pass-through
```
