### ISSUE TITLE
[Bug]: realtime-preview model_prices_and_context_window.json for Azure not working

### ISSUE THREAD

**Issue by marty-sullivan** [BerriAI/litellm#9814]
### What happened?

Great job with the /v1/realtime price tracking in proxy! It works well for me for `gpt-4o-mini-realtime-preview` but for `gpt-4o-realtime-preview` the price mapping is not picked up from `model_prices_and_context_window.json`.

I've tried updating `model_prices_and_context_window.json` locally with various different model names and also renaming my deployment name in Azure but nothing seems to work. 

### Relevant log output

```shell

custom_llm_provider=custom_llm_provider,
--
)
File "/usr/lib/python3.13/site-packages/litellm/utils.py", line 4603, in _get_model_info_helper
raise Exception(
...<3 lines>...
)
Exception: This model isn't mapped yet. model=gpt-4o-realtime-preview-2024-12-17, custom_llm_provider=azure. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 1689, in async_success_handler
start_time, end_time, result = self._success_handler_helper_fn(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
start_time=start_time,
^^^^^^^^^^^^^^^^^^^^^^
...<3 lines>...
standard_logging_object=kwargs.get("standard_logging_object", None),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 1162, in _success_handler_helper_fn
raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: This model isn't mapped yet. model=gpt-4o-realtime-preview-2024-12-17, custom_llm_provider=azure. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json.
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.65.4 (latest commit to main)

**Comment by marty-sullivan** [comment]
I was able to finally get the proxy to recognize pricing by naming my Azure deployment `gpt-4o-realtime-preview-2024-10-01` even though the version is 2024-12-17. It's odd that worked because I had updated `model_prices_and_context_window.json` with several options... Not sure what is getting messed up there.

However, even though I did get the pricing to be reflected in the proxy model list, the pricing still does not seem to be working for this model. 

Using the Websockets example code, I'm able to get all costs to show up in the usage logs for `gpt-4o-mini-realtime-preview-2024-12-17` but none of the requests to `gpt-4o-realtime-preview` show up in the logs at all.

**Comment by marty-sullivan** [comment]
Indeed, it looks like there is an issue with the model version not being defined in `model_prices_and_context_window.json`.

I have tried adding an entry for `gpt-4o-realtime-preview-2024-12-17` but I don't know why it's not being recognized.

**Comment by ghost** [comment]
> I have tried adding an entry for gpt-4o-realtime-preview-2024-12-17 but I don't know why it's not being recognized.

How did you do this? @marty-sullivan

**Comment by ghost** [comment]
> However, even though I did get the pricing to be reflected in the proxy model list, the pricing still does not seem to be working for this model.

Not sure i follow how you did this

**Comment by marty-sullivan** [comment]
@krrishdholakia I am just adding an entry with the name `azure/gpt-4o-realtime-preview-2024-12-17` to `model_prices_and_context_window.json` and building the container. Should I do more than that?

**Comment by ghost** [comment]
I'm unable to repro the log not showing up. 

I can repro the spend not being tracked. 
<img width="1484" alt="Image" src="https://github.com/user-attachments/assets/eec8ad75-2182-4ac8-bbba-c794c6f4e862" />

**Comment by ghost** [comment]
Custom pricing works - https://docs.litellm.ai/docs/proxy/custom_pricing#cost-per-token-eg-azure

```yaml
  - model_name: "gpt-4o-realtime-preview"
    litellm_params:
      model: azure/gpt-4o-realtime-preview-2
      api_key: os.environ/AZURE_API_KEY_REALTIME
      api_base: https://krris-m2f9a9i7-eastus2.openai.azure.com/
    model_info:
      input_cost_per_token: 0.000005
      output_cost_per_token: 0.000005
```

<img width="1518" alt="Image" src="https://github.com/user-attachments/assets/5f44c830-45c2-4270-8d8a-e7023954542b" />

**Comment by ghost** [comment]
@marty-sullivan 

modifying the `model_prices_and_context_window.json` will have no impact. 

You can disable the check on hosted model cost map, and then update the `model_prices_and_context_window_backup.json` if you wanted to add this as an entry to the model cost map. 

<img width="1004" alt="Image" src="https://github.com/user-attachments/assets/dadc6940-a833-424b-9043-579c0636eb49" />

**Comment by ghost** [comment]
Closing as unable to repro the custom pricing cost tracking error. Please reopen if i missed something.

**Comment by marty-sullivan** [comment]
@krrishdholakia So I have done that. Set `LITELLM_LOCAL_MODEL_COST_MAP=True`

Here is what I am adding to my local `model_prices_and_context_window.json`:

```json
    "azure/gpt-4o-realtime-preview-2024-12-17": {
        "max_tokens": 4096,
        "max_input_tokens": 128000,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.000005,
        "input_cost_per_audio_token": 0.0001,
        "cache_read_input_token_cost": 0.0000025,
        "cache_creation_input_audio_token_cost": 0.00002,
        "output_cost_per_token": 0.00002,
        "output_cost_per_audio_token": 0.0002,
        "litellm_provider": "azure",
        "mode": "chat",
        "supports_function_calling": true,
        "supports_parallel_function_calling": true,
        "supports_audio_input": true,
        "supports_audio_output": true,
        "supports_system_messages": true,
        "supports_tool_choice": true
    },
```

I've also tried many variations of the name, like `azure/gpt-4o-realtime-preview` and similar.

I create a deployment in Azure and map it like this in my config YAML:

```yaml
  - model_name: 'openai.gpt-4o-realtime-preview'
    litellm_params:
      model: 'azure/gpt-4o-realtime-preview-2024-12-17'
      api_base: 'https://example.openai.azure.com/'
      api_version: '2025-03-01-preview'
      api_key: 'secret'
```

I've also tried naming my azure deployment different things like `azure/gpt-4o-realtime-preview`.

No matter what combination I do, there is a message in the detailed debug logs that state no mapping can be found for that model and the pricing is not mapped and the /v1/realtime endpoint does not log the usage of the model.

EDIT: I see above that you have addressed the model in your dev branch though, so I will just wait. I always have a lot of issues trying to edit these locally though.

**Comment by ghost** [comment]
> Here is what I am adding to my local model_prices_and_context_window.json:


@marty-sullivan it's `model_prices_and_context_window_backup.json` that would need to be edited. 

But to be clear - the documented flow is to set it under model_info on your YAML 

```yaml
  - model_name: "gpt-4o-realtime-preview"
    litellm_params:
      model: azure/gpt-4o-realtime-preview-2
      api_key: os.environ/AZURE_API_KEY_REALTIME
      api_base: https://krris-m2f9a9i7-eastus2.openai.azure.com/
    model_info:
      input_cost_per_token: 0.000005
      output_cost_per_token: 0.000005
```


Is there a reason you weren't doing that?
