### ISSUE TITLE
[Bug]: Ollama chat is only considering the first interaction

### ISSUE THREAD

**Issue by asabino2** [BerriAI/litellm#9822]
### What happened?

The chat for ollama models is only considering the first user interaction. Any other request it always responds to the first interaction (see attached image as an example)

![Image](https://github.com/user-attachments/assets/ec0385d0-b1fc-4803-bc81-d56465fdc074)

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.65.4

**Comment by enzomich** [comment]
@asabino2 This problem started in the version 1.63.8. What happens is that the message following an "Assistant" message is ignored. And I think I've found why: in the file `\Lib\site-packages\litellm\litellm_core_utils\prompt_templates\factory.py`, inside the body of the function `ollama_pt`, at the lines 242-254, there is the following code:

``` 
            if ollama_tool_calls:
                assistant_content_str += (
                    f"Tool Calls: {json.dumps(ollama_tool_calls, indent=2)}"
                )

            msg_i += 1
```
Actually `msg_i ` should be incremented **only** if `ollama_tool_calls` is `True`, which means that the line `msg_i += 1` it should be indented one more level:

```
            if ollama_tool_calls:
                assistant_content_str += (
                    f"Tool Calls: {json.dumps(ollama_tool_calls, indent=2)}"
                )

                msg_i += 1
```
After patching that file directly in the library (horrible, I know) everything went back to normal. Please give it a try, and if it works let the devs know.

**Comment by asabino2** [comment]
unfortunately it didn't work, please check if the code is correct.

![Image](https://github.com/user-attachments/assets/874d7326-29d7-4f18-bcea-d16261b40226)

![Image](https://github.com/user-attachments/assets/3287bd44-d7f2-4f51-bbdd-cb8eb79a4c4f)

**Comment by enzomich** [comment]
Hmm, strange. Have you restarted the program that uses the library module?
I tested the fix with Hugginface's smolagents library and it worked fine.
Which client software are you using?

**Comment by asabino2** [comment]
I tested it within Litellm itself. I'm using Litellm via Docker. I even managed to generate a new image from the modified container, but it still d

idn't work. I also tested it via chatbox and it also gave the same problem.

![Image](https://github.com/user-attachments/assets/056ae7df-81b8-410c-ac4b-20d6af88ca0e)

**Comment by enzomich** [comment]
Yes, if the LiteLLM client runs in Docker the library that needs to be patched is the one inside the image. OK tomorrow I'll try to have a look at it (in my time zone it's midnight now).

**Comment by pandego** [comment]
This happens to me too, but not just Ollama, GROQ api as well.

**Comment by enzomich** [comment]
I tried to install litellm[proxy] on my Windows laptop but I got an error that boils down to:
`uvloop does not support Windows at the moment`
...and I'd like to avoid Docker because I'm not familiar with how to debug programs inside a container. 

Anyway, I'm pasting below a simple test program, which makes use of a User/Assistant history created when using LiteLLM between Huggingface's smolagents and Ollama: with the unpatched LiteLLM 1.65.4.post1 it replies to the first question (because it eats up the second prompt from User: please note the diagnostic printouts in green colour showing the data posted to Ollama's REST interface with `POST Request Sent from LiteLLM`); after my patch, it works as expected. That corresponds to the behaviour when using LiteLLM from smolagents.

```
import os
from pprint import pp
import litellm
from litellm import completion

litellm._turn_on_debug()

response = completion(

    model = 'ollama/qwen2.5-coder:14b',
    api_base = 'http://localhost:11434',

    #model = 'huggingface/Qwen/Qwen2.5-Coder-32B-Instruct',
    #api_base = 'https://my-endpoint.endpoints.huggingface.cloud/v1/',

    #model = 'openai/qwen2.5-coder:14b',
    #api_base = 'http://localhost:11434/v1/chat/completions',
    #api_key = 'no_key',
    
    messages = [
        {'role': 'user', 'content': 'Hi'},
        {'role': 'assistant', 'content': 'Thought: The user has simply said "hi". I need to '
                  "respond appropriately. Since there's no specific "
                  "task or question provided, I'll just acknowledge "
                  'the greeting and ask for more information on what '
                  "they'd like me to do.\n"
                  '\n'
                  'Code:\n'
                  '```py\n'
                  'final_answer("Hello! How can I assist you today?")\n'
                  '```<end_code>',
        },
        {'role': 'user', 'content': 'How much is 2+2?'}
    ]
)

print(f'Answer: {response.choices[0].message.content}\n')

pp(response)
```

**Comment by enzomich** [comment]
@asabino2 

> I tested it within Litellm itself. I'm using Litellm via Docker. I even managed to generate a new image from the modified container, but it still didn't work. I also tested it via chatbox and it also gave the same problem.

By the way, I did the same test as you with Chatbox and it works fine for me:

![Image](https://github.com/user-attachments/assets/11f501d6-713f-49f0-b382-fc07f5bcb082)

But anyway, from what I see at https://github.com/chatboxai/chatbox , the Chatbox client is written in JavaScript/TypeScript, so the _Python_ library of LiteLLM and my fix to it should be irrelevant.

**Comment by asabino2** [comment]
strange, to me the same error continues. One issue, the docker image ghcr.io/berriai/litellm:main-v1.65.4.dev6 does not exist, however I downloaded the image ghcr.io/berriai/litellm:litellm_debug_sso_fields-dev that is referred to, but the same error also occurs with ollama considering only the first interaction. I even cleaned the litellm directory and did a new git clone, removing the image option from docker-compose.yml so that it generates an image based on the dockerfile, but the error still persists.

![Image](https://github.com/user-attachments/assets/270e0f3a-7cbd-4731-ba02-6727182b6548)

**Comment by SamFusco** [comment]
I am also getting the same issue, Ollama is only ever considering the first interaction. I run LiteLLM in docker and I am running the latest image `litellm/litellm-database:v1.65.4.dev6`.

I run open-webui as my front end and you can see that I am having the exact same issue:

![Image](https://github.com/user-attachments/assets/f732a97c-4328-4d8e-aa4c-4439664cd5a3)

I also experience the same behaviour when I try accessing/testing the model via the LiteLLM interface as well.

**Comment by enzomich** [comment]
Have you tried the patch I described above?

**Comment by SamFusco** [comment]
> Have you tried the patch I described above?
> […](#)

Are you talking about [this](https://github.com/BerriAI/litellm/issues/9822#issuecomment-2786650065) one? No but I will give it a shot and test it out

**Comment by enzomich** [comment]
Yes: it worked for me but not for @asabino2.

**Comment by SamFusco** [comment]
Literally just tried it, it didn't work for me. Still experiencing the same behaviour.

**Comment by enzomich** [comment]
Have you restarted openwebui after the patch?

**Comment by SamFusco** [comment]
Actually that was a good catch but unfortunately it is still happening. I restart Ollama as well, just incase but still no luck.

**Comment by asabino2** [comment]
I managed to make it work.

How I did it:
I down the entire docker instance with the command sudo docker compose down
I downloaded it again via git clone https://github.com/BerriAI/litellm.git
Inside the directory ./litellm/litellm/litellm_core_utils/prompt_templates I edited the factory.py file and applied the patch suggested by enzo
I went back to the directory ./litellm and edited the docker-compose.yml file, clearing the line with image in the litellm service, forcing it to recompile the image

![Image](https://github.com/user-attachments/assets/b63a0b89-311f-43d4-9d56-89706b96e313)

I ran the command sudo docker builder prune to clear any trace of image generation and then ran sudo docker compose up -d

After that it worked

**Comment by SamFusco** [comment]
Right so you rebuilt the image. I instead downloaded the file and manually edited it and passed it through like so:

```yaml
litellm:
        container_name: litellm
        image: litellm/litellm-database:v1.65.4.dev6
        restart: unless-stopped
        depends_on:
            - database
            - redis
        networks:
            - litellm-backend
            - proxy
        environment:
            - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
            - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./config/config.yaml:/app/config.yaml:ro
            - ./factory.py:/app/litellm/litellm_core_utils/prompt_templates/factory.py:ro
        command: ["--config", "/app/config.yaml", "--detailed_debug"]
```

Should be noted that the factory.py is located in `/app/litellm/litellm_core_utils/prompt_templates/`

**Comment by enzomich** [comment]
Great! So now we should tell the developers to apply the fix in the next release. Does anybody know how to do it without going through the creation of a PR? After all it's a very simple and logical change.

**Comment by enzomich** [comment]
@ishaan-jaff We have a very simple fix for this annoying bug. How can we have it committed to the code?

**Comment by SamFusco** [comment]
I know it's a bit late, but I rebuilt the image directly from GitHub, and then I applied the patch you mentioned [here](https://github.com/BerriAI/litellm/issues/9822#issuecomment-2786650065) @enzomich , and I am happy to report it has resolved the issue.

**Comment by aditya-angelone-tech** [comment]
i tried using this approach , modifying the file locallly and binding it but its not working for me
docker run -d 
    -v $(pwd)/config.yaml:/app/config.yaml 
    -v $(pwd)/factory.py:/app/litellm/litellm_core_utils/prompt_templates/factory.py:ro 
    -p 4000:4000 
    --name litellm-proxy 
ghcr.io/berriai/litellm:main-latest 
    --config /app/config.yaml 

wat cud b wrong @enzomich

**Comment by enzomich** [comment]
@aditya-angelone-tech I'm not sure because I didn't use Docker, but perhaps @asabino2 and @SamFusco can help you.

**Comment by SamFusco** [comment]
@aditya-angelone-tech you need to manually build the image with the modified `factory.py` file.

You need to do the following:
1. Clone the repo to your machine `git clone https://github.com/BerriAI/litellm.git`
2. Modify `./litellm/litellm/litellm_core_utils/prompt_templates/factory.py` so that it looks like:
```python
            if ollama_tool_calls:
                assistant_content_str += (
                    f"Tool Calls: {json.dumps(ollama_tool_calls, indent=2)}"
                )

                msg_i += 1
```
3. Rebuild the image, I use docker compose so my litellm service in my `docker-compose.yml`:
```yaml
litellm:
    container_name: litellm
    build:
        context: /path/to/git/litellm  # modify this with your path
        args:
            target: runtime
    env_file: /path/to/git/litellm/.env  # modify this with your path
    restart: unless-stopped
    environment:
        - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
        - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
        - DATABASE_URL=${DATABASE_URL}
    volumes:
        - ./config/config.yaml:/app/config.yaml:ro
    command: ["--config", "/app/config.yaml", "--detailed_debug"]
```
4. Bring up the container using `docker compose up -d`
