### ISSUE TITLE
[Bug]: LiteLLM takes very long time to response

### ISSUE THREAD

**Issue by hikouki-gumo** [BerriAI/litellm#9910]
### What happened?

LiteLLM takes very long time to response, even when response is cached. 
It should not be network issue because I tested in the same network.

What can be the root cause for the issue?

Command:
```
time curl -X POST http://${LITELLM_POD_IP}/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $API_KEY" -d '{
    "model": "gpt-4o",
    "messages": [
        {
            "role": "user",
            "content": "What is LiteLLM used for? "
        }
    ]
}'
{ ... 0.00s user 0.01s system 0% cpu 10.598 total}
```

LiteLLM logs from UI:
```
Cost: $0.000000
Cache Hit: True
Status: Success
Start Time: 2025-04-11T10:01:45.742000Z
End Time: 2025-04-11T10:01:45.743000Z
```

### Deployment topo
3 Pod Litellm + 1 Pod Posgres + 1 Pod Redis.
Pods are granted enough CPU/RAM.

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

main-v1.65.4-stable

**Comment by ghost** [comment]
Start Time: 2025-04-11T10:01:45.742000Z
End Time: 2025-04-11T10:01:45.743000Z

this is a duration of 1ms. That doesn't seem like a long time. 

If you're seeing more on your client-side then it might be related to your network.

**Comment by hikouki-gumo** [comment]
@krrishdholakia Are you sure?

Already mentioned that I tested in my local network and connect directly to Pod IP.
```
time nc -zv $POD_IP 4000
nc: connect to $POD_IP port 4000 (tcp) failed: Connection refused
nc -zv $POD_IP 4000  0.00s user 0.01s system 90% cpu 0.008 total
```

When I sent the request, request seems stuck at authenticate. 
Is there any chance redis cache is not configured correctly and does not store virtual keys. Then it has to query the database and led to the issue?

I'm not sure how LiteLLM stores virtual keys in Redis. I tried redis-cli, EXISTS sk-...mykey, but key not found. I can found normal response key in Redis (litellm.caching.caching:hash).

My config:
```
apiVersion: v1
data:
  config.yaml: |
    litellm_settings:
      cache: true
      cache_params:
        host: os.environ/REDIS_HOST
        namespace: litellm.caching.caching
        password: os.environ/REDIS_PASSWORD
        port: os.environ/REDIS_PORT
        ttl: 600
        type: redis
      request_timeout: 300
```
