### ISSUE TITLE
[Bug]: drop_params not working for (image only?) vertex_ai generation

### ISSUE THREAD

**Issue by stronk7** [BerriAI/litellm#9936]
### What happened?

It's my understanding (I may be wrong), that setting `drop_params: true` for any model, should proceed to remove any unsupported (or un-translatable) parameter in the request. And I'm using that with some other models.

But when I try to apply it to our configured `imagen-3.0-generate-002` model, it doesn't seem to make effect, and the unsupported parameters (size, response_format) are passed to vertex and that causes an empty response (without the image data/prediction) coming.

Curiously if, instead of `drop_params: true` I use `additional_drop_params: ["size", "response_format"]` then those params are effectively removed and vertex returns the images properly.

This is my current configuration:

```
  - model_name: "imagen-3.0"
    litellm_params:
      model: "vertex_ai/imagen-3.0-generate-002"
      vertex_credentials: /app/vertex_key.json
      vertex_project: "******************"
      vertex_location: "***********"
      # drop_params: true  # This doesn't make effect, should it?
      additional_drop_params: ["size", "response_format"]  # This does work.
```

And this is my CURL request to LiteLLM (simulating what some tools/apps do, always passing, `n` (that is properly translated by LiteLLM, NP with that one), `size` (that does not have translation and I'd expect to be dropped) and `response_format` (without simple translation too).

```
curl --request POST \
  --url http://example.com/v1/images/generations \
  --header 'authorization: Bearer ******************' \
  --header 'content-type: application/json' \
  --data '{
  "model": "imagen-3.0",
  "size": "512x512",
  "n": 1,
  "response_format": "b64_json",
  "prompt": "A mighty train under the rain"
}'
```

If I don't use the `additional_drop_params` trick, the response comes sort of empty (without the data/prediction results). And `drop_params`doesn't make it.

Note that I've not checked if this is exclusive to the image handling of vertex models or applies to all (text, ...)

Ciao :-)

### Relevant log output

```shell
Nothing in logs, aparently the request was ok:


INFO:     192.168.65.1:39539 - "POST /v1/images/generations HTTP/1.1" 200 OK


But it comes empty if those params aren't dropped:


{
  "created": 1744441345,
  "data": [],
  "usage": {
    "completion_tokens": 0,
    "prompt_tokens": 0,
    "total_tokens": 0,
    "completion_tokens_details": null,
    "prompt_tokens_details": null
  }
}
``
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.65.4-stable
