### ISSUE TITLE
[Feature]: Support injecting cache control flags on anthropic requests

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#9949]
### The Feature

Test criteria: Specifically: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0

```yaml
model_list:
  - model_name: "anthropic-claude-3-5-sonnet"
    litellm_params:
      model: bedrock/anthropic.claude..
      inject_cache_control_breakpoints: true
      inject_cache_control_breakpoints_number: 4
      inject_cache_control_breakpoints_locations: ["tools", "system"]
```

At that time you add a new Anthropic model to the LiteLLM proxy, you can specify optional metadata like:

- `inject_cache_control_breakpoints: true` - allows LiteLLM to inject cache control breakpoints into any prompts sent through this model
- `inject_cache_control_breakpoints_number: 4` - limits the total number of cache control breakpoints that LiteLLM can inject into any prompt in this model (right now Anthropic caps this limit to 4 but that number could change in future models released)
- `inject_cache_control_breakpoints_locations: ["system", "tools", "messages.user.content", "messages.assistant.content"]` - specifies the locations where LiteLLM should inject cache control breakpoints within a given prompt.  For example, if only system is specified, then LiteLLM will limit breakpoint injection to just that location of the prompt.

For example:
If inject_cache_control_breakpoints: true and
If inject_cache_control_breakpoints_number: 4 and
If inject_cache_control_breakpoints_locations: ["tools", "system"] , then:
LiteLLM will attempt to inject up to 4 breakpoints starting with the different tools, and then moving on to the system location of the prompt
If the prompt contains like 2 tools, then both tools + system would be injected (total of 3 breakpoints).
If the prompt contains like 5 tools, then the first 4 tools would be injected and no system would be injected (total of 4 breakpoints).
...etc...

### Motivation, pitch

This can save 90%+ in cost when calling expensive claude models 

### Are you a ML Ops Team?

No
