### ISSUE TITLE
[Feature]: Team-based logging not respected when using passthrough endpoints (e.g., Google AI Studio)

### ISSUE THREAD

**Issue by DaivikDave** [BerriAI/litellm#9967]
### The Feature

We are using litellm with team-based logging configured via default_team_settings as documented here: https://docs.litellm.ai/docs/proxy/team_logging

Here's a snippet of our configuration:

```
litellm_settings:
  success_callback: ["langfuse"]
  default_team_settings: 
    - team_id: "dbe2f686-a686-4896-864a-4c3924458709"
      success_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PUB_KEY_1 # Project 1
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_1 # Project 1
    - team_id: "06ed1e01-3fa7-4b9e-95bc-f2e59b74f3a8"
      success_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PUB_KEY_2 # Project 2
      langfuse_secret: os.environ/LANGFUSE_SECRET_2 # Project 2
```

When using the OpenAI client (Go SDK), team-based logging works as expected:

```
client := openai.NewClient(
		option.WithBaseURL("http://localhost:8000"),
		option.WithAPIKey(LiteLLM_key),
	)

...

chatCompletion, err := client.Chat.Completions.New(context.TODO(), openai.ChatCompletionNewParams{
    Messages: openai.F([]openai.ChatCompletionMessageParamUnion{
        openai.UserMessage("Greet Me"),
    }),
    Model: openai.F("gpt-4o-mini"),
}, option.WithJSONSet("metadata", metadata))

```

However, when we make requests via a passthrough endpoint (e.g., Google AI Studio) https://docs.litellm.ai/docs/pass_through/google_ai_studio, the logs are routed to the default Langfuse project configured via LANGFUSE_PUBLIC_KEY and LANGFUSE_SECRET_KEY, instead of the team-specific keys defined in default_team_settings.

📉 Existing Behavior:
Passthrough requests ignore the team_id mapping derived from the LiteLLM API key (created via the console) and instead fall back to the default logging keys defined in LANGFUSE_PUBLIC_KEY and LANGFUSE_SECRET_KEY.

✅ Expected Behavior:
Passthrough requests should honor the team_id associated with the LiteLLM API key and route logs to the corresponding Langfuse project, as defined in the default_team_settings.

### Motivation, pitch

We would like improved logging support for passthrough endpoints to enable team-specific observability.

### Are you a ML Ops Team?

No

### Twitter / LinkedIn details

@DaivikDave
