### ISSUE TITLE
[Bug]: max_internal_user_budget cannot be configured

### ISSUE THREAD

**Issue by mknet3** [BerriAI/litellm#9985]
### What happened?

Adding the configuration for `max_internal_user_budget` and `internal_user_budget_duration` does not take any effect.

```yaml
  proxy_config:
    litellm_settings:
      max_internal_user_budget: 10 # max budget for internal users
      internal_user_budget_duration: "1d" # reset every day
```

The configuration in the UI is shown as None:

![Image](https://github.com/user-attachments/assets/599e8184-23b9-43d5-9077-deeea6302ab6)

And we don't see any error in logs.

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.66.0-stable

### Twitter / LinkedIn details

https://www.linkedin.com/in/mcaneteubeda/
